### ISSUE TITLE
Cargo functionality testing suite

### ISSUE THREAD

**Issue by vignesh-sankaran** [rust-lang/crates.io#1000]
I'll add to this idea over time, as an initial thought, we could run all the cargo subcommands that are linked to crates.io and ensure that they all work. Maybe we could have this as a separate TravisCI test, whether built with Rust or shell scripts.

EDIT: Oh yay this is issue 1000 :)

**Comment by Turbo87** [comment]
closing this issue, as there hasn't been much activity here over the past few years
