### ISSUE TITLE
Mark fields that are used by shields.io

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/crates.io#1001]
The shields.io service expects certain fields to exist in the JSON response of `'https://crates.io/api/v1/crates/' + crate` -- listed [here](https://github.com/badges/shields/blob/6534a2a1a821da91854d5d940f6e469c1c4851e2/server.js#L624-L663). In https://github.com/badges/shields/issues/1059 it looks like their license badge either never worked (?) or was broken at some point by a crates.io change.

Let's put a comment above fields that are used by shields.io so that if they need to change in the future, we know to follow up with a PR to shields.io.

**Comment by kzys** [comment]
@carols10cents Can we close this issue now, since the PR has been merged?
