### ISSUE TITLE
Neither readme nor description displayed if readme key points to file that does not exist

### ISSUE THREAD

**Issue by retep998** [rust-lang/crates.io#1005]
https://crates.io/crates/winapi

![](http://i.imgur.com/SaoZSX4.png)

`Cargo.toml` has `readme = "README.md"` but there is no `README.md` causing neither readme nor description to display.

**Comment by carols10cents** [comment]
So we just deployed a change to which crate we used to render readmes and rerender everything, and winapi still doesn't have a readme, but now the description IS displaying. I'm... not sure why, but this looks fixed now to me.
