### ISSUE TITLE
Could not publish crates with 2024 edition

### ISSUE THREAD

**Issue by Evian-Zhang** [rust-lang/crates.io#10091]
I followed the [Rust 2024 call for testing](https://blog.rust-lang.org/2024/11/27/Rust-2024-public-testing.html) to upgrade my crate [static-keys](https://github.com/Evian-Zhang/static-keys) (which is a crate running in nightly) to Rust 2024 edition.

However, when I want to publish this crate by `cargo publish`, it turns out error:

```plaintext
error: failed to publish to registry at https://crates.io

Caused by:
  the remote server responded with an error (status 400 Bad Request): failed to parse `Cargo.toml` manifest file

  TOML parse error at line 13, column 11
     |
  13 | edition = "2024"
     |           ^^^^^^
  data did not match any variant of untagged enum MaybeInherited
```

Is this behavior intentional?

**Comment by Turbo87** [comment]
the new edition isn't supported yet by our server, but it should be relatively straightforward to fix. I'll take a look.

**Comment by eth3lbert** [comment]
I haven't looked into it yet, but I'm guessing we'll need to add new version support for `cargo-manifest`.

**Comment by Turbo87** [comment]
yeah, exactly. feel free to open a PR if you have time. I can merge and release later today.
