### ISSUE TITLE
Page title doesn't update on some pages

### ISSUE THREAD

**Issue by huonw** [rust-lang/crates.io#101]
These all just have `Cargo` for the page title, at the time of writing:
- https://crates.io/crates
- https://crates.io/keywords
- https://crates.io/keywords/math
- https://crates.io/dashboard
- https://crates.io/me
- https://crates.io/me/crates

(https://github.com/rust-lang/crates.io/pull/89 fixed crate pages.)

**Comment by pimterry** [comment]
I'm going to fix this, probably later today. I'm thinking along the lines of the below, any objections?

https://crates.io/crates - 'Crates - Cargo'
https://crates.io/keywords - 'Keywords - Cargo'
https://crates.io/keywords/math - 'Math - Keywords - Cargo'
https://crates.io/dashboard - 'Dashboard - Cargo'
https://crates.io/me - 'Settings - Cargo'
https://crates.io/me/crates 'My Crates - Cargo'

**Comment by alexcrichton** [comment]
@pimterry sounds good to me!

**Comment by carols10cents** [comment]
This looks like it was fixed by #423 but just didn't get closed automatically.
