### ISSUE TITLE
Download counts for individual days are always 0

### ISSUE THREAD

**Issue by alex** [rust-lang/crates.io#103]
The chart is ok, but if you highlight a point on it, it says `0`:

![screen shot 2015-01-01 at 2 09 35 pm](https://cloud.githubusercontent.com/assets/772/5593395/f75dc76a-91bf-11e4-8b51-4a5e7e217519.png)

**Comment by alexcrichton** [comment]
cc @markberger

**Comment by markberger** [comment]
Would this be a suitable fix?

![screen shot 2015-01-02 at 2 42 09 pm](https://cloud.githubusercontent.com/assets/965436/5599011/c68ebcec-928d-11e4-91f8-bd666d626cb1.png)

I haven't been able to find anything in the Google API that would remove the overlapping lines when the number of downloads is 0. Any suggestions?

**Comment by alexcrichton** [comment]
Hm, if we delete data points for days where a release didn't exist (as opposed to substituting 0), would it look better?

**Comment by markberger** [comment]
Google charts doesn't seem to like that:

```
 Uncaught Error: Row 0 has 3 columns, but must have 6
```

**Comment by alexcrichton** [comment]
Ah oh well, showing a stacked list of numbers sounds good to me!

**Comment by alexcrichton** [comment]
(it's at least better than what we have now)

**Comment by alex** [comment]
Looks like a great improvement to me. Thanks!

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang/crates.io/pull/105
