### ISSUE TITLE
Org mode files are rendered as markdown

### ISSUE THREAD

**Issue by bomgar** [rust-lang/crates.io#1039]
Org mode readmes are rendered as markdown. This looks really broken. 

Example: https://crates.io/crates/fw

It would be better to just render the raw content.

**Comment by dead10ck** [comment]
[Same for asciidoc](https://crates.io/crates/urlencode). Looks like it just assumes anything that starts with `README` is markdown.

**Comment by carols10cents** [comment]
I'm going to combine this with #995.
