### ISSUE TITLE
Reserved crate names related to Rust Project

### ISSUE THREAD

**Issue by vignesh-sankaran** [rust-lang/crates.io#1052]
Came across [this project](https://github.com/nrc/rls-crate), and feel like this isn't the only one I've come across in the name of reserving a crate name. Maybe we could have a list of project names directly linked to The Rust Project that are reserved and can't be used?

**Comment by carols10cents** [comment]
What would the purpose of such a list be? How do crate names reserved by Rust team members differ from crate names reserved by anyone else? https://crates.io/crates/rls

**Comment by vignesh-sankaran** [comment]
The main purpose would be make sure that no 3rd parties can use a Rust project-related name for another purpose. I don't think we can stop placeholder crates though. The case for this is a bit tenuous, yes.

**Comment by carols10cents** [comment]
Yeah so placeholder crates already solve this, the rust team can reserve crates like anyone else can and that prevents 3rd parties from using a name for another purpose. I don't think there's anything new to do here.
