### ISSUE TITLE
Chart loading makes page jerky

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/crates.io#106]
When loading a crate's page, the page jerks around a lot and it's tough to scroll around while the graph for download data is loading (I'm using Firefox).

This is clearly not ideal, and I'm not sure where the issue is, but this definitely needs to be fixed.

**Comment by lazypenguin** [comment]
Is this still an issue? Not able to re-produce.

**Comment by alexcrichton** [comment]
I suppose not, yay!
