### ISSUE TITLE
considerations on parking

### ISSUE THREAD

**Issue by softprops** [rust-lang/crates.io#1063]
I am aware that crates.io is uses first come first serve policy for publish crates but I find this use questionable an cause for the concern 

![screen shot 2017-09-19 at 1 05 26 am](https://user-images.githubusercontent.com/2242/30576566-c6c5d1a4-9cd6-11e7-81bb-4453fe474070.png)

What your seeing is what a first time rust user would see when visiting crates.io in the very first list of crates to select from.

If you look at these 0.0.0 crates you will find no code and you may actually never find code if you do not meet this users policy for reclaiming the name 

some excerps from the current owners crate home page [home](https://gist.github.com/est31/da97a67dd7356e1dae5c0dd34b5a342c)

> I've reserved some crate names on crates.io for future use.
> I'm willing to turn over any crate names to interested parties under some criteria:
> Your crate is a significant contribution to the ecosystem and not just e.g. some test project or something you never intend to finish.
> You actually have it almost done so that its usable by other people

There is a bit of irony in there in that this person is trying to ensure the crate.io ecosystem is not polluted but the way they are going about doing so _is_ what I'd consider polluting, in a way its defaming a good portion of the crate.io home page. The hub for crate discovery!

**Comment by softprops** [comment]
I do not expect a policing policy but I'm aware one of the efforts of 2017 is to make good quality crates easier to discover. This users's behavior seems to be directly working against this goal. I think there should be a means of reported abuse.

**Comment by carols10cents** [comment]
As you note, this isn't against the crates.io policies, so we are not going to remove these crates. 

> What your seeing is what a first time rust user would see when visiting crates.io in the very first list of crates to select from.

These crates will scroll off the "newest crates" list soon.

> I'm aware one of the efforts of 2017 is to make good quality crates easier to discover. This users's behavior seems to be directly working against this goal.

We plan to continue the work [we've been doing](https://github.com/rust-lang/rfcs/pull/1824) to increase signals of good crates for people to use when evaluating crates. The name shouldn't be the only indication that you've found a good crate, and we are giving and plan to continue giving more information to crate users to help them find the best crates.

Thank you for the issue!
