### ISSUE TITLE
Invalid tarballs on crates.io

### ISSUE THREAD

**Issue by lukaslueg** [rust-lang/crates.io#1084]
There are some crates whose tarballs are zero-sized or otherwise invalid. Maybe those should be ferried across river styx? Among others:

* q 0.0.1
* db 0.0.1
* argo 0.0.1
* cssselect 0.0.1
* ferrite 0.0.1
* hashids-rs 0.0.0
* libbreakpad-client-sys 0.1.0
* mongo 0.0.1
* oxidation 0.0.1

**Comment by carols10cents** [comment]
I'm not sure what to do about these other than forcibly yank these versions... but thank you for looking into this!

**Comment by locks** [comment]
Added these to the list in https://github.com/rust-lang/crates.io/issues/1821. Thanks for the list!
