### ISSUE TITLE
Refactor backend tests

### ISSUE THREAD

**Issue by vignesh-sankaran** [rust-lang/crates.io#1097]
So I'm thinking that we could restructure the tests so that all function-level tests are done within the module that they are contained within, and higher level tests that incorporate more functions can be done at that specific module. `src/tests` would be restructured so that they are only a blackbox test of the backend API.  If the tests become too long within a file, we can have those tests contained within a separate file or files within the module.

An upside of doing this is that we can gain more visibility over what crates.io's test coverage currently looks like, and work to improve coverage from there.

**Comment by Turbo87** [comment]
closing as there hasn't been any activity on this issue for quite some time
