### ISSUE TITLE
Easier access to project licenses

### ISSUE THREAD

**Issue by a-dma** [rust-lang/crates.io#1113]
I'm trying to put together a release tarball, and I would like to collect all the `LICENSE` files for my dependencies since most of the time these are required for proper copyright attribution and redistribution.

Whilst trying to do this, I realized that the process is far more convoluted than I expected (and than it needs to be). I ended up having to (semi-automatically) handpick all the files from the individual git repos. This is considering the fact that some projects have no git repo, some have it listed in the homepage field, and some link to specific branches that can be re-interpreted by things like GitHub, but that can't be cloned directly. Moreover, the licenses themselves are stored with all sorts of names such as `LICENSE`, `LICENCE`, `LICENSE.md`, `LICENSE.txt`, `COPYING`, etc. This makes the whole automation process a collection of special cases...

There are tools that allow to visit the dependency tree and list the different dependency, possibly highlighting discrepancies with the project's own license, but they can't help with the collection the actual license file.

I saw that crates.io shows the actual license type of each crate, and after a bit of digging around I was able to use the APIs to retrieve the JSON blob with the relevant data. For example below is a snippet of the JSON blob for the latest version of Cargo

```
{
      "id": 64980,
      "crate": "cargo",
      "num": "0.21.1",
      "dl_path": "/api/v1/crates/cargo/0.21.1/download",
      "readme_path": "/api/v1/crates/cargo/0.21.1/readme",
      "updated_at": "2017-09-10T16:41:42Z",
      "created_at": "2017-09-10T16:41:42Z",
      "downloads": 870,
      "features": null,
      "yanked": false,
      "license": "MIT/Apache-2.0",
      "links": {
        "dependencies": "/api/v1/crates/cargo/0.21.1/dependencies",
        "version_downloads": "/api/v1/crates/cargo/0.21.1/downloads",
        "authors": "/api/v1/crates/cargo/0.21.1/authors"
      }
    }
```

As you can see the license is clearly stated as `MIT/Apache-2.0`.

Onto my proposal: I'd like to make the retrieval of the license file easier by adding a `license_path` value in the JSON object (similarly to the `readme` file) and make that a mandatory requirement for publishing on crates.io.
Since a license is already required, I don't think that this change will be too invasive. This will make the collection of license files trivial.

**Comment by carols10cents** [comment]
So another issue is that currently, crates are required to have either a `license` identifier OR a `license-file` key that points to a file in the tarball-- but if you have a `license` identifier, nothing in cargo or crates.io enforces that you've actually included a license file. So in order for this to be comprehensive, there would also have to be a SPDX ID -> license text component, and this is starting to get out of the realm of crates.io's responsibility, imo. 

So even if we started requiring a `license_path` today, we'd still have a backfilling problem. This might be better as a new tool or as an enhancement to a tool like cargo-lichking.

**Comment by a-dma** [comment]
Thanks for the reply.

I see your point. However, I believe that if Cargo (and crates.io) enforces that a license is present in some way shape or form, it should also be responsible to make it retrievable.

I don't think many languages get the license issue right, but Cargo has a very good opportunity of doing so, in my opinion.
