### ISSUE TITLE
Add a UI for adding/removing someone as an owner of a crate

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#1117]
Right now, you can only add or remove a person or a team as an owner of a crate using cargo's CLI. (Also right now you can only list pending invitations and accept or decline them in crates.io's web UI). This seems a little strange; it'd be nice to have a web UI for adding or removing owners of a crate that you're an owner on.

I'm not sure exactly what this should look like or how it should work on the frontend; that's all implementer's choice! I think it should be able to use the same API routes that cargo uses though!

**Comment by iain8** [comment]
Hi @carols10cents I can take a look at this feature this weekend.

**Comment by withoutboats** [comment]
Closed by #1143.
