### ISSUE TITLE
appveyor link in crates.io is not correct even when setting new project_name attribute for projects with underscores

### ISSUE THREAD

**Issue by sagiegurari** [rust-lang/crates.io#1124]
I added project_name as defined in #587 but still the link created in crates.io is not working correctly.
what am I doing wrong?

https://crates.io/crates/rust_info

**Comment by treiff** [comment]
@sagiegurari, Yeah this is strange.  It looks like we show the badges in 3 places (that I'm aware of).

Looks like it went into master 2 days ago.  I'm not sure how often it's deployed.  With the recent PR this should work, unless there is something I'm missing.  If it's shipped, I'll take another look.

@carols10cents can you confirm if #1111 has been deployed?

**Comment by carols10cents** [comment]
It was not deployed, but I just did! @sagiegurari I see your appveyor badge in the sidebar and clicking on it works for me, can you confirm everything is working as you'd expect now that I've deployed? 😅

**Comment by sagiegurari** [comment]
works great. thanks a lot 👍
