### ISSUE TITLE
Unable to add an owner, no error

### ISSUE THREAD

**Issue by kvark** [rust-lang/crates.io#1132]
```bash
[kvark@carbon collision]$ cargo owner -a Rhuagh
    Updating registry `https://github.com/rust-lang/crates.io-index`
       Owner adding ["Rhuagh"] to crate collision
[kvark@carbon collision]$ cargo owner -l
    Updating registry `https://github.com/rust-lang/crates.io-index`
kvark (Dzmitry Malyshau)
csherratt (Coraline Sherratt)
```
Trying to add [this person](https://github.com/Rhuagh) to `collision` crate.
What's going on?

**Comment by kvark** [comment]
Apparently, adding a person sends an invitation. Cargo 1.22 writes:
> Owner user Rhuagh has been invited to be an owner of crate collision

So I suppose this is a non-issue. A person will appear in the actual list after the invitation is accepted.

**Comment by carols10cents** [comment]
Yup, you've got it! We [discussed how to surface this in cargo](https://github.com/rust-lang/cargo/issues/4537) and decided going to great lengths to surface invitations in old versions of cargo wasn't worthwhile.
