### ISSUE TITLE
On each crate's page, show a list of crates commonly used in conjunction with this crate

### ISSUE THREAD

**Issue by Boscop** [rust-lang/crates.io#1135]
On the IRC someone was asking for ways to explore the crate ecosystem...
That gave me an idea for a suggestion:
On each crate's page, show a list of crates commonly used by other crates who use this crate.
As a "crate recommendation system" similar to Amazon's "people who bought this also bought these items".
Here is an example output:
```js
People who bought rocket also bought:
rocket_contrib: 6
serde: 6
rocket_codegen: 5
serde_derive: 5
serde_json: 4
version_check: 3
iron: 3
compiletest_rs: 3
log: 3
ansi_term: 2

People who bought rayon also bought:
rand: 17
serde: 14
serde_derive: 13
lazy_static: 12
clap: 10
log: 9
serde_json: 8
byteorder: 7
clippy: 6
bincode: 6

People who bought bincode also bought:
serde_derive: 24
serde: 24
rand: 16
env_logger: 14
lazy_static: 11
rustc-serialize: 11
log: 11
quickcheck: 10
serde_json: 10
regex: 8

People who bought regex also bought:
lazy_static: 136
clap: 92
log: 82
serde_json: 80
serde: 78
serde_derive: 68
rustc-serialize: 64
env_logger: 58
hyper: 51
tempdir: 51

People who bought winapi also bought:
kernel32-sys: 107
libc: 41
winapi: 33
winapi-build: 31
user32-sys: 31
advapi32-sys: 23
winreg: 19
gdi32-sys: 16
x11-dl: 15
ws2_32-sys: 12
```

Here the code, under 50 lines (currently it only looks at the deps of crates on crates.io, not those of user crates on github):
```rust
extern crate crates_index;
extern crate petgraph;
extern crate bidir_map;

use std::env::args;
use std::cmp::Reverse;
use petgraph::prelude::*;
use bidir_map::BidirMap;

fn main() {
	let index = crates_index::Index::new("_index".into());
	if !index.exists() {
		index.retrieve().expect("Could not retrieve crates.io index");
	}
	let mut g = Graph::new();
	let mut node_ids = BidirMap::new();
	for crate_ in index.crates() {
		node_ids.insert(crate_.latest_version().name().to_string(), g.add_node(()));
	}
	for crate_ in index.crates() {
		let deps = crate_.latest_version().dependencies();
		for (i, a) in deps.iter().enumerate() {
			for b in &deps[i+1..] {
				let (id_a, id_b) = (*node_ids.get_by_first(a.name()).unwrap(), *node_ids.get_by_first(b.name()).unwrap());
				let commonly_depended_on = if let Some(edge) = g.find_edge(id_a, id_b) {
					g[edge]
				} else {
					0
				};
				g.update_edge(id_a, id_b, commonly_depended_on + 1);
			}
		}
	}
	let mut args = args();
	args.next();
	if let Some(crate_) = args.next() {
		let mut neighbors = g.edges(*node_ids.get_by_first(&crate_).unwrap()).map(|e| (node_ids.get_by_second(&e.target()).unwrap(), e.weight())).collect::<Vec<_>>();
		neighbors.sort_by_key(|&(_, weight)| Reverse(weight));
		println!("People who bought {} also bought:", crate_);
		for &(name, weight) in &neighbors[..10.min(neighbors.len())] {
			println!("{}: {}", name, weight);
		}
	}
}
```
On each crate's page, this list could also contain each crate's Cargo.toml `description` because crate names often aren't descriptive enough.
This could make it easier for people who are new to Rust to quickly explore the crate ecosystem to find the crates they probably want to use, and it could possibly reduce the number of cases where people end up reimplementing something because they mistakenly think there is no crate that solves their problem.

**Comment by epage** [comment]
Some of us have started a process of manually identifying related crates.  For example, [assert_cmd suggests other CLI testing crates](https://github.com/assert-rs/assert_cmd).  Having this automated would be a big help and allow the ecosystem to grow more organically.

**Comment by kornelski** [comment]
Looks like Serde is the Rust's "Harry Potter problem": https://www.quora.com/Recommendation-Systems-What-exactly-is-Harry-Potter-Problem

**Comment by Turbo87** [comment]
this sounds quite similar to https://github.com/rust-lang/crates.io/discussions/4331, so I'll close this issue as a duplicate unless anyone objects :)

**Comment by epage** [comment]
@Turbo87 looks like that is a discussion.  Are those being treated as backlog items for determining something is a duplicate?

Also, it doesn't look like Github creates backlinks on discussions, so it might be useful when closing an Issue in favor of a discussion, to link to the issue from the discussion so people can explore additional context.

**Comment by Turbo87** [comment]
> Are those being treated as backlog items

not necessarily as backlog items, but more as feature requests that people have had. not having this feature isn't necessarily an "issue" in the regular sense of the word, so we've started moving some of those out of the "Issues" tab. I hope that makes sense :)

**Comment by epage** [comment]
Interesting idea to play with.  Just expect friction with users searching and adding to the wrong area as it goes against most people's expectations for github projects as I suspect most people treat "Issues" as a misnomer and its really "Backlog" with features vs bugs being tracked as labels.

**Comment by Turbo87** [comment]
> Just expect friction with users searching and adding to the wrong area

sure, I'm absolutely expecting that. if you press the "New Issue" button above it will take you to https://github.com/rust-lang/crates.io/issues/new/choose, where the "Feature request" option will actually take you to the "Discussions" tab.

the other small advantage of using discussions is that it's easier for users to vote on what they think should have the highest priority.
