### ISSUE TITLE
Badges for latest version of a crate

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/crates.io#114]
[Gemfury](http://badge.fury.io/) provides badges that show the latest version of a Rubygem, NPM package, CocoaPod, etc. These are nice to include in a README to avoid having to update a "latest version" section or something.

Rather than going through Gemfury, crates.io could simply provide a URL like `https://crates.io/badges/$package/latest`, which issues a redirect to a [shields.io](http://shields.io/) badge URL containing the necessary information. For example, the `json_macros` badge might redirect to something like `https://img.shields.io/badge/crates.io-json_macros%20=%20%220.1.3%22-brightgreen.svg`:

[![crates.io: json_macros = "0.1.3"](https://img.shields.io/badge/crates.io-json_macros%20=%20%220.1.3%22-brightgreen.svg)](https://crates.io/crates/json_macros/0.1.3)

The crate page could then include a handy way to get the Markdown for a crate's badge for the maintainer's convenience.

**Comment by steveklabnik** [comment]
Yeah, shields.io is great.

**Comment by lfairy** [comment]
This sounds like something that should be implemented on shields.io, not on our end. With Rust approaching 1.0, we should be a first-class citizen on the site.

**Comment by lfairy** [comment]
Given that badges/shields#363 has been merged and deployed now ([example]), the only thing left to do is

> The crate page could then include a handy way to get the Markdown for a crate's badge for the maintainer's convenience.

[example]: https://img.shields.io/crates/v/maud.svg
