### ISSUE TITLE
Narrow screen width causes right column to overflow

### ISSUE THREAD

**Issue by colindean** [rust-lang/crates.io#1148]
I've got a crates.io tab open to https://crates.io/crates/digitalocean that is 832 px wide according to `window.innerWidth` and it looks like this on the side:

<img width="271" alt="screen shot 2017-10-26 at 11 51 25 am" src="https://user-images.githubusercontent.com/197224/32063169-8547def8-ba44-11e7-8a8d-1c119fb7689c.png">

**Comment by someguynamedmatt** [comment]
@colindean What browser was that on?

**Comment by colindean** [comment]
Chrome, latest as of when I filed it. I don't know the specific version but I speculate it was Chrome 60 or 61.

**Comment by someguynamedmatt** [comment]
Awesome. Thanks!

**Comment by carols10cents** [comment]
I think this was fixed by https://github.com/rust-lang/crates.io/pull/1242!

**Comment by colindean** [comment]
Confirmed fixed by this reporter 👍
