### ISSUE TITLE
Cargo logo design

### ISSUE THREAD

**Issue by vis-kid** [rust-lang/crates.io#115]
After informing @alexcrichton about my design plans for crates.io, I started working on a logo for Cargo that is less detailed, simpler and symbiotic to the Rust logo with the gear. It is based on Mark Simonson’s typeface [Mostra Nuova](http://www.marksimonson.com/fonts/view/mostra-nuova), which has references to Italian Art Deco posters and advertising in the 1930s. It is very geometric but has also subtle optical adjustments to keep it from being too mechanical. But exactly that bit of mechanical aura fits well the symbolism of crates and cargo imho. I was looking for something tangible and grounded while looking modern at the same time which hopefully has good chances of aging well. 

<img src="https://cloud.githubusercontent.com/assets/1353214/5726052/9b60b736-9b58-11e4-9c25-af18de84c104.jpg" width="270" />

The whitespace with spikes inside the big & small Cargo C fits exactly around Rust’s logo gear and implies the 
- idea of a protective layer - the primary function of a crate that stores items - around Rust and the 
- idea of gear multiplication achieved through Rust driving a bigger community of developers who publicly host their Rust packages with Cargo and multiply the value and convenience of Rust thereby manifold. 

Naturally the **C** stands for **Cargo**, the **community**, **C** as a language and also **Open Source** as represented by a visual echo of the [Open Source Initiative icon](http://opensource.org/).

The color is meant to be down to earth, grounded, and as future proof as possible by using a simple primary color. I have experimented with a couple other colors too, a darker purple would personally be my second choice. The goal should be to define a color that is not already taken by other major OS projects / communities since Rust hopefully defines a new major community of it’s own. 

You will find a lot more iterations of the logo in the images below. I’ve played with size, shape and color and hope that I’ve  provided enough options to choose from.

A simpler logo like this makes branding more effective, is better suited for merchandise and it’s easier to build a visual identity around it. Please let me know your feedback, I’m more than happy to work some more on the logo to refine it :smile_cat: 

![logo01](https://cloud.githubusercontent.com/assets/1353214/5726331/a91a9dcc-9b5a-11e4-9bfb-5a8f58e7c2ce.jpg)
![logo02](https://cloud.githubusercontent.com/assets/1353214/5726328/a916d44e-9b5a-11e4-97bc-ed72e21dd9c0.jpg)
![logo03](https://cloud.githubusercontent.com/assets/1353214/5726329/a9172bb0-9b5a-11e4-9632-fe00f8a0cd8f.jpg)
![logo04](https://cloud.githubusercontent.com/assets/1353214/5726327/a91597d2-9b5a-11e4-98e4-6679965ee6ef.jpg)
![logo05](https://cloud.githubusercontent.com/assets/1353214/5726330/a9185346-9b5a-11e4-86a6-1218a3fdf75e.jpg)
![logo06](https://cloud.githubusercontent.com/assets/1353214/5726332/a91e904e-9b5a-11e4-943b-b823bdcaa523.jpg)
![logo07](https://cloud.githubusercontent.com/assets/1353214/5726333/a9303d8a-9b5a-11e4-8ebc-7635b87bc2a6.jpg)
![logo08](https://cloud.githubusercontent.com/assets/1353214/5726334/a93179e8-9b5a-11e4-8cf9-4e6381a1ff27.jpg)
![logo09](https://cloud.githubusercontent.com/assets/1353214/5726335/a934e326-9b5a-11e4-8f0c-c1b9b1699de0.jpg)
![logo10](https://cloud.githubusercontent.com/assets/1353214/5726336/a93656c0-9b5a-11e4-92c8-3a9904ab703a.jpg)

**Comment by nagisa** [comment]
**I** like the page 1 → column 1 → row 2 logo most. Though I’m generally biased towards minimalism.

**Comment by thehydroimpulse** [comment]
@nagisa felt the same way!

**Comment by azerupi** [comment]
I really like this logo, I am really not a fan of the dark green color though.

Maybe it's best to stick with neutral colors like the first one (monochromatic), at least until an official color scheme emerges?

**Comment by Turbo87** [comment]
I agree with @nagisa. The huge C on most of the others is a bit too large IMHO.

**Comment by softprops** [comment]
One thing that hasn't been super clear to me is what's up with the gear logo vs ferris the crab -- http://www.rustacean.net. I'm guessing there was some inspiration taken from the golang gopher there. In any case, is there a chance of ferris making a cameo here?

**Comment by vis-kid** [comment]
@softprops Sorry for the radio silence. Missed that one.
No cameo of Ferris intended. The idea was to have the outline of the Rust logo in there where it would be able to dock / or fit in. Sort of a visual closure.

**Comment by vis-kid** [comment]
@brson @nagisa @Turbo87 @azerupi @thehydroimpulse These logos were just meant as a first attempt. I agree that the big C ones are a bit heavy. I’m totally willing to spend a lot more time on them. Want this logo to be excellent. Have a lot more time to work on the logo and the overall design this year. Advice about how we can move forward with the crates.io design effectively would be much appreciated!

**Comment by vis-kid** [comment]
@azerupi The official color scheme would emerge as the result of the redesign. This would be a much better investment in quality imho. It would not be a good idea to just predefine a color scheme that a designer has to follow no matter what—taking the current colors as a basis is fine though. In fact, that’s exactly what I did when I played with a few designs for the site over the last couple of months.

**Comment by julianrichen** [comment]
@vis-kid I'm not sure if your taking suggestions & I know the logo can't be overly complicated but have you considered making the "C" a forklift (the driver compartment) and the "argo" part a shipping container? The "C" would have two little wheels under it, maybe a smoke stack off the back and then extending off it would be the metal arms supporting "argo" container. The "C" forklift would then become the mascot and add some personality to the community.

Having a mascot in the logo like Travis CI, Gulp, Grunt, Docker, CoreOS, etc... is nice imo.

**Comment by klingtnet** [comment]
Here is my sketch for a Cargo logo. It's heavily inspired by the one from @vis-kid but it's more print-friendly because it uses larger tooths for the symbolic gear wheel. The font used is Fira Sans which is also the one that is used for Rust's documentation.
![cargo-logo](https://cloud.githubusercontent.com/assets/1538057/15805677/cc49ea6a-2b31-11e6-8a47-18eb6ee0493f.png)

**Comment by carols10cents** [comment]
I think the ship has sailed at this point (pun intended).

**Comment by itzzjustmateo** [comment]
I think an orange one would fit
