### ISSUE TITLE
Opening crate with latest yanked version from search leads to yanked version itself

### ISSUE THREAD

**Issue by DoumanAsh** [rust-lang/crates.io#1156]
If you go look for `quickcheck` which currently has latest version 0.4.2 yanked https://crates.io/search?q=quickcheck and try to access it by just clicking you get a yanked version.

But if instead you go to direct link you'll get 0.4.1 https://crates.io/crates/quickcheck

Would be nice to align the behavior(preferably if search would lead to latest non-yanked version)

**Comment by Majora320** [comment]
Same for one of my crates (steamid-ng). Would really love for this to get fixed.

**Comment by carols10cents** [comment]
Closing as a duplicate of #510. Thanks!
