### ISSUE TITLE
Timezone confusion in "Last Updated"

### ISSUE THREAD

**Issue by sfackler** [rust-lang/crates.io#1160]
I'm in PST, so it seems like there's some UTC vs local time confusion somewhere.

![capture](https://user-images.githubusercontent.com/1455697/32479693-eddfb9fa-c33f-11e7-98f1-dcfeeef8a31b.PNG)

**Comment by carols10cents** [comment]
Yep, we're working on it. Closing as a duplicate of https://github.com/rust-lang/crates.io/issues/1123.
