### ISSUE TITLE
merge toml docs

### ISSUE THREAD

**Issue by setharnold** [rust-lang/crates.io#1163]
Hello, I'd like to suggest merging all the documentation about the Cargo.toml file into one webpage.

Somehow I never find the information I need on the first page I land on when searching, and doing multiple "find in page" searches across multiple pages is more work than doing it on a single page.

I propose merging these pages into a single page:

http://doc.crates.io/manifest.html
http://doc.crates.io/pkgid-spec.html
http://doc.crates.io/build-script.html
http://doc.crates.io/config.html
http://doc.crates.io/environment-variables.html
http://doc.crates.io/specifying-dependencies.html

I'm less convinced about merging in 'the guide':

http://doc.crates.io/guide.html

strictly because I can see the value in a short and sweet walkthrough. Two pages would still be easier for me than the current maze of twisty pages all alike.

Thanks

**Comment by carols10cents** [comment]
Hi, the cargo docs are actually in the cargo repo. Mind moving this issue over there? Thanks!
