### ISSUE TITLE
Test timezone handling on backend

### ISSUE THREAD

**Issue by jtgeibel** [rust-lang/crates.io#1164]
As discussed in #1146, it would be nice to test the date format to ensure proper timezone handling.  This could be done by setting the time to a specific value and checking the output against a static string.

**Comment by celaxodon** [comment]
Hi, I'd like to take a shot at this one.

**Comment by sgrif** [comment]
It's worth noting that time zone handling is basically internal to Diesel and completely handled there. We should be careful to make sure we're testing "actual things that are in crates.io" and not just things that are well tested elsewhere.

(The TL;DR of Diesel's time zone handling is "it's UTC")

**Comment by carols10cents** [comment]
> It's worth noting that time zone handling is basically internal to Diesel and completely handled there.

@sgrif this test is for the JSON formatting of times, [which we broke](https://github.com/rust-lang/crates.io/issues/1123) and has nothing to do with diesel.

**Comment by sgrif** [comment]
Gotcha. Sorry, I misunderstood
