### ISSUE TITLE
GitHub org/team names should be treated case insensitively

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#1167]
See https://github.com/rust-lang/cargo/issues/4019#issuecomment-343606443.

GitHub treats organizations case insensitively; you can visit either github.com/ParityTech or github.com/paritytech and these are the same organization. This is probably the same for teams as well, but we should check this.

We're not currently treating teams.login in a case-insensitive fashion. We should:

- run a migration to LOWER all teams.login values
- change the uniqueness constraint on teams.login to be unique on LOWER
- always look up teams in the database using the user's input lowercased
- when comparing the team name to team slugs in github API responses, always lower the team slug from github
- add some tests that ensure adding teams to crates using different casing works

**Comment by cgati** [comment]
I'm interested in giving this issue a try.

**Comment by carols10cents** [comment]
@cgati awesome!!! Please let me know if you have any questions!!

**Comment by cgati** [comment]
@carols10cents I have what I believe to be a working fix, however I'm getting hung up on creating a test case. I intend to mimic the existing `add_team_as_member` test, but providing a body with mixed case org:team values. I'm stuck when it comes to creating appropriate `http_data`, however. Is there any guidance you could provide in this regard?

**Comment by carols10cents** [comment]
Sure! So what I usually do is copy an existing http_data file, it's a lot easier than trying to record a new one. Since you're mimicing `add_team_as_member`, the `team_add_team_as_member` file should be a good one to copy. It should get the same name as the test name you're creating (plus `team_` to start since it's in the `team.rs` file).

I wouldn't worry about testing what would happen if GitHub sends back data with some uppercase, since that would involve editing what GitHub is returning in these http_data files.

Does that make sense?

**Comment by cgati** [comment]
Thanks, I appreciate it! I ended up with that last night and submitted a [pull request](https://github.com/rust-lang/crates.io/pull/1171) which passed the linter originally but failed rustfmt. I remedied that, but the formatted code now fails the linter. Going to have to look into what I can do to pass all tests after work.

**Comment by tamird** [comment]
Instead of downcasing all the data and adding custom logic, why not have the database do it for you? https://www.postgresql.org/docs/current/static/citext.html

Looks like this was already done :( this issue should be closed?

**Comment by carols10cents** [comment]
yep, thanks!
