### ISSUE TITLE
Location of the guide?

### ISSUE THREAD

**Issue by parkr** [rust-lang/crates.io#117]
Ahoy,

I was just digging a little deeper, building something temporally-based. I realized I needed the `time` package... but had no idea how to specify it. The [crates.io guide](http://doc.crates.io/guide.html) does not include the incantation:

```toml
[dependencies]
time = "0.1.12"
```

I had no idea how that was supposed to be structured and stumbled upon it because I've been following the TOML spec since its inception when Tom wrote me over Skype about this crazy new idea he had because he was raging about YAML.

Anyway, I'd really like to update the guide linked above with this data but cannot seem to track down the file with its contents. I looked in this repo and several others on this org – sadly nothing came of that endeavor. The Ember app here seems to have a reference to a guide, but the template is entirely empty (well, just an `{{ outlet }}`), so I'm at a loss. I'm happy to contribute, but the path getting there is not an easy one.

Everything is terrible, and my attempts to make it better are constantly being thwarted. So I open this issue in hopes that some kind soul will be able to shed some light on whereabouts that source is. Have a lovely evening, all.

**Comment by parkr** [comment]
Ok, I finally found it. https://github.com/rust-lang/cargo/pull/1183

**Comment by huonw** [comment]
The docs [are in the cargo repo](https://github.com/rust-lang/cargo/tree/master/src/doc), and yeah, the guide was written before crates.io existed, so it is definitely outdated e.g. https://github.com/rust-lang/cargo/issues/1035
