### ISSUE TITLE
For less common crates, the downloads' graph makes little sense

### ISSUE THREAD

**Issue by Xion** [rust-lang/crates.io#1172]
E.g. https://crates.io/crates/cargo-cult, https://crates.io/crates/rofl, and countless others

It seems like each point on the graph shows a 7-day running average. While unexpected, this is basically fine if the crate is popular and is being downloaded hundreds of times per day. The reader can still interpret it as the _actual_ daily download count because graphically, there is little to no difference.

But if a crate is fetched only a single-digit of times per day, you can see "fractional download days" which doesn't really make any sense. I think the graph should just draw the per-day data points directly, which would correctly show empty gaps for unpopular crates, while not changing much for the popular ones.

**Comment by dhardy** [comment]
I don't see a problem with this approach myself (averages frequently turn integral amounts into non-integrals). If you look at the stats of some more-used crates (e.g. https://crates.io/crates/rand) then there are clearly two days every week with less activity, hence a weekly-running-average seems a good choice.

**Comment by locks** [comment]
Is this still applicable? I feel like something in the UI has changed meanwhile.

**Comment by smarnach** [comment]
The graph shows the actual daily download numbers as dots. In addition it shows the seven-day averages as stacked lines.

However, this is probably not obvious to everyone looking at the graph, so we should add some explanation.

**Comment by Turbo87** [comment]
> Is this still applicable? I feel like something in the UI has changed meanwhile.

Nope, this is no longer applicable due to the recent changes :)
