### ISSUE TITLE
Moving  crates documentation to different domain

### ISSUE THREAD

**Issue by rohitjoshi** [rust-lang/crates.io#1175]
I know this has been discussed multiple time but many companies block  `.rs` domain for security reasons and we are not able to access  https://docs.rs  at work. 

See question I had posted earlier.

https://www.reddit.com/r/rust/comments/63fv2n/rust_documentation_through_comdocs_domain_rs/

**Comment by carols10cents** [comment]
Thank you for this issue!

If you're talking about the documentation of crates.io itself, which is primarily meant for those who are working on crates.io, once you have crates.io's code locally you can run `cargo docs` and have the docs locally available.

If you're talking about the documentation of any crate, the same workaround works, but changing the URL of docs.rs itself should be [filed as an issue on that repo](https://github.com/onur/docs.rs).

If you're suggesting that crates.io blacklist the documentation of any crate who chooses to host their documentation on docs.rs, crates.io isn't going to do that. Getting people to switch from docs.rs to something else is a broader community issue that should be discussed on [the users forum](https://users.rust-lang.org/) or similar and will be a much larger effort.
