### ISSUE TITLE
crate page does not have description

### ISSUE THREAD

**Issue by vitiral** [rust-lang/crates.io#1178]
# Only the list view has the description:
![list-view](https://user-images.githubusercontent.com/5587659/33332466-9718531e-d421-11e7-9b6d-e229a4d781bd.png)

# In the crate view it cannot be found
![crate-view](https://user-images.githubusercontent.com/5587659/33332465-96f2c0cc-d421-11e7-9fc3-c7699735a20e.png)

**Comment by Turbo87** [comment]
@vitiral the description is usually replaced by the README for those crates that have one. so I guess this is actually intentional in the current design.
