### ISSUE TITLE
Remove (yank?) entire libraries from Crates.io

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/crates.io#118]
I accidentally uploaded a library with the wrong name (accidentally prefixed 'rust-' in the crate name).

https://crates.io/crates/rust-gpx instead of https://crates.io/crates/gpx

I'd like to delete rust-gpx from the registry. I tried to yank its only version and got this:

```html
~/D/r/rust-gpx (master|✔) $ cargo yank --vers 0.0.1 rust-gpx
    Updating registry `https://github.com/rust-lang/crates.io-index`
Press ENTER or type command to continue
        Yank rust-gpx:0.0.1
failed to yank: failed to get a 200 OK response: Response {502, via: 1.1 vegur, content-type: text/html, content-length: 166, date: Wed, 21 Jan 2015 01:29:35 GMT, connection: keep-alive, server: nginx, <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
]
```

**Comment by alexcrichton** [comment]
I think the error you're seeing is https://github.com/rust-lang/crates.io/issues/76, and in general we don't want to promote deletion of crates after they've been uploaded (as it would break any dependencies). In this case though I've deleted the `rust-gpx` crate for you.

**Comment by frewsxcv** [comment]
Thanks @alexcrichton

**Comment by kirillkh** [comment]
I have the same problem with monitor_rs. I want to publish it as just "monitor".
