### ISSUE TITLE
Make changelog info available on crate page

### ISSUE THREAD

**Issue by LeopoldArkham** [rust-lang/crates.io#1187]
I was thinking it might be nice to have the ability to display changelog information for a crate. At the simpler level, this might mean rendering a `CHANGELOG.md` file, if one exists, in a sibling tab to the main description. I wouldn't want it to be immediately visible because that would crowd the page.

A more advanced version might parse this information and display it jointly with the existing links to each relevant version. This would require a specific format to be established and probably adds more complexity to the interface than necessary, though.

I see two advantages to this:
- It's a good indication of the health and activity level of a crate. A new version that fixes a documentation type isn't the same as one that introduces new features, speedups, bug fixes, etc.
- It keeps the information about breaking changes in the same place that you would already be consulting if considering whether or not to update a dependency.

**Comment by carols10cents** [comment]
Hi! There's an [open RFC](https://github.com/rust-lang/rfcs/pull/2129) for this with extensive discussion on implementation, so I'm going to close this in favor of the RFC. Thanks

**Comment by LeopoldArkham** [comment]
My bad, I only searched the issues.
