### ISSUE TITLE
Crate author email forwarding

### ISSUE THREAD

**Issue by carllerche** [rust-lang/crates.io#1197]
It would be nice if crates.io offered some sort of email forwarding. Something like all emails to `http@crates.io` would be forwarded to the owners of the `http` crate.

This would allow the email forward to be listed in the `Cargo.toml` and have "ownership" managed in one place.

**Comment by Turbo87** [comment]
this sounds relatively complex to implement and as there hasn't been any activity on this issue in quite some time I'll go ahead and close this for now.
