### ISSUE TITLE
User Agent logs

### ISSUE THREAD

**Issue by withoutboats** [rust-lang/crates.io#1198]
Do we currently keep logs of the User Agent passed with each request to the API? If not, could we start keeping it, and publish the User Agent data?

cargo sets a user agent which includes what version of cargo is being used. This would be extremely valuable telemetry about what versions of Rust people are actually using.

**Comment by carols10cents** [comment]
As of 4138c08a60783fe487e646b305587325b2716a24, we are logging user agent in papertrail, the log drain service we use! I'm not sure the best way to extract+publish the cargo versions from there -- how often would that information be useful? Where should it be published?

**Comment by smarnach** [comment]
I think this issue is about making aggregates over the user agents available, not the full logs.

We could, for example, run a daily aggregation job that adds a histogram of user agent strings for the past day to the database, and include that table in the public dump.

**Comment by kzys** [comment]
Yes. Rust developers want to know the versions of Rust and crates.io contributors may want to know the versions of browsers.

**Comment by djc** [comment]
If someone could write up a few sentences of instructions (for example, places in the code that are relevant, database schema changes that might be necessary), I'd be interested in having a look at this.

**Comment by djc** [comment]
This is very cool! Is a blog post (or at least a tweet/toot) on this forthcoming?

**Comment by Turbo87** [comment]
@djc there have been a couple of unofficial tweets/toots, but nothing official yet. there are two reasons for that: a) our usage of DataDog is still in experimental phase so we can't promise stability yet, and b) we are working on changing downloads to go directly to the CDNs in which case we need to change the pipeline that generates this dashboard.

once these two blockers are cleared we can announce it a bit more officially :)
