### ISSUE TITLE
"nightly binaries" are one-year old

### ISSUE THREAD

**Issue by bluehood** [rust-lang/crates.io#1202]
As discussed in [this PR](https://github.com/rust-lang/cargo/issues/4785) in the cargo repository, the linux 64-bit binaries available at http://doc.crates.io/#install-nightly-cargo are broken in Debian 9 and Ubuntu 16.04 due to certificate issues -- almost surely caused by the "nightly binaries" actually providing the old rust cargo 0.16.0-nightly

**Comment by carols10cents** [comment]
Hi, sorry, Alex directed you incorrectly, the docs at doc.crates.io actually live in the cargo repo, so I'm going to move this issue back over there :) Thanks!
