### ISSUE TITLE
Don't rewrite existing docs.rs links

### ISSUE THREAD

**Issue by DoumanAsh** [rust-lang/crates.io#1206]
Today I published two crates since winapi got update.

https://crates.io/crates/windows-win
https://crates.io/crates/clipboard-win

In both cases crates.io ignores my package.documentation attribute and instead enforces own link to docs.rs

Thanks to that instead of pointing to docs.rs for windows platform as I specified:
```
documentation = "https://docs.rs/windows-win/2.1.0/x86_64-pc-windows-msvc/windows_win/"
documentation = "https://docs.rs/clipboard-win/2.1.0/x86_64-pc-windows-msvc/clipboard_win/"
```

It points to:
```
https://docs.rs/windows-win/2.1.0/
https://docs.rs/clipboard-win/2.1.1/
```

It is not really nice since in past crates.io did not ignore this attribute and windows only crates need a way to point on windows platform docs as otherwise it points to empty docs.

The same shit happens to winapi

**Comment by retep998** [comment]
I'm *really* hoping this is just a bug that will be fixed soon and not an intentional design decision to screw over developers of Windows specific crates.

**Comment by DoumanAsh** [comment]
I suspect it is due to this commit https://github.com/rust-lang/crates.io/pull/676/files#diff-3b42270ea1ffeadfd86a176b30af0adfR39

**Comment by steveklabnik** [comment]
> not an intentional design decision to screw over developers of Windows specific crates.

Come on, man.

**Comment by retep998** [comment]
People *continue* to be confused by the **broken** documentation links that crates.io provides. https://github.com/retep998/winapi-rs/issues/582

**Comment by Turbo87** [comment]
I've just tried this out with https://docs.rs/windows-win/ and it does seem to use the `default-target` from the `Cargo.toml` file now, so I'll go ahead and close this issue since it does not seem relevant anymore.
