### ISSUE TITLE
`Shift+S` doesn't focus the search bar like in rust docs.

### ISSUE THREAD

**Issue by hherman1** [rust-lang/crates.io#1208]
See title! On firefox nightly.

**Comment by Turbo87** [comment]
![bildschirmfoto 2017-12-20 um 13 44 46](https://user-images.githubusercontent.com/141300/34207729-001759d4-e58c-11e7-935b-8b5572a88787.png)

as written in that placeholder you just need to hit the <kbd>S</kbd> key without using <kbd>Shift</kbd>

**Comment by sgrif** [comment]
Should we change that placeholder to say `Click or press 's' to search...`?

**Comment by Turbo87** [comment]
oh... now I see the problem! 😄 

I think we can make it work with both <kbd>Shift</kbd> + <kbd>S</kbd> and <kbd>S</kbd> 🤔
