### ISSUE TITLE
Add an option to order crates by last updated time

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#1210]
Add to at least the API (and may as well add to the UI as well) the option to sort by last updated.

Crates' last_updated time is changed when a new version is published. This sort should put crates that have had a new version published most recently first. 

This should be as straightforward as adding an ORDER BY; this is *not* a stream of new versions. That is, if this set of events happens:

- 3 days ago: crate A published version 1.0.0
- 2 days ago: crate B published version 0.5.0
- 1 day ago: crate A published version 2.0.0

The list of crates ordered by last updated time should be:

- 1 day ago: crate A
- 2 days ago: crate B

As opposed to:

- 1 day ago: crate A
- 2 days ago: crate B
- 3 days ago: crate A

**Comment by moore3071** [comment]
I'd like to go ahead and tackle this, but I have two clarifying questions first.

1. Has there been any progress on #630. If not would it be possible to get a one-time sanitized snapshot for working on this?
2. Should we discuss breaking down the `Krate::search` function as mentioned [here](https://github.com/rust-lang/crates.io/blob/master/src/krate/search.rs#L29)?

**Comment by carols10cents** [comment]
There has not been any progress on #630, and unfortunately I don't have time in the near future to make a recent sanitized snapshot. 

I think it should be possible to publish just a few crates and versions to your local crates.io to get enough data for testing this out-- instructions are [here](https://github.com/rust-lang/crates.io/blob/master/docs/CONTRIBUTING.md#publishing-a-crate-to-your-local-cratesio). Let me know if there are any problems with the instructions!

If you'd like to try refactoring `krate::search`, please feel free!! I don't want to make that a precondition of this change, though, so it's up to you :)

**Comment by moore3071** [comment]
I unfortunately can't publish any crates to my local crates.io until #1254 is resolved, and therefore won't be able to properly deal with this until that issue is resolved.

Since I'd be hesistant to work on an issue that somebody else has called dibs on, I'd like to say that anyone can go ahead and take on this issue in the meantime

**Comment by moore3071** [comment]
Now that my issue with my local crates.io is resolved, I was able to address this issue. I didn't refactor `krate::search`, but the new functionality is in place along with access to it from the frontend.

**Comment by jtescher** [comment]
@carols10cents can this issue now be closed as well? Seems like the work has been done.

**Comment by carols10cents** [comment]
Sounds good!
