### ISSUE TITLE
crate demo/example screenshot gallery browse mode

### ISSUE THREAD

**Issue by dobkeratops** [rust-lang/crates.io#1218]
Imagine a convention for producing a screenshot or image indicative of what a crate does - and having a page on crates.io which browses these images in gallery format (with additional textual/tag search refinement) - 

Obviously this is not suitable for everything (since many libraries are more abstract in nature), but for the domains where it is suitable it would make sifting through the rust ecosystem a more visually engaging experience; such a browse mode might *encourage* people to make interesting visualizations/tests/demonstations.

( I suppose you could display a little dependancy graph or something by default if nothing is given). 

I know that images can be shown in the crate's own page that gets rendered in the site: but the point would be a mode where something like this is visible *before* you've decided to click on that .. self-advertising for the crate.

**Comment by Turbo87** [comment]
since this proposal hasn't received a lot of feedback in the past two years I'll go ahead and close this issue. crates.io now renders the README of the crates, so if relevant, screenshots can be added there.
