### ISSUE TITLE
Page Up / Page Down / Space bar don't scroll

### ISSUE THREAD

**Issue by bluss** [rust-lang/crates.io#122]
Paging through the website may stop working in Firfox if I just click the content once.

On loading: http://doc.crates.io/build-script.html  it pages fine, but clicking the content once it stops responding to the page up/page down keys or equally space / shift space.

This happens often enough in regular use of the website that I consider it a problem.

**Comment by alexcrichton** [comment]
Could you elaborate a bit on what you mean by "click the content"? I tried this out and it all worked as expected to me.

**Comment by steveklabnik** [comment]
I am also experiencing this erorr, and have for a while, but have been lazy in reporting.

Basically, if you click in the main window, which normally ensures that the arrow keys work, they don't.

I'm also seeing this:
![2015-01-26-102411_42x191_scrot](https://cloud.githubusercontent.com/assets/27786/5902080/84335a68-a545-11e4-857b-819d8ea1a617.png)

**Comment by bluss** [comment]
Yes, same scrollbars. My firefox is old though, on debian (v 31), what about you Steve?

Click the content meant click anywhere inside the light colored background of the text or the text itself. I guess it was bound to be frustrating anywhere it does not reproduce.

**Comment by steveklabnik** [comment]
Yup, I'm on debian too! 31.2.

**Comment by carols10cents** [comment]
Are yinz debian folks still seeing this bug?

**Comment by bluss** [comment]
Seems to be gone. Firefox (esr) 45.7.0

**Comment by carols10cents** [comment]
Cool, thanks! ❤️
