### ISSUE TITLE
Not getting email

### ISSUE THREAD

**Issue by carllerche** [rust-lang/crates.io#1224]
I was added as an owner to a crate, but there was no effect.

Supposedly, an email is sent to invite a new owner. However, I have not received any email and it did not go to my spam folder either.

**Comment by carols10cents** [comment]
We haven't implemented emails for crate invitations yet. Do you see a pending invite if you go to https://crates.io/me/pending-invites (from the user menu)?

**Comment by carllerche** [comment]
Ah, yes. The invite is listed there. I had no idea that page was there. Thanks.
