### ISSUE TITLE
License for this repository?

### ISSUE THREAD

**Issue by wking** [rust-lang/crates.io#1225]
I'd like to transition from `/` to `AND` or `OR` in crates.io's `Cargo.toml` (compare rust-lang/cargo#4920). My guess is that the intended license is `MIT OR Apache-2.0` because that's the same semantics [Rust uses for most of its code][1].

This repository only recently gained a similar human-readable explanation.  The first mention of “Apache” in this repo landed in fbdf1575a (2014-06-29) with a file header that included a similar human-readable license grant (great, but just for that file).  Then 7a2b8894d (2014-10-20) landed `LICENSE-APACHE` (and `LICENSE-MIT`) but no human-readable grant (e.g. in the README or a COPYRIGHT file).  4b07668170 (2015-01-12) dropped the one file that had an `Apache-2.0 OR MIT` grant header.  4c4381169 (2017-04-26) landed [the current human-readable explanation][2].  663ffc7538 (2017-04-28) added `license` information to `Cargo.toml` with the [underspecified][3] `/` form.

I expect we can express the expectations of most contributors by changing our current:

    license = "MIT/Apache-2.0"

to:

    license = "MIT OR Apache-2.0"

However, without local docs unpacking the meaning (like [Rust][1] has), it's not clear to me whether all 130+ crates.io contributors had the same impression of the intended license.  Are the crates.io maintainers comfortable making the update without contacting all of those contributors?  Or would they rather assume that the contributors were familiar enough with the Rust ecosystem to interpret `/` as `OR`?  What were the intentions of folks who first contributed before 4c4381169 (~⅔ of contributors) when this repository had just `LICENSE-APACHE` and `LICENSE-MIT`?  What about before 7a2b8894d (only @alexcrichton, @stefanpenner, @sfackler, and @wycats) where this repository had no project-wide licensing information at all?

[1]: https://github.com/rust-lang/rust/blob/1.23.0/COPYRIGHT#L16-L19
[2]: https://github.com/rust-lang/crates.io/blame/6802c0500a3fd6aa532af187d9dc1b5160354b33/docs/ARCHITECTURE.md#L13
[3]: https://github.com/rust-lang/cargo/issues/2174

**Comment by sfackler** [comment]
I believe the `/` is pretty universally understood to mean "your (the consumer's) choice of MIT or Apache/2.0" - it's been described that way in the Rust FAQ for years IIRC.

I hereby relicense my old contributions under `MIT OR Apache-2.0` if that's relevant :)

**Comment by wking** [comment]
On Tue, Jan 09, 2018 at 07:12:55PM +0000, Steven Fackler wrote:
> I believe the `/` is pretty universally understood to mean "your
> (the consumer's) choice of MIT or Apache/2.0" - it's been described
> that way in the Rust FAQ for years IIRC.

The FAQ entry is here [1], and (like [2]) I think the language there
is pretty clear.  But those are both *for Rust*, and they don't
mention the ‘/’ syntax.

There are other cases like rust-egl that are using ‘/’ for AND [2,3],
although I'm not sure how common that is.  Perhaps it is rare enough
that we can assume all crates.io contributors understood *this* ‘/’
instance to mean OR?

[1]: https://www.rust-lang.org/en-US/faq.html#why-a-dual-mit-asl2-license
[2]: https://github.com/rust-lang/rust/blob/1.23.0/COPYRIGHT#L16-L19
[3]: https://github.com/servo/rust-egl/blob/v0.2.0/Cargo.toml#L7
[4]: https://github.com/rust-lang/cargo/issues/2174
