### ISSUE TITLE
Unable to view documentation for older releases

### ISSUE THREAD

**Issue by gaurikholkar** [rust-lang/crates.io#1229]
For log=0.3.9 and lower versions, the link behind log documentation doesn't work. It needs to be changed as per versions for ex `https://docs.rs/log/0.3.8/log/` instead of `https://doc.rust-lang.org/log/log/index.html`
```
log

A Rust library providing a lightweight logging facade.

Build Status Build status

    log documentation[https://doc.rust-lang.org/log/log/index.html]
    env_logger documentation
```

**Comment by sgrif** [comment]
This is the result of rendering that project's README, not something that crates.io is generating. You can open an issue on that project to address an issue with their README, though as you've mentioned, the latest version is pointing where it should be. Packages cannot be changed once they've been uploaded. The documentation link that crates.io generates (which is based on the Cargo.toml file or defaults to docs.rs) is correct for all versions.
