### ISSUE TITLE
Search field not cleared back when going back into history

### ISSUE THREAD

**Issue by nox** [rust-lang/crates.io#1230]
## Steps to reproduce

 1. Go to crates.io;
 2. Type `rayon` and press <kbd>Enter</kbd>;
 3. Go to previous page.

## Expected result

The search field is empty.

## Actual result

The search field still contains `rayon`.

**Comment by nox** [comment]
Any news on this?

**Comment by Turbo87** [comment]
I don't necessarily see this as a bug, more as an implementation detail. Can you share why you think that this is a significant issue for you?

**Comment by nox** [comment]
That's how virtually all websites behave, I don't see how you can claim that this is an implementation detail.

**Comment by Turbo87** [comment]
try entering something in the GitHub search bar above and then press e.g. the "Issues" tab. a regular website would have cleared the search bar input, but GitHub didn't. I don't think "virtually all websites" is a correct assessment here.
