### ISSUE TITLE
Automatically build packages on crates.io on various platforms

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/crates.io#124]
<a href="https://github.com/pornel"><img src="https://avatars.githubusercontent.com/u/72159?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pornel](https://github.com/pornel)**
_Saturday Jan 31, 2015 at 23:13 GMT_

_For earlier discussion, see https://github.com/rust-lang/cargo/issues/1257_

_This issue was labelled with:  in the Rust repository_

---

It would be great if crates.io provided a build bots running on various platforms and marked on which platforms the package builds (and passes tests?) successfully.
- This would help detect packages that don't work on Windows or other systems (and perhaps allow users to filter out such packages from search results).
- It would help detecting missing (undeclared) dependencies and "works on my machine!" errors.

**Comment by Turbo87** [comment]
while this does seem like a great idea, it does not look like we'll have the resources to do something like this any time soon. I'm going to close this issue for now and we can reopen in case our resource availability changes significantly in the future.
