### ISSUE TITLE
Badge alt-text appears to be part of crate title

### ISSUE THREAD

**Issue by SamWhited** [rust-lang/crates.io#1241]
If a badge does not load on crates.io the alt-text is shown but it appears to be part of the surrounding content. It should be distinguished in some way (eg. a smaller colored link). For example, imagine if both badges in the following screenshot had failed to load:

![imagetitle](https://user-images.githubusercontent.com/512573/35166343-2f973ce0-fd17-11e7-9816-b6c161049497.png)

**Comment by sgrif** [comment]
This is the behavior of the browser, not crates.io. I don't believe we have any control over this.

**Comment by SamWhited** [comment]
Could the badges not be moved into spans that are styled differently? Then if the image fails to render they wouldn't be a part of the title.

**Comment by nox** [comment]
This is definitely in control of crates.io, the badges are in the same `<div class=info>` as the crate name. Btw, why are those using `div` elements instead of title-related ones?

**Comment by kornelski** [comment]
Text styles set on `<IMG>` affect rendering of the alt text.

**Comment by Turbo87** [comment]
closing this issue due to https://github.com/rust-lang/crates.io/pull/2440 being merged :)
