### ISSUE TITLE
API documentation, discussion

### ISSUE THREAD

**Issue by moore3071** [rust-lang/crates.io#1245]
Is there any documentation for the crates.io API currently? If so, then would it be possible to link to it on crates.io? (both where it is mentioned on the homepage and maybe in the docs dropdown)

If there isn't any documentation currently, then it might fit best in the documentation of krate.rs. https://docs.rs/cargo-registry/0.2.1/src/cargo_registry/krate.rs.html#550-570 mentions GET /crates route, and could easily include information such as parameters.

A super brief form of documentation could even be added in the form of a descriptive JSON response to the base api/v1/ endpoint like Github's page at https://api.github.com/

**Comment by carols10cents** [comment]
No, there is not any documentation for the API right now. Please see these related issues:

- https://github.com/rust-lang/crates.io/issues/741
- https://github.com/rust-lang/crates.io/issues/731
- https://github.com/rust-lang/crates.io/issues/912

**Comment by moore3071** [comment]
Thanks @carols10cents! I don't know how I missed those first two issues. This issue can probably be closed now as it adds little else to the conversation, but I'll leave that to your discretion.
