### ISSUE TITLE
relm readme incorrectly rendered as markdown

### ISSUE THREAD

**Issue by mattico** [rust-lang/crates.io#1246]
I think that [`readme_to_html`](https://github.com/rust-lang/crates.io/blob/4969e7a901b4ad9fa71da505d22560c852baeac3/src/render.rs#L227) is supposed to ignore non-markdown files, but relm's asciidoc readme is incorrectly rendered as markdown: https://crates.io/crates/relm

![image](https://user-images.githubusercontent.com/853158/35303768-b8827e72-0058-11e8-865f-7af4b00234a8.png)

**Comment by sgrif** [comment]
It looks like that version was published before the change to handle non-markdown readmes was deployed. Recent versions are no longer rendered as Markdown.
