### ISSUE TITLE
Badge for projects that follow the style guidelines

### ISSUE THREAD

**Issue by lahwran** [rust-lang/crates.io#125]
This was proposed on irc (in the main #rust channel on moz) and someone suggested I mention it here. :D

I'm not sure it's a boolean value so much as gradations - you can entirely follow the style guidelines, but some of the guidelines are more important than others. two space indentation is less annoying than tab indentation, which is less annoying than UpperCamelCase function names.

**Comment by Turbo87** [comment]
since there hasn't been any movement on this in quite some time I'll assume there is not much need for this and will go ahead and close this for now.
