### ISSUE TITLE
[search] Package versions are not text

### ISSUE THREAD

**Issue by behnam** [rust-lang/crates.io#1252]
In the search rusult page, like <https://crates.io/search?q=unic>, the package versions are images, making then not *findable* in the browser.

IMHO, using an HTML/CSS/SVG approach would better here, or even having the version as plain/rich text instead of badge.

One indicator of the version being different from other badges is the fact the the version badges are not linked, because they are local data.

What do you think?

**Comment by sgrif** [comment]
It used to be text, and was changed to be an image in https://github.com/rust-lang/crates.io/commit/00888f81. I agree with all the points made in that commit.
