### ISSUE TITLE
SSL error with local crates.io

### ISSUE THREAD

**Issue by moore3071** [rust-lang/crates.io#1254]
I tried to run `cargo publish --index=my_path/tmp/index-co` after following the instructions in `docs/CONTRIBUTION.md`. I then received the following error:

``
error: [35] SSL connect error (error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol)
``

I traced the error back to [this](https://github.com/openssl/openssl/blob/master/ssl/record/ssl3_record.c#L250) block from openssl by using openssl's CLI. I've also attached two files for some extra info:
[cargo_publish.txt](https://github.com/rust-lang/crates.io/files/1718141/cargo_publish.txt)
[openssl_test.txt](https://github.com/rust-lang/crates.io/files/1718142/openssl_test.txt)

relevant environment info:
- OpenSSL 1.1.0g  2 Nov 2017
- OS: Linux
- distro: Arch

It appears that the response from the local crates.io server to the initial ClientHello is  smaller than an SSLv2 ServerHello which forces cargo publish to abort.

**Comment by moore3071** [comment]
After building an Ubuntu 16.04 environment with Vagrant and setting up crates.io, I received the same error when trying to publish to the Vagrant index from within the Vagrant box. I'm fairly confident in saying the error isn't with my environment  given these facts.

**Comment by jtgeibel** [comment]
@moore3071 what URLs do you have in the `/home/my_user/Documents/code/crates.io/tmp/index-co/config.json` file?  You probably want to just use `http://127.0.0.1:8888`, that is, not https.  If you want to use ssl locally you'll need to put the backend behind nginx or something similar.

**Comment by moore3071** [comment]
I guess I changed that to https at some point. After changing it back, everything worked. Closing this issue as resolved. Thanks, @jtgeibel!
