### ISSUE TITLE
shields.io badge shows prerelease version; should show latest stable version

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/crates.io#1257]
The CSV package (https://crates.io/crates/csv) currently shows both of these at the same time:

<img width="621" alt="screen shot 2018-02-16 at 6 23 48 am" src="https://user-images.githubusercontent.com/547158/36270959-0162310a-12e2-11e8-8836-a25a88b87e4f.png">
<img width="157" alt="screen shot 2018-02-16 at 6 23 54 am" src="https://user-images.githubusercontent.com/547158/36270960-01974da4-12e2-11e8-9ce2-d3de851ac926.png">

It seems the beta thing may be confusing crates.io to not show the correct Cargo.toml line?  I'm not sure, but figured it was worth mentioning.

**Comment by sgrif** [comment]
There's an argument for either the badge or the Cargo.toml line being correct. We should probably decide whether we want to ever consider pre-release versions to be the "latest" version or not.

**Comment by carols10cents** [comment]
We decided in https://github.com/rust-lang/crates.io/pull/577 not to recommend pre-release versions, so the shields.io badge should be changed to match the Cargo.toml snippet.

**Comment by locks** [comment]
This is actually a symptom of the problem described in https://github.com/rust-lang/crates.io/issues/654, so we will track it there. Thanks for reporting!

**Comment by FabijanC** [comment]
Isn't this still an issue? E.g. consider this shield from the URL https://img.shields.io/crates/v/blockifier:
![Crates.io Version](https://img.shields.io/crates/v/blockifier)

And consider these versions:
https://crates.io/crates/blockifier/versions

**Comment by Turbo87** [comment]
yes, but that is an issue on the shields.io side. https://crates.io/api/v1/crates/blockifier returns:

```
max_stable_version: "0.5.0"
max_version: "0.8.0-rc.1"
```

which shields.io could use to display 0.5.0 instead.

**Comment by FabijanC** [comment]
Thanks for pointing this out! I see there is an open issue on their side: https://github.com/badges/shields/issues/8666
