### ISSUE TITLE
Crate page could show what to write in your Cargo.toml

### ISSUE THREAD

**Issue by brson** [rust-lang/crates.io#126]
As a newbie I searched for 'libc' on crates.io, but after I found it I still didn't know how to add it as a dependency. The instructions are easy enough that this page could just tell you what to write.

**Comment by brson** [comment]
It does already basically say what to write, but not that it goes in a '[dependencies]' section, that didn't exist in my Cargo.toml.

**Comment by carols10cents** [comment]
Since `cargo new` now adds a `[dependencies]` section to `Cargo.toml`, I think this can be closed. Please reopen if you feel this isn't the case! ❤️
