### ISSUE TITLE
Enum generate invalid code

### ISSUE THREAD

**Issue by hfiguiere** [rust-lang/crates.io#1261]
The following code:

````rust
#[repr(C)]
pub enum PropertyValue {
    String(String),
    Int(i64)
}

#[no_mangle]
pub extern "C" fn get_int(value: &PropertyValue) -> i64 {
    match value {
        Int(i) => i,
        _ => 0
    }
}
````

generates invalid C/C++ code with cbindgen.
The problem lies in:
````C
struct String;

struct PropertyValue {
  enum class Tag {
    String,
    Int,
  };

  struct String_Body {
    String _0;
  };
````

`String` is declared as opaque, but then used as if it wasn't.

I'm not sure what the proper solution would be short of ignoring the enum altogether.

**Comment by hfiguiere** [comment]
Removing the `#[repr(C)]` works around the problem in my case.

**Comment by jtgeibel** [comment]
@hfiguiere I'm guessing you're refering to this [cbindgen](https://github.com/eqrion/cbindgen).  Please open an issue there if you're still having issues.

**Comment by hfiguiere** [comment]
oops, I really meant to file this in `cbingen`. Not sure why I landed here.... and I didn't pay enough attention. 

Will refile in the right place.

**Comment by hfiguiere** [comment]
I am very sorry
