### ISSUE TITLE
Fuzzy searching

### ISSUE THREAD

**Issue by moore3071** [rust-lang/crates.io#1266]
A big benefit that a lot of the proposed search engines for Crates.io have is fuzzy searching. This **is** possible with Postgres itself. Postgres allows fuzzy searching with a module called [pg_trgm](https://www.postgresql.org/docs/current/static/pgtrgm.html#id-1.11.7.41.8). This module uses trigrams to identify potential mispellings.

This would be a nice enhancement to the current search functionality, but I can't say how it would affect the performance or query time.

**Comment by sgrif** [comment]
Let's centralize discussion in #1270 as this seems closely related.
