### ISSUE TITLE
Feature usage stats

### ISSUE THREAD

**Issue by dhardy** [rust-lang/crates.io#1268]
I love the download stats crates.io shows; it's useful to see which versions get used the most (although sometimes the "other" category can be a large fraction e.g. when several pre-release versions are released).

But to get to the point: it would be nice to see stats for feature usage, i.e. the percentage of dependencies using each optional feature. Ideally this should be by version (since new versions may change avialable features).

**Comment by sgrif** [comment]
Unfortunately, we aren't given any of the information needed to measure this. Making this happen would probably require changes in Cargo (which may require an RFC). I'd open an issue there.
