### ISSUE TITLE
Feed for Dashboard Content

### ISSUE THREAD

**Issue by killercup** [rust-lang/crates.io#127]
You can 'follow' crates but the only place you can see updates is on the dashboard. It would be quite useful to have a RSS/Atom feed for this data (per-user with a secret token in the URL).

**Comment by frewsxcv** [comment]
I just realized there's no RSS library available for Rust. I'm going to start working on one tonight.

**Comment by frewsxcv** [comment]
If anyone comes across this and wants to get started on implementing this crates.io feature, I've got a rss library I've been working on https://github.com/frewsxcv/rust-rss that should help with this

**Comment by Hawk777** [comment]
I personally would like to see this feature as well, but I don’t think there’s any need for it to be per-user or to be authenticated. Why not just give each crate a public RSS feed containing all released versions of that crate? If you want to be notified about new releases of multiple crates, you can just subscribe to multiple crates’ RSS feeds. That also allows you to organize the feeds for different crates however you want in your RSS reader; for example, maybe you want to group together crates that are security-critical (and therefore you want to look at more promptly), or perhaps you want to organize them by which of your own projects consume them. That would be harder to do if you had only a single feed with all the crates you care about mixed together.

**Comment by AntoniosBarotsis** [comment]
I would also be very much interested in this, agree with everything @Hawk777 mentions in his reply. This could be very useful for watching dependencies you really want to stay up to date with.

**Comment by passcod** [comment]
Just noting that if someone was actually interested in a dashboard RSS feed, the closing PR doesn't implement that.

**Comment by Turbo87** [comment]
No, but it's very easy to subscribe to just the crates you're interested in, which is basically equivalent to having a "dashboard feed", but way easier to provide from our side
