### ISSUE TITLE
Is it possible to host your own crates.io?

### ISSUE THREAD

**Issue by vityafx** [rust-lang/crates.io#1272]
In my company we don't want to publish crates to the public service, we would like to publish them in our own corporate server. Sometime ago I heard that `crates.io` in near future will have stand-alone functionality. Is it possible now?

**Comment by carols10cents** [comment]
It is possible; it's not the smoothest experience right now. Follow the instructions in the [CONTRIBUTING.md documentation, especially the section on using your local crates.io with Cargo](https://github.com/rust-lang/crates.io/blob/master/docs/CONTRIBUTING.md#using-your-local-cratesio-with-cargo).

Please open new issues for specific problems with these instructions!
