### ISSUE TITLE
Some crates.io pages load with broken HTTPS icon, due to insecure "meritbadge.herokuapp.com" image URLs

### ISSUE THREAD

**Issue by dholbert** [rust-lang/crates.io#1274]
STR:
 1. Load either of these pages in Firefox or Chrome:
https://crates.io/crates/cargo-update
https://crates.io/crates/actix-web
2. Look at the left edge of your URL bar where you'd expect to see a nice HTTPS lock.

ACTUAL RESULTS:
UI shows that you're not fully secure (orange "!" in Firefox, and an `i` in Chrome). If you click that icon, it tells you some resources (images) weren't loaded securely.

If I right-click the page in Firefox and choose "View Page Info" and then "Media", I can see that these are the insecure URLs:
`http://meritbadge.herokuapp.com/cargo-update`
`http://meritbadge.herokuapp.com/actix-web`

These URLs load just fine if I upgrade them to HTTPS (and indeed, they seem to auto-redirect to HTTPS on their own, anyway).  So: crates.io should just be referencing them directly using an HTTPS url, not an HTTP url.  That should prevent the degraded-HTTPS UI from showing up here (and will prevent some MITM shenanigans).

**Comment by dholbert** [comment]
Here's a screenshot of what this looks like right now (together with the page info dialog showing the one image being loaded with a needlessly insecure http:// url):
![screenshot of degraded HTTPS UI](https://user-images.githubusercontent.com/426803/37545954-fbeeb3c2-2927-11e8-9504-20f2f19cd95b.png)

**Comment by Turbo87** [comment]
those badges are part of the README of those projects. I don't think there's much we can do about that... 🤔

**Comment by dholbert** [comment]
Thanks! Agreed, nothing to be done on the crates.io side then. I'll submit some pull requests to update the URLs in those projects' README files.

**Comment by dholbert** [comment]
Posted pull requests:
https://github.com/nabijaczleweli/cargo-update/pull/76
https://github.com/actix/actix-web/pull/154

**Comment by dholbert** [comment]
Found & fixed a few more of these:
https://github.com/rust-lang/regex/pull/549
https://github.com/dropbox/rust-brotli-decompressor/pull/5

**Comment by DerMolly** [comment]
@dholbert do you know who maintains https://meritbadge.herokuapp.com/ ? Because changing the links on Repos is fine and all, but more importantly the generated link on https://meritbadge.herokuapp.com/ should use https.

**Comment by dholbert** [comment]
I have no idea who maintains it. But I'm not sure how they'd have any control of whether or not repos use http URLs or not when they reference images there.  (I suppose they could turn off HTTP entirely so that only https urls would work, but that's pretty severe.)  The issue here isn't with meritbadge.herokuapp.com itself, but rather with external content using http when referencing URIs at that domain.

Note that HTTP meritbadge URLs do seem to **redirect** to https-provided resources -- e.g. http://meritbadge.herokuapp.com/brotli-decompressor redirects to https://img.shields.io/badge/crates.io-v2.3.0-brightgreen.svg .

**Comment by DerMolly** [comment]
They don't have control over the usage of http-links for badges, except for what you described, but they could update their software to generate markdown with the a functioning https-link. That would make it more likely a https-link ends up on most pages on crates.io

**Comment by dholbert** [comment]
Do you know that this markdown (and the URL) comes from software that they provide?

If so (and if it generates HTTP links) it would surprise me, because this issue is pretty rare -- the vast majority of packages on crates.io are displayed with https badges.  Only a few use/used HTTP urls, and I'm guessing that was human error and/or copypasting from some out-of-date template which has perhaps since been updated (which is why it's rare).

But yeah, I don't know where this markdown actually comes from -- if you do, please pass along the word to them. :)

**Comment by DerMolly** [comment]
I was quite sure that https://meritbadge.herokuapp.com/ generated http links, but when I'm looking now it seems to don't do that. Sorry to bother then.
