### ISSUE TITLE
Version numbers aren't shown when shields.io is busted

### ISSUE THREAD

**Issue by nox** [rust-lang/crates.io#1276]
The version number is nonetheless present in the HTML source, as an `alt` attribute, but the `title` one takes precedence on hover.

On Firefox:

<img width="377" alt="capture d ecran 2018-03-17 a 21 58 11" src="https://user-images.githubusercontent.com/123095/37559892-4f9e8360-2a2e-11e8-8b98-3cac3bddc304.png">

On Safari:

<img width="304" alt="capture d ecran 2018-03-17 a 21 58 36" src="https://user-images.githubusercontent.com/123095/37559895-5d2affe0-2a2e-11e8-83fa-66d98dcf9694.png">

**Comment by sgrif** [comment]
This was fixed in #1354
