### ISSUE TITLE
Feedback on Dependabot

### ISSUE THREAD

**Issue by greysteil** [rust-lang/crates.io#1294]
Hey team,

First up, thanks for all your work on Cargo and crates.io. I just added Rust support to [Dependabot](https://dependabot.com), which now consumes the crates.io API and shells out to Cargo to generate new lockfiles, and both were an absolute breeze to use. In particular, the way `cargo update -p <package name>` works (doing resolution but not pulling down any files) is *fantastic*.

I've got two questions I'd love your help with:
1) Is there an API endpoint I can use to get the latest package releases? I'd like to poll it every 10 minutes so that Dependabot can give people updates "live" if they want them (rather than daily/weekly)
2) I'd really love your feedback on Dependabot, and whether there's anything it could do better when dealing with Rust repos. It's running on my fork of crates.io [here](https://github.com/greysteil/crates.io/pulls) so you can see the PRs it generates - any advice? Ideally I'd *love* to get it to the point where you'd want to run it on this repo. (It's free - I honestly just want feedback.)

Many thanks, and thanks again for Cargo and crates.io.

**Comment by jtgeibel** [comment]
> Is there an API endpoint I can use to get the latest package releases?

I see 2 main options here.  One is to access the index directly.  The other is to add an API to crates.io to support this.

## Track the index directly

Github offers an API where you can [query for the commit SHA of a reference](https://developer.github.com/v3/repos/commits/#get-the-sha-1-of-a-commit-reference).  You could check with that API and pull down the changes if the SHA has changed.  Then analyze the diff of the new commits to detect what new versions are published.

Yank/unyank operations consist of replacing a line (deletion and removal).  Publishing of a new versions or a new crate is a single addition.

Pros: The index is the ultimate truth of what cargo sees when resolving dependencies.  The git log is an append only structure and it is unlikely that we would ever rewrite the commit history.
Cons: May be a bit tricky, especially if you only care about new versions that are published.

## New API on crates.io

Crates.io could add support for an API to query any versions newer than a specific ID number.  The route would return a list of any versions with a higher ID number (or an empty list if it is still the newest).  The API would probably be limited to 100 versions per request.

Pros: Probably simpler for most consumers of the data.
Cons: Doesn't provide any considerations for yank/unyank.

# Feedback

> I'd really love your feedback on Dependabot

Overall this seems like a great addition to the ecosystem!

It may be nice to have an option where breaking version bumps are filed as individual PRs (where CI will quickly flag any breakage that needs to be addressed) and semver compatible versions are batched once a week (where the risk of batching them is low and the PR can probably be merged unchanged).  I think that would strike a good balance for projects with a lot of dependencies.

**Comment by greysteil** [comment]
> I see 2 main options here. One is to access the index directly. The other is to add an API to crates.io to support this.

I didn't realise the index was hosted on GitHub. I can pull from that pretty straightforwardly, so will do that - thanks for the pointer.

> Overall this seems like a great addition to the ecosystem!

Thanks!

> It may be nice to have an option where breaking version bumps are filed as individual PRs (where CI will quickly flag any breakage that needs to be addressed) and semver compatible versions are batched once a week

I think this is great feedback - thanks. I've heard the same thing for the other languages Dependabot supports, so am keen to add that flow.

Thanks so much for taking the time to look through, and for your help.

**Comment by greysteil** [comment]
FYI, I did the index integration yesterday - really straightforward thanks to the format of the commit messages. Thanks for the pointer.

I've also made Dependabot listen for security vulnerabilities published to https://github.com/RustSec/advisory-db, so it's getting pretty good at handling GitHub-as-a-database setups now.
