### ISSUE TITLE
Authorized actions inaccessible: "must be logged in to perform that action"

### ISSUE THREAD

**Issue by badboy** [rust-lang/crates.io#1299]
I am currently unable to do any action on the site. 
Changing the email or generating a token leads to the same error message: 

> ... must be logged in to perform that action

![Screenshot of page with error when trying to generate a token](https://pbs.twimg.com/media/DZtIdCfX0AA8KOw.jpg:large)

Sometimes I also only get a green page without any content on <https://crates.io/me>.
Requires to delete the cookies and re-login to even get to the page.

![Blank green page](https://screenshotscdn.firefoxusercontent.com/images/ddb85986-e533-4ac2-9ad8-6e1a5304aa20.png)

**Comment by carols10cents** [comment]
Yuck. What browser are you using?

**Comment by badboy** [comment]
Tested it in Safari, Chrome and Firefox and all three showed the same problem. Tried again a couple minutes later and was not able to reproduce it unfortunately (and didn't debug it further when it occured).

I'll close this for now and will reopen with more info when I run into it again.
