### ISSUE TITLE
buildpacks file is now out of date

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-lang/crates.io#1337]
rcaught/cmake was yanked so we'll need to update [this](https://github.com/rust-lang/crates.io/blob/master/.buildpacks#L1) to what @alexcrichton updated it to

how is this intended to be maintained? manually?

**Comment by alexcrichton** [comment]
Er sorry forgot to push but this is the change -- https://github.com/rust-lang/crates.io/commit/567ecaea3e004b7c1e1a81d2a13ec83ede447739

**Comment by sgrif** [comment]
Seems like this is resolved then.
