### ISSUE TITLE
Page titles are disappeared

### ISSUE THREAD

**Issue by pravic** [rust-lang/crates.io#1341]
Probably because of #1310.

Despite #423 and https://github.com/rust-lang/crates.io/blob/4c42eaf6738100917219c0632250e13ed07f303e/app/templates/dashboard.hbs#L1

they have gone somehow.

**Comment by Turbo87** [comment]
thanks for reporting the issue. I'm somewhat surprised by this because we have explicit tests for the document titles and they did not fail. will have to investigate why that is... 🤔 

I've opened #1342 which should fix this issue.

**Comment by pravic** [comment]
@Turbo87 Thank you!
