### ISSUE TITLE
Renaming of a github login is handled badly

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/crates.io#136]
Access to all previous crates are lost unfortunately.

**Comment by nulldatamap** [comment]
Is there any plans for this issue to get fixed any time soon? I'm maintaining a crate which was published with my old Github name, since then I've renamed and I don't have the old token any more.

**Comment by alexcrichton** [comment]
@nulldatamap unfortunately I don't have a fix in store, but if you reach out to me on IRC or send me an email I can fix things up manually

**Comment by alexcrichton** [comment]
Now fixed!
