### ISSUE TITLE
Improve package discoverability ala Rust CI

### ISSUE THREAD

**Issue by huonw** [rust-lang/crates.io#138]
[Rust CI's "projects" view](http://rust-ci.org/projects/) feels easier to use to discover interesting packages than crates.io, at the moment.

I think this is partly due to the dense, non-paginated listing and the fact that it's relatively easy to interactively find relevant categories (rather than having to "guess" at keyword names).

I don't think duplicating Rust CI approach directly will scale, but I wonder if there's still some improvements we can make, e.g. maybe we could paginate less aggressively than 10-per-page.

**Comment by robo9k** [comment]
It might also help if keywords weren't case-sensitive (e.g. [vm](https://crates.io/keywords/vm) vs. [VM](https://crates.io/keywords/VM)).
[rustkit.io](http://rustkit.io/) provides another way to browse (some) projects.

**Comment by l29ah** [comment]
Yeah, the current database is a disaster re browsing, comparing to https://hackage.haskell.org/packages/ for instance.

**Comment by carols10cents** [comment]
Now that categories has been deployed and is starting to be used, do yinz feel like this situation has improved? Or is pagination still too aggressive?

**Comment by carols10cents** [comment]
I'm going to close this since I think categories are good enough to solve this problem; please reopen if you think more improvements are needed for this.
