### ISSUE TITLE
Whitelist Apache-2.0 WITH LLVM-exception

### ISSUE THREAD

**Issue by sunfishcode** [rust-lang/crates.io#1382]
The "LLVM Exception" is a new Apache-2.0 relative [registered with SPDX](https://spdx.org/licenses/LLVM-exception.html). It modifies Apache-2.0 by adding an exception for GPLv2 compatibility, and an exception for compiler output. 

It is the license the LLVM project is [planning to transition to](http://llvm.org/foundation/relicensing/), and it's an attractive option for other compiler-related projects as well, because of the strengths of the base Apache-2.0 license, the flexibility granted by the exception clauses, the extensive scrutiny it has received by numerous parties involved in the LLVM license change process, and the fact that LLVM itself is expected to use it.

As such, it's desirable for crates.io to accept it as a valid license option.

**Comment by sgrif** [comment]
Please open an issue on https://github.com/rust-lang-nursery/license-exprs

**Comment by sunfishcode** [comment]
Ah, thanks for pointing me to the right place. I've now filed https://github.com/rust-lang-nursery/license-exprs/issues/21.
