### ISSUE TITLE
moving average graph has an offset relative to points

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/crates.io#1388]
The moving average graph seems to have an offset relative to the points. For example I just looked at the libc crate, and the leftmost eight points for Other are:

* 3253, 3127, 1796, 1611, 3213, 3295, 3102, 3101

The average of the first seven (3253 to 3102) is 2771. Clicking on the eighth point displays:

* Other 7-day avg.: 2771.00
* Other: 3,101
* …

I think the moving average should be shifted by one sample to the left. Though then there might be an issue with the rightmost sample: usually the rightmost point is for an incomplete day, so including thta point in a moving average could look weird, as the moving average would dive down early in the day. I would leave the rightmost sample without a moving average, just like the current situation for the leftmost samples.

And come to think of it, maybe the first few samples should have some value for moving average. Three possible solutions:

1. Get some more data so that the moving average can be calculated even if the past points are not visible directly in the graph. This seems to be the most meaningful though it could be harder to implement. Also there could be an issue where the maximum average is larger than the maximum sample if for example a very high spike in downloads happens to be just to the left of the graph, so vertical scaling would have to consider the maximum average as well as the maximum point (I have no idea whether the graphing code would handle this automatically or not).

2. Substitute zeros for the missing points. I don't really like this, as then the left of the graph would have a weird rise from zero which has nothing to do with actual download numbers.

3. For the first few points, have a narrower moving average. So for example for the points shown above, the first average would simply be 3253, the second would be (3253+3127)/2, and would be labelled 2-day avg. instead of 7-day avg., and so on.

**Comment by sgrif** [comment]
This is the standard way to display a moving average. You typically don't include the current time segment in the moving average, as it makes it harder to see deviations between that particular time segment and the trend
