### ISSUE TITLE
The "Documentation" drop down is not accessible from the home page

### ISSUE THREAD

**Issue by nham** [rust-lang/crates.io#139]
I think this is a poor design. I needed to look up how the features in Cargo.toml work. That documentation is located on the 'Manifest Format' page, but the link to that page is only accessible from the "Documentation" drop down on either the Getting Started page or the Guide page.

There was a previous issue for this, #121, that I believe was incorrectly closed. If I'm looking for documentation on the manifest format, then "Getting Started" is not what I want. I'm already started with Cargo, I don't need to get started. Also the Guide doesn't contain what I want. It is not great to have to navigate to an irrelevant intermediate page to get access to the drop down menu I need. 

Can this be added to the home page? Maybe there could be some kind of central documentation page that the home page links to?

**Comment by TimNN** [comment]
I wholeheartedly agree with this! 

I especially think that both links currently at the top right (Login & List all crates) provide much less value, than a documentation dropdown would provide.

**Comment by birkenfeld** [comment]
I think this can now be closed.

**Comment by alexcrichton** [comment]
Ah I unfortunately had to roll back https://github.com/rust-lang/crates.io/pull/267 because the alignment was off (see screenshot on the PR)

**Comment by carols10cents** [comment]
Looks like this has been fixed since by making the menu label say "Docs" :)

<img width="1072" alt="screen shot 2016-12-14 at 7 30 28 pm" src="https://cloud.githubusercontent.com/assets/193874/21207072/e4feb7f4-c233-11e6-9756-5bd9f36bbc82.png">
