### ISSUE TITLE
add info on crate size

### ISSUE THREAD

**Issue by jaroslaw-weber** [rust-lang/crates.io#1393]
It would be nice to have information about the crate size without downloading it (in the crate's page).

**Comment by jtgeibel** [comment]
Yes, this would be a nice addition.  I recently hit the 10MB limit on a `-sys` crate that was pulling in a lot of code and resources that weren't actually needed for the build.  I probably would have noticed this and trimmed things down sooner if the page on crates.io had shown the size.

I don't think this is tracked anywhere in the database yet, but this is definitely something we could start tracking for newly published versions.  Would you be interested in putting together a PR for review?

**Comment by jaroslaw-weber** [comment]
I will try to send a PR later :)

**Comment by jtgeibel** [comment]
You're right, this has been resolved so I'm closing.  Thanks!
