### ISSUE TITLE
crates.io feature validation inconsistent with cargo/rustc

### ISSUE THREAD

**Issue by iliekturtles** [rust-lang/crates.io#1395]
crates.io's feature validation is inconsistent and rejects features with "." even though these features are accepted by `cargo`/`rustc`. This validation isn't applied when using `cargo publish --dry-run`.

```sh
$ cargo publish
...
   Uploading uom v0.18.0 (file:///S:/uom)
error: api errors: invalid upload request: invalid value: string "1.20.0", expected a valid feature name
 containing only letters, numbers, hyphens, or underscores at line 1 column 931
```

This appears to be the check: https://github.com/rust-lang/crates.io/blob/0ccbf09f492209fa5f91abf98f32583ea3f7ab40/src/views/krate_publish.rs#L110

As a workaround I was able to change the `1.20.0` feature to `1_20_0`.

**Comment by sgrif** [comment]
@alexcrichton Is cargo intended to accept this feature name?

**Comment by alexcrichton** [comment]
Currently yeah it's intended to reject that, we wanted to stick to "mostly rust identifiers" for now

**Comment by sgrif** [comment]
Thanks! @iliekturtles the bug is in Cargo not crates.io. It should be getting rejected there.

**Comment by iliekturtles** [comment]
Great, will submit a new issue this week!
