### ISSUE TITLE
Syntax highlighting incorrectly highlights multiline strings

### ISSUE THREAD

**Issue by mistydemeo** [rust-lang/crates.io#1399]
The [cue crate](https://crates.io/crates/cue)'s embedded README includes a Rust code block with a multiline string. Crates.io's syntax highlighting is tripping over it.

It looks like the syntax highlighting is breaking either because of the multiple lines, or because of the escaped quotes on the first line. As you can see in the attached screenshot, the first line highlights the period in `example.img`, and numbers on all subsequent lines are also coloured.

<img width="403" alt="screen shot 2018-05-20 at 11 38 21 pm" src="https://user-images.githubusercontent.com/780485/40293726-20a239d6-5c87-11e8-9278-34d98a8986c8.png">

**Comment by carols10cents** [comment]
For the syntax highlighting, we use [ember-prism](https://github.com/shipshapecode/ember-prism), which uses [PrismJS](https://prismjs.com/), so this issue would have to be fixed there.

**Comment by locks** [comment]
I've updated ember-prism in https://github.com/rust-lang/crates.io/pull/1853 but it doesn't seem to solve the issue. I'll close this issue and upstream to PrismJS! Thanks for reporting.
