### ISSUE TITLE
Please make are mirror crates.io

### ISSUE THREAD

**Issue by sinitcin** [rust-lang/crates.io#1403]
Hello! In my country government make are block list of IP. And my internet provider block crates.io =( 

Please help me!

**Comment by Rafagd** [comment]
Not sure if this solves your problem, but I saw this link earlier today and it just might: http://www.integer32.com/2016/10/08/bare-minimum-crates-io-mirror-plus-one.html

**Comment by sinitcin** [comment]
Oh, thank you! I get try =) 

На 5 июня 2018 г., 22:29, в 22:29, "Rafael G. Dantas" <notifications@github.com> написал:п>Not sure if this solves your problem, but I saw this link earlier today

**Comment by carols10cents** [comment]
I'm going to close this as a duplicate of #67.
