### ISSUE TITLE
Redirecting 404 is unfriendly

### ISSUE THREAD

**Issue by andersk** [rust-lang/crates.io#141]
https://crates.io/crates/nonexistent redirects to https://crates.io, which makes it hard to correct a manually typed URL and try again. It also breaks the back button.

**Comment by eternaleye** [comment]
Sourceforge has spent the last week demonstrating just how awful this is - it redirecting downloads while the site is broken rather than properly 404'ing has caused real issues for Exherbo's distfile mirroring setup.

**Comment by steveklabnik** [comment]
:+1:

**Comment by comex** [comment]
Bump.

**Comment by steveklabnik** [comment]
This no longer redirects!

**Comment by durka** [comment]
This has come back!
