### ISSUE TITLE
"GPL-3.0-or-later" is not accepted as a valid license

### ISSUE THREAD

**Issue by ProgVal** [rust-lang/crates.io#1435]
I get this when running `cargo publish`:

>error: api errors: unknown license or other term: GPL-3.0-or-later; see http://opensource.org/licenses for options, and http://spdx.org/licenses/ for their identifiers

But "GPL-3.0-or-later" is listed here: https://spdx.org/licenses/

**Comment by sgrif** [comment]
Closing this, since it's an upstream issue
