### ISSUE TITLE
Offload downloads tracking by parsing CDN logs

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/crates.io#1442]
Currently 80% of the requests to crates.io is for download redirects, which also tracks download count. However, this approach has the following issue:

- High write volume to the underlying database. This can be a bottleneck given the high percentage of download requests.
- Non-cachable response, which forces a round trip for every crate. This also prevents a CDN to be used effectively.

The reality is that we don't have to. For example, [RubyGems.org](https://github.com/rubygems/rubygems.org/blob/master/app/jobs/fastly_log_processor.rb) processes Fastly logs directly (which is also awesome because it's providing free services for OSS). This allows complete offload of analytics to the CDN, which is more specialized in processing such log data.

**Comment by ishitatsuyuki** [comment]
As this requires a cron job to collect aggregate stats, a good way (backend) we can start with is to offload all download analytics to Redis and then putting it into database with a cron job.

**Comment by ishitatsuyuki** [comment]
Current blocker:

Due to the fact that CloudFront logs dump can be delayed for typically 1 hour and up to 24 hours, we need to modify things related to the aggregation code somehow.

 - Aggregation stops before even reaching 24 hours: https://github.com/rust-lang/crates.io/blob/4bcb22a208788c94a526684b7fd0a964c10fd317/src/bin/update-downloads.rs#L54

- Regarding the aggregation code, can we use a materialized view instead?

- How far should we go back querying logs? Should it be just for one day, or should we extend it for the whole date range is missing the download counts? Alternatively, should we use a backend-specific "last data fetched" timestamp?

**Comment by ishitatsuyuki** [comment]
@sgrif Do you think using materialized view as above is viable?

**Comment by sgrif** [comment]
We could replace some of our counter cache columns with a materialized view based on some aggregate query based on `version_downloads`, yes. I don't think that change is worth it though. It's just moving some complexity around for no obvious benefit.

I'm also really not sure what the problem you're trying to solve here is. Yes, the way we handle download counting absolutely will become a performance bottleneck at some point in the future. But our traffic will have to increase by more than an order of magnitude before we have to scale our servers, and at least 3-4 orders of magnitude before we get to the point where "make our PG instance beefier" stops being a viable answer.

This is something we have to address in a few years, but I don't think it's the best place to spend time right now.

**Comment by sgrif** [comment]
> If I understand correctly, incremental aggregation on materialized view is fully handled by the DBMS. This means that we can at least get rid of this complicated incremental calculation from the codebase.

Well what we'd be doing is replacing these queries with something to update the views, and then put the logic of these queries in the body of the view, and add some joins anywhere that we need these counts. That's not really simpler, it's just moved the complexity around.

> Apart from server load, it's simply a redundant overhead to the client. The redirect requires a round trip to the server; I want to eliminate it by making the redirect (or response itself) cached.

Given the size of the file download happening after the redirect, I don't think the overhead of a round trip to the server is particularly relevant.

**Comment by ishitatsuyuki** [comment]
> Given the size of the file download happening after the redirect, I don't think the overhead of a round trip to the server is particularly relevant.

No, the entire problem here is latency. It can take nearly a second accessing from a different continent like here, Japan.
Edge cache or edge computing cuts this overhead.

**Comment by Turbo87** [comment]
we've lately switched over to counting the downloads in-memory and regularly syncing the count to the database, instead of  doing it for every endpoint. since the above is not as much of an issue anymore, I'm going to close this issue. if somebody still wants to tackle this, let me know and I will reopen the issue :)
