### ISSUE TITLE
error: failed to invite owners ... It looks like you don't have permission ...

### ISSUE THREAD

**Issue by vi** [rust-lang/crates.io#1446]
```
$ cargo  owner --add github:rust-bus:maintainers 
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to invite owners to crate ...: api errors: It looks like you don't have permission to query a necessary property from Github to complete this request. You may need to re-authenticate on crates.io to grant permission to read github org memberships. Just go to https://crates.io/login
```

I did `https://crates.io/login`, Githus asked for permissions, I accepted, (crates.io got into a sort of redirect loop after that, but it shows my profile page now), but `cargo owner --add` still shows the error.

`crates.io` entry of Github's https://github.com/settings/connections/applications shows one permission: `Read org and team membership`.

**Comment by carols10cents** [comment]
This is confusing, and I'm sorry. Have you granted crates.io permissions to the rust-bus *organization*? To check this, go to https://github.com/settings/applications, click on crates.io, and scroll down to where the organizations are listed. Is the rust-bus org listed there with a green check?

**Comment by vi** [comment]
That's how it looks:

![screenshot](https://user-images.githubusercontent.com/173219/42054738-d919bffc-7b1d-11e8-8c8a-28bca476f3ab.png)

I don't know where to add organisations.

**Comment by carols10cents** [comment]
Hmmmm, that's really strange, this is what that page looks like to me:

<img width="1280" alt="screen shot 2018-06-28 at 10 59 06 pm" src="https://user-images.githubusercontent.com/193874/42071012-faf775e8-7b26-11e8-995b-6606665b2bff.png">

Are you a member of the rust-bus organization?

We have https://github.com/rust-lang/crates.io/issues/997 for improving this error message to be more helpful.

**Comment by vi** [comment]
> Are you a member of the rust-bus organization?

No. I expect membership it to be for maintainers of Rust Bus, not for usual users.

**Comment by carols10cents** [comment]
Ah, well, currently you need to be a member of the team to be able to add the team as an owner of a crate, and we don't have plans to change that requirement.

**Comment by kornelski** [comment]
Sorry for the confusion. That's a dupe of #1366. I've updated our docs to point to another command that doesn't run into this limitation.
