### ISSUE TITLE
Clicking on crates.io search result leads to different page than the direct link.

### ISSUE THREAD

**Issue by samsieber** [rust-lang/crates.io#1452]
If you go straight to the serde_json page from a this link: https://crates.io/crates/serde_json it brings up 1.0.22. If you search for serde_json from crates.io and click on the serde_json crate link, it brings up 1.0.23, which has been yanked.

This was really confusing for me, because I didn't find serde_json on crates.io through a direct link, so thought serde_json had been generally yanked, not just 1.0.23.

But the bigger issue is that the page you arrive to through a creates.io search result crate link is different than what the url actually shows if you go directly there.

**Comment by birkenfeld** [comment]
This is similar for `futures`, where the 0.2 line has been yanked. https://crates.io/search?q=futures gives 0.2.1 as the version (also in the badge), and clicking there leads to the "yanked" page.

The search/index should not link to yanked versions, but the latest non-yanked one.
