### ISSUE TITLE
Click or press 'S' to search... doesn't work on alternative keyboard layout

### ISSUE THREAD

**Issue by kanru** [rust-lang/crates.io#1473]
Environment:
- Browser: Firefox 63.0a1
- OS: Linux 4.17.0-1-amd64
- Desktop: Gnome 3.28.2

My keyboard layout is set to Dvorak from Gnome settings. It seems ember-keyboard is only looking at the `code` value instead of the `key` from the keyevent. From the spec "The [code] value is not affected by the current keyboard layout or modifier state, so a particular key will always return the same value."

https://github.com/patience-tema-baron/ember-keyboard/issues/84 is a similar issue reported to ember-keyboard upstream.

Do we really need to use a library for this feature? Is it possible to register a keyevent handler and just filter the key by keyevent.key?

**Comment by carols10cents** [comment]
OMG so *that's* why it's not working for me!!! I use dvorak too, and noticed hitting "s" stopped working recently, but I hadn't investigated and I suspected it was a Firefox Nightly problem.

Thank you for tracking this down!

**Comment by ballpointcarrot** [comment]
@carols10cents @kanru With this change deployed now, is this issue set to be closed? It seems to be working now for me (also on Dvorak :D )

**Comment by kanru** [comment]
Works for me too!

**Comment by locks** [comment]
Thank you for the updated reports, closing it!
