### ISSUE TITLE
Proposal to record rustc version when downloading a crate

### ISSUE THREAD

**Issue by mehcode** [rust-lang/crates.io#1479]
Currently we only record that a crate (at a specific version) is downloaded. I'm proposing to extend this by adding "rust" and "edition" parameters that `cargo` would submit. It'd be good information to have, knowing if a crate is being consistently used by older rust versions.

---

I'd prefer to actually track _builds_ from `cargo build` (as that would be far more accurate). That would require extending `cargo` with usage metrics and making it opt-in with a `y/n` prompt, etc. I think that's worth it but I'm unsure how the community would react to that.

**Comment by sgrif** [comment]
This would require an RFC.
