### ISSUE TITLE
Deny rust keywords as crate names

### ISSUE THREAD

**Issue by pyfisch** [rust-lang/crates.io#1480]
User @swmon recently registered a lot of crate names that happen to be rust keywords like  [if](https://crates.io/crates/if), [while](https://crates.io/crates/while) and [type](https://crates.io/crates/type).

These crates should not have been published in the first place as they can't be used because of the reserved word and the [cargo command line tool](https://github.com/rust-lang/cargo/blob/db48c63b3641a29a20b572ed516c58c84450e3bd/src/cargo/ops/cargo_new.rs#L131) already blacklists them.

I propose to blacklist the names in the back-end and remove the crates already published.

To implement this I think [`fn valid_name`](https://github.com/rust-lang/crates.io/blob/9b4a92cf16f712dbc4f3074fb40641b0f2b64c88/src/models/krate.rs#L251) needs to be changed.

(This is maybe a good "first PR" issue.)

**Comment by terry90** [comment]
I'll do it then 👍

**Comment by jtgeibel** [comment]
Closing based on the reasons outlined in https://github.com/rust-lang/crates.io/pull/1482#issuecomment-418565821.

**Comment by 89z** [comment]
https://github.com/rust-lang/crates.io/issues/1747
