### ISSUE TITLE
Yanked crate interacts strangely with download graph

### ISSUE THREAD

**Issue by huonw** [rust-lang/crates.io#149]
E.g. https://crates.io/crates/order-stat/ has version 0.1.1 yanked. At the time of writing the latest version is 0.1.2 which the legend of the download graph says is the yellow colour, but the tool tip indicates that spikes in what looks like the yellow line are actually downloads of 0.1.1.

![crates io-yanked-graph](https://cloud.githubusercontent.com/assets/1203825/7347719/9f9fe934-ed2e-11e4-9b50-000dc8df367d.png)

**Comment by Eh2406** [comment]
If this is a problem with the graphing ui code it may have been fixed in pr #552

**Comment by locks** [comment]
I believe this issue is no longer applicable.
