### ISSUE TITLE
Searching for "html tree" can't find "kuchiki" crate.

### ISSUE THREAD

**Issue by measlytwerp** [rust-lang/crates.io#1497]
kuchiki's Cargo.toml:

```
description = "(朽木) HTML/XML tree manipulation library"
```

I tried searching for "html" but was unable to find the crate, instead you have to search for "html/xml" to get the expected result.

I've filed an issue with them (kuchiki-rs/kuchiki#48) and asked them to add keywords to their `Cargo.toml`. But regardless, I'd have expected this crate to have shown up in the search results.

**Comment by sgrif** [comment]
Our search follows the behavior of PostgreSQL full text search, which we don't have direct control over. I'd open an issue there if you want that behavior changed, but there's not really anything we can do here.
