### ISSUE TITLE
crates.io allows RC4 for TLS connections

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang/crates.io#150]
Unless there is a good reason to support it, the nginx configuration should be changed to disallow it.

The Mozilla wiki has a good guide for [recommended cipher suites](https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility). Hyneck Schlawack also has a [good guide](https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/).

**Comment by alexcrichton** [comment]
The site is hosted on Heroku, so unfortunately there's not much we can do about this (we don't configure SSL at all).

**Comment by kamalmarhubi** [comment]
I found a [comment] on the Heroku discussion forum that suggest "that re-provisioning the SSL addon does the job". Could be worth a shot?

[comment]: https://discussion.heroku.com/t/disable-ssl-support-for-rc4-ciphers-pci-failure/892/8#

**Comment by kamalmarhubi** [comment]
@alexcrichton (@-mentioning because I'm unsure of how GitHub notifications work)

**Comment by alexcrichton** [comment]
I've opened a support ticket to see what we can do, thanks for investigating @kamalmarhubi!

**Comment by kamalmarhubi** [comment]
:thumbsup:

**Comment by alexcrichton** [comment]
Looks like that comment on the forums may have been in relation to another app, this is the response we got:

> Our *.herokuapp.com and SSL Load balancers should pref better ciphers instead of forcing RC4. We support RC4 so that older browsers can still connect, but we order the cipher at the very bottom so modern browsers use better encryption.

**Comment by kamalmarhubi** [comment]
Makes enough sense. I should have checked. I ran it through [SSL Labs server test][ssltest], it complained, and then I reported the issue.

Thanks for checking!

[ssltest]: https://www.ssllabs.com/ssltest/
