### ISSUE TITLE
Set up continuous deployment

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/crates.io#1505]
One factor I believe that is slowing down development is the lack of continuous deployment.

Currently, the crates.io team deploys periodically. It seems that the team takes deployment as a risky operation, but I believe setting up continuous deployment will improve the situation because:
- Each deployment has a smaller changeset.
- They are automated so less possibility of human error.
- We learn how to recover if something goes wrong. (e.g. with rollbacks)

Here, rollback is a requirement but I think Heroku provides it already. Database migrations are the tricky things here. A common approach is to write non destructive (and backward compatible) migrations.

Additionally, it would be good to have a staging environment. Given that it's hard to replicate the production environment locally, having a staging environment allows us to have confidence before putting a new feature to live.

**Comment by carols10cents** [comment]
We have a staging environment -- https://staging-crates-io.herokuapp.com/. When I do a deploy, I deploy to staging first, manually test what has changed, and then deploy to production. And we've still broken things. 

Our automated test suite would need to be more comprehensive for me to feel confident enough to do continuous deployment. Namely, we'd need some full-stack tests (https://github.com/rust-lang/crates.io/issues/868), right now we only have front-end tests with a mocked back-end and back-end tests that we don't verify match the mocked back-end.

So I would say this is blocked by https://github.com/rust-lang/crates.io/issues/868.

**Comment by kzys** [comment]
> We have a staging environment -- https://staging-crates-io.herokuapp.com/. When I do a deploy, I deploy to staging first, manually test what has changed, and then deploy to production. And we've still broken things.

Can we deploy to the staging environment automatically/continuously from master? Deploying to the staging environment is better than deploying directly to the production. So it should be automated and enforced, rather than asking each developer to do that.

**Comment by Turbo87** [comment]
2.5 years later (😅) we have finally talked about this in the weekly team meeting and decided to give this a try for the staging environment. I will try to set up automatic deployment from `master` to the staging environment in the next weeks.

CD for production would be nice, but the concensus was that the database migrations are making this a bit risky, so we are unlikely to introduce this any time soon. if anyone has ideas on how we can reduce the risk caused by those, we're open for suggestions.

**Comment by Turbo87** [comment]
we've been running CD for staging successfully for a while now, but the deployment to production will likely stay a manual task. we've enabled Heroku pipelines though, which makes it possible for us to promote staging builds to production with the click of a button.
