### ISSUE TITLE
Realtime API

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/crates.io#1508]
There are some known services (mainly docs.rs) that continuously watch updates on crates.io to trigger jobs (doc build, dependency update PR, etc). 

This will probably need a way for baseline fetch as well, which could be achieved with a database dump (https://github.com/rust-lang/crates.io/issues/630).

The requirements for the APIs are:
- Streams (probably WebSocket) of changes, including relations (document-based NoSQL excels at this)
- A window of backlog of changes (to allow consistency when a short disconnect happens)

Some ways to implement reactiveness are:
- Use a database that is designed for direct sync (bypasses backend) ([CouchDB](https://couchdb.apache.org/))
- Use a database that is capable of realtime watches (MongoDB, RethinkDB)
- Roll our own implementation based on some PubSub and filtering based on timestamp datas

**Comment by samueltardieu** [comment]
There is also the possibility of using a RSS/Atom feed + WebSub. Work would be minimal on crates.io (generate XML feed with the 100 latest applications + ping the hub and let it do its work).
