### ISSUE TITLE
Dashboard could display Total Downloads

### ISSUE THREAD

**Issue by reem** [rust-lang/crates.io#151]
"Total downloads of all crates on which you are an owner" would be a neat metric to display on the dashboard.

**Comment by PritiKumr** [comment]
I was trying to take this on. I saw that we're using `bin/update-downloads.rs` to update various download counts. I was wondering if we can have a counter in the `crate_owner` table as well and keep it updated.

**Comment by PritiKumr** [comment]
@reem okay, I've constructed a diesel query to do a `SUM` on a filtered set of `crate_downloads`. Working on the front end now. Will raise PR soon.

**Comment by carols10cents** [comment]
This has been finished and deployed, forgot to close the issue, oops!
