### ISSUE TITLE
"Request desktop site" on mobile does not work

### ISSUE THREAD

**Issue by alexreg** [rust-lang/crates.io#1513]
At least, on latest iOS. It just remains on the mobile site.

**Comment by jtgeibel** [comment]
We don't serve HTML differently for mobile vs. desktop.  As far as I'm aware, everything is handled via CSS media queries based on the screen width.

Is there something specific that you're not seeing on mobile that you think should be included with small screen widths?  As an example, holding my phone vertically on the account dashboard does not show my profile picture.  However, the picture is shown when holding my phone horizontally.

https://github.com/rust-lang/crates.io/blob/27842db1eba52304569b20d6a710bd2ef544df7d/app/styles/me.scss#L63-L65

**Comment by jtgeibel** [comment]
I've confirmed with the latest Firefox and Chrome on mobile, and this now appears to be working.  With responsive CSS, we depend on the screen width reported by the browser.  On Firefox and Chrome, it seems they now lie about the screen size when the desktop site is requested.

Here is the behavior I'm seeing in both browsers on the homepage:
* When on mobile, with my phone vertical the sections at the bottom of the page are stacked vertically.
* With my phone horizontally, the sections are displayed in a 2x3 grid, the same as on desktop.
* When I request the desktop version of the site, the grid is displayed with the phone in both vertical and horizontal positions.
