### ISSUE TITLE
Short crate URLs

### ISSUE THREAD

**Issue by timvisee** [rust-lang/crates.io#1523]
I'm accessing crate pages on `crates.io` quite a lot, by directly typing the `crates.io/crates/rand` URL in my browsers address bar. I think it's quite verbose/cumbersome, and type `create` a little too often.

What about implementing a short crate URL such as `crates.io/c/rand` in a similar fashion as reddit does with subreddits and user profiles. The short URL could be an alias, or a redirect to the full URL. Existing URLs won't break, of course.

I'm interested in what other think? It's a small but useful change I believe. I couldn't find a previous discussion on this topic. I'm happy to implement this through a PR if others can confirm such a change is desired.

**Comment by sgrif** [comment]
I'd be fine with this as long as it was implemented as a redirect.

**Comment by timvisee** [comment]
@sgrif Awesome! I've submitted a basic implementation with redirects, see #1526 .

**Comment by carols10cents** [comment]
I've decided to close this, as browsers and search engines provide even shorter ways to do this:

- In Firefox, create a bookmark for crates.io with the location set to `https://crates.io/crates/%s` and the keyword set to `crate`. Then you can type "crate rand" into your address bar and it'll take you to https://crates.io/crates/rand.
- In Chrome, go to settings, search engine, manage search engines, then add a search engine with the keyword `crate` and the URL set to `https://crates.io/crates/%s`. Then you can type "crate rand" into your address bar and it'll take you to https://crates.io/crates/rand.
- [Duck Duck Go](https://duckduckgo.com) has a [bang search](https://duckduckgo.com/bang) for [crates.io](https://duckduckgo.com/bang?q=crates), so you can do `!crate rand` and it'll search crates.io for rand. Make DDG the default search in your browser and it'll work from your address bar as well.

**Comment by timvisee** [comment]
Sure. Sorry that I want really able to come up with a proper implementation at the time. I agree this wouldn't be to useful anymore these days. Thanks for giving me the opportunity anyway!
