### ISSUE TITLE
Crate using namespaced-features is rejected when attempting to publish

### ISSUE THREAD

**Issue by tikue** [rust-lang/crates.io#1525]
`error: api errors: invalid upload request: invalid value: string "crate:serde", expected a valid feature name at line 1 column 1862`

I assumed I could publish crates using experimental cargo features, but perhaps that's not true?

**Comment by jtgeibel** [comment]
Reading through the tracking issue rust-lang/cargo#5565 it looks like this will require additional data to be stored in the index.  The details of that will need to be sorted out first.

**Comment by Turbo87** [comment]
This has been implemented on the crates.io side a while ago, so I guess we can close the issue :)
