### ISSUE TITLE
Can't see cursor in search box

### ISSUE THREAD

**Issue by mcandre** [rust-lang/crates.io#1528]
The frontend for crates.io strangely hides the text cursor when the search box has focus.

**Comment by jtgeibel** [comment]
This appears to work fine for me on:
* Ubuntu 18.10
  * Firefox 63
  * Chrome 70
* Windows 10 (1810)
  * Firefox 64b1
  * Edge 44

What OS and browser combination are you seeing issue on?

**Comment by kzys** [comment]
Works for me on Safari / macOS.

**Comment by locks** [comment]
I also cannot reproduce this! If you still encounter the problem @mcandre please provide the OS and browser versions were you are reproducing it.
