### ISSUE TITLE
Should crate page show yanked versions?

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/crates.io#1552]
On https://crates.io/crates/futures every version listed in the sidebar is yanked. Even if new versions are pushed this is going to persist because newer versions will be `0.1.*` while it was the entire `0.2` series that was yanked (and versions are sorted by version, not publish date).

It seems like the overview in the sidebar should maybe not show yanked versions, and just show the latest un-yanked versions. The "show all XX versions" page could then be used if a user wants to see the yanked versions.

**Comment by drager** [comment]
I agree with @Nemo157!

I think the latest 0.1.* versions should be listed but a new kind of list could also be added to the crate's overview page, that displays yanked versions. I think it's interesting to see the yanked ones directly at the crate's overview page, i.e not navigate to a separate page. So below "Versions" a new headline can be added called "Yanked versions".

**Comment by Turbo87** [comment]
the list of the five top versions has disappeared from the sidebar a while ago, so I guess this is no longer an issue
