### ISSUE TITLE
chrono-crate doc need updating?

### ISSUE THREAD

**Issue by andy5995** [rust-lang/crates.io#1557]
I'm not sure if the chrono-crate doc needs updating. I'm fairly new to rust and maybe that's the source of my confusion. 

There is a [forum thread](https://users.rust-lang.org/t/using-std-duration/22218) where I explain how I'm perceiving things. Apparently I'm wrong but just wanted to offer some feedback and double-check before I let it go.

**Comment by carols10cents** [comment]
Hi, this issue should be filed in [chrono's repo](https://github.com/chronotope/chrono), crates.io just hosts crates, we don't control their content :)
