### ISSUE TITLE
Pagination numeric links at bottom of reverse_dependencies don't work

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/crates.io#156]
https://crates.io/crates/serde/reverse_dependencies

They link to '#'

![screen shot 2015-05-19 at 6 57 38 pm](https://cloud.githubusercontent.com/assets/416575/7715769/f4465550-fe58-11e4-9ef3-152afe8c0f40.png)

**Comment by Turbo87** [comment]
fixed in #208
