### ISSUE TITLE
Can't login on Android

### ISSUE THREAD

**Issue by naturallymitchell** [rust-lang/crates.io#1577]
Sign in with GitHub doesn't seem to work.

**Comment by carols10cents** [comment]
Which android version and which browser, please?

**Comment by mitchtbaum** [comment]
Android 5, Chrome 70

**Comment by locks** [comment]
Latest Chrome on Android is 76 and I cannot reproduce this issue, so I'm closing it for now.
If it's still an issue please let us know!
