### ISSUE TITLE
Alerts for performance regressions

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/crates.io#158]
Recently crates.io suffered a huge performance regression:

![https://i.imgur.com/ibBy9g2.png](https://i.imgur.com/ibBy9g2.png)

The reason behind this regression was that I deployed a version of crates.io linked against bustream 1.0, which accidentally didn't actually buffer anything. This meant that all DB reads/writes took an _enormous_ amount of time (e.g. 500ms per req), resulting in the huge regression. While an easy fix, we really should have reporting which alerts us to this sort of thing. 

Something like just sending an alert whenever the response time is way outside the normal response time for a period of time.

**Comment by alexcrichton** [comment]
cc @brson, @edunham

**Comment by kzys** [comment]
Can we enable Threshold Alerting? 

https://devcenter.heroku.com/articles/metrics#threshold-alerting

**Comment by sgrif** [comment]
Yeah, we've had alerting set up on this for a while now. Thanks.
