### ISSUE TITLE
Index contains crates that are not on the crates.io site?

### ISSUE THREAD

**Issue by kornelski** [rust-lang/crates.io#1590]
e.g. "amusement" crate:

https://github.com/rust-lang/crates.io-index/blob/8d6a58a0b9f1930e00531f4afecdb1b70012d883/am/us/amusement

Gives:

https://crates.io/crates/amusement

> Crate 'amusement' does not exist

I that some kind of lag/error, or crates purged for spam/abuse?

**Comment by sgrif** [comment]
These are crates that were purged this week for violating our policies. The index should have been cleaned shortly after, but it ended up getting missed due to human error. This will get fixed before the end of the week.
