### ISSUE TITLE
Direct link to download published crate sources

### ISSUE THREAD

**Issue by dhardy** [rust-lang/crates.io#1592]
A couple of times now I have wanted to download the source for a published crate. Sometimes a link to the code repository is all you need, but sometimes the link is missing (or there isn't even a published repository), and sometimes you need to inspect the exact code of a release.

Since Cargo publications are just source tarballs, inspecting the `.crate` files is easy if you can get them, however apparently the only way to do this is to make Cargo download the crate as a dependency, then retrieve it from Cargo's cache.

**Summary:** add a direct download link for each published `.crate` file. 
**Related:** #193

**Comment by dhardy** [comment]
Thanks, but that's quite a URL to remember. I would prefer a link on the page (or maybe under the "all versions" page).

**Comment by Turbo87** [comment]
as described in e.g. https://github.com/rust-lang/crates.io/issues/2113 and some of the other linked issues, our official recommendation is to use tools like https://github.com/JanLikar/cargo-clone to download the raw source of crates if you need them, or use our API endpoint for it directly.

since the mainstream way of downloading crates is always going to be `cargo` usage, a prominent "Download" button on the page could cause quite a bit of confusion to our users. since downloading a `.crate` file manually is a relatively uncommon thing and there are already cargo plugins that allow this, we don't think the tradeoff of having such a button is worth it.

**Comment by pragmatrix** [comment]
> a prominent "Download" button on the page could cause quite a bit of confusion to our users

Agreed, but there is also lies the solution, don't make a download button prominent. The users needing it will find it, the ones who don't, won't be confused.

**Comment by eth3lbert** [comment]
> How do you typically review code before you run it locally if not by downloading the tarball?

I have shown two approaches for inspecting the contents at https://github.com/rust-lang/crates.io/discussions/10754#discussioncomment-12439380.

**Comment by RalfJung** [comment]
Downloading the .crate file is also necessary if one wants to figure out (or at least get a good clue) which commit of the upstream git repo a crate version is based on. It is quite frustrating to know that this data exists, but struggling to find it each time since it is hidden so well.

**Comment by Turbo87** [comment]
https://docs.rs/crate/serde_json/latest/source/.cargo_vcs_info.json 😉 

but yeah, we should probably make this particular bit of information more visible

**Comment by RalfJung** [comment]
That doesn't work for all crates, sadly: https://docs.rs/crate/rustup-toolchain-install-master/latest/source/.cargo_vcs_info.json.

I found the answer on diff.rs, in the end.

**Comment by RalfJung** [comment]
Now that we have a "code" view for each crate (which I love ❤️ ), it is quite frustrating that I cannot just as easily download the entire code for the crate. A local editor is a *much* more comfortable way of looking at the code than this narrow (often so narrow it needs horizontal scrolling, even though my screen is plenty wide enough) source code view.

A little "download code" button on the "code" tab would make a lot of sense IMO. :)
