### ISSUE TITLE
Index anomalies

### ISSUE THREAD

**Issue by ehuss** [rust-lang/crates.io#1593]
I noticed you've been discussing some deviations with the database, the index, and the crate files. I've written a tool for validating an index, and I ran it against crates.io. Please feel free to ignore/close this, just thought it was curious. Here are the results:

- Missing `.crate` files:
    - gobject-2-0-sys-0.0.2.crate
    - gobject-2-0-sys-0.0.3.crate
    - gobject-2-0-sys-0.0.4.crate
    - gobject-2-0-sys-0.0.5.crate
    - gobject-2-0-sys-0.0.6.crate
    - gobject-2-0-sys-0.0.7.crate
    - gobject-2-0-sys-0.0.8.crate
    - gobject-2-0-sys-0.0.9.crate
    - gobject-2-0-sys-0.1.0.crate
    - gobject-2-0-sys-0.2.0.crate
    - glib-2-0-sys-0.0.1.crate
    - glib-2-0-sys-0.0.2.crate
    - glib-2-0-sys-0.0.3.crate
    - glib-2-0-sys-0.0.4.crate
    - glib-2-0-sys-0.0.5.crate
    - glib-2-0-sys-0.0.6.crate
    - glib-2-0-sys-0.0.7.crate
    - glib-2-0-sys-0.0.8.crate
    - glib-2-0-sys-0.1.0.crate
    - glib-2-0-sys-0.1.1.crate
    - glib-2-0-sys-0.1.2.crate
    - glib-2-0-sys-0.2.0.crate
    - deploy-0.1.0.crate (YANKED)
    - deploy-0.1.1.crate (YANKED)
    - deploy-0.1.2.crate (YANKED)
- Versions appear multiple times in index:
    - stitch 0.1.0 (different checksums)
    - zaif-api 0.1.0
    - dep_c 1.0.0
    - dep_d 3.1.0
    - wright 0.2.2 (different checksums)
    - replicante_agent_models 0.1.1
- No matching dependency versions found:
    - `concat_bytes` matching requirement `^0.0.0` from package `webplatform:0.1.3`.
    - `db-key` matching requirement `^0.0.3` from package `leveldb:0.3.3`.
    - `db-key` matching requirement `^0.0.4` from package `leveldb:0.3.4`.
    - `db-key` matching requirement `^0.0.4` from package `leveldb:0.3.5`.
    - `db-key` matching requirement `^0.0.4` from package `leveldb:0.3.6`.
    - `db-key` matching requirement `^0.0.4` from package `leveldb:0.3.8`.
    - `db-key` matching requirement `^0.0.4` from package `leveldb:0.3.9`.
    - `db-key` matching requirement `^0.0.4` from package `leveldb:0.4.0`.
    - `db-key` matching requirement `^0.0.4` from package `leveldb:0.4.1`.
    - `db-key` matching requirement `^0.0.4` from package `leveldb:0.4.2`.
    - `db-key` matching requirement `^0.0.4` from package `leveldb:0.5.0`.
    - `db-key` matching requirement `^0.0.4` from package `leveldb:0.5.1`.
    - `dir-diff` matching requirement `^1.0.7` from package `dir-diff:0.3.0`.
    - `openssl` matching requirement `~1.0.0` from package `pop3:0.0.1`.
    - `serde_codegen` matching requirement `^0.10.0` from package `tokei:2.1.0`.
    - `syntex` matching requirement `^0.18.0` from package `serde_codegen:0.6.1`.
    - `syntex` matching requirement `^0.7.5` from package `tokei:2.1.0`.
    - `wasm-bindgen-test-project-builder` matching requirement `= 0.2.13` from package `wasm-bindgen:0.2.13`.
- No matching dependency name found:
    - `glib-2_0-sys` from package `grust:0.0.10`.
    - `glib-2_0-sys` from package `grust:0.0.2`.
    - `glib-2_0-sys` from package `grust:0.0.3`.
    - `glib-2_0-sys` from package `grust:0.0.4`.
    - `glib-2_0-sys` from package `grust:0.0.5`.
    - `glib-2_0-sys` from package `grust:0.0.6`.
    - `glib-2_0-sys` from package `grust:0.0.7`.
    - `glib-2_0-sys` from package `grust:0.0.8`.
    - `glib-2_0-sys` from package `grust:0.0.9`.
    - `glib-2_0-sys` from package `grust:0.1.0`.
    - `glib-2_0-sys` from package `grust:0.1.1`.
    - `glib-2_0-sys` from package `grust:0.1.2`.
    - `glib-2_0-sys` from package `grust:0.1.3`.
    - `glib-2_0-sys` from package `grust:0.2.0`.
    - `glib-2_0-sys` from package `grust:0.3.0`.
    - `glib-2_0-sys` from package `libnotify-sys:0.0.2`.
    - `glib-2_0-sys` from package `libnotify-sys:0.0.3`.
    - `glib-2_0-sys` from package `libnotify-sys:0.1.0`.
    - `glib-2_0-sys` from package `libnotify-sys:0.1.1`.
    - `glib-2_0-sys` from package `libnotify:0.0.1`.
    - `glib-2_0-sys` from package `libnotify:0.0.2`.
    - `glib-2_0-sys` from package `libnotify:0.0.3`.
    - `glib-2_0-sys` from package `libnotify:0.0.4`.
    - `gobject-2_0-sys` from package `grust:0.0.10`.
    - `gobject-2_0-sys` from package `grust:0.0.2`.
    - `gobject-2_0-sys` from package `grust:0.0.3`.
    - `gobject-2_0-sys` from package `grust:0.0.4`.
    - `gobject-2_0-sys` from package `grust:0.0.5`.
    - `gobject-2_0-sys` from package `grust:0.0.6`.
    - `gobject-2_0-sys` from package `grust:0.0.7`.
    - `gobject-2_0-sys` from package `grust:0.0.8`.
    - `gobject-2_0-sys` from package `grust:0.0.9`.
    - `gobject-2_0-sys` from package `grust:0.1.0`.
    - `gobject-2_0-sys` from package `grust:0.1.1`.
    - `gobject-2_0-sys` from package `grust:0.1.2`.
    - `gobject-2_0-sys` from package `grust:0.1.3`.
    - `gobject-2_0-sys` from package `grust:0.2.0`.
    - `gobject-2_0-sys` from package `grust:0.3.0`.
    - `gobject-2_0-sys` from package `libnotify-sys:0.0.2`.
    - `gobject-2_0-sys` from package `libnotify-sys:0.0.3`.
    - `gobject-2_0-sys` from package `libnotify-sys:0.1.0`.
    - `gobject-2_0-sys` from package `libnotify-sys:0.1.1`.

See also:
https://github.com/rust-lang/crates.io/issues/1177 which explains some of these anomalies.

**Comment by sgrif** [comment]
Can you share the tool you're using for these validations?

**Comment by ehuss** [comment]
I have posted it at https://crates.io/crates/cargo-index.  It's fairly basic right now.  To validate `.crate` files, you have to download all the crates separately.  Or without the `--crates` flag it just skips the checksum validation.

**Comment by pinkforest** [comment]
fyi - There are some crates and code around in the community that corrupts cargo downloads and will not match the checksum leading to some confusion around the community.

Typical problem is people not calling write_all with tokio writer or not using flush() on buffered handles like STDOUT's

I've pushed crates as unmaintained in advisory that have gone unmaintained especially with this issue affecting the community downloading crates.

**Comment by pietroalbini** [comment]
Fixed `glib-*` and `gobject-*`, see [thread on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/Invalid.20crate.20download.20link/near/288217436).

**Comment by Turbo87** [comment]
the "version appears multiple times" issue should also be fixed by now. the missing dependencies issue is generally also tracked by https://github.com/rust-lang/crates.io/issues/1786, so I guess we don't need a second issue for the same problem :)
