### ISSUE TITLE
We should ensure a version is not in the index before adding it

### ISSUE THREAD

**Issue by sgrif** [rust-lang/crates.io#1594]
Related: #1593 

Currently we assume that if a crate isn't in our database, it's also not in the index. When we add a new version to a crate, we just append a new line to the file. Any time we're in this situation, it's an index anomaly, which should result in at minimum the push being rejected, and probably should result in someone getting paged to resolve whatever put us in this situation in the first place

**Comment by Eh2406** [comment]
One small thing, it would be lovely if the crate we use to verify the index was available as a stand alone thing, jointly maintained by the Crates.io and Cargo teams. So both of our test sweets can be sure we don't break it and sow others can use it.

**Comment by sgrif** [comment]
I agree with the idea in general, but I'm not really envisioning a general "verify the index" tool, I'm imagining something much dumber at the moment

**Comment by Turbo87** [comment]
since we now treat the database as the primary source of truth and generate the index file completely from the database content this has become a situation that can't happen anymore :)
