### ISSUE TITLE
Show last updated timestamp in search results

### ISSUE THREAD

**Issue by kadfak** [rust-lang/crates.io#1597]
Currently it's cumbersome to check whether a crate is still being actively developed or not when searching. To see when the crate was last updated, you have to move away from the search results page and do that for every crate individually.

**Comment by kzys** [comment]
You meant this page: https://crates.io/search?q=foobar ? I personally like the idea.

**Comment by kadfak** [comment]
That's correct.
Compare with [NPM](https://www.npmjs.com/search?q=foobar), [NuGet](https://www.nuget.org/packages?q=foobar), for example.
