### ISSUE TITLE
Rename "Game engines" and "Games"

### ISSUE THREAD

**Issue by erlend-sh** [rust-lang/crates.io#1598]
<img width="961" alt="screenshot 2019-01-18 at 10 43 40" src="https://user-images.githubusercontent.com/583842/51380516-2ffd4700-1b12-11e9-959a-058192ecb850.png">

A "Game engine" is a specific thing in the game industry. Most of what is listed in this category is just general game development tooling, not game engines. I suggest renaming this category to "Game Development".

"Games" on the other hand is very misleading, as is made evident by this category's description. I suggest renaming it to "Fun" or "For Fun".

**Comment by erlend-sh** [comment]
I found precedent for this type of discussion in #488. Is there any particular process I’m supposed to follow here?

**Comment by sunjay** [comment]
To leave it backwards compatible, maybe it could be renamed to "Game Development / Game Engines"?

**Comment by erlend-sh** [comment]
Sure, as long as the new slug is `game development`. But I really wouldn't worry too much about backwards compatibility here as the gamedev ecosystem is still young and hasn't established any taxonomy conventions yet.

**Comment by sunjay** [comment]
I'm specifically talking about backwards compatibility for those who have already listed the game engine category in their crates. They shouldn't get unlisted if the name changes.

**Comment by chsm** [comment]
Not familiar how the categories are implemented, but can't game engines be included as a child category of game development? Then folks who currently list the game engine category for this create can continue to be listed under the parent category (game development) as well?

**Comment by Lisoph** [comment]
What about renaming "Games" to "Entertainment"? Seems more fitting even with the current description.

**Comment by Lokathor** [comment]
Having a Games category is totally fine and should stay that way.

Renaming the other category to Game Development I agree with.

**Comment by erlend-sh** [comment]
How can this be moved forward? There appears to be unanimous support for a renaming to “Game Development”

**Comment by kzys** [comment]
@erlend-sh I've just made a PR, but we need to move existing crates to this new category.

Another way of doing that is changing the display name to "Game Development" first to see how the Rust community reacts, and change the slug later.

**Comment by kzys** [comment]
@erlend-sh @Lokathor How about just changing the display name first? It doesn't satisfy

> Sure, as long as the new slug is game development

but I got your 👍 :)

**Comment by erlend-sh** [comment]
Yeah I’m on board with just changing the display name as a first step.

**Comment by kzys** [comment]
From @carols10cents (https://github.com/rust-lang/crates.io/pull/1720#pullrequestreview-310781411)

> I think adding a new "Game development" category with a description that it's for not-engines and adjusting the description for "Game engines" so that it's clear what belongs there vs. "Game development" would be a good path forward.

Folks on this issue - What would be the good descriptions for "Game development" and "Game engines"? While I know a bit of game development (yes, we shouldn't call them "game engines"), I'm not a pro and English is my second language.

**Comment by Lokathor** [comment]
* Games: For crates that are primarily a binary that you run and play.

* Game Development: For crates that focus on some individual part of accelerating the development of games (RNG, graphics, sound, etc).

* Game Engines: For crates that try to provide a "one-stop-shop" for all of your game development needs.

(this is draft-level writing but it's the basic idea that I see as the distinction.)
