### ISSUE TITLE
Support uploading/displaying changelogs.

### ISSUE THREAD

**Issue by huonw** [rust-lang/crates.io#160]
I'm not sure what this would look like, but it would be useful to be able to see what's changed.

(I could also imagine a `cargo diff foo 1.0.3 1.3.2` that downloads/displays the changelogs between those versions.)

**Comment by lukaslueg** [comment]
I would much prefer to have a changelog in Cargo.toml, which is then parsed by cargo or rendered by crates.io

**Comment by ruuda** [comment]
Here’s a suggestion for a small change that could help a lot: add a `changelog` field to the crate metadata, similar to `homepage`, `repository` and `documentation`. Crates.io would include a link to the changelog under the “Links” section, similar to the other fields.

People could link it to a `changelog.md` file in a repository browser such as GitHub, or to a dedicated page on a project site.

As a user of a crate (as opposed to when I am still deciding on whether to use a crate), the two things for which I most often visit a crate page are the docs and the changelog. A direct link could save a click and page load (assuming the changelog is linked from the repository page).

**Comment by carols10cents** [comment]
Discussion of this should now happen on [RFC 2129](https://github.com/rust-lang/rfcs/pull/2129), and if that is accepted, it'll get its own tracking issue, so I'm going to close this one.
