### ISSUE TITLE
Update .travis.yml now that we are using Homu

### ISSUE THREAD

**Issue by jtgeibel** [rust-lang/crates.io#1603]
It looks like Homu uses an `auto` branch instead of `staging`.  In our `.travis.yml` file we exclude builds on the `staging.tmp` branch.  This was previously required with `bors-ng`.

We can remove this exception now, but it's not yet clear to me if we need to add a similar rule for Homu.

**Comment by kzys** [comment]
Aren't we using bors-ng?

**Comment by carols10cents** [comment]
Not anymore

**Comment by kzys** [comment]
@carols10cents do you know where do we have our Homu's cfg.toml?

**Comment by carols10cents** [comment]
> @carols10cents do you know where do we have our Homu's cfg.toml?

@kzys I believe it's [over here in rust-central-station](https://github.com/rust-lang/rust-central-station/blob/8dea96e6658d4666aa39ebb91332c7c3fc580245/homu.toml.template#L266-L279)

**Comment by kzys** [comment]
Thanks! Since there is no `[repo.crates-io.branch]`, my PR (#1721) should work as expected - Homu creates "auto" and Travis CI ignores the branch.

**Comment by kzys** [comment]
And how about updating @bors's profile to include the link to the repository? Removing Philip K. Dick reference may make someone sad, but it would be more pragmatic and helpful for new comers.
