### ISSUE TITLE
Wrong author after using "back" button

### ISSUE THREAD

**Issue by diwic** [rust-lang/crates.io#161]
Steps to reproduce:
 * Go to https://crates.io/crates/alsa - notice that the author is David Henningsson
 * Input "dbus" + Enter in the search box
 * Click the first result, "systemd-dbus" - notice that the author is Hugo Duncan
 * Click back (with your mouse) twice
 * Notice how the alsa crate's author has changed from "David Henningsson" to "Hugo Duncan".

Experienced with Firefox 38.0 on Ubuntu 14.04.

**Comment by alexcrichton** [comment]
I think this is a dupe of #70, but thanks for the report!
