### ISSUE TITLE
Show github teams in "Manage owners" view

### ISSUE THREAD

**Issue by killercup** [rust-lang/crates.io#1617]
Currently, the "manage ownership" view doesn't show the Github teams that own the crate.

For example, if I go to <https://crates.io/crates/rustfix>, I can see `github:rust-lang-nursery:rustfix` as an owner of the crate (as well as Oli and me). If I click on "Manage owners" (the `/crates/rustfix/owners` route), the Github team isn't in the list. Additionally, the input field on that page is labelled "username", so I can't tell if adding teams is possible (e.g. using the same syntax as in `cargo owner --add github:rust-lang-nursery:rustfix`).

**Comment by frewsxcv** [comment]
this appears to be resolved https://crates.io/crates/rustfix/owners
