### ISSUE TITLE
Add dropdown box to allow selecting more results per page

### ISSUE THREAD

**Issue by therealprof** [rust-lang/crates.io#1625]
As discussed at the RaH it would be really handy to allow displaying more results per page to make it easier to find stuff when browsing through a largish category.

@sgrif mentioned he would be okay with allowing changing the display to up to 100 entries per page to keep load on the servers at an acceptable level.

**Comment by carols10cents** [comment]
As discussed in https://github.com/rust-lang/crates.io/pull/1762, we decided to increase the number of crates on one page from 10 to 50, rather than offering a dropdown. The increase was implemented in #1883, and I'm going to be deploying it in a little bit, so I'm closing this issue. Thanks!
