### ISSUE TITLE
Provide UI to allow searching within categories

### ISSUE THREAD

**Issue by therealprof** [rust-lang/crates.io#1626]
In embedded we often have the strong desire that we'd like to narrow searches to the `no_std` category. At the RaH @sgrif mentioned that the backend already allows narrowing down searches but this is currently not exposed in the user interface.

Providing a user interface to allow this would be a *huge* usability improvement for us.

**Comment by erlend-sh** [comment]
Agreed!

On an administrative note, either #491 should be closed and link here or this issue should be closed as a duplicate.

**Comment by carols10cents** [comment]
Yep, I think this is a duplicate of #491. Closing, thanks!
