### ISSUE TITLE
inconsistent number format in Stats Overview (point `.` with different meaning)

### ISSUE THREAD

**Issue by colin-kiegel** [rust-lang/crates.io#1628]
When I look at the download stats pop-over, the number format is incosistent.

- The 7-day average has a decimal point **1855.86** (one thouasand fifty five ... and a fraction)
- The daily downloads separates thousand by a point **2.140** (two thousand one houndred fourty)

The following example is from [here](https://crates.io/crates/pretty-assertions)

![grafik](https://user-images.githubusercontent.com/7691186/53199611-ce079400-361f-11e9-9994-7be53ccf972a.png)

My HTTP-Request header is like this, if it plays any role:
```
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
Accept-Language: de,en-GB;q=0.7,en;q=0.3
```

**Comment by bryanburgers** [comment]
You included the `Accept-Language` header, so you've probably guessed this already. It's probably an issue where we display the current date's value as a locale-formatted number, and the 7-day average as a locale-unaware number.

Using my browser (`Accept-Language | en-US,en;q=0.5`) I see commas in the current date value.

In app/components/download-graph.js, I see this code:

```
return {
    v: avg,
    f: avg.toFixed(2),
};
```

which may be contributing, but I'm not sure yet.
