### ISSUE TITLE
Allow & render markdown for the description

### ISSUE THREAD

**Issue by tomaka** [rust-lang/crates.io#165]
I tried to write a nice description in [my Cargo.toml](https://github.com/tomaka/glium/blob/f1bd7fe11276e290b6d12b3b8b43ef5410796b2b/Cargo.toml#L5-L17):

``` toml
description = """
Elegant and safe OpenGL wrapper.
Glium is an intermediate layer between OpenGL and your application. You still need to manually handle
the graphics pipeline, but without having to use OpenGL's old and error-prone API.
Its objectives:
 - Be safe to use. Many aspects of OpenGL that can trigger a crash if misused are automatically handled by glium.
 - Provide an API that enforces good pratices such as RAII or stateless function calls.
 - Be compatible with all OpenGL versions that support shaders, providing unified API when things diverge.
 - Avoid all OpenGL errors beforehand.
 - Produce optimized OpenGL function calls, and allow the user to easily use modern OpenGL techniques.
"""
```

But on crates.io the white spaces and line breaks are ignored, leading to an ugly mess: https://crates.io/crates/glium

In my opinion it would be nice to add a `<pre>` around or something.

**Comment by steveklabnik** [comment]
Markdown usually requires a double space for a new paragraph, so if we were to do that, this would still end up looking like this, as a note...

**Comment by tomaka** [comment]
In reality my Cargo.toml has better spacing. For some reason the extra lines seem to have been eaten by github when I copy-pasted it here.

**Comment by alexcrichton** [comment]
Currently we don't allow markdown for various security concerns, but if we could mitigate those then we would just use a normal markdown parser.

**Comment by CruzBishop** [comment]
What about a simple Markdown parser that, to start with, only formats *italic*, **bold**, __underlined__, ~~strikethrough text~~ and newlines?

I'm not sure how to go about it, but it's one of the things I wanted to work on eventually for experience

**Comment by azerupi** [comment]
> only formats italic, bold, strikethrough text and newlines?

Links and lists are probably also a good idea

**Comment by anthonynguyen** [comment]
Is this resolved?

**Comment by carols10cents** [comment]
#869 renders the *readme* markdown, this issue is for supporting markdown in the *description* in Cargo.toml. Unless the readme markdown rendering is sufficient for @tomaka's needs?

**Comment by anthonynguyen** [comment]
It seems like the goal was for the page on crates.io to have a nicely-formatted info section, which is achieved by rendering the readme

**Comment by tomaka** [comment]
What @anthonynguyen said.

**Comment by joshtriplett** [comment]
I think there's still value in having (limited) markdown in the description, similar to what's supported in the README. See https://crates.io/crates/tide-tracing for an example, where it'd be nice to have those links get rendered as links wherever the description appears.
