### ISSUE TITLE
Have a way to yank a crate from the UI

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#1659]
What needs to be done: This looks like a lot, but I tried to provide a lot of detail and examples to work from. The actual code changes shouldn't be very big.

- If the current user is an owner of the current crate, add a link or button in the sidebar with each version that says "yank" if the version is not yanked and "unyank" if the version is yanked. (Or is there a better place to put this control? I'm open to different UIs)
  - The HTML for the versions list in the sidebar is in https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/app/templates/crate/version.hbs#L195-L208
  - To tell if the current user is an owner, use the `isOwner` helper like the "Manage owners" section does here https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/app/templates/crate/version.hbs#L167-L173
  - Because we only show the latest 5 versions in the sidebar, the new link/button should be shown on the "All versions" page as well so any version can be yanked. The "All versions" page's HTML is here https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/app/templates/crate/versions.hbs

- The link/button should send a [`DELETE` request to `/api/v1/crates/[crate name]/[version num]/yank`](https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/src/router.rs#L23) for yanking and a [`PUT` request to `/api/v1/crates/[crate name]/[version num]/unyank`](https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/src/router.rs#L23) for unyanking.
  - A similar link/button is the "Remove" button for removing an owner https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/app/templates/crate/owners.hbs#L67
  - Which calls the ember `removeOwner` controller function: https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/app/controllers/crate/owners.js#L34-L49
  - Which calls the ember crate model `removeOwner` function: https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/app/models/crate.js#L48-L50
  - Which calls the ember crate adapter `removeOwner` function: https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/app/adapters/crate.js#L16-L22
  - I'm not actually sure how idiomatic Ember this example is; if this example isn't good, feel free to do whatever the normal Ember way of doing this would be.
  - There should be an indication to the user that the request is being sent and then that the request has completed either successfully or with an error. You should be able to yank and unyank the same version repeatedly without reloading the full page.

- The ember tests should assert that the UI behaves as expected. This commit has an example of adding an ember test for the "remove owner" functionality: https://github.com/rust-lang/crates.io/commit/f524472a5f920958f43a7d6ae79bea925ab66969

- There should be a test in the Rust code that yank and unyank can be performed by `MockCookieUser`s as well as `MockTokenUser`s.
  - Implement `yank` and `unyank` helper methods on [like they are on `MockTokenUser`](https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/src/tests/krate.rs#L63-L79)
  - Duplicate [this test](https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/src/tests/krate.rs#L1450-L1486) and instead of calling `yank` and `unyank` on the `MockTokenUser`, call them on the `MockCookieUser`.
  - The owners tests are good examples of using a `MockCookieUser`. https://github.com/rust-lang/crates.io/blob/adf28ad82b4ec2aa8af95c03e42f9f361296278f/src/tests/owners.rs

**Comment by thiagoarrais** [comment]
I would like to work on this.
