### ISSUE TITLE
Optionally show publicly whether user has enabled 2FA

### ISSUE THREAD

**Issue by rugk** [rust-lang/crates.io#1667]
It would be great if one could opt-in to show publicly that the user has enabled "2FA" for their account.

For users downloading crates, this can ensure confidence and promote the very important security features.

**Comment by carols10cents** [comment]
There is no 2FA on crates.io; we use GitHub for authentication and [as far as I can tell, 2FA enablement is not something available through GitHub's API](https://developer.github.com/v4/object/user/).

Furthermore, [GitHub might not always be the only authentication provider](https://github.com/rust-lang/crates.io/issues/326). We'd have to make sure every provider made 2FA status available through their API... so I don't think it's likely we'd implement this.
