### ISSUE TITLE
Show badges or other info for crates that are known to build on stable or nightly

### ISSUE THREAD

**Issue by bluss** [rust-lang/crates.io#168]
We have this information via crater runs -- we know which crates build on stable, still build on nightly, and which crates build on neither, it would be nice to expose this information.

Especially good to badge crates that support the stable channel, but it's also nice to have an objective indicator for "dead" crates.

**Comment by rw** [comment]
+1

**Comment by bitshifter** [comment]
+1

A workmate tried diving into Rust and his first experience was trying to find a supporting library for the small application he tried to write, but the library didn't compile and his Rust experiment stopped there. I think it would have helped to warn the user if something isn't building on stable (or just not show it by default).

If the information is available it might also pay to specify which versions of stable a package builds on.

**Comment by retep998** [comment]
It would also be incredibly useful if crater could test other platforms, especially Windows,  and display which platforms a given crate actually supports.

**Comment by jan-hudec** [comment]
Most crates have [TravisCI](https://travis-ci.org/) and/or [AppVeyor](https://ci.appveyor.com/) badges in their `README.md`s and perhaps we could look at the targets and check for the set of platforms the crate was built on.

Advantages:

 * It would not need much resources.
 * It would show those platforms the author considers supported.

Disadvantages:

 * It would not cover the case when the crate started failing on newer compiler version, though that should be rather rare—the compiler is quite good with backward compatibility.
 * There is no standard for the configuration names, so we could either just rely on everybody basing their configuration on [rust-everywhere](https://github.com/japaric/rust-everywhere) anyway and look for TARGET=, or we'd have to parse the build logs for `--target` option to `cargo` and, absent that, logs from rustup setting the default target.

**Comment by Turbo87** [comment]
Since this is a relatively complex feature request, the crates.io team is currently quite busy, and there has been relatively little movement on this issue in the past I'll go ahead and close this request for now. If someone can come up with a plan (and ideally PRs) on how to implement this we can always reopen.
