### ISSUE TITLE
Documentation around crates.io protocol

### ISSUE THREAD

**Issue by mitchdenny** [rust-lang/crates.io#1680]
Hi there, I'm interested in understanding more about protocol used between ```cargo``` and http://crates.io. Is there documentation available anywhere or is the best place to start reversing it out from ```router.rs```:
https://github.com/rust-lang/crates.io/blob/master/src/router.rs

If it doesn't exist thats fine, not sure if the project would be open to a contribution that tries to capture it in a markdown file for folks that follow along after me.

**Comment by ehuss** [comment]
The protocol that cargo uses is documented here: https://doc.rust-lang.org/nightly/cargo/reference/registries.html#web-api

**Comment by mitchdenny** [comment]
Thanks! Closing this issue.
