### ISSUE TITLE
Unable to publish crate (503 Service Unavailable)

### ISSUE THREAD

**Issue by dignifiedquire** [rust-lang/crates.io#1698]
I am trying to publish my crate, but getting the following response 

```
   Uploading pgp v0.2.0 (/Users/dignifiedquire/opensource/rpgp/rpgp)
error: failed to get a 200 OK response, got 503
headers:
	HTTP/1.1 100 Continue



	HTTP/1.1 503 Service Unavailable

	Connection: keep-alive

	Server: Cowboy

	Date: Tue, 26 Mar 2019 14:31:43 GMT

	Content-Length: 506

	Content-Type: text/html; charset=utf-8

	Cache-Control: no-cache, no-store



body:
<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>
```

**Comment by dignifiedquire** [comment]
To make sure it is not an authorization issue, I tried logging in with a fresh token, but still getting the same error

**Comment by dignifiedquire** [comment]
Note: I published two other crates earlier today, without any issues from the exact same setup

**Comment by dignifiedquire** [comment]
I was able to fix the issue, by excluding some largish files I had in my repo. It would be nice to get an error that it is a size issue though, rather than this cryptic response

**Comment by sgrif** [comment]
It's not actually even getting to our server, the error you received is the hard timeout on how long a request can take. We're working on some changes to how publish works to make sure that the timeout never occurs (at which point it would get to our server and you'd receive an error that the crate is too large, the limit on what we accept is 10MB `.crate` files)

**Comment by sgrif** [comment]
Closing since it looks like you've figured out what happened, and there's nothing immediately actionable for us here

**Comment by wimvelzeboer** [comment]
Just for anyone else receiving this error. I had the same error but a different cause. I had a `./docs` folder in my repo (which was generated by `cargo docs`. After removing this folder it published fine.

**Comment by Turbo87** [comment]
@wimvelzeboer what you've seen is likely related to https://github.com/rust-lang/crates.io/issues/13193
