### ISSUE TITLE
Downloads statistics seem broken

### ISSUE THREAD

**Issue by stjepang** [rust-lang/crates.io#1704]
The downloads graph at https://crates.io/crates/crossbeam-channel displays zero 7-day avg downloads for the latest version (0.3.8). This must be wrong since the latest version is widely used and definitely has been downloaded at least once.

I suspect something is wrong due to yanking. Version 0.3.5 was yanked and all versions newer than 0.3.5 appear to be downloaded zero times, which can't be true. Looks like a bug.

**Comment by sgrif** [comment]
I can confirm that the download counts are present in the database and are being correctly served by the API, so the bug appears to be in the UI

**Comment by atouchet** [comment]
This is affecting other crates as well. It's not just crossbeam-channel that is showing incorrect values.

**Comment by kzys** [comment]
Yes. The API looks fine. Let me take a look.

https://crates.io/api/v1/crates/crossbeam-channel/downloads

**Comment by HadrienG2** [comment]
In my case, the crates.io download statistics pretend that the newest versions of my crates were downloaded before they were uploaded:

    https://crates.io/crates/testbench
    https://crates.io/crates/triple_buffer

Unless I missed the release announcement of time travel features in Cargo, it seems likely that the statistics are wrong.

**Comment by bryanburgers** [comment]
I don't think this has anything to do with yanking. I can find crates with no yanks (https://crates.io/crates/lazy_static, https://crates.io/crates/tokio-io-pool) that seem to exhibit the same issue.

**Comment by sgrif** [comment]
Fixed by https://github.com/rust-lang/crates.io/pull/1728
