### ISSUE TITLE
Crates.io does not sent a verification message to my email

### ISSUE THREAD

**Issue by AhmedMostafa16** [rust-lang/crates.io#1707]
I logged in my Github account and `cargo` requested to verify an email and I did. I added my email and I asked to Resend button more than 5 times but I don't get anything.

![Screenshot_2019-04-05 Settings - Cargo packages for Rust](https://user-images.githubusercontent.com/41272326/55653410-f6b5a880-57dd-11e9-88bd-6c20f05de35e.png)

OS: Windows 10 Build 1809.
Rust Version: 1.35.0 (Nightly).

**Comment by carols10cents** [comment]
Hi, I checked the logs for our mail service provider and they're saying the emails went through to you. Could you check your spam filter please? Thanks!

**Comment by BenLeadbetter** [comment]
I'm having the same issue at the moment. I've checked my spam and there are no emails there. Haven't received an email for two days now :-/

**Comment by BenLeadbetter** [comment]
I changed my email to my gmail alternative and I got my confirmation. Maybe it didn't like my `@hotmail.com` ??

**Comment by carols10cents** [comment]
@BenLeadbetter Can you please email help@crates.io and let us know the two email addresses you tried? We recently added some more logging around email sending so hopefully we can figure out what's going on. Thanks!

**Comment by BenLeadbetter** [comment]
Thanks for the reply! I’ve emailed

Sent from my iPhone ***@***.*** like you suggested. Thanks!

On 17. Mar 2022, at 00:40, Carol (Nichols || Goulding) ***@***.***> wrote:

﻿

@BenLeadbetter<https://github.com/BenLeadbetter> Can you please email ***@***.******@***.***> and let us know the two email addresses you tried? We recently added some more logging around email sending so hopefully we can figure out what's going on. Thanks!

**Comment by codereport** [comment]
> I changed my email to my gmail alternative and I got my confirmation. Maybe it didn't like my `@hotmail.com` ??

My hotmail adress also did not work. Switching to a gmail address solved the issue.
