### ISSUE TITLE
comment in codebase requests that the team is contacted.

### ISSUE THREAD

**Issue by dardevelin** [rust-lang/crates.io#1718]
As the title indicates, there is a comment in the codebase that requests that the team is contacted if the code remains commented out post nov 7 2018.

https://github.com/rust-lang/crates.io/blob/cfe6e08dc7d6684c09f82ebf12d7e5ed66436bc9/src/middleware.rs#L99

**Comment by kzys** [comment]
From https://github.com/rust-lang/crates.io/commit/9a17c16e6c213b141533b60b97651181ccad594e. So @sgrif would know the reason :)

**Comment by SoniEx2** [comment]
I'd rather have a cargo option to disable user agents. they're only useful for tracking, anyway.

**Comment by sgrif** [comment]
This has been fixed.
