### ISSUE TITLE
Automatically expire api tokens every few months

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang/crates.io#1724]
(see also #1723 )

please expire the public keys every few months so as to prevent stale keys from sticking around and creating an unnecessary attack surface.

**Comment by sgrif** [comment]
https://github.com/rust-lang/crates.io/issues/1723#issuecomment-491954456

**Comment by SoniEx2** [comment]
doesn't require changes to cargo or anything else. just crates.io.

**Comment by sgrif** [comment]
Sorry, I didn't realize that you meant for this to apply to API tokens and assumed it was based on your other PR. I don't think we're willing to just start expiring people's tokens since it affects existing workflows, but I'll leave this open for discussion

**Comment by SoniEx2** [comment]
it should apply to whatever the client uses to access the server, be it tokens or public keys or some other completely different mechanism.

**Comment by Turbo87** [comment]
New API tokens can now be created with explicit expiry dates, so I guess we can finally close this issues :)
