### ISSUE TITLE
Please add category slug "ludum-dare"

### ISSUE THREAD

**Issue by ctsrc** [rust-lang/crates.io#1731]
It'd be nice to have a category for Ludum Dare game jam submissions that are written in Rust.

Please add category slug `ludum-dare`.

**Comment by kzys** [comment]
https://ldjam.com

> Ludum Dare is one of the world's largest and longest running Game Jam events. Every 4 months, we challenge creators to make a game from scratch in a weekend.

**Comment by ctsrc** [comment]
@kzys Yup, that's the one!

**Comment by sgrif** [comment]
This isn't the sort of thing we typically create categories for. They have to be fairly broad, and relevant to a large percentage of the Rust userbase. Keywords are better suited for this sort of thing, as they're user-defined and also taken into account for search.
