### ISSUE TITLE
Show contents of crates and automatically-verify that they match linked repository

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/crates.io#1734]
The source code published to crates.io does not need to match the one in the git repository linked to the crate. I think that being able to easily inspect the code is a critical feature for trusting the crates.io ecosystem, and also that crates.io should be able to automatically verify that the code uploaded to crates.io matches that of the linked repository (e.g. by using git tags to diff the code or similar).

**Comment by gnzlbg** [comment]
cc @shnatsel

**Comment by carols10cents** [comment]
We do not require crates to have any repository specified. Docs.rs has a way to browse the published source online, so crates.io is not going to duplicate that.
