### ISSUE TITLE
Use Macaroons as crates.io API credentials?

### ISSUE THREAD

**Issue by tarcieri** [rust-lang/crates.io#174]
I have been working on a Rust library that implements the Macaroons (http://macaroons.io) bearer credential format:

https://github.com/cryptosphere/rust-macaroons

See this Air Mozilla talk for some more background on Macaroons:

https://air.mozilla.org/macaroons-cookies-with-contextual-caveats-for-decentralized-authorization-in-the-cloud/

Macaroons enable a lot of use cases which aren't possible with other credential formats.

One that's particularly compelling: creating a credential which grants time-limited authority to do something without needing to loop in the issuing service to "remint credentials". You could potentially do something like:

```
cargo delegate servo --ttl 5m
```

Or something to that effect to generate a credential that can be used to publish a particular crate for a short period of time.

The format is incredibly extensible so it can enable attenuating an API credential to pretty much any use case you can think of.

I'm not sure if these are useful or helpful features, and there are other credential formats that are more popular to consider (e.g. JWT), but my personal opinion is that Macaroons represent the state-of-the-art of bearer credentials.

I think one of the most interesting use cases is robots: you can make a credential to hand a robot (e.g. @bors) that gives them time-limited authority to publish a crate.

**Comment by cmr** [comment]
:+1:

**Comment by alexcrichton** [comment]
This sounds like a great idea! So long as everything continues to work backwards compatibly and across all platforms this is basically just a "let's get this done" issue.

**Comment by tarcieri** [comment]
For backwards compatibility, I'd suggest continuing to support the existing format, but switching to issuing credentials as Macaroons. Perhaps you can set a sunset date at some point in the future to switch over wholesale.

I'll start looking into this, since there's interest in this approach.

**Comment by alexcrichton** [comment]
Yeah that seems totally plausible!

**Comment by Turbo87** [comment]
since there hasn't been any movement on this issue for close to 5 years I'll go ahead and close this issue. if this ever becomes relevant again feel free to reopen :)

**Comment by tarcieri** [comment]
These days I'd suggest @geal's "biscuit" for this purpose, FWIW.

https://github.com/CleverCloud/biscuit

But also agree with closing this issue.
