### ISSUE TITLE
Add default README files.

### ISSUE THREAD

**Issue by matrizx** [rust-lang/crates.io#1742]
When publishing a crate, if no `readme` is specified in `Cargo.toml`, a list of commonly used readme names should be looked through, and if the directory contains that file automatically use it as the readme (similarly to how GitHub does it).

**Comment by sgrif** [comment]
This behavior is entirely controlled by Cargo, we never actually read the file, we only render what Cargo sends us as the contents of the README. You'd need to open an issue on Cargo for a change to occur here.
