### ISSUE TITLE
API access blocked: unable to process request (c004837b-ce80-46d6-bf07-20ad919915fa)

### ISSUE THREAD

**Issue by zleonov** [rust-lang/crates.io#1743]
Hi, I am hoping we can get in contact. I have sent several emails to help@crates.io, but received no response. Please don't think that I am trying to spam you guys, I am just looking for a way to get this resolved.

A copy of my email below:
***
Hi,

I am an engineering manager at Flexera, a company that helps enterprises manage their hardware and software assets.

My group is responsible for maintaining and categorizing our Open Source Software catalog in support of our OSS management solutions. We saw that the Rust language is growing in popularity, and wanted to add projects from crates.io to our database.

Originally we didn’t seem to find documentation detailing your crawler policy.
I saw that other projects were using the API (https://github.com/rust-lang/crates.io/wiki/Projects-that-use-crates.io%27s-API), but it appears we might have hit the API too often, because right now we are getting:

We are unable to process your request at this time. This usually means that you are in violation of our crawler policy (https://crates.io/policies#crawlers). Please open an issue at https://github.com/rust-lang/crates.io or email help@crates.io and provide the request id e7a9b632-6b1d-4ee2-b228-d54fcd0c0ee9

I now see your crawlers policy (https://crates.io/policies#crawlers) and want to assure you we will fully comply with it. I checked to see the crates.io-index (https://github.com/rust-lang/crates.io-index) but it does not have the information that we need.
We have no problem adhering to 1 request per second or less.

We will add the appropriate user agent to our request headers, I propose: User-Agent: Flexera (zleonov@flexera.com)
***
Thanks a lot guys,

Zhenya Leonov
Senior Manager, Data & Content Services | Flexera Software - SCA
1901 Harrison Street, Oakland, CA 94612
408.202.3868
zleonov@flexera.com | https://www.flexera.com/

**Comment by sgrif** [comment]
I apologize that your email didn't receive a response. It looks like it got flagged as spam. Since you have agreed to limit your request rate to 1 request per second and add an identifying User Agent header, you should now be able to send traffic to our API.
