### ISSUE TITLE
Please conside DELETING spam crates own by swmon

### ISSUE THREAD

**Issue by XuShaohua** [rust-lang/crates.io#1747]
This user, https://crates.io/users/swmon, created 104 crates, but all of the are empty.
So some meaningful crate names have been take by him.

**Comment by sgrif** [comment]
Thanks. We're aware of this user.

**Comment by AaronRocinante** [comment]
Please also do something about the crates created by this user https://crates.io/users/mahkoh
He has lots of empty crates and one of them is called math

**Comment by jhpratt** [comment]
@sgrif Is there a way for someone to take over one of that user's crates? I'm interested in "sign", specifically. Given that there's clearly no intention of using the name and no way to contact the owner, I'd imagine it could be forcibly transferred at some level.

**Comment by carols10cents** [comment]
@jhpratt We don't transfer any crates without the owner's permission.

**Comment by jhpratt** [comment]
@carols10cents Is there any plan to introduce a policy for clearly abandoned, empty crates then? I obviously fully understand not forcing a transfer on any crate that has content, even if inactive. But in a situation like this, I see zero reason why it _shouldn't_ be transferred to someone willing to make it a maintained crate.

**Comment by sgrif** [comment]
@jhpratt Any policy changes will require an RFC. https://github.com/rust-lang/rfcs/pull/2614 is likely of interest to you.

**Comment by 89z** [comment]
https://github.com/rust-lang/crates.io/issues/1480
