### ISSUE TITLE
Accessing www.crates.io (both with http and https) returns "Server not found"

### ISSUE THREAD

**Issue by dlight** [rust-lang/crates.io#175]
Instead, they should both redirect to `https://crates.io` with a 301 code.

If the issue is that the SSL certificate isn't a wildcard, then at least `http://www.crates.io`  should redirect.

**Comment by alexcrichton** [comment]
This is actually because the DNS record for www just doesn't exist (intentionally so)

**Comment by carols10cents** [comment]
> This is actually because the DNS record for www just doesn't exist (intentionally so)

This sounds like a wontfix then, please reopen if I'm mistaken!
