### ISSUE TITLE
Can you provide an option just to update the Readme/description page without updating the version number?

### ISSUE THREAD

**Issue by abbychau** [rust-lang/crates.io#1750]
as title.

sometimes I just want to update doc or readme and showing it on crates.io as well

**Comment by sgrif** [comment]
No, the readme is tied to the version

**Comment by abbychau** [comment]
I know that there is no.

This is a feature request.

**Comment by carols10cents** [comment]
I think what sean was trying to say is that the README is part of the `.crate` file that is an immutable artifact labeled by the version number, so letting you update the README file would break a fundamental decision we've made about how crates.io works.

**Comment by abbychau** [comment]
I understand that readme is part of the crate, which shares the same design like packagist and npmjs too.
I would think that it is more a feature of "cargo publish" and "crates.io" that to make the configuration of the description page of the package configurable so to reduce useless version bumps, rather than a crate design problem. 

In contrast, making README.md(or README) to be a special file to be fetched is instead introducing unnecessary convention knowledge. 

Can you consider introducing `cargo publish_readme local_file_as_text_input.md` so to update the description of the crate? so that no version bumping is needed, and thus reducing unnecessary dependending projects' updates.

**Comment by Kxuan** [comment]
The author may just want update `FAQ` section, contact email, or the text about where to read doc and example. It does not affect any code in the crate.

And it should not notify all users of the crate to update to a new version.

**Comment by ofersadan85** [comment]
Joining this request. The readme stated in `Cargo.toml`
```toml
readme = "README.md"
```
Can be subject to many changes that don't break user code or functionality. As long as the line in `Cargo.toml` isn't changed, updating a readme can have many use cases:
1. Updating contact details, urls etc.
2. Fixing typos
3. The readme could have deprecated usage instructions that relate to another version (developer forgot to update the readme)

I imagine it would not break your philosophy to have a command that does just this? Something like
```bash
cargo publish --readme-only
```
