### ISSUE TITLE
Have a "one-click" removal option for admins to remove a version across both crates.io and docs.rs

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#1764]
Recently, we had a trademark violation crate we needed to take down. We took care of crates.io, but that didn't remove the crate from docs.rs.

The short-term solution for this issue could be documenting the exact procedures/commands/etc that should happen manually when we need to remove a version or an entire crate, across both crates.io and docs.rs.

The long-term solution for this issue could be creating a button/command/something for admins of crates.io to quickly remove a version or all versions of a crate that removes the same content from docs.rs automatically.

This is a sibling issue of https://github.com/rust-lang/docs.rs/issues/368, filed in both places so we can collaborate ❤️

**Comment by carols10cents** [comment]
Documentation started at https://github.com/rust-lang/crates-io-cargo-teams/blob/master/crate-removal-procedure.md

**Comment by kzys** [comment]
Moved to https://github.com/rust-lang/crates-io-cargo-teams/blob/master/docs/crate-removal-procedure.md

**Comment by Turbo87** [comment]
docs.rs is automatically monitoring the index and should be able to implement the removal on their side if they see that a crate is completely deleted from the index. Since this implementation needs to happen on the docs.rs side (or has already happened?) I will close this issue :)

**Comment by syphar** [comment]
@Turbo87 docs.rs is doing this for quite some time already, probably since https://github.com/rust-lang/docs.rs/pull/1742 (June 2022) and https://github.com/rust-lang/docs.rs/pull/2163 (July 2023)

**Comment by Turbo87** [comment]
good to know. thanks! :)
