### ISSUE TITLE
Allow sorting search results by number of reverse dependencies

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/crates.io#1770]
The title sums it up.

**Comment by locks** [comment]
Is this in the API or the website?

**Comment by smarnach** [comment]
We'd need it in the API either way.

It is not completely clear how the number of reverse dependencies of a crate is supposed to be defined. The [query we use for the reverse dependencies page](https://github.com/rust-lang/crates.io/blob/fd08c18b7a9dd7191fea3a7dc79fe7153f29d368/src/models/krate_reverse_dependencies.sql) is rather slow and definitely not suitable for sorting, so we would need a new database index to make this work.
