### ISSUE TITLE
Redirect from one crate to another, or rename.

### ISSUE THREAD

**Issue by onelson** [rust-lang/crates.io#1775]
I'm looking for advice.

I'm in a situation where I'm unclear as to the best approach to proceed. I'm not sure if this constitutes a dupe of #166 or if it's technically something else.

I have a _family of crates_, as in there are some -src and -sys crates which depend on each other, and a higher level crate to rest on top of them. Originally I started with just the top level crate, and I have regrets about the name choice (it was overly broad). The -sys and -src are named consistently, and I wish to re-align the family by renaming the top level crate to match.

Since several versions have already been published to the old name, I'd like it to continue to resolve. A scheme I am strongly considering is to, with my next release:

- include a notice at the top of the readme to indicate the name change (and leave it there forever?!)
- publish to both names

I have also considered the option of publishing back-versions to the new name effectively making it so the old crate is a dead version line, but the new has all the releases.

I suppose I could also publish a final divergent update to the old crate with a deprecation notice and link to the new name.

Is there any mechanism that could help me with this effort on the registry side? Naming things is hard, and I'm sure to not be the last person to find themselves in this situation.

Thanks for your insights!

**Comment by sgrif** [comment]
Unfortunately we can't change the name of an existing crate for you, and there's nothing in place today that would allow you to redirect. Publishing a final version with a deprecation that points to the new name is a pretty common strategy that I've seen used both in Rust and other ecosystems, and I'd recommend doing that.

**Comment by onelson** [comment]
Will do. Thanks for the sanity check, @sgrif !
