### ISSUE TITLE
request id dca42478-3e18-4efe-bedd-685f9fecdce0

### ISSUE THREAD

**Issue by ananevans** [rust-lang/crates.io#1779]
I run a script I wrote last year, that violated the crawler policy put in place since then. I was trying to collect the number of downloads for each crate and I didn't wait between consecutive requests since I wasn't aware of the crawler policy.

I will not run it again, I will just use the old data. 

Could I get access back so I can compile my project?

I emailed help@crates.io, but got no reply.

**Comment by sgrif** [comment]
Hi Ana,

I'm sorry that it took so long to reply to your email. Your traffic has been unblocked, and you should have a reply in your inbox.
