### ISSUE TITLE
s-snappy-sys Inconstencies in the index

### ISSUE THREAD

**Issue by kornelski** [rust-lang/crates.io#1786]
Possibly some incomplete spam deletion?

s-rocksdb-sys@0.5.5 depends on missing crate s-snappy-sys:

https://github.com/rust-lang/crates.io-index/blob/dda27c830ecbaa294716a365a9f22db467649da0/s-/ro/s-rocksdb-sys

https://crates.io/search?q=s-snappy-sys

Similarly:

susy-rocksdb-sys@0.5.5 depends on missing crate susy-snappy-sys
rs-rocksdb-sys@0.5.5 depends on missing crate rs-snappy-sys
s-trie-standardmap@0.1.1 depends on missing crate keccakhash
s-trie-standardmap@0.1.1 depends on missing crate s-bytes
susydev-rocksdb-sys@0.5.5 depends on missing crate susydev-snappy-sys

**Comment by Turbo87** [comment]
We discussed this issue in the crates.io team meeting on Friday and concluded that we will probably keep the index in this semi-broken state. There are a couple of possible options for this:

- keep it as-is
- delete the dependency declarations from the depending crates
- delete the depending crate versions with the dependency

There might be more, but out of these options it seems that keeping it as-is is the least invasive option. We are open to revisiting the decision in the future though.

Note that we recently had to delete two more crates (`qtrac-retest` and `differ`) with reverse dependencies that are now in a similar state as `s-snappy-sys`.
