### ISSUE TITLE
consider mirroring crates.io index on platforms not restricted by U.S. laws

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/crates.io#1790]
From the [GitHub and Trade Controls](https://help.github.com/en/articles/github-and-trade-controls) page:

>GitHub.com, GitHub Enterprise Server, and the information you upload to either product may be subject to trade control regulations, including under the U.S. Export Administration Regulations (the EAR).

>On which countries and territories are U.S. government sanctions applied?
>Crimea, Cuba, Iran, North Korea, and Syria.

>Will non-enterprise users in these sanctioned countries still be blocked from GitHub?
>For individual users, who are not otherwise restricted by U.S. economic sanctions, GitHub currently offers limited restricted services to users in these countries and territories. This includes limited access to GitHub public repository services for personal communications only.

(Friday, July 26, 2019)

The question is if people from the restricted countries are able to clone git repositories, and, since the [crates.io-index](https://github.com/rust-lang/crates.io-index) is hosted on github, are able to use cargo to download crates from crates.io (which to my knowledge requires cloning the index first).

If there is indeed a restriction preventing a `cargo fetch` from working in those countries, it might be worth exploring alternatives to hosting the index on github.

**Comment by sgrif** [comment]
To my knowledge, users in sanctioned countries are able to clone the index and there are no plans to change that. If you've found that not to be the case, please let us know. However, after looking into this, I do not believe that users are affected by this.
