### ISSUE TITLE
Can we have a "mathematics" category slug?

### ISSUE THREAD

**Issue by ornamentist** [rust-lang/crates.io#1791]
Crates.io category slugs includes a very broad "science" slug, covering a huge range of fields and disciplines.

Could we have a "mathematics" slug for crates that are specifically mathematically oriented (like my crate https://crates.io/crates/un_algebra)? 

I understand this might lead to requests for, for example, "physics" or "chemistry" slugs, although "mathematics", "physics", "chemistry" etc are still very broad terms.

**Comment by carols10cents** [comment]
Hi @ornamentist ! Sorry this has taken so long, but @mindriot101 has opened https://github.com/rust-lang/crates.io/pull/1893 for this. They'd like some feedback/suggestions on what the description for the category should be-- do you have any thoughts? Thanks!

**Comment by carols10cents** [comment]
Fixed by https://github.com/rust-lang/crates.io/pull/1893
