### ISSUE TITLE
GitHub OAuth app missing icon

### ISSUE THREAD

**Issue by mikemorris** [rust-lang/crates.io#1792]
Just a minor polish issue, but it would be nice if the GitHub OAuth app had a custom icon instead of the default avatar.

<img width="357" alt="Screen Shot 2019-05-29 at 7 57 46 PM" src="https://user-images.githubusercontent.com/1149913/62262706-ac3ce500-b3e7-11e9-9a58-467ad38fac34.png">

Perhaps the logo used on crates.io?
![Cargo-Logo-Small-c39abeb466d747f3be442698662c5260](https://user-images.githubusercontent.com/1149913/62262785-f920bb80-b3e7-11e9-9003-cc21146c4278.png)

The logo can be updated (as a member of the rust-lang organization) by selecting the OAuth app from https://github.com/organizations/rust-lang/settings/applications/, then uploading a new icon.

<img width="479" alt="Screen Shot 2019-07-31 at 11 10 08 PM" src="https://user-images.githubusercontent.com/1149913/62262936-7a784e00-b3e8-11e9-87f1-03e6f82a3595.png">

**Comment by carols10cents** [comment]
You're absolutely right! I've taken care of this.
