### ISSUE TITLE
feature request: notification when dependencies need update

### ISSUE THREAD

**Issue by nestordemeure** [rust-lang/crates.io#1794]
Most crates are published with up-to-date dependency versions. As time goes by, it might not be the case anymore and authors could miss it which could cause users to indirectly depend on code which has known bugs / security vulnerabilities.

Crates.io could send an email (/ message  / notification on crates.io) when a new version of a dependency, on which one of our published crates depends, goes out.
This would not only mitigate the problem but might also encourage crates to have more homogene dependencies (everyone depends on the latest version).

The feature could be globally, or on a per crate basis, deactivable.

**Comment by carols10cents** [comment]
I think this is better served by [Dependabot](https://dependabot.com/rust/) rather than crates.io. You definitely have a good idea though!

**Comment by nestordemeure** [comment]
I never heard about dependabot but it, indeed, seems to fill this purpose. One downside is that, since it is not a default, I don't expect most package on cargo to use it and thus it might not make a huge difference to the ecosystem.

(by the way, great work on crates.io/cargo, its one of the things that makes Rust shine)
