### ISSUE TITLE
Old Cargo can't download crate anymore

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/crates.io#1808]
My 1.15.0 build in Travis started failing with this output today:

```console
$ cargo build --manifest-path tests/crate/Cargo.toml
warning: unused manifest key: badges.appveyor.repository
warning: unused manifest key: badges.travis-ci.repository
warning: unused manifest key: package.categories
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading serde v1.0.99
error: unable to get packages from source

Caused by:
  failed to get 200 response from `https://crates.io/api/v1/crates/serde/1.0.99/download`, got 500
The command "cargo build --manifest-path tests/crate/Cargo.toml" exited with 101.
```

https://travis-ci.org/serde-rs/json/jobs/573591356

I've retriggered this build a few times and it still fails the same way. I've retriggered the builds on other rustc (1.18.0, 1.31.0, stable, beta, nightly) and those all seem to work.

Any idea what could be going wrong? If it's nothing obvious, I will try to debug further.

**Comment by dtolnay** [comment]
Here is a different repo failing the same way on a different crate, also on rustc 1.15.0. This reduces the chance that it's some local build cache associated with the Travis repo that's in a bad state.

```console
$ cargo test --test test
warning: unused manifest key: badges.travis-ci.repository
warning: unused manifest key: badges.travis-ci.repository
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading proc-macro-hack v0.4.2
error: unable to get packages from source

Caused by:
  failed to get 200 response from `https://crates.io/api/v1/crates/proc-macro-hack/0.4.2/download`, got 500
The command "cargo test --test test" exited with 101.
```

https://travis-ci.org/dtolnay/mashup/jobs/573599639

**Comment by sgrif** [comment]
Thanks for the report. This should now be fixed. Can you confirm that your build with old versions of cargo is passing once again?

**Comment by dtolnay** [comment]
Yes it's fixed. Thank you!
