### ISSUE TITLE
Add user's comments under crates

### ISSUE THREAD

**Issue by jankoprowski** [rust-lang/crates.io#1820]
Hello,

  Thank you for great language and your work!
  What I think might be useful is to give people possibility to comment under crate.
  Comments should be moderated.
  This might be a goldmine of use cases of community gathered around crate.

Regards,

Jan

**Comment by carols10cents** [comment]
We don't have enough moderators to do this work. Thanks for the ideas though! If you want to make comments about a crate, I suggest you write some blog posts that will come up if someone does a google search for a crate.
