### ISSUE TITLE
Support licensezero on crates.io

### ISSUE THREAD

**Issue by mgattozzi** [rust-lang/crates.io#1828]
[licensezero](https://licensezero.com/) is a different kind of license for developers, but is not listed at https://spdx.org/licenses and as such gives an api error when trying to publish to crates.io. Would it be possible to add this license or no?

**Comment by ehuss** [comment]
You may use any license by using the `license-file` key instead of `license`, and point to a file with your license.

**Comment by carols10cents** [comment]
Yes, please use `license-file` instead for this. Thanks!

**Comment by mgattozzi** [comment]
Ah I didn't know about this! Thanks @ehuss and @carols10cents!
