### ISSUE TITLE
Anchor links in READMEs don't work on initial page load

### ISSUE THREAD

**Issue by thombles** [rust-lang/crates.io#1847]
I saw a link in [a tweet](https://twitter.com/dpc_pw/status/1174781770060845056) of the following form: https://crates.io/crates/oorandom#user-content-a-brief-history-of-random-numbers

Expected behaviour: Page loads, README loads, JS triggers a scroll to the now-present anchor

Current behaviour: Page loads, README loads, scroll stays at the top, visitor is left wondering what they're looking at

**Comment by locks** [comment]
Attempted fix at https://github.com/rust-lang/crates.io/pull/1848 :)

**Comment by thombles** [comment]
Amazing, thanks! :)
