### ISSUE TITLE
Link older version of repositories to appropriate commit branch on GitHub

### ISSUE THREAD

**Issue by srikwit** [rust-lang/crates.io#1858]
Hello Team,

This is a feature request for crates.io and from the perspective of someone maintaining an older version of a Rust project.

The current version of crates.io allows us to view the older version details and their release date of a given crate.

For some crates hosted on GitHub, not all Cargo version bumps within the crate are designated as releases or tags. Clicking on the Repository link on a given crate will only take us to the latest version of the crate on GitHub.

I believe authors should have a feature to provide mapping between a given version on crates.io and its equivalent commit branch on GitHub.

**Comment by carols10cents** [comment]
We don't currently require *any* repository link for a crate; nor do we require that the repository link be to a GitHub repository. The best way to audit crate code is to download the crate file from crates.io that gets included into your project.
