### ISSUE TITLE
Crates.io should support mysql as a backend

### ISSUE THREAD

**Issue by achanda** [rust-lang/crates.io#186]
This'd be a step towards running a in-house version of crates.io. Companies often have preferences for databases. If a company already has a mysql deployment, they'd rather want to use that than creating a postgres deployment. For this to work, `crates.io/src/migrate/lib.rs` and `crates.io/src/db.rs` needs to be abstracted away to handle mysql.

**Comment by carols10cents** [comment]
I don't think we're going to do this.
