### ISSUE TITLE
Support for GitHub Actions badges

### ISSUE THREAD

**Issue by matchai** [rust-lang/crates.io#1862]
With GitHub Actions launching publicly this November, and existing Rust projects beginning to use it as their primary CI platform, I would love to see support for GitHub Actions badges. This would perform similarly to existing GitLab badge support.

GitHub Actions badges are documented here: https://help.github.com/en/articles/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository

If y'all don't mind, I'll try opening a PR in the next few days to add support. 😄

**Comment by smarnach** [comment]
We already have #1838 to address this.

**Comment by matchai** [comment]
No clue how I missed that one when searching. 😅 
My bad! Closing this one.
