### ISSUE TITLE
different content displayed on refresh, sometimes

### ISSUE THREAD

**Issue by howaboutsynergy** [rust-lang/crates.io#1865]
Try this page: https://crates.io/crates/linked-hash-map
Sometimes you see this:
![Screenshot_2019-10-10_18-38-05](https://user-images.githubusercontent.com/49106389/66588617-2aa6c780-eb8d-11e9-85b8-3187eba647df.png)

sometimes this:
![Screenshot_2019-10-10_18-38-16](https://user-images.githubusercontent.com/49106389/66588624-2f6b7b80-eb8d-11e9-80f0-f9404c4d7a5e.png)

simply by refreshing the (same) page (ie. F5)

This seems to be true for any package page, eg.
here's another:
https://crates.io/crates/okofdb
![Screenshot_2019-10-10_18-39-07](https://user-images.githubusercontent.com/49106389/66588700-52962b00-eb8d-11e9-883c-d76718ab2f08.png)

![Screenshot_2019-10-10_18-39-27](https://user-images.githubusercontent.com/49106389/66588705-56c24880-eb8d-11e9-8181-c2bb8a209bd1.png)

**Comment by howaboutsynergy** [comment]
hmm that doesn't happen on firefox. On Firefox the first page is briefly shown then replaced by the second page in like 1 second.

**Comment by smarnach** [comment]
I can't reproduce this issue in any of my browsers (Firefox, Chromium, Chrome).

Can you reproduce the issue with the "Network" tab of the developer tools open? If so, does the list of requests include https://crates.io/api/v1/crates/linked-hash-map/0.5.2/readme with a 302 status code, and https://static.crates.io/readmes/linked-hash-map/linked-hash-map-0.5.2.html with a 200 status code? Are there any error messages in the JavaScript console?

**Comment by howaboutsynergy** [comment]
Thanks for the great ideas,
I've got a `(pending)` on the html, and it must then, clearly, be Chromium's fault. Just wish I knew why/how. But since I'm using some ungoogled-chromium patches and some of my own, they must be it. So closing as my bad.

<details>

good:
![Screenshot_2019-10-16_23-34-34](https://user-images.githubusercontent.com/49106389/66961416-e032b880-f06e-11e9-800b-46774b87afe1.png)
![Screenshot_2019-10-16_23-34-43](https://user-images.githubusercontent.com/49106389/66961419-e2951280-f06e-11e9-889f-c26abf995f6b.png)


bad:
![Screenshot_2019-10-16_23-35-36](https://user-images.githubusercontent.com/49106389/66961427-e88af380-f06e-11e9-8f62-dcf67f5269b2.png)
![Screenshot_2019-10-16_23-35-45](https://user-images.githubusercontent.com/49106389/66961429-eaed4d80-f06e-11e9-903b-bb5f2bfd262b.png)


</details>

![pending](https://user-images.githubusercontent.com/49106389/66961433-ef196b00-f06e-11e9-895c-fe0459dac9c7.png)
![stalled](https://user-images.githubusercontent.com/49106389/66961470-03f5fe80-f06f-11e9-8d25-ddcfac89908c.png)

But note that it only happens sometimes, but I assume you've tried multiple times? (like 10 should do, with shift+LMB on the Refresh button)

if I do shift+refresh after a while, the old request gets cancelled (shows 13.8min):
![cancelled](https://user-images.githubusercontent.com/49106389/66961927-09077d80-f070-11e9-8716-257dad2f96ef.png)

the request when it fails looks like:
![req](https://user-images.githubusercontent.com/49106389/66961955-17559980-f070-11e9-822f-96255b11e962.png)


and when it succeeds looks like:
![reqok](https://user-images.githubusercontent.com/49106389/66962209-b37fa080-f070-11e9-9433-462c89e5f0c3.png)

**Comment by smarnach** [comment]
I tried many times, and could not reproduce this on Chromium. And this indeed looks like your browser doesn't even finish sending the request, so there is nothing we can do on the crates.io end. The rendered readme files are stored on AWS S3, and served via AWS CloudFront, so this request isn't even sent to a server we control.
