### ISSUE TITLE
Timeout when publishing

### ISSUE THREAD

**Issue by tafia** [rust-lang/crates.io#1866]
It's been one hour that I am trying to publish a new version of my crate and I always get a `error: [28] Timeout was reached`.

My target/package/crate is about 4.4M.

**Comment by tafia** [comment]
Didn't work from one computer but worked from another. Closing it even if it is not clear what was happening. (i could publish other crates from the failing computer)

**Comment by sgrif** [comment]
We have a hard 30 second timeout on all requests. Unfortunately this means that large publishes may be limited by your bandwidth. This is something we'd like to eventually fix by having publishes bypass our web server entirely, but that's an extremely large project that's unlikely to be completed any time soon. In the short term, if your crate is under 10 MB and you run into this issue in the future, you can attach the crate file in an email to help@crates.io and we will handle this for you

**Comment by tafia** [comment]
Thank you for taking time to answer a closed issue.

As explained my crate was 4.4M, it didn't work with one computer but worked with another one on the same network. I didn't always get the error message saying to send an email to help@crates.io. Sometimes, it just wrote `timeout was reached`.

I believe a large part of my crate size comes from assets used in tests. Is there a way to publish a crate without these tests/examples?

Anyway thanks again.

**Comment by smarnach** [comment]
You can use the [`exclude` and `include` keys in the `package` section of `Cargo.toml`](https://doc.rust-lang.org/cargo/reference/manifest.html?highlight=exclude#the-exclude-and-include-fields-optional) to define what files are included in the upload.

Alternatively, if you are on a slow internet connection, you can copy your crate to a remote server with a fast internet connection first, and run `cargo publish` from there (e.g you could use a small instance from the AWS EC2 or GCE free tiers). The upload to the remote server is allowed to take any amount of time, and the upload from the cloud server should be fast enough to easily finish within 30 seconds.
