### ISSUE TITLE
A high value of per_page throws an exception

### ISSUE THREAD

**Issue by achanda** [rust-lang/crates.io#187]
For this URL `https://crates.io/crates/mio/reverse_dependencies?per_page=200` I see the following exception. This occurs for all endpoints which supports pagination.

<img width="1243" alt="screen shot 2015-08-24 at 2 10 51 pm" src="https://cloud.githubusercontent.com/assets/2165463/9452594/099cd02a-4a6a-11e5-8892-3eef5d7c3b7e.png">

There should be a way to get all reverse dependencies. At least, this should not error out.

**Comment by Gankro** [comment]
I agree this shouldn't error out like this, but e.g. Github's APIs don't allow you to fully disable pagination.

**Comment by achanda** [comment]
True, but I don't believe crates.io supports relative links for pagination. The github API supports that. This enables a client to know how to reach the next page if one exists. This enables getting all the data page by page. How would a client do that for crates.io?

**Comment by alexcrichton** [comment]
Yeah we're just returning a normal API error that the `per_page` is too high (200 > 100). I don't think the error handling of API requests is handled too well right now across the board.

**Comment by kyrias** [comment]
Right now you'll have to make one request and then take the total number of result under the meta key and divide by the number of request you're making, but I wonder how much work it would be to implement next-page links.

**Comment by achanda** [comment]
Looks like the exception is gone now, but the count says NaN

<img width="1368" alt="screen shot 2016-08-25 at 10 36 37 am" src="https://cloud.githubusercontent.com/assets/2165463/17979551/0514d766-6ab0-11e6-85e2-a15027b0847b.png">

**Comment by kyrias** [comment]
Mmmm.  This will probably require adding a handlebars helper to check whether it's NaN, though I'm not sure how to add that.

**Comment by carols10cents** [comment]
On https://crates.io/crates/mio/reverse_dependencies?per_page=200, the API request (https://crates.io/api/v1/crates/mio/reverse_dependencies?page=1&per_page=200) returns this JSON:

```
{"errors":[{"detail":"cannot request more than 100 items"}]}
```

Similar errors happen in other places with pagination, such as browsing all crates: https://crates.io/crates?per_page=500 makes a request to https://crates.io/api/v1/crates?page=1&per_page=500&sort=alpha that returns the same JSON.

It'd be nice to have a way to handle this error and display the detail on the page for anyplace that has pagination, but I'm not sure the right way to do that with ember :(

**Comment by smokytheangel0** [comment]
I would really like to take a look at this one, is there a precedent for adding alot of dummy crates to a local build, or do I have to figure something out myself?

**Comment by carols10cents** [comment]
We have [database dumps of public information available](https://crates.io/data-access), so you can have all the crates in your local build! The archive has info in it for how to load the data into your local db, please let me know if anything in there is unclear or doesn't work!

**Comment by smokytheangel0** [comment]
thanks Carol.

**Comment by Turbo87** [comment]
closing this issue as https://github.com/rust-lang/crates.io/pull/2940 should have fixed this :)
