### ISSUE TITLE
Base list of allowed HTML tags and attributes on the Ammonia defaults

### ISSUE THREAD

**Issue by smarnach** [rust-lang/crates.io#1872]
Our readme renderer uses [Ammonia](https://docs.rs/ammonia/2.0.0) to sanitise the HTML. We currently explicitly [list all HTML tags and attributes we allow in the source code](https://github.com/rust-lang/crates.io/blob/af26bb3ab2dceb4810f0edce145d43ec484b7028/src/render.rs#L25-L91). To simplify this code, and to allow some additional safe attributes we currently don't allow, we could rely on [Ammonia's defaults](https://github.com/rust-ammonia/ammonia/blob/v2.0.0/src/lib.rs#L257-L329) instead, and [add any additional items we may need](https://docs.rs/ammonia/2.0.0/ammonia/?search=add).

Suggested steps:

* Consider upgrading to the latest Ammonia release.
* Compare the list of currently allowed tags in crates.io to the defaults in Ammonia.
* Update the code to in `MarkdownRenderer::new()` (linked above) to only add these additional tags to the defaults.

**Comment by AZanellato** [comment]
I can try this :smile:
