### ISSUE TITLE
Add badge for Github Actions CI

### ISSUE THREAD

**Issue by Empty2k12** [rust-lang/crates.io#1877]
In https://github.com/rust-lang/crates.io/blob/master/src/tests/badge.rs, there should be an action to set a (/ multiple?) Github Actions CI badge(s).

The format of the badge URL can be found here: https://help.github.com/en/github/automating-your-workflow-with-github-actions/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository

Necessary parameters are `OWNER`, `REPOSITORY`, `WORKFLOW_NAME` or `WORKFLOW_FILE_PATH`. Optional parameters are `branch` and `event`.

This is an example of a Rust Workflow whose badge a user might want to add to crates.io: https://github.com/Empty2k12/rust-github-actions-test/workflows/Rust/badge.svg?branch=master, which looks like ![](https://github.com/Empty2k12/rust-github-actions-test/workflows/Rust/badge.svg?branch=master)

**Comment by carols10cents** [comment]
https://github.com/rust-lang/crates.io/pull/1838 is in progress to implement this.

**Comment by Empty2k12** [comment]
My bad.

Since there is no issue open for #1838 I vouch to keep this open. Reading through #1838, other people have opened issues with the exact same issue since they didn't find an issue.

**Comment by Turbo87** [comment]
we've today decided to go in a different direction which should probably resolve this problem. more details are available in https://github.com/rust-lang/crates.io/issues/2436
