### ISSUE TITLE
TravisCI badge looks broken

### ISSUE THREAD

**Issue by theLastOfCats** [rust-lang/crates.io#1884]
TravisCI badge not download properly.

<img width="874" alt="image" src="https://user-images.githubusercontent.com/3687591/67854555-968fa680-fb21-11e9-8f8a-5bbf4dffe467.png">

**Comment by kzys** [comment]
Where is this page? https://crates.io/crates/actix looks fine for me.

**Comment by theLastOfCats** [comment]
This is how it works for me on Firefox 70.0

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/3687591/67941501-c9e83900-fbe6-11e9-97e1-d32bce237224.png">

Seems like problem on my side

**Comment by carols10cents** [comment]
Yes, I would check for the request to travis being blocked by an extension or adblocker/tracking blocker.
