### ISSUE TITLE
Try out GitHub Actions

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#1903]
This issue is great for someone looking to learn about how GitHub Actions and crates.io's CI work!

[rust-lang/rust is working on moving to GitHub Actions](https://internals.rust-lang.org/t/evaluating-github-actions/11292); I'd love for us to be on a similar CI setup. I meant to try Azure Pipelines here as well when rust-lang/rust moved, but seeing as they're moving again (even though aiui GitHub Actions is Azure under the hood), I don't see a reason for us to try Azure Pipelines if the eventual goal is consistency.

Pietro says GitHub actions should feel faster than Travis, so let's give it a try!

Implementation instructions:

- [Follow the documentation for GitHub Actions](https://help.github.com/en/actions/automating-your-workflow-with-github-actions). I actually don't know too much about it so I can't be much more specific here, but if you have any questions, please ask them here. I can take a look too and we can figure it out together! [These example Rust/Cargo workflows look relevant](https://internals.rust-lang.org/t/evaluating-github-actions/11292/4?u=carols10cents).
- Open a PR with the GitHub Actions configuration and try to get it to have the same result that Travis gets. Ping me if any of the repo's settings need to be changed.

**Comment by weihanglo** [comment]
I'd love to work on this!

**Comment by smarnach** [comment]
@weihanglo Feel free to go ahead! If you have any questions, you can ask here.

**Comment by weihanglo** [comment]
I’ve opened a pull request and got some question to figure out. Please take a look.
https://github.com/rust-lang/crates.io/pull/1942/files
