### ISSUE TITLE
Get rid of `Browserslist: caniuse-lite is outdated. Please run next command npm update` warning

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#1914]
I'm seeing this whenever I run `npm run start:local` and I'm starting to get annoyed :P 

[Here's another project having this problem and lots of people talking about the solutions](https://github.com/postcss/autoprefixer/issues/1184)

## Implementation instructions

I'd love if someone could:

- Verify that you currently see this message when you run `npm run start:local`
- Figure out the minimum number of packages that need to be `npm update`d to make the message go away. That is, I'd like to not have to `npm update` everything-- updating anything in the lists below is fine with me.
- Submit a PR with the updates needed to package.json and package-lock.json

I'm not sure if it's browserslist or caniuse-lite that needs to be updated? Or both? Or a parent? 

```
 $ npm ls browserslist
cargo@0.0.0 /Users/carolnichols/rust/crates.io
├─┬ @ember/jquery@0.6.1
│ └─┬ ember-cli-babel@7.11.0
│   └─┬ @babel/preset-env@7.4.3
│     ├── browserslist@4.5.5
│     └─┬ core-js-compat@3.0.1
│       └── browserslist@4.5.5
├─┬ ember-cli-babel@6.14.1
│ └─┬ babel-preset-env@1.7.0
│   └── browserslist@3.2.8
├─┬ ember-cli-qunit@4.3.2
│ └─┬ ember-cli-babel@6.12.0
│   └─┬ babel-preset-env@1.7.0
│     └── browserslist@3.2.8
├─┬ ember-fetch@6.5.1
│ └─┬ caniuse-api@3.0.0
│   └── browserslist@4.5.5
└─┬ ember-moment@7.5.0
  └─┬ ember-macro-helpers@0.17.0
    └─┬ ember-weakmap@3.1.1
      └── browserslist@2.4.0

$ npm ls caniuse-lite
cargo@0.0.0 /Users/carolnichols/rust/crates.io
├─┬ @ember/jquery@0.6.1
│ └─┬ ember-cli-babel@7.11.0
│   └─┬ @babel/preset-env@7.4.3
│     ├─┬ browserslist@4.5.5
│     │ └── caniuse-lite@1.0.30000962
│     └─┬ core-js-compat@3.0.1
│       └─┬ browserslist@4.5.5
│         └── caniuse-lite@1.0.30000962
├─┬ ember-cli-babel@6.14.1
│ └─┬ babel-preset-env@1.7.0
│   └─┬ browserslist@3.2.8
│     └── caniuse-lite@1.0.30000849
├─┬ ember-cli-qunit@4.3.2
│ └─┬ ember-cli-babel@6.12.0
│   └─┬ babel-preset-env@1.7.0
│     └─┬ browserslist@3.2.8
│       └── caniuse-lite@1.0.30000851
├─┬ ember-fetch@6.5.1
│ └─┬ caniuse-api@3.0.0
│   ├─┬ browserslist@4.5.5
│   │ └── caniuse-lite@1.0.30000963
│   └── caniuse-lite@1.0.30000735
└─┬ ember-moment@7.5.0
  └─┬ ember-macro-helpers@0.17.0
    └─┬ ember-weakmap@3.1.1
      └─┬ browserslist@2.4.0
        └── caniuse-lite@1.0.30000735  deduped

```

As of this writing, the [latest browserslist is 4.7.3](https://www.npmjs.com/package/browserslist) and the [latest caniuse-lite is 1.0.30001011](https://www.npmjs.com/package/caniuse-lite).

**Comment by hbina** [comment]
AFAIK, caniuse-lite will perpetually give out this warning every 6 months or so.

**Comment by carols10cents** [comment]
Cool, a contribution opportunity every 6 months! :)
