### ISSUE TITLE
Add cache-control headers for readme files.

### ISSUE THREAD

**Issue by smarnach** [rust-lang/crates.io#1915]
We added cache-control headers for `.crate` files in #1871. We should also add cache-control headers for readme files. While it is rare, readme files can change when we regenerate them, so we can't mark them as immutable, and should limit the cache time to some lower value, say one week.

**Comment by hbina** [comment]
So I assume https://github.com/rust-lang/crates.io/blob/1ccd73057330af607067a0fec84044f424c87432/src/uploaders.rs#L90 should no longer wraps `extra_headers` in `Option<T>`?

**Comment by rye** [comment]
Do I have it right that #1924 resolved this?

**Comment by smarnach** [comment]
@rye Yes, this is fixed now.
