### ISSUE TITLE
Content security policy disallows data SVG in CSS

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#1938]
The [pretty checkmarks](https://github.com/rust-lang/crates.io/blob/master/app/styles/me.scss#L211) that @DSpeckhals added in https://github.com/rust-lang/crates.io/pull/1913 worked locally but are being blocked in production because of our content security policies:

```
Content Security Policy: The page’s settings blocked the loading of a resource at data:image/svg+xml,%3Csvg width='32' hei… (“img-src”).
```

I know it's tiny, but is there a reason we can't just put this as an SVG in [public/assets](https://github.com/rust-lang/crates.io/tree/master/public/assets) @DSpeckhals ?

**Comment by DSpeckhals** [comment]
I'm sorry. I didn't realize this. Yes, I think I can put it in the assets directory.

**Comment by carols10cents** [comment]
No worries, I didn't realize it either!
