### ISSUE TITLE
The crates.io website should link to its repo

### ISSUE THREAD

**Issue by sp3d** [rust-lang/crates.io#194]
People using crates.io are the people who have the most insight into how to improve it. We should make the transition from being a user of crates.io to an improver of crates.io as easy as possible, and a first step would be linking this repo from crates.io itself.

**Comment by Gankro** [comment]
It's in the top right corner of literally every page.

**Comment by alexcrichton** [comment]
Yeah, @gankro is right, so closing as "this is done"

**Comment by sp3d** [comment]
I completely didn't see that. My bad.
