### ISSUE TITLE
Glitch in the download graph

### ISSUE THREAD

**Issue by azerupi** [rust-lang/crates.io#196]
I just uploaded a new version of my crate and the graph is a little weird. It should be all blue but the line is drawn in red (color of the newly published version) for some reason.

![crates_bug](https://cloud.githubusercontent.com/assets/7647338/10087292/55c8f8f4-6313-11e5-8ebf-cbcc115c1a56.png)

**Comment by alexcrichton** [comment]
Ah this is actually just a facet of the rendering library that we're using, it's showing all components of the graph (even those with a count of 0 on all data points), and that just happens to be highlighted as a bold red line (e.g. we're using a stacked representation so red is on top of blue). Basically though this is currently working as intended, albeit slightly odd!

**Comment by azerupi** [comment]
Ah, ok :) It's a bit confusing though
