### ISSUE TITLE
[feature request] well-known URLs for crate links

### ISSUE THREAD

**Issue by durka** [rust-lang/crates.io#197]
I often type out a crates.io link, e.g. crates.io/crates/libc, with the sole intention of scrolling down and clicking "Documentation". But what if I could type crates.io/crates/libc/docs or crates.io/docs/libc and it would automatically redirect to the crate's doc link? Similarly for the homepage and repository links. A 404 is fine if the crate hasn't provided a link.

Does this sound like a useful feature?

[moved from rust-lang/cargo#2024]

**Comment by alexcrichton** [comment]
Sounds like a good idea to me!

**Comment by Turbo87** [comment]
@durka I guess this can be closed now that #207 is merged, right?

**Comment by durka** [comment]
Yes. Though now that it's simple I might open a new PR to add "/home" and "/repo" :)
How often is the live site rebuilt?

**Comment by Turbo87** [comment]
no idea, asked @alexcrichton the same thing in #208 just now

**Comment by durka** [comment]
Ping?

**Comment by alexcrichton** [comment]
Oh sorry, the site is deployed manually and I haven't done so yet (hit a few bugs and such), I hope to get it updated this week, however!
