### ISSUE TITLE
`cargo run` passes arguments incorrectly

### ISSUE THREAD

**Issue by dhardy** [rust-lang/crates.io#198]
Code in `src/main.rs`:

    fn main() {
        println!("Arguments:");
        for arg in std::env::args() {
            println!("\t'{}'", arg);
        }
    }

Cargo's `run` command passing arguments:

    $ cargo run -- one two "three and four"
     Running `target/debug/argtest one two three and four`
    Arguments:
            'target/debug/argtest'
            'one'
            'two'
            'three'
            'and'
            'four'

Notice that it splits "three and four". This is what it *should* do:

    $ target/debug/argtest one two "three and four"
    Arguments:
            'target/debug/argtest'
            'one'
            'two'
            'three and four'

**Comment by steveklabnik** [comment]
This bug is on the wrong repo, can you re-file over at https://github.com/rust-lang/cargo/issues/new please! Thanks.
