### ISSUE TITLE
RFC: /repo/:crate_name redirects to repository URL

### ISSUE THREAD

**Issue by iliana** [rust-lang/crates.io#1993]
I'm finding that a very common reason I have for visiting /crates/:crate_name or docs.rs/:crate_name is to click on the link to the code repository for that crate.

I think it'd be neat if, e.g., https://crates.io/repo/chrono redirected (302 Found) to https://github.com/chronotope/chrono, and if crates.io maintainers generally like that idea I'll go implement it.

**Comment by carols10cents** [comment]
This [exists already actually](https://github.com/rust-lang/crates.io/blob/1c0ee979c7a26afc084ca48c2db55eba00d4b816/app/routes/crate/repo.js)! It's just that the URL is crates.io/crates/chrono/repo :)

Is that ok or should we add the other form as well (I don't want to break the existing URL)? Clearly this is too secret, do you have any ideas on how to tell people about this?

**Comment by iliana** [comment]
Oh interesting! Admittedly I didn’t read the code first.

The reason I thought of /repo/:name is just to make it easier to type out for me. I don’t know if that’s reason enough :)

**Comment by carols10cents** [comment]
Yeah I don't know either!

I'm going to leave this open to see if anyone else has comments on what the URL format for this feature should be, and how we could better tell people this exists.

**Comment by Turbo87** [comment]
as there seem to have been very little activity on this issue lately I'll close this for now :)
