### ISSUE TITLE
FetchAdapter deprecation warning after recent frontend version bumps

### ISSUE THREAD

**Issue by jtgeibel** [rust-lang/crates.io#1995]
Current master is emitting the following warning one or more times for many of the tests.

```
WARN: DEPRECATION: FetchAdapter is deprecated, it is no longer required for ember-data>=3.9.2 [deprecation id: deprecate-fetch-ember-data-support]
```

It's confusing to me that `ember-data>=3.9.2` is mentioned, when we are still on `ember-data=2.18.2`.  (#1990 has already been opened to upgrade ember-data, but that PR is failing)

This warning appears to have been introduced in #1977.  (See https://travis-ci.com/rust-lang/crates.io/jobs/268668867 for the full log.)

**Comment by jtgeibel** [comment]
cc @Turbo87

**Comment by Turbo87** [comment]
part of the issue was caused by https://github.com/ember-cli/ember-fetch/issues/391. by now we are on ember-data@3.15, but `ember-fetch` is still showing the deprecation because I haven't resolved the deprecation yet. I'll have a look at that tomorrow :)
