### ISSUE TITLE
GitLab pipeline badges broken

### ISSUE THREAD

**Issue by anarchistmae** [rust-lang/crates.io#1997]
GitLabs CI badges are no longer working, I suspect that at some point the URL format changed, for my `doccy` crate the image URL used on crates.io looks like:

```https://gitlab.com/anarchistmae/doccy-rs/badges/release/0.1.x/build.svg```

Which is a 404 page, changing `build.svg` to `pipeline.svg` and it works:

![](https://gitlab.com/anarchistmae/doccy-rs/badges/release/0.1.x/pipeline.svg)

**Comment by carols10cents** [comment]
Thanks for the report! [It indeed looks like GitLab's badges have changed URLs](https://docs.gitlab.com/ee/user/project/pipelines/settings.html#pipeline-status-badge).

This would be a great first issue for someone! Implementation instructions:

- Edit [the gitlab badge HTML](https://github.com/rust-lang/crates.io/blob/1c0ee979c7a26afc084ca48c2db55eba00d4b816/app/templates/components/badge-gitlab.hbs) to change build.svg to pipeline.svg
- Run `npm run start:live` to test against crates.io, visit localhost:4200/crates/doccy and verify that the GitLab status badge loads
