### ISSUE TITLE
Clarify wildcard end date on FAQ

### ISSUE THREAD

**Issue by rgardner** [rust-lang/crates.io#200]
Just looked through the FAQ and noticed that there was no mention of the current deprecation and impending prevention of publishing crates with wildcard dependencies.

I like the warning @sfackler added to cargo:

> Starting December 11th, 2015, crates.io will begin rejecting packages with wildcard dependency
> constraints.

I think this should be bolded and put at the top of [the wildcard FAQ entry.](http://doc.crates.io/faq.html#can-libraries-use--as-a-version-for-their-dependencies)

I'm happy to submit a PR for this.

**Comment by sfackler** [comment]
Yep, that makes a ton of sense - go for it!
