### ISSUE TITLE
Content-type must be set to json in order to view API results; prevents viewing in browser

### ISSUE THREAD

**Issue by MrJohz** [rust-lang/crates.io#201]
Accessing https://crates.io/api/v1/crates/treexml in my browser produces an "Oops, that route doesn't exist" HTML error page, making it difficult to play with the API.

Browser: Google Chrome Version 45.0.2454.101
User Agent: Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

Also tested using a custom user-agent of "MrJohz/Test"
Also tested using [Advanced Rest Client](https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo) - this produced `{"errors":[{"detail":"Not Found"}]}`.

Am I doing something really wrong?  The same URL works when I put it through `curl`.

**Comment by alexcrichton** [comment]
Ah yeah this is an unfortunate bug today, if the Content-Type is set to HTML a different path is taken, regardless of the HTTP path being requested, but if the Content-Type is json you'll get a json response

**Comment by carols10cents** [comment]
Fixed in #913!!!
