### ISSUE TITLE
SSL error: common name invalid. Cannot access crates.io from Chrome/OSX 10.10

### ISSUE THREAD

**Issue by xrl** [rust-lang/crates.io#202]
I am unable to access crates.io from my laptop's web browser. I can still use crates for all `Cargo.toml` work. Could there be something wrong with my SSL cert chain?

![image](https://cloud.githubusercontent.com/assets/693059/10561780/73622fc4-74ee-11e5-87eb-36c39f50e785.png)

**Comment by xrl** [comment]
Also, I tried publishing a crate and it failed with this:

```
$ cargo publish
    Updating registry `https://github.com/rust-lang/crates.io-index`
warning: manifest has no description, license, license-file, documentation, homepage or repository. See http://doc.crates.io/manifest.html#package-metadata for more info.
   Packaging rtps v0.1.0 (file:///Users/xavierlange/code/dds/rtps)
   Verifying rtps v0.1.0 (file:///Users/xavierlange/code/dds/rtps)
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling byteorder v0.3.13
   Compiling bitflags v0.3.2
   Compiling rtps v0.1.0 (file:///Users/xavierlange/code/dds/rtps/target/package/rtps-0.1.0)
   Uploading rtps v0.1.0 (file:///Users/xavierlange/code/dds/rtps)
http error: Peer certificate cannot be authenticated with given CA certificates
```

**Comment by alexcrichton** [comment]
Hm yeah perhaps there's something wrong with some CA store somewhere? If browsers fail to connect to crates.io then Cargo is likely to fail for the same reason (they use the same certificate store).

**Comment by xrl** [comment]
OK, I just figure it out. I had a hard-coded host entry which was set to an IP that is not longer valid. Had to use `openssl s_client -connect crates.io:443` to see it was resolving to some other site with SSL. Weird issue and I don't recall why I had it set up that way... Things work now, however!
