### ISSUE TITLE
Add user expectations to the crates.io guide

### ISSUE THREAD

**Issue by mdinger** [rust-lang/crates.io#203]
People who look at the crate should expect a few things consistently across crates and these should be documented:

* Auto-built documentation. This is commonly done via [travis-cargo](https://github.com/huonw/travis-cargo) and github pages
* Documentation should be linked from the readme
* Auto-built and tested via https://travis-ci.org or http://homu.io/ though homu is more strict
* http://shields.io/ for build status (if using travis) and version numbers. All others are optional I guess.
* A license should be chosen
  - maximal conformance with Rust is achieved via dual licensing with MIT & Apache

---

These mostly pertain to the github readme and come up frequently when new crates are released. Maybe this will get easier if/when rust starts self-hosting the documentation for all crates but in the meantime, this seems like a good idea.

I'd probably put it at the beginning of the 'Using crates.io' page so people see it before uploading a crate.

Maybe this list should be longer but nothing else really jumps out at me.

**Comment by steveklabnik** [comment]
This information is actually in the cargo repo, would you mind moving the issue over there?

**Comment by mdinger** [comment]
Done
