### ISSUE TITLE
GitHub Actions displays frontend lints to every PR

### ISSUE THREAD

**Issue by jtgeibel** [rust-lang/crates.io#2042]
Since GitHub Actions was enabled in #1942, the 8 lints detected by `npm run lint:js` are detected by GitHub and shown on every PR.

For example, PR 2031 touches unrelated files and has a beta "Unchanged files with check annotations" at the [bottom of the file change list](https://github.com/rust-lang/crates.io/pull/2031/files).

Alternatively, PR 2039 touches a file with a warning and [several notifications appear inline with the diff](https://github.com/rust-lang/crates.io/pull/2039/files).

I don't know how difficult it is to address those lints, so for now I'm suggesting that we temporarily remove this check from our configuration for GH Actions.

cc @Turbo87

**Comment by Turbo87** [comment]
@jtgeibel we can ignore the checks for those specific offending lines using a particular ESLint comment. I'll open a PR to get this fixed. Thanks for bringing it to my attention 👍
