### ISSUE TITLE
using algolia for the search ?

### ISSUE THREAD

**Issue by mackwic** [rust-lang/crates.io#205]
Hi crates.io !

I think crates.io is elligible for the free plan of [algolia](https://www.algolia.com/). Using their search engine would give a far better search experience for crates.

Things we can gain:
- fuzzy search and other tricky substitutions
- nice ranking
- real-time response
- maybe searching in the name + the description (not sure if the actual search do that)

I think it's primordial for crates.io to have a great search experience as it encourages the discoverabilty of the crates. As an illustration, doing `cargo search net` today will not show the library `pnet`. Using algolia would make the result more relevant.

What do you think ?

**Comment by alexcrichton** [comment]
Sounds plausible to me! Right now we're just using basic postgres text search, but that's just because it was the easiest thing to setup initially. One thing I'd be curious about with algolia is if it's easy to run in development? Not really a blocker either way, just curious!

**Comment by mackwic** [comment]
I guess so ? It's a SaaS search engine, so you would just query with your testing dataset. I have to admit I never integrated Algolia so I don't really now... I think it's a common use-case.

I think @Jerskouille can help us on the matter. :)

**Comment by Jerskouille** [comment]
Hi @alexcrichton !

We'd love to build a demo for you and create a pull request, but if you want to play with the API yourselves, feel free to create an account and to drop us a line for us to set you up as a community plan. :)

We've been working a lot on documentation search lately, and here are a few examples if you want to see it live: 

- https://react.parts/native
- https://fortawesome.github.io/Font-Awesome/icons/
- http://laravel.com/docs/5.1

We've also been working on some demos/tools for ourselves that you can check out here:

- https://rubygems.algolia.com/
- https://nodejs.algolia.com/
- https://bootstrap.algolia.com/

I think @mackwic already sold the product here, I just have a small correction to make, the engine doesn't support fuzzy matching, but you can definitely define some aliases.
We unfortunately don't have an `algoliasearch` crate yet, but we'll make sure to fix this issue in a near future, so you might want to stick with the current implementation in `cargo` right now (If you wanna try anyway, you can check our `curl` documentation [here](https://www.algolia.com/doc/curl)).

**Comment by alexcrichton** [comment]
Thanks for the info! Definitely seems like some good info to start from.

**Comment by Turbo87** [comment]
There are only ~3000 crates (aka. objects) on crates.io right now, but I suspect that this number will grow quite a bit as time passes. From what I'm reading on https://www.algolia.com/pricing their free plan would limit us to a maximum of 10000 index objects. If we implemented search using their service we would limit ourselves to 10000 crates which doesn't seem like a good idea. Am I missing some kind of "free for open source" thing?

**Comment by Jerskouille** [comment]
@Turbo87 You're right about the specificity of open source projects with Algolia. We handle these on a case by case basis, but as you can see on the [issue](https://github.com/madebyform/react-parts/issues/11) on the React.parts project, we'll grant the crates.io account an unlimited amount of operations and more than enough records to handle this growth.

**Comment by Turbo87** [comment]
@Jerskouille I see, thanks for clearing that up! :+1:

**Comment by carols10cents** [comment]
I don't think we're going to do this.
