### ISSUE TITLE
Owner invite doesn't work when username is specified with different casing

### ISSUE THREAD

**Issue by YaLTeR** [rust-lang/crates.io#2081]
I'm trying to invite https://crates.io/users/matherunner to my crate https://crates.io/crates/hltas. I tried adding `Matherunner`, `matherunner` as well as his email address, multiple times, always getting "An invite has been sent to matherunner". However, he never got any emails and his owner invites are empty.

## Implementation instructions

- [Start from this branch](https://github.com/rust-lang/crates.io/tree/failing-test-2081) that has a test that fails because the username of the invited owner is specified in a different case than it is in the database.
- Get the test to pass by changing [this `filter`](https://github.com/rust-lang/crates.io/blob/7020cb2218b0458f97a03757edd167be4d8097cf/src/models/owner.rs#L74) to be case insensitive using the `crate::lower` function like [this code does](https://github.com/rust-lang/crates.io/blob/7020cb2218b0458f97a03757edd167be4d8097cf/src/controllers/user/other.rs#L11-L14) (I'm not sure why that code chooses to lowercase the provided name in Rust and then use the SQL `crate::lower` function on the `gh_login`... I think both should be done with SQL in this case?) We have [an index on `lower(gh_login)`](https://github.com/rust-lang/crates.io/blob/7020cb2218b0458f97a03757edd167be4d8097cf/migrations/2017-10-09-135625_add_lower_gh_login_index/up.sql#L2) so this query will be fast.

**Comment by carols10cents** [comment]
I'm sorry this isn't working! I indeed don't see any invitations created by you for the hltas crate. 

I tried inviting someone to one of my crates in the web UI, so invitations works in general.

I tried inviting `matherunner` and that didn't create an invitation, but inviting `Matherunner` did-- so I think we have a bug where we're not comparing the names case-insensitively.

I'm not sure why `Matherunner` didn't work for you-- is there any chance there was whitespace around the name? (We should be removing that if that's the case)

Can you try inviting them from the commandline, with `cargo owner -a Matherunner hltas`

We also have a bug that we're not reporting when and why invitations fail 😰 I looked in the logs for your requests and they all had status 200.

**Comment by YaLTeR** [comment]
> I tried inviting matherunner and that didn't create an invitation, but inviting Matherunner did-- so I think we have a bug where we're not comparing the names case-insensitively.
>
> I'm not sure why Matherunner didn't work for you-- is there any chance there was whitespace around the name? (We should be removing that if that's the case)

Ah, it might be the case that I tried inviting with the capital first letter only before he has logged into crates.io for the first time, and only with the lowercase first letter afterwards. I tried inviting with the capital first letter again now.

**Comment by YaLTeR** [comment]
Looks like that worked!

**Comment by carols10cents** [comment]
Great! I'm going to make this issue about the case problem and create some more for the other problems. Sorry this was such trouble, and thank you for reporting this so we can fix it!
