### ISSUE TITLE
Split frontend from backend

### ISSUE THREAD

**Issue by Turbo87** [rust-lang/crates.io#209]
Would it make sense to split the frontend from the backend code? Right now they are mashed together and luckily Ember does not expect the source code to be in the `src` folder too, but there is no clean separation.

We could either move both into separate repositories or at least use separate folders with a common README file. Since the API isn't particularly stable yet the second solution might be better although I would prefer the first one in the long term.

**Comment by alexcrichton** [comment]
I personally kinda like having all the code in one repo for now (none of it's that big), but being a little more explicitly about what's in what directory would be fine by me (e.g. reorganizing the internal structure)

**Comment by Turbo87** [comment]
Okay, good to know. I'll take a look into this after #208 is merged.

**Comment by carols10cents** [comment]
I think the organization is okay, and this bug has been around for a while, so I'm going to close this. ❤️
