### ISSUE TITLE
Inconsistent search results between initial search and later search

### ISSUE THREAD

**Issue by hobofan** [rust-lang/crates.io#2106]
I came across some strange behavior today, where a crate with the exact name match didn't appear in a search result. Reloading the page however did make the result appear.

Steps to reproduce:

- Go to `https://crates.io/`
- Search for `cargo_metadata` -> Match does not appear
- Reload the page -> Match does appear

Looking into the requests made, there appears to a slight difference in requests made between the search request done during site load, and any subsequent searches.

Initial search request: `https://crates.io/api/v1/crates?page=1&per_page=10&q=cargo_metadata`
Subsequent requests: `https://crates.io/api/v1/crates?all_keywords=&page=1&per_page=10&q=cargo_metadata`

**Comment by carols10cents** [comment]
Hi! We recently deployed functionality enabling the `all_keywords` parameter, so it looks like we messed something up, oops! I'm in the process of looking into it.

I'm able to reproduce the behavior you're describing, except that on the *initial* search request is where I'm seeing the `all_keywords` parameter, and on subsequent requests reloading the search results page I'm *not* seeing the parameter. Can you check again to see if that's what you're seeing too, or if there are multiple problems or nondeterminism or something going on? 😅

**Comment by hobofan** [comment]
TBH, I might have just mixed up the two tabs I copy/pasted it from 🤷‍♂.

Thanks for the quick fix! :)
