### ISSUE TITLE
Download button

### ISSUE THREAD

**Issue by hvenev** [rust-lang/crates.io#2113]
I think it would be nice to have an easy way to download source tarballs from crates.io that are equivalent to what cargo uses.

**Comment by jtgeibel** [comment]
I think crates like `cargo-clean` and `cargo-download` are good, portable alternatives.  We originally had a download button, but it was removed a *long* time ago (late 2014).  While some platforms bundle support for gzipped tar files and auto-detect our file type, unfortunately some common platforms do not.

Also see #15 and #1219 for previous discussions.

**Comment by hvenev** [comment]
Right... there is no way to download cargo-clean or cargo-download without either cargo-clean or cargo-download.

What I'm trying to say is, downloading from crates.io should not require using cargo.

**Comment by jtgeibel** [comment]
You can install via `cargo install cargo-clone` (sorry, I had a typo in the previous comment). It's also possible to hit the API endpoint directly to download a crate, but it's not possible to provide a smooth, cross-platform experience without some client side code.
