### ISSUE TITLE
forum, discussions, group

### ISSUE THREAD

**Issue by LucianoBestia** [rust-lang/crates.io#2132]
I miss on crates.io to see "discussions" from users of the crate. 
There is only the readme of the author. And we know that it is always all fantastic, no problem, just works.
It would be helpful to see other users use-cases and problems and how to solve it. 
I don't mean to have the forum inside the crates io. This is too much data. But have an official link to somewhere else. Maybe Google Groups or other sites for group discussion about exactly and only this crate.
Just like we can select a repository and readme.md in the cargo.toml, there could be a link for Discussions. And then on crates io this link will be near to the Documentation link.

**Comment by xoac** [comment]
What is wrong with repository link? In most cases it's stored on github or gitlab (or similar one) where you can check issues. I think adding "additional issues forum" will unnecessary split "one place to check in two".

**Comment by LucianoBestia** [comment]
I think a discussion is not an issue. For example a discussion what other crates have similar functionality and what is the main difference. All rust developers have an account on user.rust-lang.org. it looks a good place for discussions about crates in crates.io. We just need a new category for that.

**Comment by xoac** [comment]
Disadvantage of official link would force authors to watch another place.
Many crates provide discussion on chats. For example tokio use discord. But other authors would like to use different solution. So I could agree with you only if that discussion link would be optional and author could choose backed solution (so not official link).
I think very small crates don't need discussion at all. 

If you are looking for similar crate to other you could ask on reddit or user.rust-lang.org adding official discussion don't solve problem that people would be asking in other places.

**Comment by LucianoBestia** [comment]
I see that GitHub is now experimenting with an option called "Discussions".
That would solve my issue perfectly.
