### ISSUE TITLE
What is the limit to use //crates.io/api/v1 ?

### ISSUE THREAD

**Issue by LucianoBestia** [rust-lang/crates.io#2133]
I cannot find anywhere what are the limits of using //crates.io/api/v1.
I read in discussions there are 5000 requests per hour ?
Is it limited by IP ? Or is there a secret token in use?
Is there a limit per MB ?
For example if I write a utility to get metadata of one crate.
For example:  https://crates.io/api/v1/crates/web-sys
Is this limit per user of my utility (ip) ?
Or is it per my utility for all the users in the world (secret token)?

**Comment by carols10cents** [comment]
Here are our crawler policies: https://crates.io/policies#crawlers
