### ISSUE TITLE
Linking directly to a new version from the front page shows no downloads

### ISSUE THREAD

**Issue by jtgeibel** [rust-lang/crates.io#2143]
Under #1931 we made the decision to link directly from the front page to a version if we were showing that version number in parenthesis next to the crate name.  This seemed like a reasonable change to make at the time, but in retrospect it can cause confusion.  (In fact I confused myself because I just deployed a change, and wasn't sure why I wasn't seeing any downloads when clicking on crates from the front page.)

When clicking on a link under "Just Updated", you are taken directly to the newest version of that crate.  Because that version was just published, it will not have any downloads.  Even if the crate has old versions which are frequently downloaded, the version specific page shows only the downloads for that version.  This is unfortunate, because the "Just Updated" links are prominent on the front page and clicking on them gives the immediate impression that a crate has no history of downloads.

This issue is confounded by the fact that there is no easy way to navigate from a specific version of a crate, to the overview page for the crate.  These pages look almost identical, with the only differences I can see being the exact contents of the readme, and the download graph.

## Proposed solution

We should update the front page components to point to the crate overview pages like we did previously.  Optionally, we should provide an easy and prominent way to navigate from a version page back to the crate overview page.  We could also make it clearer on the version page that the graph is showing download for that version only.

This would be a great first PR if anyone is interested.

**Comment by Zexbe** [comment]
Ok, I'm going to try

**Comment by Zexbe** [comment]
I am done. The contribution steps didn't work for me.
I had to do figure out some extra steps to make npm work:
`npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe`
`npm install -g ember-cli`

**Comment by Turbo87** [comment]
Resolved by #2155
