### ISSUE TITLE
README: Add support for basic HTML styling

### ISSUE THREAD

**Issue by 19h** [rust-lang/crates.io#2151]
Hey,

it would make me incredibly happy if crates.io would have basic html-styling support similar to Github.

The project that currently made me realize that the repo has some centered text which would probably look good on crates.io, too.

repo: https://github.com/19h/ftab-dump
crate: https://crates.io/crates/ftab-dump

If this is entirely only due to lack of prior-investment (aka PRs welcome) I would be more than happy to work on this. Otherwise, what's the project's stance on this?

Thanks!

**Comment by Turbo87** [comment]
sorry for the radio silence here. 

I tend to agree that supporting a few basic html constructs does not seem like a problem. we'd have to figure out how to teach that to the markdown renderer though. on the frontend we just render the html directly, so the work would have to be done on the backend side.
