### ISSUE TITLE
API for total crate downloads

### ISSUE THREAD

**Issue by nvzqz** [rust-lang/crates.io#2169]
I notice that `/api/v1/crates/*/downloads` returns the most recent downloads but not the total number of downloads as presented on the crate's page. However, you can get the total downloads for a user from `/api/v1/users/*/stats`.

**Comment by jtgeibel** [comment]
The `/api/v1/crates/{name}` endpoint includes fields for both `downloads` and `recent_downloads`.  Versions (`/api/v1/crates/{name}/{version}`) also contain a field for `downloads`.  So the total count of crate/version `downloads` you're looking for should be available from those endpoints.
