### ISSUE TITLE
crate_owners.created_by in the data dump

### ISSUE THREAD

**Issue by kornelski** [rust-lang/crates.io#2183]
It would be useful to have `created_by` id in the `crate_owners.csv` in the data dump. Who invited who is useful for analyzing trust relationship between crate owners.

**Comment by sgrif** [comment]
My initial reaction to this idea was that this seemed somewhat like PII (though in hindsight I can't really say why I felt that way). But the most common case here is that crates have a single owner who can manage invitations, so this is generally already inferable. I don't see much reason to exclude this information

**Comment by jtgeibel** [comment]
My initial reaction was a similar aversion to publishing this information, but I also don't really see a strong reason not to.  I've added it to the agenda for this week to discuss with the team.
