### ISSUE TITLE
Allow change ownner

### ISSUE THREAD

**Issue by xoac** [rust-lang/crates.io#2188]
Hi guys. As we all know, we don't live forever or sometimes we just drop (or move ;)) our life and begin a new one. It would be great to have **change owner policy**:

I suggest:
1. only approved - the current crate.io policy (we don't change ownership without the current owner's agreement)
2. after inactivity of `<duration>` - the crate.io team can transfer crate name to somebody if the owner didn't have any activity for `<duration>`. Of course the policy would be first to try to contact the author of the crate and change ownership only if the author doesn't respond.

The decision could be made as box in settings. 

![on-ate-for-schoo-night-dudes-see-you-again-tomorrow-41850312](https://user-images.githubusercontent.com/1863020/74481675-74911880-4eb3-11ea-9ed0-9079a6d6b1e4.png)

**Comment by jtgeibel** [comment]
This has been discussed many times already and the consensus is that any change in policy here will need to go through the RFC process.

**Comment by xoac** [comment]
I found just one issue and it was about deleting or changing owner without their permission (#1742).  This one is more about giving a choice and is backward compatible. 

#1742 The [pre-RFC](https://internals.rust-lang.org/t/pre-erfc-crate-name-transfer/9027) is also about rules where you can be dispossessed of your crate.
 - - - -
Ok - I found where the discuss should be continue: https://github.com/rust-lang/rfcs/pull/2614
