### ISSUE TITLE
OpenSearch not working on Chrome

### ISSUE THREAD

**Issue by carlosgaldino** [rust-lang/crates.io#219]
Hi,

I noticed that the OpenSearch doesn't work on Chrome. I've visited the website and performed several searches there but it was never added as a search engine on the browser like every other website with OpenSearch gets added.

I cloned the repo to try to reproduce locally but for my surprise `localhost` is now able to search on `crates.io` so I have no idea about what can be wrong on production. That's why I'm opening this issue here. Do you have any ideas about what could be wrong?

Thanks.

P.S.: For Safari and Firefox on my machine it works just fine.

Chrome: Version 46.0.2490.80 (64-bit) for Mac OS X 10.10.3

**Comment by alexcrichton** [comment]
Ah no unfortunately I don't know much about this (I think it was largely copied from elsewhere), but sounds fishy!

**Comment by Turbo87** [comment]
works fine for me on Chrome 46.0.2490.86 / OS X 10.11.1

**Comment by carlosgaldino** [comment]
Hm, so there might be some issue with my computer then. I already added it manually anyway. Thank you all!
