### ISSUE TITLE
Add a periodic background job to check the consistency of the index

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/crates.io#2227]
Currently we have no way to get paged if we lose consistency between the crates.io database and the git index. Having such alerts would improve the team's response time to outages like [2020-02-20](https://paper.dropbox.com/doc/crates.io-incident-report-2020-02-20--AvFTBBeQGlY3itjQagpXctvLAg-PSMOfVpJTZfQFKKvgEGu9).

The job should run periodically, with an high enough frequency to produce actionable alerts but a low enough frequency to avoid disruptions to other jobs in the queue. Also, it should ignore crates in the database still waiting for the background job pushing the index commit to execute (we already have separate alerts if those jobs stay in the queue too much).

**Comment by Turbo87** [comment]
At this point we are generating the index files completely from the database content, so unless an index sync job repeatedly fails (which would trigger the on-call team) the index should not get out of sync anymore.
