### ISSUE TITLE
Add in-depth logging for background jobs

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/crates.io#2229]
We should add more logging in the job executor (swirl), to record this information:

* A job starts executing, with the name and all the parameters of such job.
* A job finishes executing, with its output and execution time.

**Comment by jtgeibel** [comment]
I think this is addressed by #2231 (for git index operations) and #2066 (for update_downloads and database_dump jobs).  The logging is done by the individual jobs and not directly by the executor, but I believe the current level of logging is now sufficient for these background jobs.
