### ISSUE TITLE
crates.io Design

### ISSUE THREAD

**Issue by Turbo87** [rust-lang/crates.io#223]
#115 and #164 have already started redesigning the overall look of crates.io, but haven't been merged in the end. I think we can agree that the current design has some room for improvement and with the Rust community growing each day a good looking package index certainly helps with the motivation.

The Python community lately started working on their package index replacement at https://warehouse.python.org/ and I think the design so far looks quite good. I took the liberty of [reaching out](https://github.com/pypa/warehouse/pull/751#issuecomment-158450891) to the responsible designer asking whether we could potentially reuse the design or parts of it and got a very positive [reply](https://github.com/pypa/warehouse/pull/751#issuecomment-158465358).

Is this something that should be worked on or will it be turned down in the end like the other two PRs above?

/cc @alexcrichton @steveklabnik

**Comment by brson** [comment]
Some of the work in the linked issues is very nice.

I hope we can come up with a strategy to make progress here.

**Comment by steveklabnik** [comment]
I also think the design looks really great as well. 

> Is this something that should be worked on or will it be turned down in the end like the other two PRs above?

I wouldn't start working on it yet. We need to figure out exactly how we want to go forward with design stuff in general before we can say what that should be...

**Comment by Turbo87** [comment]
Thanks for the fast responses!

@steveklabnik let me know if I can help in figuring that out. Looks like some people are actually motivated to work on this *now* :wink:

**Comment by petevine** [comment]
Any chance of seeing some platform statistics grouped by target triple? (even a tool-tip over the total number of downloads would be great)

Thx

**Comment by softprops** [comment]
Please keep the current color branding. It's very unquie among pkg manager sites. Navigation and ux can def be improved. The color scheme is great though. Plz keep it

**Comment by Turbo87** [comment]
@brson @steveklabnik any news on this?

**Comment by steveklabnik** [comment]
@Turbo87 yes! @brson is going to try to move some of this forward. He's doing a ton of other work because of the release this week, but expect to hear something soonish.

**Comment by Turbo87** [comment]
@steveklabnik thanks for the feedback, that's good to hear! please let us know if you need help in any way.

**Comment by brson** [comment]
Soonish. Real soonish :(

**Comment by Anachron** [comment]
Hey guys, I could also help. I suggest using a dynamic/trimable framework like Semantic UI.

**Comment by vis-kid** [comment]
@brson @Turbo87 
Hi guys! I’d love to be involved as well and take on some responsibility if possible. In the little free time I had last year, I played with a few designs (actually tons) for crates.io and am able to implement code as well. 

Wanted to spend some considerable time on this project this year. #115 shows a couple of rough logo ideas I had a while back. Would like to continue working on them also. Hope the train didn’t leave without me :pray:

I want this site to look awesome!

**Comment by Turbo87** [comment]
@brson any news on this? it's been quite some time...

**Comment by Anachron** [comment]
@Turbo87 well there is docs.rs now: https://docs.rs/

**Comment by brson** [comment]
@Turbo87 :disappointed: My understanding is that @aturon and @wycats have taken responsibility for making progress on this.

**Comment by Turbo87** [comment]
@aturon @wycats any comments? I'm tempted to close this issue due to inactivity...

**Comment by alexcrichton** [comment]
cc @carols10cents 

@Turbo87 sorry not much more from myself :(

**Comment by locks** [comment]
Thank you everyone for the discussion! I am closing this issue as there will be a new redesign attempt after the success of rust-lang.org. See you soon~
