### ISSUE TITLE
Report: not rendering in MS-Edge

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#2233]
We got this report via email, and I haven't had time to investigate.

The site appears to not be rendering, except for the green background, in MS-Edge.

We should maybe add edge to percy if that's possible, or use browserstack.

<img width="1560" alt="2020-02-18" src="https://user-images.githubusercontent.com/193874/75563449-5fba9600-5a18-11ea-88d9-7f962e897634.png">

**Comment by montao** [comment]
Thank you for the acknowledgement. There is an error message from MS-Edge when trying to browse crates.io:

`SCRIPT1028: SCRIPT1028: Expected identifier, string or number
cargo-ed26a61fb284aff4a14e1cc1aed8703c.js (319,616)`

Researching this error message it seems that the `...` syntax is not supported in Edge (My details are Microsoft Edge 44.17763.831.0). If you don't have a native environment which supports running MS-Edge then there are VMs with Edge available from Microsoft https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ You can ping me for more information or a test.

**Comment by locks** [comment]
Hm, we are currently supporting last 1 version of Edge https://github.com/rust-lang/crates.io/blob/master/config/targets.js#L9. We need to check why the compilation isn't accounting for this.

**Comment by montao** [comment]
@locks I volunteer to troubleshoot it and if I can fix it. I am on the Win10/Edge platform and could try changing the script directly according to what is reported to work in similar cases. If the script is generated/compiled then the change must be done from where it is generated though.

**Comment by carols10cents** [comment]
@montao Wait, you said you're on Microsoft Edge 44.17763.831.0? The latest Edge version according to Browserstack is 80, and crates.io rendered for me using that version in Browserstack.

Could you try updating your Edge to the latest and reopen if crates.io still isn't rendering? We don't have the developers to support older versions of browsers. Thanks!
