### ISSUE TITLE
I wanna use this name

### ISSUE THREAD

**Issue by deeprobin** [rust-lang/crates.io#2245]
This crate is empty & I want to use this name for a crate with content: https://crates.io/crates/vector/

Is this possible?

Kind regards
Robin Lindner

**Comment by carols10cents** [comment]
We do not transfer crates without the consent of the current owner. Thanks!

**Comment by deeprobin** [comment]
@carols10cents I don't know how to contact the owner & it is an empty repository.

And I don't like creating an empty crate just to reserve the name

**Comment by smarnach** [comment]
We have been unable to contact the crate owner as well, so within the limits of our current policy, there is nothing else we can do.
