### ISSUE TITLE
Consider adding a page to show the publish/yank/unyank queue

### ISSUE THREAD

**Issue by jtgeibel** [rust-lang/crates.io#2248]
We don't currently provide any way (beyond production access) to see if there is a backlog of index operations queued in the background worker.  It would be nice if we had a page that would show the status of any pending index operations.

This could be an admin-only panel, but I don't think that is necessary.  As long as we only show jobs related to the index, then we aren't disclosing any additional ops information that couldn't already be reverse-engineered by hitting our API and observing the index.

This would be mostly useful during an indecent response, but users may also find it useful.  In particular, it would help communicate that there is always a slight delay (and during a GitHub outage a potentially long delay) between publishing and availability.

**Comment by Turbo87** [comment]
we now at least show the number of queued up background tasks in Grafana, so I'll close this for now until someone wants to pick this up again
