### ISSUE TITLE
Crate license is incorrectly shown for previous versions

### ISSUE THREAD

**Issue by limeburst** [rust-lang/crates.io#227]
How to reproduce this issue:

1. Release a version of a crate with any license.
2. Release a new version with a new license.
3. Clicking on the old version does not update the page to show the old license.

**Comment by Turbo87** [comment]
I don't think that "ui" is the right label. https://github.com/rust-lang/crates.io/blob/master/src/krate.rs#L52 shows that the backend is providing the license information only per crate, not per version. Once the information is available on the backend it should be an easy change on the frontend

**Comment by alexcrichton** [comment]
Oh, right! I forgot about that as an implementation detail. Yeah currently we don't track license-per-version but rather license-per-crate, so that'd explain the behavior here!

**Comment by est31** [comment]
Why was this closed? This is an oversight and should be fixed.

**Comment by carols10cents** [comment]
@est31 

> Why was this closed? This is an oversight and should be fixed.

This was closed because it's a bug report, but the system is behaving as designed. Feel free to open a new issue proposing that the way we track licenses be changed to per-version rather than per-crate for discussion.

**Comment by est31** [comment]
@carols10cents opened: #736
