### ISSUE TITLE
Test for broken badges 

### ISSUE THREAD

**Issue by locks** [rust-lang/crates.io#2315]
While working on a feature (https://github.com/rust-lang/crates.io/pull/2311) @Turbo87 noticed that a badge was broken and removed it from the fixtures (https://github.com/rust-lang/crates.io/pull/2313).
However, it brought to light that we are not currently testing for broken badges and what is displayed in that case.

**Comment by Turbo87** [comment]
closing due to https://github.com/rust-lang/crates.io/issues/2436
