### ISSUE TITLE
Missing `api/v1/me` request when originally unauthenticated

### ISSUE THREAD

**Issue by jtgeibel** [rust-lang/crates.io#2329]
I'm not sure when this started, but this is observable in production (and staging).

Steps:
1. Sign out.
2. Open the network debug panel.
3. Refresh the page.  (Skipping this step does not reproduce the problem.  My guess is that without the step the app is caching data from before step 1.)
4. Click the "Log in with GitHub" link.
5. Complete the authentication workflow if necessary.
6. Use the menu to navigate to "Account Settings".
7. Observe that there are no crates listed under "Email Notification Preferences".  Observe that no request was sent to the `/api/v1/me` endpoint to obtain this data.
8. Reload the page and an XHR request to `api/v1/me` is sent (in addition to the HTML `/me` page load). 

The bug is the missing information in step 7.  In step 8, reloading the application seems to send a request to `/api/v1/me` early during application boot.

cc @Turbo87 @locks

**Comment by Turbo87** [comment]
thanks for reporting that. I'll have a look :)

**Comment by Turbo87** [comment]
I can confirm this issue, and I have a rough understanding now of why this is happening:

- the `/me` page shows the list of owned crates based on the `ownedCrates` property in the `session` service
- `session.ownedCrates` is populated by the `fetchUser()` method on the `session` service, which gets called when the application starts up and the `isLoggedIn` localstorage key exists
- when we go through the GitHub auth flow we receive the user account information from the `GET /api/private/session/authorize` request, but that does not include the `ownedCrates`, so we only set `session.currentUser`, but not `session.ownedCrates`

I think the easiest way to fix this for now is to do another `/api/v1/me` request on the `/me` route, in case `ownedCrates` is empty, which indicates that the user might have just authenticated. It will lead to a duplicated request for users that actually have no crates, but if we think that this should be optimized we could also track that in a dedicated property on the `session` service.
