### ISSUE TITLE
"Last updated" field does not show the correct value

### ISSUE THREAD

**Issue by azerupi** [rust-lang/crates.io#234]
When browsing crates.io I noticed that every crate showed the same "Last updated" time
![libccargo](https://cloud.githubusercontent.com/assets/7647338/11755604/c5441fb0-a053-11e5-9ef5-e1d92cb00221.png)

I just updated my crate at that moment, so it seems that it is displaying the value for my crate and not the actual crate I visit.

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang/crates.io/commit/aa810c42095f488c54b14b01589333aa274058f2, thanks!
