### ISSUE TITLE
Insufficient spacing between Dev-Dependencies and Versions

### ISSUE THREAD

**Issue by mrmonday** [rust-lang/crates.io#235]
Looking at: https://crates.io/crates/pnet_macros/

Using Firefox 42.0 on Linux:

![2015-12-11-215439_439x229_scrot](https://cloud.githubusercontent.com/assets/165689/11756456/e1dccac0-a051-11e5-8089-53db9fb9af45.png)

You'll notice that the formatting makes it look like the dev-dependency `pnet_macros_support` requires a version `>= 0.10.6.0`, since there is insufficient spacing between the two columns.

**Comment by carols10cents** [comment]
Yup, this still happens and pnet_macros is still a pretty good way to reproduce this. I had to play with the browser width a bit but found a width that produces similar results:

<img width="868" alt="screen shot 2017-02-21 at 4 53 17 pm" src="https://cloud.githubusercontent.com/assets/193874/23186831/7fdf781e-f856-11e6-9677-e4d117ecfabb.png">

This'll involve adding some sort of forced spacing in between those two sections-- I'm not that great at CSS, so I'm not sure if margin or padding will be best, or if there's a way to handle it with flexbox.

Also doing a little cross-browser testing at various widths (firefox, chrome, ie, safari?) would be A++++!

**Comment by carols10cents** [comment]
@shepmaster is willing to answer any questions anyone might have about this!
