### ISSUE TITLE
trailing slash redirect steals back button

### ISSUE THREAD

**Issue by durka** [rust-lang/crates.io#236]
Steps to reproduce:

1. Go to [https://crates.io/crates/libc](https://crates.io/crates/libc) (note the lack of trailing slash).
2. Observe the automatic redirect to [https://crates.io/crates/libc/](https://crates.io/crates/libc/).
3. Try the Back button -- you don't end up back here.

**Comment by ivan** [comment]
:+1: 

Just noticed this when I clicked through to diesel on https://users.rust-lang.org/t/announcing-diesel-a-safe-extensible-orm-and-query-builder-for-rust/3815

**Comment by ryanwilliams** [comment]
This patch fixes it, but I don't know enough about Ember or the project to say if it causes any weird side effects:


    diff --git a/app/routes/crate/index.js b/app/routes/crate/index.js
    index 6987b39..ea370d8 100644
    --- a/app/routes/crate/index.js
    +++ b/app/routes/crate/index.js
    @@ -2,6 +2,6 @@ import Ember from 'ember';

     export default Ember.Route.extend({
         redirect() {
    -        this.transitionTo('crate.version', '');
    +        this.replaceWith('crate.version', '');
         }
     });

**Comment by alexcrichton** [comment]
I think that'd do the trick, feel free to send a PR!

**Comment by Turbo87** [comment]
@alexcrichton I think this issue can be closed now

**Comment by alexcrichton** [comment]
Indeed, thanks @ryanwilliams and @Turbo87!

**Comment by durka** [comment]
I believe this fix caused a new bug.

1. Go to https://crates.io/
2. Search for "foo" and click on the first link ("tenacious").
3. Search for "bar" and click on the first link ("bar").
4. Click the back button. You end up back at the tenacious page, skipping the search results page.

Should I file this separately?

**Comment by durka** [comment]
Hmm, maybe it wasn't caused by the fix for this, since I still see the original bug.

**Comment by Turbo87** [comment]
@durka I suspect that the live site hasn't been updated yet

**Comment by steveklabnik** [comment]
I see https://crates.io/search?q=bar

**Comment by durka** [comment]
@steveklabnik I cleared my cache, tried it on a different computer, still see the bug.

**Comment by alexcrichton** [comment]
@durka I updated the site indeed and can also reproduce, could you file a separate bug?

**Comment by durka** [comment]
Sure.
