### ISSUE TITLE
Feature Request: Custom Badges

### ISSUE THREAD

**Issue by sagiegurari** [rust-lang/crates.io#2377]
I see there are many requests for badges (for example i'm waiting on github actions badge PR).
Anyway, it seems like hard work to code for every badge.
For example new CI and coverage providers popup all of the time.

what if we could add custom badges to the cargo.toml.
than crates.io would display them but would only make them clickable if they are going to a trustworthy domain (we can have a list, like github, microsoft, ...).

Then in the Cargo.toml users can provide many custom badges that would contain:
* badge url
* target click url
* alt text

This would reduce a lot of overhead that is going on today of catching up with all badge requests.

**Comment by Turbo87** [comment]
thanks for the suggestion @sagiegurari, but unfortunately we've today decided to go in a different direction which should hopefully also resolve this problem. more details are available in https://github.com/rust-lang/crates.io/issues/2436
