### ISSUE TITLE
Broken "Menu ▼" dropdown

### ISSUE THREAD

**Issue by panicbit** [rust-lang/crates.io#239]
The "Menu ▼" dropdown in the layout for small devices is broken.
Clicking it only results in an error in the JS console:

![error](https://cloud.githubusercontent.com/assets/628445/11856952/c8e50314-a454-11e5-83f7-84d1e0241b8f.png)

**Comment by alexcrichton** [comment]
cc @Turbo87

**Comment by panicbit** [comment]
741a77f60c4988844f3228f585f9b1e8ae360099 Seems to introduce the problem.

**Comment by panicbit** [comment]
I've tried to implement the `rl-dropdown` for the menu bar, which worked fine except the dropdown isn't closing on submitting a search query.
`rl-dropdown` doesn't seem to provide an easy option in this in use case.
Maybe making the dropdown a custom component in addition to using the `rl-dropdown` mixin is the best approach here but I failed to set that up properly :disappointed:.

**Comment by softprops** [comment]
+1 was just going to post a new issue but saw this instead. I primarily use crates.io as a search engine. Any chance of rethinking the ux of search and making the search something you don't have to click into a menu to find? I'm not a designer but I'd be happy to give it a shot.

**Comment by panicbit** [comment]
I agree, searching for crates is an essential part, so keeping it on the page even for mobile devices would be ok. Doing so would allow us to fix the dropdown menu since the searchbar is the only problematic thing.

**Comment by Turbo87** [comment]
still on vacation with patchy Internet connection, but I'll have a look
once I'm back (unless someone else fixes it before that)

panicbit <notifications@github.com> schrieb am Mi., 6. Jan. 2016 12:34:

**Comment by alexcrichton** [comment]
Fixed in #244
