### ISSUE TITLE
Error on network failure is incomprehensible

### ISSUE THREAD

**Issue by kjgorman** [rust-lang/crates.io#240]
Basically if you load the crates.io page but then there is some network interruption after that point, new ajax requests will begin to fail (fair enough).

When this happens an 'oops something went wrong' page is presented, including a stack trace. I guess for an open source project like this it is probably not an issue to include debug information to public users, but the error message seems like it could be more helpful.

This came up for me when the wifi at JFK started throttling after the 30 free minutes had been used up. Obviously just refreshing the page bounced me to the "buy more wifi" splash, but it seems like it wouldn't be impossible to present a more pleasant error when there's no network connectivity.

This is the error I received at the time:
![screen shot 2015-12-16 at 7 57 54 pm](https://cloud.githubusercontent.com/assets/1994486/11858498/3690466e-a430-11e5-90d8-58c3f7f973ca.png)

You can replicate (with a less insane stack trace) by using chrome network throttling to turn off network access once you've loaded the page.

**Comment by tshepang** [comment]
I saw this today, also due to bad network.

**Comment by jugglerchris** [comment]
You get something very similar going to a non-existant crate, for example https://crates.io/crates/adsfadf , but it does also say "Create adsfadf does not exist" and "e is undefined".  Not sure if that's a separate issue!

**Comment by dtolnay** [comment]
I filed #844 for the non-existent crate issue. I think that one is a recent regression.
