### ISSUE TITLE
Support Sec-CH-UA headers

### ISSUE THREAD

**Issue by est31** [rust-lang/crates.io#2431]
Since #1534, there is now a `User-Agent` header requirement. However, the header [is being deprecated by Chrome](https://www.chromestatus.com/feature/5704553745874944) and maybe in the future, Chrome may not send such a header at all.

Thus, crates.io should require either the `Sec-CH-UA` header OR the `User-Agent` header to be set.

Spec: https://wicg.github.io/ua-client-hints/#sec-ch-ua

**Comment by jtgeibel** [comment]
I haven't seen anything to indicate that any browsers have plans to remove the `User-Agent` header altogether.  The Chrome notice says "we want to partially freeze (but not remove)".

If a browser does announce a plan to drop this header we will certainly have to reconsider the current policy, but I don't think there is anything to indicate we need to change at this time.

**Comment by est31** [comment]
Note that my request is about supporting the new header, not switching to it altogether.

Supporting the new header once Chrome *removes* the old header would be the very last moment and until then Chrome canary users etc. wouldn't be able to access crates.io.

Also note that I haven't said they plan to remove it, only that it might happen in the future. Maybe they'll keep it around forever, but I doubt that because the intent is clear. The freezing is to force people to read the Sec-CH-UA header instead and once enough people read the header, they'll most likely remove the `User-Agent` header. I guess their plan is to first check how many people switch and how many websites break once the change has been rolled out for a few years.

I actually welcome this because user agents have gotten pretty messy and are privacy invading and while the new proposal makes things more complicated, it's also better for privacy.

As for crates.io, I think it should allow new tools to drop the outdated User-Agend header in favour of the newer alternative.

**Comment by jtgeibel** [comment]
I agree we wouldn't wait until the header is removed, but removing the header entirely seems like a huge backwards compatibility hazard for any browser.  Maybe that will eventually happen, but I don't think any such plans have been announced by a vendor yet.

Non-browser clients likely don't have the same backwards compatibility constraints that resulted in the current mess, and for crates.io clients can already provide any non-empty value they wish.  So the existing policy isn't forcing clients to include invasive private information.

**Comment by Turbo87** [comment]
closing this for now as it doesn't seem likely that we will implement this any time soon
