### ISSUE TITLE
Move "Maintenance Status" into the crates.io UI

### ISSUE THREAD

**Issue by Turbo87** [rust-lang/crates.io#2437]
Currently the "Maintenance Status" of a crate/version is hardcoded in the `Cargo.toml` file. If a crate is no longer maintained it is easy for this status to become outdated though, since a new release would be needed to update the status. We are aiming to simplify setting this status for the maintainer, but keeping it as a field on the `crate` resource directly in the API, and exposed in the crates.io dashboard for the maintainers to change.

What follows is the rough list of tasks that need to be done to achieve this goal:

- [ ] add the `maintenance_status` column to the `crates` database table
  - initialize the column from the current value in the `Cargo.toml` of the corresponding crate?
- [ ] expose the `maintenance_status` field in the API
- [ ] support updating the `maintenance_status` field using the API for crate owners
- [ ] show the `maintenance_status` value in the crates details page sidebar
- [ ] add a user interface to the dashboard to update the value for each owned crate

**Comment by kornelski** [comment]
Maybe the status could be stored in the registry? It could be updated similarly to the `yanked` field.

**Comment by kornelski** [comment]
What's the resolution of this? Has this feature been abandoned?

**Comment by Turbo87** [comment]
unfortunately, yes. unless someone steps up and implements it I don't see this moving forward currently.
