### ISSUE TITLE
<div class="_install-action shows code for lib instead of binary

### ISSUE THREAD

**Issue by LucianoBestia** [rust-lang/crates.io#2446]
I published my binary CLI to crates.io:  
https://crates.io/crates/lmake_readme  
On the opening page in div "install-action" it looks like it is a library:  
`lmake_readme = "0.5.1"`  
Instead it should be a binary:  
`cargo install lmake_readme`

**Comment by Turbo87** [comment]
seems like this is already mentioned by #483, right?

**Comment by carols10cents** [comment]
Yes, this is a duplicate of #483. Thanks!
