### ISSUE TITLE
Unindetified byte: unable to process request when using vim-crates plugin

### ISSUE THREAD

**Issue by XVilka** [rust-lang/crates.io#2447]
I have [vim-crates](https://github.com/mhinz/vim-crates) plugin installed and usually use it to determine what crates got an updated version. But recently got this error.
1. Install (`Plug 'mhinz/vim-crates'` then `PlugUpdate`) `vim-crates` plugin
2. Open `Cargo.toml` from [qpdb/mentat](https://github.com/qpdb/mentat) repository
3. Run `:CratesToggle` command in the vim command line. 
It produces the following error (see the screenshot):

![image](https://user-images.githubusercontent.com/203261/80193191-f4252b80-864a-11ea-9770-2c1243454d22.png)

If I ran it in the verbose mode (`:verb CratesToggle`) it shows the following:

![image](https://user-images.githubusercontent.com/203261/80194453-f8eadf00-864c-11ea-8ab4-aa625d9da025.png)

cc @mhinz

**Comment by jtgeibel** [comment]
Thanks for the report @XVilka.  It looks that extension is using a generic user-agent header and is getting caught by some checks we had to put in place to stop a bot that was impacting site performance.

Would you mind opening a report upstream against `mhinz/vim-crates` to provide a more specific user-agent header?  While this plugin isn't a crawler, following our guidelines at https://crates.io/policies#crawlers would help to avoid getting accidentally blocked.

**Comment by Turbo87** [comment]
closing this in favor of https://github.com/mhinz/vim-crates/issues/6 :)
