### ISSUE TITLE
Crates published with invalid semver version

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/crates.io#2463]
I was looking at data in the docs.rs database and noticed this crate: https://crates.io/crates/hxgm30-client, I believe the version it specifies (`0.3.0-alpha.01`) is invalid according to the semver standard. I'm not 100% certain of this though, so have opened https://github.com/semver/semver/issues/563 to clarify.

**Comment by hbina** [comment]
I believe this is _very_ common?

**Comment by Nemo157** [comment]
Not as far as I know, I don't have the data to hand anymore, but I believe this was the only crate I noticed with an invalid version in the docs.rs database (though, there could potentially be identical bugs in both the crates.io semver validator and [`pg-semver`](https://github.com/theory/pg-semver) that result in them accepting the same superset of versions).

**Comment by steveklabnik** [comment]
There have been other crates published due to this kind of bug in semver; IMHO we should fix the bug in semver, but also crates.io doesn't need to remove; cargo knows how to parse some incorrect versions and warn about it.

**Comment by Turbo87** [comment]
this is blocked for now on https://github.com/steveklabnik/semver/issues/206 getting fixed

**Comment by jyn514** [comment]
https://github.com/dtolnay/semver/issues/206 was fixed in semver 1.0.

**Comment by hi-rustin** [comment]
Also, it has been upgraded in https://github.com/rust-lang/crates.io/pull/3653.

**Comment by paolobarbolini** [comment]
Another example of this issue is raft 0.5.0 specifying `~2.0-2.2` as the `protobuf` version

**Comment by Turbo87** [comment]
I guess we can close this issue as the original issue is fixed.

I'm not sure what to do about the `raft` comment above, but I guess we can track that in a dedicated issue, since it's related to a dependency requirement, and not a version number itself.
