### ISSUE TITLE
Widened page has no margins on mobile

### ISSUE THREAD

**Issue by jhpratt** [rust-lang/crates.io#2486]
Could you please add a small inline margin (1-2em or so) on mobile? The newly-widened screen seems to have missed that.

I can submit a PR if desired — it should just be one or two lines of additional CSS, possibly under a media query.

**Comment by Turbo87** [comment]
@jhpratt thanks for reporting. I noticed that too today. I could look into it tomorrow unless you want to give it a go yourself :)
