### ISSUE TITLE
Add guide to maintaining a quality crate.

### ISSUE THREAD

**Issue by AndrewBrinker** [rust-lang/crates.io#249]
There's a lot to handle when taking on the leadership of a package for the Rust ecosystem. It may be worthwhile to write a guide to the creation and maintenance of an active, high-quality crate.

The guide could cover topics like:

- Handling versioning, including proper practice for Semver, and making sure to tag versions in git and push them to GitHub (or whatever you're using for code hosting, if it's not GitHub).
- Having and enforcing a code of conduct.
- Setting up continuous integration.
- Making your project welcoming to newcomers.

Thoughts?

**Comment by alexcrichton** [comment]
Sounds like a plausible idea to me! 

cc @steveklabnik

**Comment by AndrewBrinker** [comment]
If it's alright then, I am going to get started on some draft ideas. Obviously, this will be something to get in touch with crate maintainers about, to solicit input from people with experience. I'll keep you all posted.

**Comment by steveklabnik** [comment]
I'm also interested in being kept in the loop here, for sure.

**Comment by steveklabnik** [comment]
(It's worth knowing that doc.crates.io is actually in the Cargo repo)

**Comment by AndrewBrinker** [comment]
Thanks! I'll go ahead and open an issue over there then.
