### ISSUE TITLE
Fractional download count axis label

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/crates.io#250]
(Low priority, slightly amusing)

Pages like https://crates.io/crates/zero/ have a graph of number of download (per day?) whose vertical scale is adapted to the data. When everything is low enough, it graph can have nonsensical vertical line markers and axis labels for fractional download numbers, e.g. “0.25”, “0.50”, “0.75”, “1.00”.

![screenshot from 2016-01-17 00-06-40](https://cloud.githubusercontent.com/assets/291359/12374987/39418ba2-bcae-11e5-8c01-7ddbe36c75c6.png)

The graphing library probably has a parameter to stick to integers.

**Comment by Turbo87** [comment]
https://developers.google.com/chart/interactive/docs/gallery/areachart

it looks like there is no such parameter. it might be possible to adjust `vAxis.gridlines.count` according to the precomputed data, but I don't think it's worth it.

**Comment by carols10cents** [comment]
I'm going to give this a close, I don't think it's worth fixing either. Most crates immediately get more than one download :)
