### ISSUE TITLE
alpha10 should be newer than alpha9

### ISSUE THREAD

**Issue by Sherlock-Holo** [rust-lang/crates.io#2501]
when a version is `0.1.0-alpha10`, it should be newer than `0.1.0-alpha9`, that means `alphaN` should be newer than `alphaM` if `N > M`

in https://crates.io/crates/fuse3/versions, crates.io thinks `alpha10` is even older than `alpha2`, that's not right

**Comment by ehuss** [comment]
The [semver spec](https://semver.org/#spec-item-11) indicates that pre-release segments with letters are compared lexically. You need to separate the segments with `.` in order to get numeric ordering, like `-alpha.10`.

**Comment by pksunkara** [comment]
I agree. Crates.io is following semver spec.

**Comment by jtgeibel** [comment]
Closing based on the comments above that this is to spec.
