### ISSUE TITLE
Add funding links to crates

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/crates.io#2534]
It would be nice if crates.io could automatically detect a `.github/FUNDING.yml` and mention that you can support the project on its crate detail page. It would be nicer if there's was also a way to set it in my owner dashboard, however I think most use would be covered by reading the funding file.

**Comment by Turbo87** [comment]
since there hasn't been any activity on this issue for a while I'll go ahead and close it. the easiest solution to this is probably to include that kind of information in the README file of the crate and then crates.io will automatically display it.
