### ISSUE TITLE
Make keyword links case-independent

### ISSUE THREAD

**Issue by kud1ing** [rust-lang/crates.io#254]
- This gives a result: https://crates.io/keywords/Amazon
- This gives an error message: https://crates.io/keywords/amazon

It would be a pitty if "postgresql" and "Postgresql" or "PostgreSql" would be treated as different keywords.

I suggest to make the lower case keyword url match all variants of a keyword.

**Comment by gsquire** [comment]
If this is desired behavior, I think I can tackle this. I'm not sure if crates are treated as case-sensitive.

**Comment by alexcrichton** [comment]
Sure! Crates are currently case insensitive today, yeah, so there should be some example code handling this.

**Comment by carols10cents** [comment]
I think this is fixed! Please reopen if I'm mistaken! ❤️

**Comment by kud1ing** [comment]
Seems fixed. Thank you.
