### ISSUE TITLE
https://crates.io/search?q=truetype results are poorly ordered

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang/crates.io#2541]
The first result after the exact match is "stb_truetype_bugfix_19072017". This crate was last updated three years ago and has had only 432 downloads. "rusttype_bugfix_19072017" also ranks quite highly.

**Comment by Turbo87** [comment]
@jrmuizel do you have any concrete suggestions on how to fix this? otherwise this issue isn't really actionable unfortunately.

**Comment by jrmuizel** [comment]
Why does stb_truetype_bugfix_19072017 get listed before stb_truetype? Is there a description or documentation for how the relevance metric is computed?

**Comment by Turbo87** [comment]
https://github.com/rust-lang/crates.io/issues/1270 has a bit more information on this. since that issue describes a situation fairly similar to yours I'll close this issue as a duplicate for now.
