### ISSUE TITLE
Recent commit allows `+` in package names

### ISSUE THREAD

**Issue by ThePuzzlemaker** [rust-lang/crates.io#2550]
I was looking at code and found out that by patching Cargo's code to allow `+` in package names, you can upload a package to the crates.io registry with `+` in the name.

This issue stems from commit [5f842f7](https://github.com/rust-lang/crates.io/commit/5f842f73c6a9f32719508db4b1c534959b02f6e8), where `+` is allowed in feature names.

The function `Crate::valid_name` in [`src/models/krate.rs`](https://github.com/rust-lang/crates.io/blob/master/src/models/krate.rs) uses `Crate::valid_ident`, which uses `Crate::valid_feature_name`. Due to `Crate::valid_feature_name` now allowing `+`, and no further checks in `Crate::valid_name` to deny `+`, it allows a user to submit a package with `+` in its name.

By changing some checks in Cargo's code, and running `cargo publish --allow-dirty --no-verify` (using the patched Cargo) I was able to publish the package `test+package`.

[Here](https://github.com/rust-lang/crates.io-index/commit/3a56c06e3f827102cd9ed5a766dd6fc18cb6d5fe) [is](https://github.com/rust-lang/crates.io-index/blob/master/te/st/test%2Bpackage) [evidence](https://crates.io/crates/test%2Bpackage).

**Comment by kornelski** [comment]
This broke lib.rs, because I have an assert like this one:

https://github.com/rust-lang/crates.io/blob/bb411ae3e64b33f00411bb13fbeaace1fe2f7421/src/krate.rs#L214-L219

**Comment by ThePuzzlemaker** [comment]
Is there a way that I can help to get that package removed? 

I apologize I published that package, I did not think it would cause any problems at the time but now I realize that reasoning was invalid.

If there's any way I can/need to help, feel free to mention me

**Comment by kornelski** [comment]
That's OK, I've added a workaround for that package.

**Comment by pietroalbini** [comment]
@ThePuzzlemaker could you test your patched cargo against https://staging.crates.io?

Sign up there, verify your email address (you'll have to replace the URL in the email you receive to point to staging.crates.io instead of crates.io, a fix is in #2543) and generate a token.

Add this to your `~/.cargo/config`:

```toml
[registries]
staging = { index = "https://github.com/rust-lang/staging.crates.io-index" }
```

Then do:

```
cargo login --registry staging <token>
cargo publish --registry staging --allow-dirty --no-verify
```

**Comment by pietroalbini** [comment]
[Removed the `test+package` crate from crates.io.](https://github.com/rust-lang/crates.io-index/commit/fab480f0d3da74840dee31c95bebd9b6465f6ec3)

**Comment by ThePuzzlemaker** [comment]
@pietroalbini Does not work:
```
error: api errors (status 200 OK): invalid upload request: invalid value: string "test+package", expected a valid crate name to start with a letter, contain only letters, numbers, hyphens, or underscores and have at most 64 characters at line 1 column 22
```
should I close now?

**Comment by pietroalbini** [comment]
@ThePuzzlemaker we haven't deployed the change on production yet, we'll close the issue once the deploy is done. Thanks for testing the fix worked!

**Comment by pietroalbini** [comment]
The fix was deployed! Thanks again @ThePuzzlemaker for reporting this issue to us!
