### ISSUE TITLE
Test uploaded crates can be unpacked by all released Cargo versions

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang/crates.io#256]
This is a remediation item for https://github.com/rust-lang/cargo/issues/2326 which resulted in some crates being published that could not be unpacked.

Because crates.io does not allow changing published crates except to mark them yanked, this would be best caught by the server at upload time.

**Alternatives**
1. Do nothing. If this happens again, require all affected crates' authors to yank the affected versions is clearly not ideal.
2. Add a test in `cargo` to ensure that no nightly does this again.
3. Verify this in the client (`cargo`) at upload time.

I think (1) is clearly not a good approach. (2) is a good step, and should happen. It does not prevent accidental use of affected versions. Both (2) and (3) leave a "hole" in that a malicious client could publish crate versions that cannot be unpacked, leaving us with the remediation in (1).

**Comment by Eh2406** [comment]
Related to https://github.com/rust-lang/crates.io/issues/580

**Comment by Turbo87** [comment]
closing in favor of #580
