### ISSUE TITLE
Deprecation warning for `{{title}}` helper

### ISSUE THREAD

**Issue by jtgeibel** [rust-lang/crates.io#2568]
I'm seeing the following warning in the console:

> Using `{{title}}` helper is deprecated, use `{{page-title}}` instead. /tmp/broccoli-3979O9diMfBpPOVk/out-423-colocated_template_processor/cargo/templates/application.hbs

It looks like we have 3 instances of this helper:

```console
$ git grep "{{title"
app/templates/application.hbs:{{title "crates.io: Rust Package Registry" separator=' - ' prepend=true}}
app/templates/crate/version.hbs:{{title this.crate.name}}
app/templates/search.hbs:{{title (concat "Search Results for '" this.q "'")}}
```

**Comment by Turbo87** [comment]
yeah, noticed that too. I'll take care of it :)
