### ISSUE TITLE
Where can I find the crate's "description"

### ISSUE THREAD

**Issue by LucianoBestia** [rust-lang/crates.io#2573]
I cannot find the crate's "description" in 
https://github.com/rust-lang/crates.io-index

Where can I find it ?
I miss also the repo url there.

**Comment by jtgeibel** [comment]
The index only contains information needed by `cargo` to do dependency resolution and to verify the crate's checksum. We don't want to increase the size of the index by including auxiliary information about each crate.

If you're looking for bulk information, the easiest way to obtain this is via the [database dumps](https://crates.io/data-access). For individual crates, the data is available via the API.
