### ISSUE TITLE
build a small new repo similar to github.com/rust-lang/crates.io-index

### ISSUE THREAD

**Issue by LucianoBestia** [rust-lang/crates.io#2574]
The repo https://github.com/rust-lang/crates.io-index has too much data.
We can fetch it regularly, but then we filter out a very small amount of usable data.
A lot of utilities would need a smaller and more compact repo with only these data:
```json
{
    "crates": [
        {
        "name": "a1",
        "description": "This is a test crate. Thanks for coming my homepage."
        "versions": ["0.1.1"]
        "repo": "https://github.com/keonjeo/a1"
        },
        {
        "name": "num-traits",
        "description": "Numeric traits for generic mathematics",
        "versions": ["0.2.12","0.2.11","0.2.10","0.2.9","0.2.8","0.2.7","0.2.6",,"0.2.5","0.2.4","0.2.3","..."}]
        "repo":"https://github.com/rust-num/num-traits"
        },
        ...
    ]
}
```
Is it possible for crates.io to make such a repo and push the changes regularly?
Just like the crates.io-index, but smaller. 
So the developers of utilities can easily with minimal effort fetch this data regularly?
It could one json file. Or maybe 2, 3, files. It cannot be a lot of data in here. 
The version should be limited to the last 10 non-yanked version. 
Some crates have 600 non-yanked versions. Who need this?
Shouldn't this old version get yanked somehow?

**Comment by jtgeibel** [comment]
I don't think a git repo would be a format to provide this type of information. Even if you only need access to the last 10 non-yanked versions, the git repository will still contain all previous versions of files.

> Is it possible for crates.io to make such a repo and push the changes regularly? [...]  So the developers of utilities can easily with minimal effort fetch this data regularly?

This would also add the complexity of trying to keep 2 git repositories and the database in sync, and it seems like the scope of information contained would just grow over time until it contains the info in the main index and more.

>  Some crates have 600 non-yanked versions. Who need this?

Cargo needs to see all versions for dependency resolution. I also expect a lot of tools beyond cargo have reasons to obtain information on older versions of crates.

>  Shouldn't this old version get yanked somehow?

Automatically yanking old versions of crates would be a huge change to the ecosystem and would have to go through the RFC process (though I doubt there would be much appetite for such a change).

**Comment by LucianoBestia** [comment]
Thank you for pointing me to the database dump.
You don't really care about third party tooling around the crates.io database.
No problem.

**Comment by carols10cents** [comment]
> You don't really care about third party tooling around the crates.io database.

We are a volunteer team with very limited amount of time to spend maintaining crates.io; our priority is keeping the main site up and running well, yes.

**Comment by LucianoBestia** [comment]
I appreciate your work, don't misunderstand me. It is fantastic for limited resources.
I didn't want to offend, to be clear. I just wanted to know how much you count on third party tools development.
And I understand the problem of fragmentation in the ecosystem to be avoided.
I am happy you pointed me to the database. I will build something around it and let you know.
Thanks.
