### ISSUE TITLE
Crate page for async-stdio shows incorrect version number and dependencies

### ISSUE THREAD

**Issue by jdm** [rust-lang/crates.io#2597]
https://crates.io/crates/async-stdio shows a version of 0.0.0.0 and no dependencies, while the versions list shows a list of published versions and https://gitlab.com/jrobsonchase/async-stdio/-/blob/master/Cargo.toml shows multiple dependencies.

**Comment by JohnTitor** [comment]
That's because any version other than `0.0.0` is the alpha releases. crates.io shows information from the latest _stable_ version IIUC.

**Comment by sgrif** [comment]
John's comment is correct. The crate page shows the last non-prerelease version. This behavior is expected. Once you release a non-prerelease version > 0.0.0, that page will update
