### ISSUE TITLE
How do I rename a published crate

### ISSUE THREAD

**Issue by Alfriadox** [rust-lang/crates.io#2618]
I accidentally published a crate under the name "Linguist" (I meant to write "linguist"). I yanked it immediately and it has no downloads/dependencies. Is there anyway to rename this crate?

**Comment by ehuss** [comment]
Transferred to crates.io issue tracker.

**Comment by carols10cents** [comment]
Not at this time, no. This is a duplicate of https://github.com/rust-lang/crates.io/issues/1451.
