### ISSUE TITLE
Deprecation of GitHub teams API URL format that we use

### ISSUE THREAD

**Issue by jtgeibel** [rust-lang/crates.io#2619]
While investigating #2617, I noticed a response header linking to this blog post about [deprecation of the API URL we are using](https://developer.github.com/changes/2020-01-21-moving-the-team-api-endpoints/). It looks like we have until February 1st, 2021 to migrate to the new API path.

* [Legacy URL](https://docs.github.com/en/rest/reference/teams#get-team-membership-for-a-user-legacy) - here is [our existing usage](https://github.com/rust-lang/crates.io/blob/3dbbcb0c15f529a39fcbf5d6e95a686b439489e5/src/models/team.rs#L223) of that API.
* [New API, scoped by org](https://developer.github.com/v3/teams/members/#get-team-membership-for-a-user)

There are 2 forms of the new URL. The slug version `GET /orgs/:org/teams/:team_slug/memberships/:username` uses the org and team slugs, which we currently store in the database as `teams.login` in the form `github:org:team`. However my understanding is that with this format we'll probably also want to issue a separate API call to ensure `teams.github_id` matches the current team.

For the id based format, `GET /organizations/:org_id/team/:team_id/memberships/:username`, I don't believe that we currently track the `org_id` anywhere. Perhaps we could start tracking this and use the existing API (before it goes away) to backfill all the `org_id`s in the database.

**Comment by thiagoarrais** [comment]
I'd like to tackle this in case anyone else isn't trying already. I can dedicate some time on an off over the coming weeks. I'm sure it's doable before the deprecation date.

I think I'll start by writing a PR for collecting the org_id when the teams are inserted into the database. Then we can work on backfilling the existing teams. Is that ok?

**Comment by StylusEater** [comment]
@thiagoarrais I'm happy to work on this with you. I too planned to start work on it. Let me know your thoughts. I'm located in US/Eastern and could work with you over Discord this weekend.

**Comment by thiagoarrais** [comment]
Nice, StylusEater. I can't work on the weekends, though. Maybe we can work together but asynchronously?

Anyway, I've opened a [(draft) PR for the initial change](https://github.com/rust-lang/crates.io/pull/2725). I'd really love to get some feedback on it. Tests are failing locally, but I'm not sure if this isn't a configuration issue.

Another possible course of action you can take is writing the backfill procedure based on this PR.

**Comment by thiagoarrais** [comment]
Quick update:

1. Removed the draft marker from [the first PR](https://github.com/rust-lang/crates.io/pull/2725)
2. Started a [new branch](https://github.com/thiagoarrais/crates.io/tree/use-orgid-for-membership-check) for the final code. Will turn it into a PR after the org ids are populated in the db.

**Comment by thiagoarrais** [comment]
**Question:** regarding the db backfill, as I understand we need a user token in order to query the GitHub API (`/teams/{team_id}`). May there be teams for which there are no valid tokens?

**Comment by thiagoarrais** [comment]
Quick update no. 2: wrote a backfilling procedure.

**Comment by thiagoarrais** [comment]
Update no. 3: finished the final code (PR #2810). Should only be merged after backfilling db.
