### ISSUE TITLE
security: host READMEs in an iframe rather than inline

### ISSUE THREAD

**Issue by jsha** [rust-lang/crates.io#2628]
Hi! Thanks for your work on crates.io. I'm learning Rust, and I work in security (4 years at Twitter doing application security, 5 years at Let's Encrypt doing backend dev and PKI). I figured crates.io is very important to the security of the Rust ecosystem, so I've been going through the code and plan to file some issues and PRs. Hope you find them helpful!

One thing I noticed is that READMEs get rendered directly into each crate's page. I see that the README HTML [is sanitized by Comrak](https://github.com/rust-lang/crates.io/blob/987cac80f42d48763c8b3bd12dd779f8ef7c6eab/src/render.rs#L59-L80). I assume Comrak is good at that task, but the problem of HTML sanitization is notoriously hard, and new techniques for bypasses are often discovered. If someone finds a way to get around Comrak's sanitization, they would have an XSS on crate.io. The result of such an XSS would be that they could write JS that would act as their victim on crates.io, publishing malicious crates, adding the attacker as an owner of the victim's crates, or adding API tokens controlled by the attacker to the victim's account.

One common defense-in-depth against XSS is to host untrusted content on a different domain. This takes advantage of the browser's [Same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) to isolate the untrusted content. Even if someone manages an XSS on the untrusted domain, they can't run JS in the context of the main domain.

Crates.io's README setup seems particularly well set up to take advantage of this technique: The READMEs are already hosted on a separate domain (static.crates.io). We would need to create an iframe that loads the README from that domain, instead of interpolating the README into the main page. We would also need to make some changes so the iframe contents receive the correct CSS, and do a little work to ensure the iframe has the correct size.

What do you think? Does this seem like a good approach?

**Comment by Turbo87** [comment]
While an iframe would potentially improve our security a little bit, I think it would decrease the UX because it would cause us to have a scrolling container inside the regular scrolling page. Ensuring that the iframe has the necessary `height` to not scroll can work, but is relatively complicated to build.

Since we use a Content Security Policy which disallows inline scripts, wouldn't that be enough?

**Comment by jsha** [comment]
Good point! I generally think of CSP as a defense-in-depth rather than a first line of defense. For instance, [MDN says](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP): "Content Security Policy (CSP) is an added layer of security that helps to detect and mitigate certain types of attacks, including Cross Site Scripting (XSS) and data injection attacks." But, given that Comrak's sanitization is the first line of defense, relying on CSP rather than iframes as backup seems reasonable. And I agree, setting the size of the iframe correctly is fairly complex. Not only would the child frame have to postMessage to the parent frame about its height, the parent frame would have to postMessge to the child about the available width, and the dance would have to be repeated on resize (but not too frequently to avoid chewing CPU if someone is rapidly resizing the window across many different sizes).

When I load a crates page on crates.io right not, I see that CSP indeed forbids unsafe-inline for scripts, but allows script-src: unsafe-eval and style-src: unsafe-inline.

content-security-policy: default-src 'self'; connect-src 'self' *.ingest.sentry.io https://docs.rs https://static.crates.io; script-src 'self' 'unsafe-eval' https://www.gstatic.com; style-src 'self' 'unsafe-inline' https://www.gstatic.com https://code.cdn.mozilla.net; font-src https://code.cdn.mozilla.net; img-src *; object-src 'none'

Do you know what aspects of the site require those to be allowed? If we could get rid of them, CSP would be an even stronger defense. Here's a talk and a whitepaper from 2013 about stealing page data by injecting styles. I will admit that I haven't followed the field closely since about 2014, so it's possible these attacks are obsolete.

https://mikewest.org/2013/09/xss-no-the-other-s-cssconfeu-2013/
https://www.nds.ruhr-uni-bochum.de/media/emma/veroeffentlichungen/2012/08/16/scriptlessAttacks-ccs2012.pdf

**Comment by Turbo87** [comment]
> Do you know what aspects of the site require those to be allowed?

Unfortunately, I don't. AFAICT the only thing that might need those is the Google Charts code on the crates detail page. We are planning to eventually replace them with something self-hosted though.

**Comment by jsha** [comment]
Alright, closing out this issue. I'm convinced that this approach is probably more effort than it's worth, given the secondary layers of protection. Thanks for talking it over with me!
