### ISSUE TITLE
math crate on crate.io

### ISSUE THREAD

**Issue by Rustinante** [rust-lang/crates.io#2655]
I saw that the owner of the math crate said to content them here for a transfer request.
https://crates.io/crates/math
Can they see this? I'm interested in the crate. Thanks

**Comment by carols10cents** [comment]
Hi, you are now the owner of the math crate. Thanks!

**Comment by aaron-cerebras** [comment]
Thank you!!

**Comment by Rustinante** [comment]
Thank you!!
