### ISSUE TITLE
Cannot generate new token -  An error occurred while saving this token, must be logged in to perform that action

### ISSUE THREAD

**Issue by bergercookie** [rust-lang/crates.io#2658]
I have recently signed up to crates.io via my github profile and I'm not trying to crate an API key to upload a crate.
I'm getting the following error message when I'm trying to do the latter:

![latest-screenshot](https://user-images.githubusercontent.com/5816719/88486554-66711900-cf76-11ea-92ff-b774a029bcf2.png)

Am I doing something wrong?
Is there any alternative way of generating the API key?

**Comment by jbr** [comment]
+1, I am getting a similar error when attempting to accept an invite, but in order to view my invites page I necessarily am logged in. I think this is probably a more general problem than token creation:
<img width="467" alt="image" src="https://user-images.githubusercontent.com/13301/88487122-4b32e900-cf37-11ea-9249-6a7a95c038ee.png">

**Comment by jbr** [comment]
For anyone researching this issue, I was able to make my request go through with the following changes:
```

// this request is copied verbatim from the browser
// it fails with 403 {"errors":[{"detail":"must be logged in to perform that action"}]}, which is the same result in-browser
curl 'https://crates.io/api/v1/me/crate_owner_invitations/CRATE_ID_ELIDED' \
  -X 'PUT' \
  -H 'authority: crates.io' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Mobile Safari/537.36' \
  -H 'content-type: application/json; charset=UTF-8' \
  -H 'origin: https://crates.io' \
  -H 'cookie: cargo_session=SESSION_ELIDED' \
  --data-binary '{"crate_owner_invite":{"invited_by_username":"USERNAME_ELIDED
s","crate_name":"CRATE_NAME_ELIDED","crate_id":CRATE_ID_ELIDED,"created_at":"TIMESTAMP_UNNECESSARILY_ELIDED","accepted":true}}' \
  --compressed
```

```
// but this one succeeds:
curl 'https://crates.io/api/v1/me/crate_owner_invitations/CRATE_ID_ELIDED' \
  -H 'cookie: cargo_session=SESSION_ELIDED' \
  --compressed \
  -X PUT \
  --data-binary '{"crate_owner_invite":{"invited_by_username":"USERNAME_ELIDED","crate_name":"CRATE_NAME_ELIDED","crate_id":CRATE_ID_ELIDED,"created_at":"TIMESTAMP","accepted":true}}'
```

As a result, it seems like it might be related to https://github.com/rust-lang/crates.io/pull/2627

**Comment by jtgeibel** [comment]
I've rolled back to the previous deploy. This should now work. Please let me know if you're still seeing issues. Sorry about that.
