### ISSUE TITLE
delete/yank typo'd package - catfact-rs

### ISSUE THREAD

**Issue by luxxxxy** [rust-lang/crates.io#2664]
Hello, I accidentally uploaded a package under the wrong name - [catfact-rs](https://crates.io/crates/catfact-rs), before reuploading it under the correct name, [catfact](https://crates.io/crates/catfact)

I tried to yank the single version, but that just made it display "0.0.0" rather than yanking the entire crate.

**Comment by carols10cents** [comment]
Yes, that is what yanking the entire crate does. We don't delete crates except for legal reasons or if they're against our policies, to keep the registry as immutable as possible. Thanks!

**Comment by carols10cents** [comment]
You can publish one last version that contains a description that says you're willing to transfer the name to anyone who wants it with the best way to contact you.

**Comment by luxxxxy** [comment]
alright
