### ISSUE TITLE
Keywords went missing

### ISSUE THREAD

**Issue by hoodie** [rust-lang/crates.io#271]
Keywords are no longer displayed on a crates profile page.
Can't tell at what point they went missing.

**Comment by alexcrichton** [comment]
cc @Turbo87, perhaps this was accidentally lost in a refactoring along the way?

**Comment by Turbo87** [comment]
@hoodie was that a recent change?

**Comment by hoodie** [comment]
Iduno, I haven't looked in about 3weeks

**Comment by Turbo87** [comment]
@alexcrichton I've tried to reproduce this problem with data from the live server and didn't get any keywords all the way back to Nov 2015 (didn't test further), but I'm pretty sure I saw them a few weeks ago.

I've also looked at the XHR responses from the server and it seems to me that the `/crates/winapi` call for example is missing the `keywords` list. It does sideload a few keywords, but it doesn't assign them to the crate. I have a feeling that #270 might be responsible for that, which would also explain why the older webclients didn't work when proxied to the live server.

/cc @sgrif

**Comment by alexcrichton** [comment]
Ah yeah that may be it. With the keywords column on the crates table removed we'll need to make a separate call to load keywords I believe.

**Comment by Turbo87** [comment]
@alexcrichton I'm not sure about that. It looks like the correct keywords are already sideloaded with the requests, just not included in the `crate` itself as a list of keyword ids.

**Comment by alexcrichton** [comment]
Hm, maybe that was accidentally left out?

**Comment by Turbo87** [comment]
I hope @sgrif will be able to tell us about it :wink:

**Comment by sgrif** [comment]
Blurgh, it didn't look like it was referenced on the client side. I'll fix this tomorrow
