### ISSUE TITLE
"Recent downloads" higher than "All-Time downloads"

### ISSUE THREAD

**Issue by diwic** [rust-lang/crates.io#2714]
I went to https://crates.io/me/crates?sort=recent-downloads and found that my `dbus-crossroads` crate had 271 "All-Time downloads" and 272 "Recent downloads". As of 2020-08-25, 20:00 CET.

**Comment by diwic** [comment]
https://pasteboard.co/Jo2cejO.png

**Comment by carols10cents** [comment]
These numbers can be slightly out of sync because they're updated via a background job that rolls the numbers up, not immediately. I'm currently seeing both all time and recent downloads fro dbus-crossroads at 273, so the system appears to be working correctly.
