### ISSUE TITLE
Minor style inconsistencies between crates.io and doc.crates.io

### ISSUE THREAD

**Issue by birkenfeld** [rust-lang/crates.io#273]
(Not sure this belongs here or in the cargo repo.)

While adding the docs header link to crates.io for #267, I noticed several differences in the stylesheet.
- The default font-face is different: doc.crates.io only specifies `sans-serif`, while crates.io specifies `"Helvetica Neue",...,sans-serif`.
- The dropdown menu "buttons" at the top (Documentation for doc.crates.io, the user menu for crates.io) are styled differently when the menu is open: only doc.crates.io makes the button look depressed and reverses the arrow direction.

**Comment by steveklabnik** [comment]
I'm not sure either, but synchronizing them would be good, probably.

**Comment by carols10cents** [comment]
I'm closing this since the cargo docs are about to be rendered completely differently using mdbook :)
