### ISSUE TITLE
Cargo search results

### ISSUE THREAD

**Issue by rolandkopka** [rust-lang/crates.io#2739]
**Problem**

`cargo search` acts weird. Sometimes it finds what I need, sometimes it doesn't. It's behaivour is unexpected.
For example `cargo search` should have less or equal number of results as the search term gets more complicated

**Steps**

1. `λ cargo search ferr` (18 crates found)
2. `λ cargo search ferri` (35 crates found)

or

1. `λ cargo search ferr say` (no result) **This should have result**
2. `λ cargo search ferri say` (4 crates found)

**Comment by ehuss** [comment]
Transferred to the crates.io repo, as it handles searching.

**Comment by Turbo87** [comment]
since https://github.com/rust-lang/crates.io/issues/1270 is somewhat similar to this issue I will close this as a duplicate :)
