### ISSUE TITLE
`XXX_XXX` and `XXX-XXX` return wildly different results

### ISSUE THREAD

**Issue by camelid** [rust-lang/crates.io#2746]
Not sure if this is a feature or a bug. E.g., with `rust_hello` and `rust-hello`:

![image](https://user-images.githubusercontent.com/37223377/91927403-44ae3480-ec8e-11ea-83b2-1b9b4116c690.png)

![image](https://user-images.githubusercontent.com/37223377/91927418-4ed03300-ec8e-11ea-9c91-cebfe784c08e.png)

**Comment by Turbo87** [comment]
closing this in favor of https://github.com/rust-lang/crates.io/discussions/4339, which goes into a roughly similar direction
