### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by camelid** [rust-lang/crates.io#2748]
I saw rust-lang/docs.rs#1013 and I figured that it might be a good idea to bring up for crates.io as well.

**Comment by Turbo87** [comment]
I'm afraid we currently don't have the capacity to maintain something like that. But if you have a bit of time and want to help out then you're more than welcome to create such a changelog and help keep it up-to-date :)

**Comment by StylusEater** [comment]
@camelid and @Turbo87 seems straight forward but also a bit problematic if someone falls behind at updating the `CHANGELOG.md`.
