### ISSUE TITLE
Enable "<namespace>/<crate_name>" pattern for future growth of crates

### ISSUE THREAD

**Issue by brightzheng100** [rust-lang/crates.io#2750]
For now, the `crates` are published by using a single `<name>` pattern which won't be great along the way while Rust growing -- I've already seen some `placeholder` crates like `Fuchsia placeholder` which look weird.

I'd suggest to have a `<namespace>/<crate_name>` pattern and only those core libs can be published without such a `<namespace>` (or a dedicated namespace with like `core`?).

Here are some examples:
- `my_user/ping` means this crate named `ping` is published by a user (GitHub user?) named `my_user`;
- `a_org/pong` means this crate named `pong` is published by org (GitHub org?) named `a_org`;
- But those crates that have been published/promoted to be core libs can ignore such a namespace, or with a dedicated namespace like `core`.

Not sure whether someone has raised the same/similar idea but I believe it may help for Rust.

**Comment by carols10cents** [comment]
This issue has been raised many times. There are many details to be ironed out, and this change needs to go through the RFC process. There was recently an RFC that the author just closed, please read it, the comments, and the linked posts for more context. Thanks! https://github.com/rust-lang/rfcs/pull/2978
