### ISSUE TITLE
Add TOML syntax highlighting

### ISSUE THREAD

**Issue by camelid** [rust-lang/crates.io#2761]
That way it will look nicer when crate READMEs have something like this:

![image](https://user-images.githubusercontent.com/37223377/92548268-6e75d700-f20b-11ea-9997-62752aa0ebae.png)

**Comment by JohnTitor** [comment]
Hm, I thought I enabled it by 26d9632759f84742bf5f6d0b5a907ef691479fab (for instance, https://crates.io/crates/clap/3.0.0-beta.2 has the `language-toml` class actually) but it didn't.
Maybe additional work on frontend is needed?
@Turbo87 do you know something about this?

**Comment by camelid** [comment]
I think this should fix it: #2808
