### ISSUE TITLE
Find good placement for yank button on crate page

### ISSUE THREAD

**Issue by jtgeibel** [rust-lang/crates.io#2794]
Per https://github.com/rust-lang/crates.io/pull/2623#issuecomment-666522853 we need to find good UI for including the yank button on a crate page.

cc @thiagoarrais

**Comment by thiagoarrais** [comment]
Maybe option B from https://github.com/rust-lang/crates.io/pull/2623#issuecomment-666522853, but with the version in the button label. It may make it clearer that the action refers to the specific version, not the whole crate.

I'm a little short on time right now, but will try to make a mockup later.

**Comment by jtgeibel** [comment]
> Maybe option B

@thiagoarrais I forgot to mention it, but option B was my favorite, and I like how you have added the version for clarification! I like the new mockup.
