### ISSUE TITLE
Search Results Ordering

### ISSUE THREAD

**Issue by tadman** [rust-lang/crates.io#281]
Searching for the [bytes](https://crates.io/crates/bytes) package produces a list of results that's bizarre.

Some repositories with just a hundred or so downloads crowd out this package which has 33K. What order are these results presented in? I can't see a pattern here.

You'd think an exact match on name would push it to the top, but apparently that's not the case.

While I'm happy I found the [nom](https://crates.io/crates/nom) package as an interesting alternative, there's a bunch of other stuff in there which really shouldn't be at the top.

**Comment by g-k** [comment]
I noticed this as well.

I had to go to the third page (almost the fourth) to find the official cargo crate: https://crates.io/search?page=3&q=cargo

**Comment by carols10cents** [comment]
This looks old-- exact matches have been getting pulled to the top for a while now, so searching for "bytes" or "cargo" has those crates listed first. Please reopen or file a new issue if you have examples of other searches that don't return what you'd expect!

**Comment by tadman** [comment]
Yeah, things look much better now. Thanks!
