### ISSUE TITLE
Behaviour of api for crate names

### ISSUE THREAD

**Issue by caulagi** [rust-lang/crates.io#283]
Is the treatment of crate names (particularly underscores and hyphens) something that can be relied on?

```
$ curl -I -H "Content-Type: application/json" -H "Accept: application/json" https://crates.io/api/v1/crates/error-def
HTTP/1.1 200 OK
Connection: keep-alive
Server: nginx
$
$ curl -I -H "Content-Type: application/json" -H "Accept: application/json" https://crates.io/api/v1/crates/error_def
HTTP/1.1 200 OK
Connection: keep-alive
Server: nginx
$
$ curl -I -H "Content-Type: application/json" -H "Accept: application/json" https://crates.io/api/v1/crates/errror_def
HTTP/1.1 404 Not Found
Connection: keep-alive
Server: nginx
```

So in this case, error_def is the correct crate name, but asking for error-def also gives a 200.  Is this documented or am I missing something?

**Comment by alexcrichton** [comment]
Yeah this is currently intentional because it helps with some renames we've done in the past. The JSON returned should have the full name of the crate, however.

**Comment by killercup** [comment]
@alexcrichton, do you plan on supporting this "forever"? I.e., can cargo-edit rely on this behaviour to cleverly outsource crate name normalisation?

**Comment by alexcrichton** [comment]
Yeah I suspect this won't change

**Comment by killercup** [comment]
Cool. We'll be using that in cargo-add, then :)
