### ISSUE TITLE
Can not find crate

### ISSUE THREAD

**Issue by Anakael** [rust-lang/crates.io#2915]
I want to setup crates.io as mirror for using from build-system.

I run server with local index and add it to `~/.cargo/config` and copy crates.io-index to my local index.

When I run `cargo build` cargo finds package in local index, but can't find crate and fail with `failed to get 200 response from `http://localhost:8888/api/v1/crates/autocfg/1.0.1/download`, got 404`

GET `http://localhost:8888/api/v1/crates` response empty array of crates.

So, the questions: "What I should do to use crates.io as mirror? How it downloads packages from original crates.io? (It should does it, shouldn't it?) and how I can obtain crates?"

**Comment by Turbo87** [comment]
hi @Anakael! unfortunately, we don't support running this codebase as a mirror for the real crates.io. there might be some other projects out there that support this, but the crates.io codebase in this repository doesn't. if you find a solution that works for you feel free to share it in this issue in case others have similar questions.
