### ISSUE TITLE
Can not add a team owner

### ISSUE THREAD

**Issue by JanisGailis** [rust-lang/crates.io#2928]
Hi!

I'm trying to add a team owner to a crate using the following command:
```
cargo owner --add github:stcorp-no:s-t-rust
```

Then crates.io complains that the team can not be found:
```
    Updating crates.io index
error: failed to invite owners to crate usgs-eros-client: api errors (status 200 OK): could not find the github team stcorp-no/s-t-rust
```

But the team does exist:
![image](https://user-images.githubusercontent.com/9655353/96566108-d836d580-12cd-11eb-90ef-2d4367088abe.png)

Both the team, and the organization are new and pretty much empty, as we don't use Github internally.

Let me know if this is the wrong repo for this issue! I was not entirely sure.

Thanks!

**Comment by JohnTitor** [comment]
Looks like this comment is related and helps you, could you check the org permission?

https://github.com/rust-lang/cargo/issues/5297#issuecomment-653709183

**Comment by JanisGailis** [comment]
Thank you, this did highlight what was the problem!

The problem was that I had authenticated `crates.io` before the organization was created, so `crates.io` was not authorized to access it. Logging out of everything, revoking `crates.io` OAuth access, and logging into `crates.io` again forced re-authorization and authorization propagation to the organization.

After doing this, it works as expected.
