### ISSUE TITLE
`cargo owner -a` fails with HTTP 500 error

### ISSUE THREAD

**Issue by tarcieri** [rust-lang/crates.io#2957]
I'm attempting to add a GitHub team (@rustcrypto/ring-compat) as the owner of the `ring-compat` crate. However, when I do so, I get a 500 response:

```
$ cargo owner -a github:rustcrypto:ring-compat
    Updating crates.io index
error: failed to invite owners to crate ring-compat: failed to get a 200 OK response, got 500
headers:
	HTTP/2 500

	content-length: 21

	server: nginx

	date: Sun, 25 Oct 2020 14:18:20 GMT

	strict-transport-security: max-age=31536000

	via: 1.1 vegur, 1.1 c1caaceb6655a57ae014aef7bc8ec389.cloudfront.net (CloudFront)

	x-cache: Error from cloudfront

	x-amz-cf-pop: SFO20-C1

	x-amz-cf-id: KNK-qspNvMWxuBEG_JPL3M3wL_isGKicdD5jFrSLyx1m4iR66_bq5g==



body:
Internal Server Error
```

The team was recently renamed and I suspect it might have something to do with that.

**Comment by pietroalbini** [comment]
The error message from the logs is: `duplicate key value violates unique constraint "teams_github_id_key"`.

**Comment by pietroalbini** [comment]
[The `on_conflict` should be updated to also detect conflicts in the GitHub ID](https://github.com/rust-lang/crates.io/blob/562b465eb2046b9405547cdba359d165d6a1b7fc/src/models/team.rs#L61-L71).

**Comment by pietroalbini** [comment]
If you encounter this bug please send an email to help@crates.io with the old team name, and we'll manually rename the team on the crates.io backend.
