### ISSUE TITLE
Refactor `lazy_cell.rs` out as a Library

### ISSUE THREAD

**Issue by indiv0** [rust-lang/crates.io#298]
I needed to use [`src/util/lazy_cell.rs`][lazy_cell] as a dependency in a project of mine, so I took the liberty of factoring it out as an independent library called [lazycell][lazycell].

I added a copyright header to the [`src/lib.rs`][lib-rs] of the library crediting `The Rust Project Developers` seeing as that's what `crates.io` uses for its license.
I also have the same header in [`LICENSE-MIT`][license-mit], and some credits in [`README.md`][readme].

Is this alright by you @alexcrichton, seeing as you wrote the module?

[lazy_cell]: https://github.com/rust-lang/crates.io/blob/master/src/util/lazy_cell.rs
[lazycell]: https://github.com/indiv0/lazycell
[lib-rs]: https://github.com/indiv0/lazycell/blob/master/src/lib.rs
[license-mit]: https://github.com/indiv0/lazycell/blob/master/LICENSE-MIT
[readme]: https://github.com/indiv0/lazycell/blob/master/README.md

**Comment by alexcrichton** [comment]
Sounds good to me, thanks for the heads up!
