### ISSUE TITLE
Table instead of list for crate downloads tooltip

### ISSUE THREAD

**Issue by est31** [rust-lang/crates.io#3000]
The crate downloads tooltip is currently showing a list:

![Screenshot_20201103_124533](https://user-images.githubusercontent.com/8872119/97981825-27ebc580-1dd3-11eb-8eda-6c11c1e975fc.png)

It's not very tidy because the 7 day averages and the (noisier) download counts are in the same list. I think it would be nicer to have a table instead, with a "downloads" and "7-day avg" columns, and rows for each version.

| Version| downloads | 7-day avg. |
| - | - | - |
| Other | 61 | 46.6 |
| 0.9.2 | 4 | 1.4 |
| 0.9.3 | 20 | 11.16 |
| 0.9.4 | 168 | 176.4 |
| 0.10.0 | 2 | 0.7 |
| 0.10.1 | 217 | 189.3 |

Then the number of rows would be halved, and one could think about adding additional rows.

Implementation wise, I guess there are two ways, either creating the html for every single datapoint (maybe a bit expensive) or doing it via a js callback, similar to [this](https://stackoverflow.com/a/34600488) SO answer.

**Comment by Turbo87** [comment]
since the download graph has significantly changed lately I'll close this issue for now :)

**Comment by est31** [comment]
Yeah it's way better now. Thanks!
