### ISSUE TITLE
Always add docs.rs link

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/crates.io#3024]
There might be cases where hosting api docs outside of docs.rs is useful (or not) but I've never seen such a case.

What I see regularly with self-hosted docs:

- Outdated documentation
- No documentation for the version I'm using
- No documentation for the platform I'm using
- Broken graphics etc
- No link to the repository

For example https://crates.io/crates/difference

**Comment by carols10cents** [comment]
There are some people who deliberately don't want to link to docs.rs, because docs.rs is broken for their crate.

**Comment by mahkoh** [comment]
I've never seen such a crate. If they exist then I expect them to be a tiny minority. They would not be harmed by an additional docs.rs link.

**Comment by mahkoh** [comment]
> * No documentation for the version I'm using

Since the rustdoc output does not contain the version it was compiled from, it is generally impossible to tell if the documentation was compiled from the version you're using. E.g. https://crates.io/crates/rand

**Comment by Turbo87** [comment]
ultimately it is up to the crate author what documentation link they want to display. if we displayed multiple links it could lead to confusion, so I agree with Carol that this is working as intended.

**Comment by alexschrod** [comment]
I don't know why this possibility couldn't simply be offered as a setting that each individual logged-in user could choose for themselves, but in the meantime (or forever I guess, if something like this never gets implemented natively):

I wrote a [userscript](https://en.wikipedia.org/wiki/Userscript) that adds a docs.rs link if the one for the given crate goes to somewhere else, and I thought I'd share it so it could benefit others as well. You'll need a browser extension that can run user scripts, like [GreaseMonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/) (for Firefox) or [TamperMonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo) (for Chrome and Chromium-based browsers) and then you go to this URL: <https://greasyfork.org/en/scripts/450970-always-add-docs-rs-link> and click "Install this script."
