### ISSUE TITLE
Allow the use of crates.io without giving away GIithub organization membership

### ISSUE THREAD

**Issue by john01dav** [rust-lang/crates.io#3027]
**Is your feature request related to a problem? Please describe.**
It seems like crates.io has no way to sign in to publish crates without giving away a list of Github organizations. Since the fact that I'm a member in some organizations is private, I don't want to give crates.io this information unless it is shown to be necessary. 

**Describe the solution you'd like**
I can think of three solutions, in this order of preference:
1) Let people sign up to crates.io with a crates.io account. I have a crate in the works that will make it easy to provide robust security for this option, so let me know if you're interested. It's code is for actix-web only, but it should be pretty easy to adapt.
2) Add other SSO providers (as many as possible), with minimum information requested from each one.
3) Turn off the request for organization access with Github SSO.

**Describe alternatives you've considered**
Right now, the only way to sign up seems to be to create and manage a second Github account. While it's possible, this is obviously not ideal since it creates administrative overhead. 

**Additional context**
I don't think that more information would be useful to add at this point, but if there's anything more I can clarify please let me know.

**Comment by Turbo87** [comment]
this appears to be a duplicate of https://github.com/rust-lang/crates.io/issues/326. thanks for sharing your thoughts though :)

**Comment by tshauck** [comment]
I'm not sure this is a duplicate, though related. As I read #326, it's for an alternative login mechanism (i.e github vs gitlab, which would be great), but this is about the scope github uses. I'm also not keen to use cargo while this is required...

![image](https://user-images.githubusercontent.com/421839/130545964-308ed75a-7c3b-4d06-b2ef-5dc36017f047.png)

**Comment by Turbo87** [comment]
@tshauck this is necessary to determine if you're part of an org/team that has owner access of a crate

**Comment by TerryRPatterson** [comment]
@Turbo87 It would be nice to be able to choice what orgs we grant read access for.
I belong to my companies org, and don't want to risk leaking proprietary information.

**Comment by BearOve** [comment]
This is indeed a problem. Giving access to private project boards that has nothing to do with crates.io is quite insecure and bad practice.

**Comment by Turbo87** [comment]
we are aware of the problem and have a few ideas on how to improve the situation. unfortunately, the implementation will take a while though. the only short term workaround is indeed to create a second user account :-/

**Comment by nathan-at-least** [comment]
Checking for updates. I have two distinct concerns about this issue:

- First, like others above, I do not want private org membership exposed to crates.io.
- Second, I do not want crates.io to authorize my crates.io user account to manage or control crates that are "owned or managed" by other people in Github orgs I happen to belong to.

It sounds like [this statement](https://github.com/rust-lang/crates.io/issues/3027#issuecomment-904350040) implies that crates.io makes authorization decisions based on Github org membership, and I want to request a way to opt-out of that.

Is there a good place for that kind of crates.io authorization discussion beyond this ticket?

If I am authorized to manage crates on behalf of all of the github orgs I belong to, this gives me a capability (thus liability) I do not need or want and presents a security risk to all of those orgs. I'm not sure if each of those orgs know that I have the ability to control their releases, so I would want to double check with each of them if that's an acceptable risk. If it's not acceptable risk, then I would need to potentially be removed from multiple github orgs, which disrupts the other (non-release) ways I collaborate with them.

To be fair, though, I'm not quite certain how to manage authorizations for crates managed by groups. I would be inclined to have crates.io-specific configuration for this, but that sounds like a fair amount of new feature complexity.

**Comment by nathan-at-least** [comment]
Also, can we re-open this ticket?

This is very distinct from #326 since it's all about existing Github users continuing to authenticate with Github, but distinct from #326 this is about privacy and authorization issues specific to Github authentication.

**Comment by LawnGnome** [comment]
> Also, can we re-open this ticket?

We can!

To be clear, the crates.io team has no immediate plans to work on this, but we're definitely open to ideas and/or PRs if there's a simple fix for this that hasn't been suggested thus far.

**Comment by Gunni** [comment]
Isn't the simple way to move orgs management over to crates.io db, have it managed there, instead of on github?

**Comment by Turbo87** [comment]
@Gunni yes, that is roughly the long term plan, plus a way to sync GitHub teams to crates.io teams.

**Comment by carols10cents** [comment]
> Isn't the simple way to move orgs management over to crates.io db, have it managed there, instead of on github?

I would not describe that as "simple" 😅

**Comment by achristmascarl** [comment]
as a temporary workaround, I deleted the `&scope=read%3Aorg` part of the url (near the end of the url) at the `https://github.com/login/oauth/authorize` step, refreshed, and was able to login using GitHub without having to grant read access to any orgs

**Comment by chrjoh** [comment]
Any update on this, issue I can not login and allow org read and remove the scope seems not to work my guess they check at the backend as I get crates.io as Authorized OAuth Apps on my account but is still logged out on crates.io
