### ISSUE TITLE
Publishing crate fails due to request timeout and HTTP 413 error

### ISSUE THREAD

**Issue by pemistahl** [rust-lang/crates.io#3028]
Hello,

I've just finished working on the first release of my new crate named *Lingua*.

https://github.com/pemistahl/lingua-rs

https://crates.io/crates/lingua

Unfortunately, I cannot upload it to crates.io because the crate file has a size of 130 MB. My internet connection is not fast enough to upload it within 30 seconds before the request times out.

Can you please publish my crate on crates.io for me or even temporarily disable the timeout so that I can upload it? It is not possible to reduce the file size anymore.

Thanks a lot!

**Comment by Turbo87** [comment]
👋  There are two problems at play here: first is that there is a soft 10 MB upload limit in effect here and apparently you already contacted help@crates.io to lift that for this specific crate.

The second problem is the 30sec request timeout, which is unfortunately imposed on us by Heroku, where crates.io is hosted. There is discussion about switching away from Heroku, but that is obviously not something that can be solved short-term. What might work is using a CI system like GitHub Actions to upload and publish the crate. If you need an example of this you can have a look at https://github.com/Turbo87/flat-projection-rs/blob/c760117ad158949b478ec2fc9ac93a67c51229af/.github/workflows/release.yml

**Comment by pemistahl** [comment]
Hi @Turbo87, thanks for your quick response.

I tried publishing the crate using GitHub Actions. The timeout does not seem to be a problem there, however, now I get a HTTP 413 error code indicating that the payload, i.e. the file size of my crate is too large according to the crates.io nginx server configuration. The stacktrace is:

```
error: failed to get a 200 OK response, got 413
headers:
	HTTP/2 413 

	content-type: text/html

	content-length: 176

	server: nginx

	date: Mon, 16 Nov 2020 12:04:46 GMT

	strict-transport-security: max-age=31536000

	via: 1.1 vegur, 1.1 15cde442051269a0307a638d23683c8c.cloudfront.net (CloudFront)

	x-cache: Error from cloudfront

	x-amz-cf-pop: IAD79-C3

	x-amz-cf-id: 5hgZ0ky4UEhqp5uw2V-NTr6r5vCuyP1As5thE8-fBPhGyl2fhAYshQ==
```

Here you can see the GitHub Actions workflow execution: https://github.com/pemistahl/lingua-rs/runs/1406177245

Is there any chance for you to lift the file size limit? The language model files which are crucial to the correct operation of my library are already compressed. I could host the language model files somewhere else and let the crate download them but this is not the way it is supposed to be, I believe. Why those strict limitations anyway? Is disk space so limited on your server?

**Comment by Turbo87** [comment]
> Is there any chance for you to lift the file size limit?

I will have to direct you to help@crates.io as I don't have the power to change that unfortunately, but AFAIK that there are a few crates that have gotten exceptions to this rule.

**Comment by pemistahl** [comment]
Alright, I will send another email then. Anyway, thank you very much for your help. 👍

**Comment by pietroalbini** [comment]
> Why those strict limitations anyway? Is disk space so limited on your server?

The problem is not a lack of storage space on our end. Almost all the crates we have weight way less than 10MB, and the soft limit prevents abuses of the service. We're happy to manually increase the limits for the crates that actually need more storage, and I see your mail to help@crates.io requesting the increase :)

**Comment by pemistahl** [comment]
As already discussed with @pietroalbini by email, I will put each language model into a separate crate and manage them within a single cargo workspace. This way, the server restrictions won't be a problem anymore.

That's why I will close this issue now, assuming that no new problems will come up. If they do, I will reopen this issue.
