### ISSUE TITLE
Undocumented solution for a problem with "cargo owner --add"

### ISSUE THREAD

**Issue by mpizenberg** [rust-lang/crates.io#3031]
I was trying to add an organization team as owner but kept getting the following message:

```
error: failed to invite owners to crate pubgrub: api errors (status 200 OK): could not find the github team pubgrub-rs/crates-io
```

The [documentation in the cargo book](https://doc.rust-lang.org/cargo/reference/publishing.html) suggests that such issue is very likely a permission problem. I tried everything suggested there, like re-logging crates.io and looking for oauth on that page https://github.com/organizations/:org/settings/oauth_application_policy but nothing worked.

The solution for me was to go to my applications page at https://github.com/settings/applications in the "Authorized OAuth Apps" tab. In there I clicked on the crates.io app. In that page, it lists organizations that the app has access to and my organization was not granted access. So in there I clicked on "Grant" and now the problem is solved.

**Comment by JohnTitor** [comment]
Hey, thanks for the report! That error isn't documented certainly, opened https://github.com/rust-lang/cargo/pull/9000 to improve the docs.

**Comment by JohnTitor** [comment]
The docs have been updated, closing as resolved.
