### ISSUE TITLE
Many crates are erroneously assigned the category "Command line utilities"

### ISSUE THREAD

**Issue by yurivict** [rust-lang/crates.io#3038]
For example:
* https://crates.io/crates/addr2line
* https://crates.io/crates/crossterm

Could you please remove the category "Command line utilities" from crates that only provide libraries?

This erroneously assigned category prevents the automatic discovery of Rust programs that can be ported to various operating systems. Typically Rust programs can be ported, but libraries can't, this is why it is important to have this category to not appear on projects which don't produce executables.

**Comment by Turbo87** [comment]
the category is up to the crate authors (see https://github.com/gimli-rs/addr2line/blob/caa29328d73bab85e0306865507a36891b64ffd5/Cargo.toml#L6), so there is not much we can do here.

**Comment by yurivict** [comment]
> there is not much we can do here

1. You can still remove the obviously false information.
2. You can add software safeguards preventing them from entering this category when it demonstrably doesn't belong there.
