### ISSUE TITLE
https://crates.io/crates/ttserver_def has a dead upstream

### ISSUE THREAD

**Issue by yurivict** [rust-lang/crates.io#3039]
The repository link is broken.

**Comment by Turbo87** [comment]
while that is certainly unfortunate there is not much we can do about this. the repository metadata is submitted in the `Cargo.toml` file, and if that is incorrect or outdated then it's up to the crate author to update it. we currently don't have the infrastructure in place to check all of the metadata links for reachability, and I don't see us being able to do that in the future either. you can see that https://docs.rs/ttserver_def/ has the same problem btw.
