### ISSUE TITLE
Documentation link always points to the latest version

### ISSUE THREAD

**Issue by troplin** [rust-lang/crates.io#307]
The documentation link for a specific version of a crate should point to the documentation of that version and not to the latest.

**Comment by alexcrichton** [comment]
Yeah right now the documentation column is on the crates table and it should probably be moved to the versions table (same for other metadata)

**Comment by ketralnis** [comment]
An example is [serde_json](https://crates.io/search?q=serde_json), where the released version is 0.7.4. [Their docs](https://serde-rs.github.io/json/serde_json/) describe their master branch, but their master branch has [several breaking API changes](https://github.com/serde-rs/json/commit/d0083d29137b9b0eac3e9355a1dd18b717e97d08), which means that the docs describe a version that's incompatible to what's actually fetched by cargo. This has bit me several times and wasted a lot of time.

**Comment by steveklabnik** [comment]
docs.rs kinda solves this

**Comment by carols10cents** [comment]
Yep, closing because docs.rs.
