### ISSUE TITLE
Is there a wishlist of needed libraries?

### ISSUE THREAD

**Issue by lud4ik** [rust-lang/crates.io#311]

**Comment by alexcrichton** [comment]
Not currently, unfortunately, but there are a few older lists scattered in various places. I'd recommend posting on the [subreddit](https://www.reddit.com/r/rust) or to our [forums](https://users.rust-lang.org/) for a more up-to-date list of what others would desire!

**Comment by steveklabnik** [comment]
There is a A-wish list tag on the RFC repo.
