### ISSUE TITLE
Retina Icons

### ISSUE THREAD

**Issue by octplane** [rust-lang/crates.io#319]
Hello,

Because I wanted to redesign the search result page a bit (I find that items take a lot of place and that the fact we can't sort by download/... is annoying), I realised most icons are not ready for High density displays. Would you be interested if I did a pass on these ?

I'm very crappy at design in general, but using Sketch, I was quickly able to do this (left is original, right is retina)
<img width="192" alt="screen shot 2016-04-22 at 13 49 20" src="https://cloud.githubusercontent.com/assets/22177/14740688/1c4a6f12-0891-11e6-90a6-a1407c4b136f.png">

I've only worked to design 2x icon. But the main work is to redo the icons using Sketch, so in vector format so that when anybody will want 3x (or 4x, who knows?), it's easy to generate.

Let me know if this seems interesting for the project.

**Comment by alexcrichton** [comment]
What nice! I'd love to add those :)

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang/crates.io/pull/322
