### ISSUE TITLE
search/browse for crates that support a specific platform

### ISSUE THREAD

**Issue by omac777** [rust-lang/crates.io#3207]
I recall seeing a capability to search for crates that support a specific platform, but I can't find it.

I would like to be able to land on crates.io
then browse to a particular platform for example aarch64
and find some float conversion crate.

I've considered searching for the crate in the search box at the home page, but the results return crates from all platforms

Thank you for listening.

**Comment by omac777** [comment]
https://docs.rs/platforms/1.1.0/platforms/platform/tier1/index.html
https://docs.rs/platforms/1.1.0/platforms/platform/tier2/index.html
https://docs.rs/platforms/1.1.0/platforms/platform/tier3/index.html

Lists all the platforms, but I have no idea which crates natively support which platform without compiling them on said platform and it failing or succeeding.  I had this assumption in my head if it compiles on x86_64, it would compile on aarch64, but I assumed wrong :) as an example scenario where it's important to know in advance.

Thank you for listening.

**Comment by Turbo87** [comment]
unfortunately I don't think there is a way for us to find out if a crate supports a specific platform or not other than trying to compile it. or at least I'm not aware of any metadata that crate authors regularly would set that would indicate something like that.

**Comment by syphar** [comment]
isn't it part of the [`docs.rs` metadata](https://docs.rs/about/metadata) ? 
and docs.rs also runs at least the doc-build for each target. 

I get that probably the docs.rs metadata is not widely used, or that builds might fail on a target while the docs build.

**Comment by syphar** [comment]
( please correct me if I'm wrong and I'm misunderstanding something here :) )

**Comment by Turbo87** [comment]
@syphar yeah, we could theoretically use that metadata. but the problem is that very few crates seem to provide such metadata and they only provide it if they actually thought about the topic. that means we have a large majority of crates that don't declare such metadata and that may or may not work, so the value of such a search filter is somewhat diminished.

**Comment by syphar** [comment]
So what (probably) remains are the doc-build results in docs.rs, which we don't have in crates.io, and ( I assume ) are no guarantee that the crate actually works.

**Comment by Turbo87** [comment]
exactly, yes. that's my understanding, at least.

**Comment by Turbo87** [comment]
due to the above discussion I don't think this issue is currently actionable. in an ideal world this would be nice to have, but it doesn't seem like something that we would be able to reasonably implement in the near future.
