### ISSUE TITLE
Versions are sorted alphabetically instead of numerically

### ISSUE THREAD

**Issue by wtfsck** [rust-lang/crates.io#3245]
**Describe the bug**

1.10.0 is sorted after 1.9.0

**To Reproduce**
1. Go to https://crates.io/crates/iced-x86
2. Scroll down to the download stats
3. 1.10.0 is sorted after 1.9.0

**Expected behavior**

1.10.0 should be sorted before 1.9.0

**Comment by Turbo87** [comment]
I suspect that https://github.com/rust-lang/crates.io/pull/3234 might be responsible for this unintentional change. I suppose we could use something like https://github.com/npm/node-semver/blob/v7.3.4/functions/sort.js to fix this.
