### ISSUE TITLE
Local caching server

### ISSUE THREAD

**Issue by mackeyja92** [rust-lang/crates.io#327]
I have many docker containers compiling rust code and every time I create them they have to go fetch the same exact packages over and over from crates. I really want a local proxy/caching server. How can this be done?

Thanks!

**Comment by alexcrichton** [comment]
Unfortunately this can't be easily done just yet, but we've got a tracking issue over at https://github.com/rust-lang/crates.io/issues/67 so I'm gonna close this in favor of that. Thanks for the report though!
