### ISSUE TITLE
I can't use safari to browse crates.io on iPad in iOS 11

### ISSUE THREAD

**Issue by tomaswuhua123** [rust-lang/crates.io#3287]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Turbo87** [comment]
@tomaswuhua123 would be great if you could give a few more details. in the current state this issue isn't really actionable for us :-/

**Comment by Turbo87** [comment]
it looks like iOS 11 is relatively old, with iOS 14 being the current release. according to our current target browser policy we only support the latest version of iOS at the moment (see https://github.com/rust-lang/crates.io/blob/beaac21fc8fffa0ac7449528716712a3ce9d1cad/config/targets.js#L7-L8).

**Comment by tomaswuhua123** [comment]
“Sorry, it looks like we were not able to load the page. Please make sure your network connection works and you are using an up-to-date browser. If the issue persists, please visit our issue tracker to report the problem.”I jump into this error when I browsed ,is it means my safari is out of date or there is some bug really lies in?

**Comment by tomaswuhua123** [comment]
I got it ,thanks a lot👌🏻👍,meanwhile I am pity for my dumb pad 😔
