### ISSUE TITLE
Mistake regarding `paths` in guide

### ISSUE THREAD

**Issue by alexreg** [rust-lang/crates.io#333]
On http://doc.crates.io/guide.html it is stated that `This path must be an absolute path.` – this is no longer true, since the path can be relative.

I am not sure if environment variables can be embedded in these paths using some syntax, but that would be a nice feature too.

**Comment by carols10cents** [comment]
I don't see this text on http://doc.crates.io/guide.html anymore; and in any case, the documentation for crates.io lives in [cargo's repo](https://github.com/rust-lang/cargo). Please reopen this issue over there if this is still a problem!

**Comment by alexreg** [comment]
How odd that such documentation lives there! Well, someone else must have noticed the issue... it's only been a year and some months since I reported it haha.
