### ISSUE TITLE
Lots of extraneous commas in Guide

### ISSUE THREAD

**Issue by alexreg** [rust-lang/crates.io#334]
It should be evident where these occurrences are: http://doc.crates.io/guide.html

**Comment by steveklabnik** [comment]
It is not evident, that's why they're there :wink: Specifics would be appreciated.

**Comment by alexreg** [comment]
Okay, here are some examples of bad commas and other punctuation issues:

`Cargo is a tool that allows Rust projects to declare their various dependencies, and ensure that you’ll always get a repeatable build.`

`This is called a manifest, and it contains all of the metadata that Cargo needs to compile your project.` – semicolon preferable to `, and`

`Now, if regex gets updated, we will still build with the same revision, until we choose to cargo update.` (last comma)

`This would be bad, because we want reproducible builds.`

`When we’re ready to opt in to a new version of the library, Cargo can re-calculate the dependencies, and update things for us:` (last comma)

`You find a bug in conduit, and you want to write a patch.`

**Comment by carols10cents** [comment]
I'm addressing most of these and some others, but I disagree with: 

> This is called a manifest, and it contains all of the metadata that Cargo needs to compile your project. – semicolon preferable to , and

> You find a bug in conduit, and you want to write a patch.

I think those are fine.

**Comment by alexreg** [comment]
Fair enough. Thanks for taking this on board at least. I know there were some other ones too, so glad you found some.
