### ISSUE TITLE
Mistakes in 'Build Script' docs

### ISSUE THREAD

**Issue by alexreg** [rust-lang/crates.io#336]
1) The sentence

`Any other element is a user-defined metadata that will be passed to dependencies.`

should instead read

`Any other element is a user-defined metadata that will be passed to *dependents*.`

2) The sentence

`We’ve also seen a brief example of how a build script can use a crate as a dependency purely for the build process and not for the crate itself at runtime.`

should appear at the end of the 2nd case study, not the 1st, where it clearly doesn't apply.

**Comment by carols10cents** [comment]
It looks like this was fixed in rust-lang/cargo#3286; I'm guessing cross-repo "fixes" doesn't automatically close issues :) Please reopen if I'm mistaken! ❤️

**Comment by alexreg** [comment]
Thanks!
