### ISSUE TITLE
Dependencies are no longer shown on a crate's page directly

### ISSUE THREAD

**Issue by foresterre** [rust-lang/crates.io#3384]
**Is your feature request related to a problem? Please describe.**

Recently, pages for crates have been getting a small make-over. One of the changes, is the removal of dependencies which used to be listed directly on the welcome page of a specific crate: on the side bar on the right. Currently, the side bar no longer contains the dependencies [1]. Instead, dependencies are listed as a separate tab [2, 3]. 

I really liked being able to see the dependencies directly, because when researching what dependency to pick, often you have certain constraints or requirements like staying within the `tokio` or `async-std` dependency bubbles, or keeping the executable size minimal, and by recognizing certain crates and dependencies, you can quickly pre-filter many crates.

Perhaps this deserves a separate issue (I'm not sure): the list of dependencies on the dependencies page takes up a bit more vertical space than the simpler `<ul>` list, which makes it harder to scan the list of dependencies as quickly as before, especially when a crate has many dependencies. An example of this would be: https://crates.io/crates/cargo/0.51.0/dependencies.

I really hope I don't step on anyone's toes, and I truly love the small colour changes and added shades. Everything looks very fresh, but also a bit too stashed away for my taste. 

I would be happy to help where I can.

**Describe the solution you'd like**

The list of dependencies back on the page of a crate, or another way to quickly review the dependencies.

**Describe alternatives you've considered**

Short cuts to view the dependencies page, like `s` which opens the search page in rustdoc (?). 

**Additional context**

[1] The sidebar which used to include dependencies:

![image](https://user-images.githubusercontent.com/79918676/110397794-d306d700-8072-11eb-99d8-0e1d6b97728f.png)

It used to look like this: https://user-images.githubusercontent.com/10433001/109478859-bab41c80-7ab4-11eb-89e0-281ec98592d3.png (from #3355, screenshot captured by @baoyachi)

[2] The available tabs

![image](https://user-images.githubusercontent.com/79918676/110397812-da2de500-8072-11eb-9d50-a87b91b18224.png)

[3] The dependencies tab

![image](https://user-images.githubusercontent.com/79918676/110397835-e3b74d00-8072-11eb-923c-2b79adbd1f3a.png)

[4] PR which removed the sidebar dependencies and introduced the dependencies tab: https://github.com/rust-lang/crates.io/pull/3346

**Comment by Turbo87** [comment]
<img width="1014" alt="Bildschirmfoto 2021-12-23 um 02 22 36" src="https://user-images.githubusercontent.com/141300/147173361-e7169bed-5d29-48d3-8b69-3cae36a1e4cb.png">

as you've probably seen by now, we're also displaying the crate descriptions of the dependencies now. that makes it easier for users to understand what these dependencies are or do, and this kind of thing would not be possible if it was just a very narrow list in the sidebar.
