### ISSUE TITLE
Error: No matching version of crate 'byteorder' found for: >=1.3.0, <1.4.0

### ISSUE THREAD

**Issue by Turbo87** [rust-lang/crates.io#3448]
**Describe the bug**

https://crates.io/crates/bincode/1.3.2/dependencies shows a dependency to the `byteorder` crate with the semver range `>=1.3.0, <1.4.0`. When clicking on the link (https://crates.io/crates/byteorder/range/%3E=1.3.0,%20%3C1.4.0) an error notification pops up:

> No matching version of crate 'byteorder' found for: >=1.3.0, <1.4.0

but https://crates.io/crates/byteorder/versions shows several matching versions.

**Expected behavior**

I expect to end up at https://crates.io/crates/byteorder/1.3.4 instead of seeing the error popup.

**Additional context**

This is most likely caused by a difference between the Rust and JS semver implementations around dependency requirements/ranges. We might have to slightly adjust the `req` fields from the API to be able to use them with the `semver` JS package.

https://github.com/renovatebot/renovate/blob/ed683a777ece2e0ea51cc967a55f2d7e3158d1e7/lib/versioning/cargo/index.ts#L26-L30 could be a potential solution.

**Comment by plaets** [comment]
Some differences were also described here: https://github.com/renovatebot/renovate/blob/ed683a777ece2e0ea51cc967a55f2d7e3158d1e7/lib/versioning/cargo/readme.md

> We might have to slightly adjust the req fields from the API  

Are changes in the backend necessary? (or maybe I just misunderstood...) Wouldn't that be a breaking change in the API?  
Instead, maybe relevant calls to js semver could be wrapped in some sort of a converter-interface that would handle the incompatibilities.

**Comment by Turbo87** [comment]
> The plan is to handle the incompatibilities on the frontend, right?

yes, exactly. in the `crate.range` route we would need to convert from cargo range to npm range before we do the lookup.
