### ISSUE TITLE
Convenient, typable URLs like npm.im/npm

### ISSUE THREAD

**Issue by danielzgtg** [rust-lang/crates.io#3460]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I can't type something like https://crates.io/rand or https://crates.im/rand into the address bar and get to the exact crate right away.

**Describe the solution you'd like**

I would like crates.io to be as convenient as typing https://npm.im/npm , which allows you to quickly type the crate name into the address bar without going through extra steps such as typing the extra `crates/` letters such as in https://crates.io/crates/rand or waiting for the page to load then clicking on the search field, entering in the package, then clicking on the search result

**Describe alternatives you've considered**

- Have the convenient typable URL be https://crates.io/rand
- Have the convenient typable URL be https://crates.im/rand
- Use some other domain
- Come up with another method to make this convenient

**Comment by Turbo87** [comment]
> * Have the convenient typable URL be https://crates.io/rand

this would prevent us from introducing new routes that conflict with existing crate names, so it does not seem like something we will implement

> * Have the convenient typable URL be https://crates.im/rand

there is nothing stopping anyone from building such a service, but with the small team of maintainers that crates.io currently has it does not seem like something we would implement ourselves. you're welcome to build something like that though :)
