### ISSUE TITLE
crates.io is down (application error)

### ISSUE THREAD

**Issue by klingtnet** [rust-lang/crates.io#348]
See the following screenshot: 
![crates_io](https://cloud.githubusercontent.com/assets/1538057/15717804/ea088748-2828-11e6-9196-f1d40ce9c470.png)

**Comment by stefanpenner** [comment]
seems to be up for me: https://crates.io/

**Comment by klingtnet** [comment]
I'm still getting the application error.

**Comment by klingtnet** [comment]
[doc.crates.io](http://doc.crates.io/) works, seems to be only the package index.

**Comment by steveklabnik** [comment]
Can you refresh? Looks like it's up again

**Comment by steveklabnik** [comment]
.... and back down. maybe not.

**Comment by klingtnet** [comment]
Back online, nice work!

**Comment by klingtnet** [comment]
@steveklabnik I will close this issue, but could you please give a quick summary on what caused the outage?

**Comment by alexcrichton** [comment]
I've just restarted the app servers, still in my phone so I haven't had a
chance to investigate yet. Appears to be tons of timeouts though which are
probably related to db connections. I'll investigate when I get to a
computer

**Comment by steveklabnik** [comment]
@alexcrichton @brson figured it out. Safe flight <3

@klingtnet it will be on the internals thread.

**Comment by brson** [comment]
[Here's my description of what happened](https://users.rust-lang.org/t/crates-io-is-down-fixed/6060/6?u=brson).

A bunch of queries deadlocked in the postgres server bumping download statistics, locking tables and blocking connections. Running `heroku pg:killall` cleared the connections out and restored operation. It's not clear why they deadlocked.

**Comment by brson** [comment]
[Further info from Heroku support](https://users.rust-lang.org/t/crates-io-is-down-fixed/6060/7?u=brson).

**Comment by alexcrichton** [comment]
Oh wow, thanks for the investigation @brson! Looks like my "restart the dynos and pray" was timed around when you must have killed the connections, so I mistakenly thought it actually fixed something!
