### ISSUE TITLE
Strange syntax error reported on Firefox 52

### ISSUE THREAD

**Issue by lu-zero** [rust-lang/crates.io#3486]
**Describe the bug**
Reporting on behalf of Kostya

**To Reproduce**
go to https://crates.io

**Expected behavior**
The page loads

**Behavior**
The page does not completely load.

![bug](https://user-images.githubusercontent.com/239012/113506604-0fc8cf80-9546-11eb-9f18-92e296528e6e.png)

In the Javascript console those are the only messages:
```
unreachable code after return statement[Learn More]  vendor-65fd41a3e9118dcf9581c1ef3aea9fc7.js:4877
SyntaxError: invalid property id  vendor-65fd41a3e9118dcf9581c1ef3aea9fc7.js:5336:253
SyntaxError: missing ( before catch  cargo-53d2e3308e6686d065c43783cf13ecbe.js:8:502
```

**Desktop (please complete the following information):**
- OS: Linux 
- Browser: Firefox
- Version: 52

**Comment by Turbo87** [comment]
Firefox 52 has been released in 2017 and is not a supported browser anymore (see https://github.com/rust-lang/crates.io/blob/master/config/targets.js). You might want to consider updating your browser to avoid potential security issues from using such an old version.

**Comment by lu-zero** [comment]
I'm not the person impacted, but might be good to provide a different error message nonetheless.

**Comment by Turbo87** [comment]
the error message already states to "make sure [...] you are using an up-to-date browser" 🤔
