### ISSUE TITLE
The 'search' feature on crates.io works in an unexpected way.

### ISSUE THREAD

**Issue by daveloyall** [rust-lang/crates.io#3492]
**The bug**
The 'search' feature on crates.io works in an unexpected way.

**Steps to reproduce the behavior**
1. Go to crates.io
2. Click into the Seach box
3. Type 'wiki' and hit enter
4. See results which do not contain the word 'wiki' according to ctrl+f on the crate page.

**Expected behavior**
I am looking for wiki software.

**Comment by plaets** [comment]
Yeah, the search functionality is currently sort of broken, it's a known issue. See #1270, #2739 (also 3187 3450, 2746)
Although I'm not sure if I understand, for me, on the first page of the search results, only two crates don't have "wiki" neither in the name nor in the description. Both had "wiki" in the somewhere readme or in the tags though. It gets worse on the second page, but as I mentioned earlier - its a known issue.

**Comment by daveloyall** [comment]
Ah, ok.  I forgot to mention two things: 1. I was performing an exhaustive search, so I had to visit all the pages that had nothing but `google-*` crates, and 2. I sorted by 'last updated'.  I sounds as if the issue is well enough documented so, I'll close.  Thank you!
