### ISSUE TITLE
Add `.webp` as a supported media URL

### ISSUE THREAD

**Issue by blaind** [rust-lang/crates.io#3500]
**Is your feature request related to a problem? Please describe.**
Wanted to add an example of animated webp file in a crate README, but could not because `.webp` is not part of supported media urls. 

Had to convert to a gif. See https://crates.io/crates/webp-animation

**Describe the solution you'd like**
Add webp to `fn is_media_url` supported array at https://github.com/rust-lang/crates.io/blob/7844bf4c543859f351fd7d82d5a971c49e80ccec/src/render.rs#L174

**Describe alternatives you've considered**
Converted to the gif

**Additional context**
Here's an earlier version of the published crate (with webp file in README), which is nonfunctional: https://crates.io/crates/webp-animation/0.1.0

[WebP](https://en.wikipedia.org/wiki/WebP) is a newer more compact image format. For browser support, see https://www.caniuse.com/webp (Safari was not supporting webp for a long time earlier, but they have nowadays support as well from version 14. See https://stackoverflow.com/a/62594498)

**Comment by Turbo87** [comment]
@blaind can you open a PR for that change? :)
