### ISSUE TITLE
Policy: only allow libre packages

### ISSUE THREAD

**Issue by throwaway1037** [rust-lang/crates.io#3509]
At the moment, proprietary packages, ie. packages containing proprietary code and/or proprietary data, such as documentation, are allowed on [crates.io](https://crates.io).

I propose instating the policy that only libre packages, ie. only software licensed under a known free (libre) software license, and documentation licensed under a known free (libre) documentation license listed [here](https://gnu.org/licenses/license-list.html) be allowed on [crates.io](https://crates.io).

One ramification of proprietary packages currently being allowed is that entirely libre GNU+Linux distros, such as [Parabola GNU+Linux-libre](https://parabola.nu), may consider removing cargo integration with [crates.io](https://crates.io) from their packages of cargo.

Only allowing entirely free (libre) packages on [crates.io](https://crates.io) would also give developers peace of mind that they are not accidentally using anything proprietary, whereas at the moment, one has to manually check each package to see if it is entirely libre. This approach does not scale well, as transitive dependencies can quickly lead to a project having tens of packages included as dependencies.

**Comment by Turbo87** [comment]
such a large-scale change would need an RFC. you can find more information on that at https://github.com/rust-lang/rfcs. you're welcome to open such an RFC, until then I'll close the issue though since it's not actionable for us right now.
