### ISSUE TITLE
Statistics of actual Rust/Cargo version usage

### ISSUE THREAD

**Issue by kornelski** [rust-lang/crates.io#3511]
Would you be able to detect which Cargo version is communicating with crates.io and collect and publish such statistics?

I'm interested to know how popular are certain Rust versions, so that I can decide on MSRV which would be compatible with majority of Rust users.

For example, Android/PlayStore publishes breakdown of used Android versions:

![Android-platform-share-Feb-2018-chart](https://user-images.githubusercontent.com/72159/114266340-b9e4a380-99ed-11eb-82bd-69ce405841a9.png)

I would be helpful to have the same for Rust/Cargo.

**Comment by Turbo87** [comment]
I guess technically that should be possible, we'd just need someone to do the work 😉 

Since https://github.com/rust-lang/crates.io/issues/1198 is discussing a similar thing I'll close this issue here as a duplicate though :)
