### ISSUE TITLE
Failed to release crates on the created crates.io.

### ISSUE THREAD

**Issue by QiangHeisenberg** [rust-lang/crates.io#3526]
I built my own private crates.io service. All went well, but there was a problem I couldn't understand when releasing crates.

Server A: Install the correct and running crates.io.

Server B: Release crates on server B.

I set the .cargo/config.toml file on server A as follows:
```
[source.crates-io]
replace-with = 'mirror'
[source.mirror]
registry ="http://mirrors.xxxxx//rust/crates.io-index/"
[registries]
my-registry = {index = "https://aaa/bbb/ccc/crates.io-index.git"}
```

Set crates.io/.env:
```
export GIT_REPO_URL=https://aaa/bbb/ccc/crates.io-index.git
```

I set the .cargo/config.toml file on server B as follows:
```
[source.crates-io]
replace-with = 'mirror'
[source.mirror]
registry = "https://aaa/bbb/ccc/crates.io-index.git"
[registries]
my-registry = {index = "https://aaa/bbb/ccc/crates.io-index.git"}
```

Then I set the Cargo.toml setting in the want to publish the crates project:
```
publish = ["my-registry"]
```

Then I enter the following command:
```
cargo login cioUI9FY87i2ggrzSBYzvmxxxxxxTKQ8xd
git add.
git commit -m "test"
cargo publish --registry=my-registry
```

The result is this:
```
root@kwephisprd21023:/home/ok# cargo publish --registry=my-registry
    Updating `https://aaa/bbb/ccc/crates.io-index.git` index
Username for 'https://aaa/bbb/.com': l00xxxx
Password for 'https://aaa/bbb/':
   Packaging ok v1.7.0 (/home/ok)
   Verifying ok v1.7.0 (/home/ok)
   Compiling ok v1.7.0 (/home/ok/target/package/ok-1.7.0)
    Finished dev [unoptimized + debuginfo] target(s) in 8.30s
   Uploading ok v1.7.0 (/home/ok)
```

On my private crates.io, there is also a successful package.
However, there was no change in the my-registry = {index = "https://aaa/bbb/ccc/crates.io-index.git"} I set up.

This resulted in me not being able to download any crates.

In addition, I set the content of config.json on https://aaa/bbb/ccc/crates.io-index.git as follows: 

```
{
"dl": "http://crates.private.crates.io.com/api/crates",
"api": "http://crates.private.crates.io.com"
}
```

https://github.com/rust-lang/crates.io/blob/master/docs/CONTRIBUTING.md
https://doc.rust-lang.org/cargo/reference/registries.html#publishing-to-an-alternate-registry

I think it all seems to be correct, and I don't know if there is an internal code error.

**Comment by plaets** [comment]
Hi, first a formatting nitpick: try using \`\`\` instead of \` to preserve newlines, the issue will be easier to read for others.

My understanding is that you can publish a crate but you can't download it, right? What kind of error do you get when you try to download a crate? `-v` flag in cargo could be useful to display more errors (although I'm not sure about this case in particular).

In https://doc.rust-lang.org/cargo/reference/registries.html#publishing-to-an-alternate-registry, the example dl address is `https://crates.io/api/v1/crates`, yours is `http://crates.private.crates.io.com/api/crates`. Are you sure you don't need `v1` in the path? For ex. `http://crates.private.crates.io.com/api/v1/crates`

Not sure if this will be helpful, but maybe will point us somewhere. I have a crates.io set up with docker compose, in my case the `~/.cargo/config` looks like this:
```
[registries]
local = { index = "http://localhost:8888/git/index" }
```
Where localhost:8888 is the address of the crates.io backend

**Comment by QiangHeisenberg** [comment]
Thank you very much for your advice. My understanding is that if the upload is normal, the registries index should change. But now I have my uploaded crate on crate.io, but the registries index has not changed. Is that normal?

**Comment by QiangHeisenberg** [comment]
The information about crates cannot be updated in crates.io-index. Therefore, the following message is displayed when you download the package: error: no matching package named `xxxx` found

**Comment by plaets** [comment]
Are you sure the background worker is running? It looks like the backend silently fails if you try to publish a crate to a registry with a failed background worker.
On my test instance, if I set `GIT_REPO_URL` to an invalid path, the background worker fails with something like:
```
worker_1    | Booting runner
worker_1    | Using local uploader, crate files will be in the local_uploads directory
worker_1    | Cloning index
worker_1    | thread 'main' panicked at 'Failed to clone index: Error { code: -1, klass: 12, message: "failed to resolve address for aaa: No address associated with hostname" }', src/bin/background-worker.rs:38:46
worker_1    | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I can publish a crate but I can't download it, which sounds like the issue you are having.

Try checking the logs of the backend and the background worker.
If you did not setup the background worker, here is the relevant part of the docs:
https://github.com/rust-lang/crates.io/blob/master/docs/CONTRIBUTING.md#starting-the-server-and-the-frontend
```
Then start the background worker (which will process uploaded READMEs):
cargo run --bin background-worker
```

**Comment by QiangHeisenberg** [comment]
I don't know exactly why, but I set GIT_SSH_REPO_URL and GIT_SSH_KEY in .env to implement normal uploading. It could be an internal request from my company. I don't know exactly why, but it works. Thank you very much for your help. It has been a great inspiration to me.

**Comment by QiangHeisenberg** [comment]
This problem has been solved, thank you.
