### ISSUE TITLE
Readme.md not found

### ISSUE THREAD

**Issue by Timmmm** [rust-lang/crates.io#3536]
Crates.io appears to only look for `README.md` (all caps) whereas I have `Readme.md`, which Github is fine with (there's no need to shout). That leads to a weird error saying there's no readme on Crates.io while Github shows it fine.

Example: https://crates.io/crates/dull

If a case insensitive search is really hard for some reason I would just check `README.md`, `Readme.md`, `readme.md` and maybe `ReadMe.md` if you like.

**Comment by Turbo87** [comment]
you can see at https://doc.rust-lang.org/cargo/reference/manifest.html#the-readme-field the we currently only look for the uppercase version (`README.md`). if you want to use something else you can use the `readme` field to override the defaults, or implement a PR for crates.io to support more options.

**Comment by Timmmm** [comment]
[Here's the code that implements it](https://github.com/rust-lang/cargo/blob/master/src/cargo/util/toml/mod.rs#L1576):

```rust
const DEFAULT_README_FILES: [&str; 3] = ["README.md", "README.txt", "README"];

/// Checks if a file with any of the default README file names exists in the package root.
/// If so, returns a `String` representing that name.
fn default_readme_from_package_root(package_root: &Path) -> Option<String> {
    for &readme_filename in DEFAULT_README_FILES.iter() {
        if package_root.join(readme_filename).is_file() {
            return Some(readme_filename.to_string());
        }
    }

    None
}
```

**Comment by hi-rustin** [comment]
I don't think we can do it in crates.io, @Turbo87  What do you think? It looks like we can't do it if cargo doesn't adapt it?

**Comment by Turbo87** [comment]
yeah, it would have to be implemented on both sides. given how easy it is to just set `readme` field in the `Cargo.toml` file instead, I'm not sure if it's worth it to implement it.

since the majority of the work needs to happen on the cargo side I'm going to close this issue. feel free to reopen on the `cargo` repo.
