### ISSUE TITLE
Drop requests in the backend if they expire before being assigned a server thread

### ISSUE THREAD

**Issue by jtgeibel** [rust-lang/crates.io#3537]
While analyzing the logs from our outage on 2021-04-18, I see that once the database was restored we processed a large backlog of expired requests. Even though the Heroku router drops connections after a 30 second timeout, these requests were still queued and eventually assigned a server thread for processing.

When assigning a request to a server thread, we should verify one or more of the following, to avoid processing requests that we can no longer respond to:

* Check that the socket is still open, dropping the request if it is not.
* Check the current response time. If the request is older than say 25 seconds, respond with an error (if the socket is still open).
* Put a cap on the number of requests that can be queued by the backend at one time.

**Comment by Turbo87** [comment]
We've migrated from conduit to axum, so this is no longer relevant AFAICT
