### ISSUE TITLE
Download graph: "Other" is shifted by one day

### ISSUE THREAD

**Issue by troplin** [rust-lang/crates.io#354]
The numbers of the "Other" category in the download graph is not in sync with the rest of the graph. It seems to be one day off.
For example, [netio 0.1](https://crates.io/crates/netio/0.1.0) was published on march 30, the graph shows 2 downloads on that day if only that version is rendered.
But if you switch to the [version-unspecific page](https://crates.io/crates/netio), suddenly there are 2 downloads on march 29 in the "Others" category.

**Comment by alexcrichton** [comment]
Hm this may actually just be a time zone thing. I don't think crates.io has much handling of time zones specifically...

**Comment by troplin** [comment]
Not sure about this.
If time zones are not handled, it should be consistent for all curves, not different for the "Other".

Currently, if I upload a new version, the graph changes completely (also for the past), because now a new version is counted in the "Other" category. All the values from that version are shifted 1 day to the left.

You can also see the effect if you download all versions of a crate at once. They don't appear all on the same day in the graph, there's a spike on the current day for the 5 most recent versions and another spike one the past day for the "Others" category. This is not so visible for crates with high numbers.

**Comment by alexcrichton** [comment]
Oh hm, definitely sounds odd!

**Comment by carols10cents** [comment]
Just tried to reproduce locally by publishing 6 versions of a crate and downloading all of them (all downloads done today), and I'm seeing all of the downloads line up on today's date:

<img width="939" alt="downloads graph screenshot" src="https://user-images.githubusercontent.com/193874/68975127-66eaca80-07c0-11ea-8abe-345db5030433.png">

I think we fixed this somewhere along the way. Please reopen if I'm missing something!
