### ISSUE TITLE
Package libtimew is shown on crates.io without a link to its homepage or source page

### ISSUE THREAD

**Issue by yurivict** [rust-lang/crates.io#3553]
URL: https://crates.io/crates/libtimew

See the screenshot:
![image](https://user-images.githubusercontent.com/271906/115977983-729ffc00-a531-11eb-8941-18200ef91c61.png)

How can people know where does it come from?

**Comment by plaets** [comment]
That's because the author did not specify the hompage or repository link in the manifest
https://github.com/woodworker/libtimew/blob/master/Cargo.toml - missing "homepage" and "repository" link
All Cargo.toml keys for reference:
https://doc.rust-lang.org/cargo/reference/manifest.html
