### ISSUE TITLE
Improvements to the release phase

### ISSUE THREAD

**Issue by jtgeibel** [rust-lang/crates.io#3571]
There are a few additional improvements we should make to our release phase:

- [ ] Refactor `Config` and `App::new()` logic so that it is possible to check all environment configuration data without actually booting the app. If the server would panic due to bad configuration, then the release command should fail to prevent the running (and correctly configured) apps from restarting.
- [ ] Check for running migrations if a read-only connection to the database is available. This will likely require upstream changes in `migration_macros` to make `any_pending_migrations()` public.
  - Currently if the database is in read-only mode then we do not attempt to run migrations as that would fail the release.

**Comment by Turbo87** [comment]
@jtgeibel would it make sense to migrate our config to use https://crates.io/crates/figment? looks like rocket.rs is using that for config soon

**Comment by hi-rustin** [comment]
@rustbot claim

I want to help improve it!

**Comment by hi-rustin** [comment]
>     * then the release command

@jtgeibel  What does the release command mean here? Do we have documentation for the current release process? Can only team members access these documents? Because I can't seem to find the documentation in the repository.

**Comment by hi-rustin** [comment]
Since I'm not very familiar with the release process, I'm unassigning myself for now. Maybe I can help improve it later when I am familiar with the process.
