### ISSUE TITLE
README.md is not found even present

### ISSUE THREAD

**Issue by arniu** [rust-lang/crates.io#3575]
Go to <https://crates.io/crates/glob>, it shows:

> glob v0.3.0 appears to have no README.md file

**Comment by JohnTitor** [comment]
This isn't a bug, glob v0.3.0 was published March 7th, 2019 but at that point, cargo didn't specify the default value of the `readme` field on Cargo.toml. That feature implemented by https://github.com/rust-lang/cargo/pull/8277 (since Jun 10th, 2020, v0.47.0).
