### ISSUE TITLE
Suggestion to alleviate squatting problem: public user reviews of crates

### ISSUE THREAD

**Issue by rodrigocfd** [rust-lang/crates.io#3629]
We all know there is a problem with [squatting](https://en.wikipedia.org/wiki/Cybersquatting) in [crates.io](https://crates.io/). This topic is being discussed time and again, and some attempts have been made to ease this problem, like #58, #624 and #1340.

Instead of creating rules to restrict the crate uploading in some way – which have found no consensus so far –, I propose the creation of an user review system similar to the one in the Android Play Store:

![Imgur](https://i.imgur.com/b4pfxh5.png)

I believe peer review could help to identify bad crates, and it would also be a way to identify *good* crates.

One could argue that this won't solve the issue, but simply move it from one place to another: squatters will now create fake profiles to generate fake reviews. But even in this case, it's *a lot* more work, so I believe it's worth. Anyway, if user pages show the crates reviewed by the user, it would help a little bit.

I understand this won't solve the problem completely, I just hope it can alleviate it.

**Comment by carols10cents** [comment]
For peer code review, please see the [cargo crev project](https://web.crev.dev/rust-reviews/).

Having comments directly on crates.io would significantly increase the moderation burden, which is not something the all-volunteer crates.io and moderation teams are interested in taking on right now.

In any case, this would need to go through the [Rust RFC process](https://github.com/rust-lang/rfcs) first to build a design and policies with the community.

Similarly to cargo crev, this could be built unofficially on a separate site from crates.io.

Also see these related issues:

- https://github.com/rust-lang/crates.io/issues/452
- https://github.com/rust-lang/crates.io/issues/1820

**Comment by najamelan** [comment]
@rodrigocfd I feel there is a misconception here of what squatting is about. Quality of crates indeed varies, and that's unavoidable. However, when you need a lib for a certain purpose, it's not that hard to weed it out. If it has good guide level docs, API docs, tests etc. You have a candidate looking into. The rest you can skip most of the time.

However squatting is about reserving names without ever using them. A bit like domain name squatting. Having a short memorable name for your library that you are serious and ambitious about is definitely desirable. 

The problem isn't identifying those crates, rather that crates is not namespaced and it is first come first serve. You can also namespace yourself by prefixing your crate names like user_library.

There is also lib.rs which uses a different algorithm for search results and evaluates crates in terms of documentation, number of dependent crates and so on to float quality crates to the top.

As for crates.io, a useful feature might be to automatically pull stars from github, gitlab, bitbucket and other git hosting services, as that is already a way users indicate a basic feedback on usefulness of a project.

**Comment by rodrigocfd** [comment]
> As for crates.io, a useful feature might be to automatically pull stars from github, gitlab, bitbucket and other git hosting services, as that is already a way users indicate a basic feedback on usefulness of a project.

That's a great idea. Is there any ticket discussing this?

**Comment by carols10cents** [comment]
We don't require any repository URL, and we don't require that it's any particular service (it could be self hosted for example), so this feature would exclude some crates.

This issue is relevant: https://github.com/rust-lang/crates.io/issues/786

**Comment by dravenk** [comment]
Under this evaluation system, Windows is undoubtedly the best system because it is easy to use for the vast majority of people, and Linux would be a terrible system.Such comments are not necessarily useful for linux fans.  I actually use mostly Mac and Linux. It is also possible that the comments posted by some professional developers will be harsh to the majority of ordinary users.
