### ISSUE TITLE
Only clone the master branch of the index during background worker startup

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/crates.io#3630]
The background worker is cloning the full index repository every time it starts up, including the historical snapshots. We should only clone the master branch to speed up booting the background worker.

**Comment by wangkirin** [comment]
Hi @pietroalbini ， I‘ve test in my machine that  it seems  the  background worker won't clone all the bracnhes.  The `git2` lib will clone the default branch.  We can see from the source code of `git2`:

https://docs.rs/git2/0.13.20/src/git2/build.rs.html#168

**Comment by pietroalbini** [comment]
@wangkirin hmm, it seems like it's indeed cloning all the branches, the git repository downloaded by the background worker on my machine weights 1.3 GB, which is too much for just the master branch. The documentation you linked is for checking out a branch after the whole repo was downloaded, not to decide what to download.
