### ISSUE TITLE
Unexpected API break: `authors` link is gone

### ISSUE THREAD

**Issue by Shnatsel** [rust-lang/crates.io#3640]
The `authors` link has been removed from API responses in this PR: https://github.com/rust-lang/crates.io/pull/3549/files#diff-7097826b14751e17e4c05c8e260d7d67776bcd35b0ce6537638ed0dac16b592cR624-R737

This caused e.g. all consumers of `crates_io_api` crate to break: https://github.com/theduke/crates_io_api/issues/30 This particular crate has issued a patch, but it still requires rebuilding and redeploying anything that interacts with the crates.io API.

Thanks to Pietro Albini for pinning down the root cause.

**Comment by hi-rustin** [comment]
I will try to revert it.
