### ISSUE TITLE
max_upload_size not used

### ISSUE THREAD

**Issue by FXTi** [rust-lang/crates.io#3649]
**Describe the bug**
According to https://github.com/rust-lang/crates.io/issues/195, `max_upload_size` can be set in Cargo.toml to specify crate's max size. However, in https://github.com/rust-lang/crates.io/commit/94e3e1bb97e3c78cbbaa45eef49da629ffcc53b5, which seems like some kind of daily refactor commit, this field is set to `None`.

**To Reproduce**
Set `max_upload_size` to some value larger than 10MiB and upload a crate bigger than 10MiB.

**Expected behavior**
Crate upload normally.

**Question**
Actually, I' m not sure if this is on purpose. If team don't want this filed to be set, this field should just be removed.

**Comment by Turbo87** [comment]
> `max_upload_size` can be set in Cargo.toml to specify crate's max size

I'm not sure where in #195 you've read that, but I don't think that's how it works. 

The `max_upload_size` column in the database is meant for increasing the regular 10MB upload limit on a case-by-case basis. The column value is manually adjusted in the database, which is also why it's usually just set to `None` for new crates.

**Comment by pietroalbini** [comment]
If you need your limit to be increased please email help@crates.io.

**Comment by carols10cents** [comment]
`max_upload_size` is set manually in the database on a per-crate basis after requesting an increase over the default limit. `max_upload_size` is used [during publish](https://github.com/rust-lang/crates.io/blob/cd37d9d524d4866ac3c6459c9cd43d8cdfbabe38/src/controllers/krate/publish.rs#L141-L146) and should not be removed.
