### ISSUE TITLE
Improve performance of the reverse dependencies endpoint

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/crates.io#3655]
Me and Justin spent some time a couple days ago trying to figure out why the reverse dependencies endpoint is so slow for crates with a large number of reverse dependencies. [This is the `EXPLAIN ANALYZE` of that query](https://explain.dalibo.com/plan/HSX).

The goal of [the query](https://github.com/rust-lang/crates.io/blob/f70ae1efc238dc30fb8882a4bfde8eed298871f5/src/models/krate_reverse_dependencies.sql) is to return all crates whose *last version* depends on the current crate. As the latest version is not stored anywhere the query is doing a subquery that sorts all the versions of each crate by their semver, which is really slow.

We should denormalize the latest version ID (semver-wise) in the crates table, and change the query to remove the subquery. After removing the subquery the query should be small enough to be converted to Diesel. Ideally denormalizing the latest version  ID and updating the query should be done in separate PRs.

**Comment by pietroalbini** [comment]
Note that this is practically reversing what we did in #592, but this is now starting to actually impact our performance.

**Comment by jyn514** [comment]
Is it possible to use an index instead of a column? That would avoid issues with the column getting out of sync.

**Comment by pietroalbini** [comment]
I'm pretty sure that query is too complex to go on an index. A materialized view *might* work depending on how long it takes for it to update.

**Comment by pietroalbini** [comment]
Yeah, played around with it and indexes don't seem to help much. This query though takes around 3.2s [(explain)](https://explain.dalibo.com/plan/4jz) on the primary db:

```sql
SELECT DISTINCT ON (crate_id) crate_id, id
FROM versions
WHERE NOT yanked
ORDER BY crate_id, to_semver_no_prerelease(num) DESC NULLS LAST;
```

We could turn it into a materialized view we refresh every time a new crate is published/yanked/unyanked/deleted, but I'm worried its speed will continue to decrease as time goes by. Another option to investigate would be to store the parsed semver in the database, without calling `to_semver_no_prerelease` in the database which is just slow.

**Comment by eth3lbert** [comment]
I'm happy to report that we've made significant progress on this issue. After applying #8737 , the average query execution time for serde has been reduced from 2.5s to 500ms in production.
