### ISSUE TITLE
Can not log in with Github

### ISSUE THREAD

**Issue by piavgh** [rust-lang/crates.io#3666]
**Describe the bug**
After clicking on the Log in with Github button, a new window appears and then disappears immediately.
After that, I am still not logged in

**To Reproduce**
1. Go to crates.io
2. Click on Log in with Github button
3. Wait until the new window disappears

**Expected behavior**

I should be able to log in with Github

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS BigSur 11.4
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 90.0.4430.212 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

**Additional context**
It works fine on Firefox. I was able to use Firefox to create my account with "Log in with Github".
Then, after my account is created via Firefox, I was able to log in on Chrome

**Comment by Turbo87** [comment]
hmm... I'm not sure what went wrong there. Unfortunately, I can't seem to reproduce it like this 😞

**Comment by wangkirin** [comment]
I cannot reproduce it  either, it is still  appears in your device?
