### ISSUE TITLE
crates.io isn't serving the index; cargo gets it from github.com

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#373]
I'm trying to make it easier for people to set up mirrors of crates.io-- right now I'm building off of [this bare minimum mirror](https://gmjosack.github.io/posts/dissecting-cratesio-minimum-mirror/) blog post, which goes over how to set up a *local* index mirror of https://github.com/rust-lang/crates.io-index.

But what if I wanted to run a read-only mirror on heroku? I know crates.io runs on heroku right now, but I give up-- I cannot for the life of me figure out how crates.io has a checkout of the index!!!

I see the [`scripts/init-local-index.sh`](https://github.com/rust-lang/crates.io/blob/master/script/init-local-index.sh) script that appears to just be for working on the backend of crates.io locally; it was created way later than crates.io existed.

I see [this code at the start of `src/bin/server.rs`](https://github.com/rust-lang/crates.io/blob/master/src/bin/server.rs#L23-L36) that looks like if the checkout dir isn't a git repository, delete that dir, recreate it, and fetch the `GIT_REPO_URL` into that directory.

But I don't see how either of these two could work on heroku, since it's an [ephemeral file system](https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem) and you can't count on files you've written being there later.

When I try to use, say, `tmp/index-co` as my `GIT_REPO_CHECKOUT` value (with `GIT_REPO_URL=https://github.com/rust-lang/crates.io-index.git`), I get a 404 from my mirror app when I point cargo at my mirror and cargo tries to update the registry.

So how do I get a registry available on heroku??? What am I missing? Thank you so much <3

**Comment by alexcrichton** [comment]
That information about heroku is... interesting! The bit at the top of `server.rs` I believe is indeed where the index is checked out, which I took as each dyno will have a checkout of the repo. If that doesn't work then I'm not really sure what's happening behind the scenes...

**Comment by carols10cents** [comment]
May I ask what crates.io has its GIT_REPO_CHECKOUT set to?

**Comment by carols10cents** [comment]
So I got more confused because I found [this part of the code that only seems to serve the git index routes in development mode](https://github.com/rust-lang/crates.io/blob/master/src/lib.rs#L123-L129), and having `HEROKU=1` puts the app in production mode, so I couldn't figure out how the index was being served at all!!!!

Then @shepmaster said "What if it's being served directly from github?" and sure enough, if I get rid of any index configs in `.cargo/config` and do a `cargo build --verbose`, I see:

```
$ cargo build --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
```

instead of what I expected, which was `https://crates.io/git/index`. And [`cargo` has its default registry URL set to github.com](https://github.com/rust-lang/cargo/blob/master/src/cargo/sources/registry.rs#L182)!

So the index *isn't* being served from crates.io!

For a mirror/internal crates server, though, I think the server in this codebase *should* serve the index, even in production mode. Crates.io could also serve the index so that this codebase doesn't have to special case the deployment to crates.io, but I can see not wanting to change cargo to use it since it'll change everyone's `~/.cargo/registry/` directory names from `github.com` to `crates.io` and that might be confusing/break things.

I was able to get an app on heroku to serve the index by removing the `if env == Env::Development` condition and adding creation of the `.git/git-daemon-export-ok` file to the code in `server.rs` that creates the checkout -- pull request coming in a minute. 

I'm wondering what the reasoning was behind this though-- to offload some requests to crates.io onto github.com? [The cargo commit that sets the `DEFAULT` registry to github.com](https://github.com/rust-lang/cargo/commit/0f9701704fe5384aaa53186a2b30857bfa2a3422) has this in its message: 

> Try to purge the word "registry" as much as possible in favor of just referring
to crates.io as "crates.io". This also enables the default index as being the
official rust-lang crates.io index.

... but doesn't *actually* refer to crates.io, it refers to github.com. 

So what is the actual intent? Would you want to change cargo to have the `DEFAULT` registry be https://crates.io/git/index?

**Comment by dwijnand** [comment]
Is this no longer the case?
