### ISSUE TITLE
Add note to "Account Settings" page about how to change Name/Github Username

### ISSUE THREAD

**Issue by lily-mara** [rust-lang/crates.io#3743]
**Is your feature request related to a problem? Please describe.**
I recently changed my name and github username. When I looked at the (already logged-in) account settings page for my crates.io account (https://crates.io/me) I was disappointed to see that the "Name" and "Github Username" fields were non-editable. I thought that this meant there was no way for me to change these fields. With other services, this sometimes means that oAuth is broken due to the changed github username. I opened a private browser window, re-logged-in to crates.io with my updated github account, and was happy to see that my information was automatically updated after the login. This is great! It's very rare for services to accept new name/username information from oAuth providers, so I want to first commend you for doing that ❤️. That being said, it was scary when I saw that I had no way to edit the information on my settings page, and I had no way to know that it would work correctly after a fresh login.

**Describe the solution you'd like**
I would like a small note added to the settings page along the lines of "To update your name and github username, change them in your github profile, then sign out and login again to crates.io. You cannot change these settings directly on crates.io, but we accept whatever values come from github."

**Describe alternatives you've considered**
I think this is the most reasonable solution.

**Comment by hi-rustin** [comment]
I am working on this.
