### ISSUE TITLE
I cannot cargo check/build due to mistaken yet removed dependency

### ISSUE THREAD

**Issue by philip78yahoo** [rust-lang/crates.io#3756]
**Describe the bug**
I am trying to cargo check but I get an error.  However the error is on a mistaken dependency which I have removed.  I am trying to use shuffle crate which has a dependency on bitvec.  I had a bitvec dependency of version 0.15 but I should have used 0.22.3.  I changed my Cargo.toml to use 0.22.3 but error keeps coming ...

error: failed to select a version for the requirement `bitvec = "^0.15"`
candidate versions found which didn't match: 0.22.3, 0.22.1, 0.22.0, ...
location searched: crates.io index
required by package `shuffle v0.1.3`
    ... which is depended on by `dominoes_mex_train5 v0.2.1 (/home/phil8gig/Documents/git/dominoes_mexTrain_rust5)`

I have tried cargo clean, cargo update, deleting ~/.cargo/registry, deleting my original directory, renaming my project, deleting ~/.local, ~/.config ~/.cargo/.package-cache

**To Reproduce**
1. Add to your Cargo.toml 
[dependencies]
bitvec = "0.15"
2. Attempt cargo check, see error
3. Edit Cargo.toml to remove the ... bitvec = "0.15"
4. Attempt cargo check, still see error

**Expected behavior**
I expect a dependecy removed from Cargo.toml to not show up in an attempt to cargo build.

**Desktop (please complete the following information):**
 - OS: centos7
 - Cargo: 1.53
 - Rustup: 1.24.3 (ce5817a94 2021-05-31) 

**Additional context**
My Cargo.toml:
[package]
name = "dominoes_mex_train5"
version = "0.2.1"
authors = ["phil"]
edition = "2018"

#----- See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
shuffle = "0.1.3"

**Comment by jtgeibel** [comment]
Have you tried deleting `Cargo.lock`?

Moving to the cargo repo, as this is not an issue with crates.io.

**Comment by jtgeibel** [comment]
I don't seem to have the ability to transfer to that repo. It might be better to ask for help on Discord or Zulip, and then opening an issue against cargo if there is some actionable improvement to the error message. Closing this issue.
