### ISSUE TITLE
Is the crates.io policies page outdated when it refers to "Mozilla Legal"?

### ISSUE THREAD

**Issue by ericseppanen** [rust-lang/crates.io#3779]
The [crates.io policies page](https://crates.io/policies) says:
>  For issues such as DMCA violations, trademark and copyright infringement, Crates.io will respect Mozilla Legal’s decisions with regards to content that is hosted.

Should this refer to the Rust Foundation instead?

The Foundation [FAQ](https://github.com/rust-lang/foundation-faq-2020/blob/main/FAQ.md) states that legal advice *"such as on how to handle DMCAs for the crates.io team"* is in-scope.

**Comment by Turbo87** [comment]
hi @ericseppanen, and thanks for the reminder. we are aware of the outdated information on that page and are working with the foundation to update it, but as with everything involving legal stuff it takes a bit longer to get correct 😅 

we will update it as soon as we know what the new content should be :)
