### ISSUE TITLE
`license-file` in Cargo.toml results in "non-standard" for crate licence

### ISSUE THREAD

**Issue by markmandel** [rust-lang/crates.io#3784]
**Describe the bug**

We are using `license-file` in our Cargo.toml to point to our local LICENSE file (which is Apache 2.0). ([source](https://github.com/googleforgames/quilkin/blob/f6e5ec15c3073435a5814b4b95027cd404a2ec5e/Cargo.toml#L24))

This resulted in crates.io reporting that we had a "non-standard" licence. This is being worked around by using the `license` field instead, but it would be lovely if it could (magically?) look at the file to determine the license.

**To Reproduce**

Create a Cargo.toml using `license-file` rather than `license` and publish it to crates.io

**Expected behavior**

It reports the correct licence that is in the licence file.

**Screenshots**

![image](https://user-images.githubusercontent.com/298370/125856154-3c02513a-0a8e-4b48-a927-ce2798e3ee8a.png)

**Desktop:**
 - OS: Linux/Debian
 - Browser Chrome
 - Version Version 91.0.4472.114 (Official Build) (64-bit)

**Additional context**
None that I can think of, but happy to know if I messed something up on my end!

**Comment by hi-rustin** [comment]
crates.io interprets the `license` field as an [SPDX 2.1 license expression][spdx-2.1-license-expressions]. The name must be a known licensefrom the [SPDX license list 3.11][spdx-license-list-3.11]. 
Parentheses are not currently supported. See the [SPDX site] for more information.

I understand that the `license-file` just specifies the file path, crates.io doesn't seem to handle the license-file yet, and if we need to parse the file, what do we do if we encounter a non-standard license? Maybe it would be better if we keep only read the `license` field?

[spdx-2.1-license-expressions]: https://spdx.org/spdx-specification-21-web-version#h.jxpfx0ykyb60
[spdx-license-list-3.11]: https://github.com/spdx/license-list-data/tree/v3.11
[SPDX site]: https://spdx.org/license-list

**Comment by carols10cents** [comment]
Yes, this feature is working as designed. I don't think we're going to add a license file parser/license recognizer.
