### ISSUE TITLE
Crates.io template

### ISSUE THREAD

**Issue by Dania99dev** [rust-lang/crates.io#3787]
Website's template seems a bit outdated.
Will it be updated? I am a front-end developer, maybe I can contribute in coding the new template?

**Comment by Dania99dev** [comment]
s

**Comment by hi-rustin** [comment]
Which template are you referring to?

**Comment by Dania99dev** [comment]
> 
> 
> Which template are you referring to?

crates.io website template

**Comment by carols10cents** [comment]
Do you mean the overall design of the website? That is quite a large project that requires significant community involvement. There was some coordination around the design of all Rust web properties; I haven't heard much about it lately. Please check the web presence room on Discord.
