### ISSUE TITLE
Dependent crates link not shown for crates without reverse dependencies

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/crates.io#379]
The dependent crates link is not shown for crates without reverse dependencies. 

I found this confusing. 

Maybe instead of removing the link we could add some text stating that the crate has no reverse dependencies: 

> (no dependent crates)

**Comment by carols10cents** [comment]
This will involve adding an `else` to [this `if`](https://github.com/rust-lang/crates.io/blob/master/app/templates/crate/version.hbs#L162-L168) and displaying the text "(No dependent crates)" instead of the link.

**Comment by Arnavion** [comment]
This can be closed right? (It wasn't autoclosed because the PR commit message didn't have a `Fixes ...`)

**Comment by carols10cents** [comment]
Whoops, you are correct! Thank you!!
