### ISSUE TITLE
Also list transitive dependencies

### ISSUE THREAD

**Issue by cessen** [rust-lang/crates.io#3815]
It is sometimes useful to know how many/what dependencies a crate has.  For example:

- If you're trying to keep your project light, you may prefer a crate with fewer dependencies even if it's less featureful or popular.
- If you want or need to audit all dependencies of your project, you will likely prefer crates with fewer dependencies (all other things being equal) to reduce that workload.
- In some cases, the full dependency tree can provide some indication of how aware the author is of the code in their own crate, and how crafted vs tossed-together it is.  For example, if it indirectly includes multiple async runtimes (not as alternatives, but always included), etc.
- Some people just prefer crates without a large number of dependencies.

Right now crates.io only lists *direct* dependencies, which in many cases gives a misleading picture of the total number of dependencies a crate has--particularly when there is a very deep dependency tree.  Sometimes a crate can appear to have fewer dependencies than another, while actually having an order of magnitude more.

Listing not only direct dependencies but also *transitive* dependencies would make it much easier to evaluate crates on this basis.  It's certainly not the only metric for choosing a crate (and definitely not the most important), but it is a useful one in many circumstances.

## Alternatives

- Just list the *number* of total dependencies (including transitive) of a crate.  For many use-cases, this is the key piece of information.  Although it doesn't allow conveniently checking *what* dependencies are pulled in.
- List the total size (in bytes/kilobytes/etc.) of all dependencies, including transitive.  For people trying to keep their projects light, or who need to audit code, this metric may be more important in practice.  This may be useful to list even if the dependencies or the count are also listed.
- Do nothing.  By recursively browsing dependencies on crates.io, users can get some sense of the total number of dependencies, although it's inconvenient and error-prone.  Users can also add the crate to their Cargo.toml and use `cargo tree` to list the full dependency tree, although this is also inconvenient--particularly when just browsing for crates--and requires downloading the crate.

**Comment by Turbo87** [comment]
sounds like an interesting idea, but it could be a bit tricky to implement in a way that performs reasonably well. @cessen would you be interested in trying to implement it?

**Comment by cessen** [comment]
I have very little experience with web-facing software, so I'm not at all confident approaching it alone.  But if I can get some guidance, I'd be happy to take a crack when I have the time.

It might be a while, though--I don't have a whole lot of spare time that isn't already going towards other projects right now.  So please don't wait on me!

**Comment by est31** [comment]
There has been an implementation attempt in #1455. It's also been recently brought up on the [rust reddit](https://www.reddit.com/r/rust/comments/oxpklj/list_transitive_dependencies_of_a_crate/).

**Comment by EriKWDev** [comment]
+1 for this. I would personally be fine with just the number of dependencies (and transitive) in the initial search result list. 

Not only would this help me find the crate with the minimum amount of dependencies, but it might perhaps incentivize some developers to depend on less crates.

**Comment by Turbo87** [comment]
The only way this would work reasonably well is if we ran `cargo` on the server for each such request and have it calculate the dependency graph. This seems like a performance nightmare though and since the dependency graph also depends on the enabled features it wouldn't necessarily be correct anyway.

Since this is unlikely to get implemented I will close this issue.

**Comment by Eh2406** [comment]
> The only way this would work reasonably well ...

For completeness there is another alternative. If there were a cargo resolver compatible algorithm implemented as a standalone library that could be compiled to wasm, then it could be calculated client-side. I am hoping this can be a benefit of the work on using PubGrub for cargo. (cc [pubgrub](https://github.com/pubgrub-rs/pubgrub) and [semver-pubgrub](https://github.com/pubgrub-rs/semver-pubgrub)) but that work is going slowly enough that closing this issue seems reasonable.
