### ISSUE TITLE
crates.io javascript syntax error in the Palemoon browser.

### ISSUE THREAD

**Issue by djarb** [rust-lang/crates.io#3833]
**Describe the bug**
In the [Palemoon browser](https://www.palemoon.org/) the crates.io pages fail to load due to JavaScript errors. Specifically, the errors that appear in the console are:

```
SyntaxError: expected expression, got '?' vendor-dab0f77c35abe2b491f0bbea05ea9337.js:1665:242
ReferenceError: require is not defined chunk.143.58c71dec755246d1b37a.js:2:1376
SyntaxError: expected expression, got '?' cargo-311b29590dbf22db90dcef8b441f058a.js:236:97
```

**To Reproduce**
1. Install Palemoon
2. Visit https://crates.io/
3. See error
4. ctrl-shift-k to see the console

**Expected behavior**
I expected such an important site to transpile their JavaScript to the es5 standard, which is supported even in niche browsers.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Palemoon
 - Version: 29.1.1

**Additional context**
Palemoon is definitely a niche browser, but it's also a browser that appeals to people who like security or are tired of Firefox removing features and customization options. Particularly for Linux users, Palemoon and other alternative browsers are becoming a more desirable choice which ought to be supported.

**Comment by Turbo87** [comment]
> I expected such an important site to transpile their JavaScript to the es5 standard

an ES5 build results in significantly larger files and that would make the site significantly slower for everyone, not just for Palemoon users. you can find the list of browsers that we support at https://github.com/rust-lang/crates.io/blob/master/config/targets.js
