### ISSUE TITLE
Stats: Ignore downloads made by bots

### ISSUE THREAD

**Issue by pczarn** [rust-lang/crates.io#386]
Crates are often downloaded by crater, travis and other automatic tools. This doesn't reflect real use. Beginners might be confused by rising download counts on their newly uploaded crates.

It's better to ignore these downloads. Alternatively, display separate stats categories for both kinds of downloads.

**Comment by tshepang** [comment]
What about automatic dependencies (i.e. those not listed in Cargo.toml)?

**Comment by carols10cents** [comment]
I don't know of a way we can reliably detect the difference between a legitimate download and bot downloads. In addition to download numbers *inflated* by bots, download numbers are likely also *deflated* by caches. The download number is always going to be inherently fuzzy, so I'm giving this a close.

**Comment by pczarn** [comment]
To detect the difference, bots could be modified to say they're bots while communicating with crates.io. However, you may be right about caches.

**Comment by tshepang** [comment]
It is better to have a lower number (caches) than an inflated number (bots), so having bots say they are bots is one thing, but even better would be if cargo can detect if it's being run manually.

**Comment by Mubelotix** [comment]
It's necessary

**Comment by jhg** [comment]
Maybe downloads done by bots are legitimate in some cases and "manual" not legitimate.

One can automate downloads from own machines. But also an automated release (with cache) can download it and I don't download it manually as it's done by the CD. I don't know if that is less real usage case than if I build and publish from my machine.

I'm not sure if it's possible to know what case is each request. It's true if requests identify itself for not count in that case it's not problem as the requester inform it's ok. Or show it separately.

All is only IMHO.
