### ISSUE TITLE
Frequent misclicks to "exact match" link, when searching crates

### ISSUE THREAD

**Issue by pot876** [rust-lang/crates.io#3910]
it would be nice to reduce link area, or remove link

**Comment by Turbo87** [comment]
can you elaborate a bit more? I'm not sure I understand what you mean

**Comment by pot876** [comment]
my scenario using crates.io web page:
1. fill search bar
2. click "sort by"
3. click "recent downloads" of dropped list
then i want list to be hidden so i make click on first free area and it is "<h1>Exact Match</h1>" wrapped with link expanding whole parent width

**Comment by pot876** [comment]
my scenario using crates.io web page:
1. fill search bar
2. click "sort by"
3. click "recent downloads" of dropped list
then i want list to be hidden so i make click on first free area and it is "\<h1\>Exact Match\</h1\>" wrapped with link and expanding whole parent width
