### ISSUE TITLE
Squatting?

### ISSUE THREAD

**Issue by qtfkwk** [rust-lang/crates.io#3925]
**Describe the bug**
No idea how actually prevalent squatting is on crates.io... but definitely it's enough that I find them regularly.

**To Reproduce**
Today I noticed [this specimen](https://crates.io/users/swmon) with about 100 packages with common words reserved.

**Expected behavior**
Please explain if this is by design... is there an official policy?
Would be possible to remove such worthless reservations so they can be used?
One way to find them would be that they haven't been updated in years, have no Github project or an empty one, no README, single version, ...

**Comment by Turbo87** [comment]
the current policy is published at https://crates.io/policies#package-ownership
