### ISSUE TITLE
Option to display downloads chart as percentage

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/crates.io#393]
The current chart is good for determining how absolute number of downloads has changed over time. It might also be helpful to display version downloads as a percent to see version adoption over time. [An example of a similar chart for Android version adoption:](https://mixpanel.com/trends/#report/android_os_adoption)

<img width="1084" alt="screen shot 2016-08-01 at 10 40 42 pm" src="https://cloud.githubusercontent.com/assets/416575/17315391/0eda34f0-5839-11e6-9f27-5ec2a267071a.png">

**Comment by frewsxcv** [comment]
Assuming we're using Google charts, it looks like there's an option to display stacked charts as a percentage:

https://developers.google.com/chart/interactive/docs/gallery/areachart#stacking-areas

`isStacked: 'percent'`

**Comment by alexcrichton** [comment]
That'd be awesome! We may even have all the data already in place (we use google charts), so may not even be that hard to try out!
