### ISSUE TITLE
Crate file download response headers indicate tar but it's actually a tar.gz

### ISSUE THREAD

**Issue by mstange** [rust-lang/crates.io#3930]
**Describe the bug**

The HTTP response headers of a crate download, for example https://crates.io/api/v1/crates/tokio/1.6.1/download , do not indicate that the crate is gzipped. They only contain `content-type: application/x-tar`.

**To Reproduce**

Execute the following on the web console of your favorite browser:

```js
await fetch("https://crates.io/api/v1/crates/tokio/1.6.1/download", { mode: "cors" }).then(async r => [r.headers.get("Content-Type"), [...new Uint8Array(await r.arrayBuffer()).slice(0, 3)].map(x => x.toString(16).padStart(2, "0")).join(" ")])
```

This prints `[ "application/x-tar", "1f 8b 08" ]`. The 1f 8b 08 are the magic bytes of gzip.

**Expected behavior**
The Content-Type should probably be `application/gzip`. Alternatively, the response could be delivered with `Content-Encoding: gzip` so that the browser does the decompression and then passes the uncompressed tar bytes to JS.
But that might cause problems for other tools which expect to have to do the decompression themselves (rather than it being handled by their network layer).

**Additional context**
This is not an important issue, I only noticed it because there are some places on the internet that say that .crate files are .tar files and my tar parser wasn't working.

**Comment by Turbo87** [comment]
I guess this would need to be changed in https://github.com/rust-lang/crates.io/blob/274f601cb5c4c8132c2250c6252818138255bab9/src/uploaders.rs#L155, but we should also ensure that older versions of `cargo` can handle this change correctly. Afterwards we could potentially iterate over all crate files on S3 and change the content type, if S3 supports such an operation.

@ehuss can you comment on this?

**Comment by ehuss** [comment]
Sorry, I don't have any particular insight on this or what will break if it is changed.  It looks like gzip encoding was explicitly removed in https://github.com/rust-lang/crates.io/commit/53cbb26d022a88f7f311740f35ec5c6d4a5a9ab0.

**Comment by arlosi** [comment]
Cargo does not inspect http headers when downloading crates.

Here's the relevant section of Cargo: https://github.com/rust-lang/cargo/blob/d14c59dfe922d7b117f952bf2f210ef503968a31/src/cargo/core/package.rs#L756

It would need to call `handle.header_function(...)` to in order to look at the headers.

**Comment by Turbo87** [comment]
in other words: https://github.com/rust-lang/crates.io/pull/3955 should be safe to merge?

**Comment by arlosi** [comment]
Yes, it should be. The `Content-Type` of existing uploaded files should also be changed (as mentioned in #3955) either before or after.

**Comment by Turbo87** [comment]
closing this as https://github.com/rust-lang/crates.io/pull/3955 has been merged
