### ISSUE TITLE
Removing useless troll crates from crates.io

### ISSUE THREAD

**Issue by BGR360** [rust-lang/crates.io#3945]
**Is your feature request related to a problem? Please describe.**
I'm pretty frustrated by what I've just found here: https://crates.io/users/kumacodes.

This user ([@kumacodes](https://github.com/kumacodes)) has published **22 empty, useless crates** under some really common and useful names. This prevents actual crate authors from being able to use these names in the future.

**Describe the solution you'd like**
Is there anything that can be done to remove troll crates from crates.io? Is there any improvement that can be made to the acceptance process? I was hoping to maybe use one of the names that this user has occupied.

**Describe alternatives you've considered**
* Sulking grumpily in my bedroom.
* Sulking grumpily on the couch.
* ~Picking a new name for my crate~ Sulking grumpily in the shower.

**Additional context**
I had a bagel for breakfast today.

**Comment by Turbo87** [comment]
please have a look at https://crates.io/policies#package-ownership

any changes to this policy will have to got through the Rust RFC process, so if you want to change how things work, that's where you can start :)

**Comment by BGR360** [comment]
> ## Squatting
> We do not have any policies to define 'squatting', and so will not hand over ownership of a package for that reason.

Rip :/

**Comment by Turbo87** [comment]
as I said, feel free to open an RFC to change this policy. I'm personally also not a fan of it, but the crates.io team is busy keeping the site maintained and currently does not have any capacity to handle such things itself.

**Comment by BGR360** [comment]
After [some chatter on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/crates.2Eio.20squatting.20support/near/254161785) it seems that:

> the crates.io team [is] completely against any squatting-related policy, including asking nicely "please don't squat on crate names".

**Comment by Wulf** [comment]
I appreciate the crates.io team following their principles and process :)

I was trying to obtain the `cra` crate for my `create-rust-app` project but I found that a user has registered many crates under their name that aren't really used. Someone tried to [contact the user](https://github.com/swmon/Charles-Crack/pull/1) to obtain a crate but they weren't successful.

Note: I don't mean to pinpoint this user in particular and I hope they don't take it the wrong way. I just wanted to share this as policies are often informed by the results of their application.

![image](https://user-images.githubusercontent.com/4259838/135780008-c8468132-6aaf-4cf7-8d8e-94a81a169d3e.png)

**Comment by WilliamVenner** [comment]
This is a silly policy that will eventually backfire. I hope that the crates.io team will reconsider in future.

**Comment by Turbo87** [comment]
@WilliamVenner as we have mentioned countless times in the past: you are very welcome to write an RFC to change the current policy. it's not like the crates.io team is the only one who can change these sorts of things.
