### ISSUE TITLE
Removing access for a team fails if the team doesn't exist anymore

### ISSUE THREAD

**Issue by manifest** [rust-lang/crates.io#3948]
**Describe the bug**
Removing access for a team fails if the team doesn't exist anymore.

**To Reproduce**
```bash
cargo owner --remove github:ORG:TEAM
```
```
error: failed to remove owners from crate CRATE on registry at https://crates.io
```

**Expected behavior**
An access for the team is removed.

**Additional context**
The team doesn't exist anymore.

**Comment by carols10cents** [comment]
This is a duplicate of #1818. Thanks!
