### ISSUE TITLE
Inability to copy crate version from "install" window

### ISSUE THREAD

**Issue by pacak** [rust-lang/crates.io#3952]
Linux uses two clipboards, X selection [1] and clipboard. X selection works best with console application. To copy something to this buffer you select it, then it can be pasted anywhere that allows keyboard input with middle mouse button. Pasting into terminal usually means X selection.

**To Reproduce**
1. Go to any crate page, for example `https://crates.io/crates/lexical-core`
2. Click on `lexical-core = "0.8.0"`
3. See "Copied to clipboard!" popup
4. Go to a console editor, let's say vim
5. Try to paste with middle click
6. Nothing gets pasted

**Expected behavior**
1. Clicking on the left of the version number and dragging to the right selects the text.
2. Middle click in a console editor pastes the version.

Usually website's desire to improve things can be disabled by blocking javascript but disabling javascript disables the whole site.

**Desktop (please complete the following information):**
Any linux. Any browser. Any console text editor.

**Additional context**

[1] https://en.wikipedia.org/wiki/X_Window_selection

**Comment by Turbo87** [comment]
sorry, but we are just using regular browser APIs to implement this copy button. if it doesn't work in your environment then I would suggest opening a bug ticket for your browser instead 🤔

**Comment by pacak** [comment]
X selection doesn't work in any browser because the API you are using
blocks selection.

**Comment by Turbo87** [comment]
ah, I see what you mean. the problem is that the whole text is a button, instead of having a dedicated "copy" button next to it?

**Comment by pacak** [comment]
Right. Whole text is a button.

**Comment by Turbo87** [comment]
oops, this shouldn't have been closed by https://github.com/rust-lang/crates.io/pull/8167, but https://github.com/rust-lang/crates.io/pull/8168 does indeed fix it
