### ISSUE TITLE
Sort by downloads doesn't

### ISSUE THREAD

**Issue by DanielKeep** [rust-lang/crates.io#396]
Right now, <https://crates.io/search?q=mmap&sort=downloads> looks like this to me:

![no-crates-io-thats-not-how-sorting-works](https://cloud.githubusercontent.com/assets/77238/17357227/18bc4d52-599f-11e6-90b5-36f4f9954f99.png)

Either this is wrong, or I've taken a serious blow to the head and can't ordering anymore.

**Comment by alexcrichton** [comment]
cc @lazypenguin

**Comment by lazypenguin** [comment]
That's strange as it's working on my local build. Looks like the results aren't coming back sorted from the API endpoint (https://crates.io/api/v1/crates?page=1&per_page=10&q=log&sort=downloads). Was the target re-built in production?

**Comment by alexcrichton** [comment]
Hm it should be yeah, maybe the sql query should be updated?

**Comment by lazypenguin** [comment]
@alexcrichton I'm running Postgres 9.5.3 on my system, I see in the travis build it's using 9.3, is that the same for production? Would you be able to test this query against that database? Should help us narrow down the issue.

```sql
SELECT crates.* FROM crates,
                               plainto_tsquery('test') q,
                               ts_rank_cd(textsearchable_index_col, q) rank
          WHERE q @@ textsearchable_index_col
          ORDER BY name = 'test' DESC, rank DESC, crates.downloads DESC
          LIMIT 0 OFFSET 10;
```

**Comment by alexcrichton** [comment]
Looks like Heroku is using Postgres 9.3.9 and that query itself doesn't return anything for me (LIMIT 0), but did you intend to test something else perhaps?

**Comment by lazypenguin** [comment]
My mistake, left off a digit on the limit. I've tested the front end with `npm start --proxy https://crates.io` and no dice, so the issue lies within the backend code as `npm run start:local` correctly sorts the objects. Trying to eliminate some possibilities here

```SQL
SELECT crates.* FROM crates,
                               plainto_tsquery('test') q,
                               ts_rank_cd(textsearchable_index_col, q) rank
          WHERE q @@ textsearchable_index_col
          ORDER BY name = 'test' DESC, rank DESC, crates.downloads DESC
          LIMIT 10 OFFSET 10;
```

**Comment by alexcrichton** [comment]
Sure:

```
  id  |        name        | rank | downloads 
------+--------------------+------+-----------
 1498 | clap               |  2.3 |    184216
 5483 | alienlanguage      |  2.3 |        96
 2061 | compiletest_rs     |  1.9 |     27969
  654 | suffix             |  1.9 |      4403
 4341 | rotor-test         |  1.9 |       783
 2425 | stree_cmd          |  1.9 |       540
 5286 | fast_inv_sqrt      |  1.7 |       135
 3453 | modbus-test-server |  1.6 |       672
  868 | punkt              |  1.6 |       645
 3056 | ascii_set          |  1.6 |       553
```

**Comment by lazypenguin** [comment]
Alex, do you mind confirming that this produces the correct sort before I submit a new pull request? 

```SQL
SELECT crates.* FROM crates,
                               plainto_tsquery('test') q,
                               ts_rank_cd(textsearchable_index_col, q) rank
          WHERE q @@ textsearchable_index_col
          ORDER BY name = 'test' DESC, crates.downloads DESC, rank DESC,
          LIMIT 10 OFFSET 10;
```

Thanks for the patience.

**Comment by alexcrichton** [comment]
Oh yeah no worries, that generates:

```
│  id  |         name         | rank | downloads
│------+----------------------+------+----------
│ 1498 | clap                 |  2.3 |    184228
│  805 | nom                  |  0.4 |    160691
│  221 | rust-crypto          |  0.1 |    118499
│  102 | encoding_index_tests |  1.2 |     89635
│   70 | glutin               |  0.1 |     81530
│  196 | quickcheck           |  4.6 |     72530
│ 3119 | walkdir              |  0.4 |     59235
│  534 | deque                |  0.1 |     58326
│  426 | websocket            |  1.3 |     49056
│ 4519 | mempool              |  0.6 |     48401
```

**Comment by Keats** [comment]
Going to https://crates.io/search?q=markdown&sort=downloads it looks like it's still working correctly?

I see the following:
![2016-12-06-162728_940x785_scrot](https://cloud.githubusercontent.com/assets/680355/20916815/1958a9ce-bbd1-11e6-9fc0-03102957c1ae.png)

**Comment by carols10cents** [comment]
> Going to https://crates.io/search?q=markdown&sort=downloads it looks like it's still working correctly?
> 
> I see the following:

@Keats I think what you're seeing is that there's a crate with the exact name that matches your query, and [crates.io is ALWAYS putting that one first](https://github.com/rust-lang/crates.io/blob/master/src/krate.rs#L478). This could be made clearer, want to file a new issue for that?

**Comment by Keats** [comment]
@carols10cents Done in https://github.com/rust-lang/crates.io/issues/493
