### ISSUE TITLE
A page for sorting by downloads

### ISSUE THREAD

**Issue by Milo123459** [rust-lang/crates.io#3963]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
A whole page for showing crates that are the most downloaded, along with different numbered pages
**Describe alternatives you've considered**
N/A
**Additional context**

**Comment by Turbo87** [comment]
> A whole page for showing crates that are the most downloaded, along with different numbered pages

you mean like https://crates.io/crates?sort=downloads?

**Comment by Milo123459** [comment]
Dear god I'm blind
