### ISSUE TITLE
Is the `login` field unique ?

### ISSUE THREAD

**Issue by LucianoBestia** [rust-lang/crates.io#3964]
I use `https://crates.io/api/v1/crates/{}/{}/` to get the info about `published_by`. For example:
```json
        "published_by": {
            "avatar": "https://avatars.githubusercontent.com/u/1940490?v=4",
            "id": 3618,
            "login": "dtolnay",
            "name": "David Tolnay",
            "url": "https://github.com/dtolnay"
        },
```
Is the field `login` unique? Can I confidently show it and know there can be only one `dtolnay` in crates.io?
I just want to be sure there are not possible duplicates. Thanks.

**Comment by Turbo87** [comment]
AFAIK yes

**Comment by carols10cents** [comment]
No, it's not. People can rename their GitHub accounts, and then the old name is available for someone else to take. We use GitHub ID for this in the backend to ensure uniqueness. The ID shown here is the crates.io account ID, and that is unique.

See https://github.com/rust-lang/crates.io/issues/1584.
