### ISSUE TITLE
Move the function generate_secure_alphanumeric_string() into a new crate

### ISSUE THREAD

**Issue by silvioprog** [rust-lang/crates.io#3986]
What do you think about moving the function [`generate_secure_alphanumeric_string()`](https://github.com/rust-lang/crates.io/blob/b50ebd3010aa64eb2c86873a195ea8245781e255/src/util/token.rs#L87) into a dedicated crate? This way, other projects could benefit with a crate dedicated to generate random tokens.

Let me know if you agree with this, if so, I'm available to help in this task by creating the crate and sending a PR changing the `crates.io` project to use it.

**Comment by Turbo87** [comment]
I'm not sure it's worth it to extract a dedicated crate just for that function. It looks simple enough to just copy to other projects, if needed.
