### ISSUE TITLE
Search does not work in Safari

### ISSUE THREAD

**Issue by dmtrshat** [rust-lang/crates.io#4019]
**Describe the bug**
Safari cannot submit a form if the submit button inside it has the `display: none property`.

**To Reproduce**
1. Go to 'https://crates.io' via Safari
2. Type something in the 'search form'
3. Press 'enter'
4. See ~~error~~ nothing 😬

**Expected behavior**
Search results are shown

**Desktop (please complete the following information):**
 - OS: [macOS Big Sur 11.6]
 - Browser [safari]
 - Version [15.0]

**Smartphone (please complete the following information):**
 - Device: [iPhone 12 Pro Max]
 - OS: [iOS15.02]
 - Browser [stock browser, safari]
 - Version [15]

**Comment by dmtrshat** [comment]
I fixed a bug in this PR-'https://github.com/rust-lang/crates.io/pull/4018 '

**Comment by themaxdavitt** [comment]
Also running into this issue with very similar desktop/mobile configurations.
