### ISSUE TITLE
search bar not working on ios

### ISSUE THREAD

**Issue by ImUrX** [rust-lang/crates.io#4020]
**Describe the bug**
the search bar in ios doesnt work

**To Reproduce**
1. type something in the search bar
2. try to press go

**Expected behavior**
should return you the search results

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 14.1

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS
 - Browser Safari
 - Version 15.0.1

**Additional context**
![image](https://user-images.githubusercontent.com/3698237/137598997-b1183d59-4de1-4150-8be2-6b0ecab1dbc2.png)

**Comment by dmtrshat** [comment]
I have already created a similar issue
Look this - https://github.com/rust-lang/crates.io/issues/4019

**Comment by JohnTitor** [comment]
Closing in favor of #4019
