### ISSUE TITLE
Policies missing from page

### ISSUE THREAD

**Issue by skade** [rust-lang/crates.io#408]
The policies outlined are not published on crates.io. This is hard for people not _in_ the community.

https://internals.rust-lang.org/t/crates-io-package-policies/1041

**Comment by crodjer** [comment]
@skade I could take this up. I am absolutely new to the rust ecosystem though.

From an initial look, it seems that the patch should go under [rust-lang/cargo](https://github.com/rust-lang/cargo)?

Also, is there a way to extract the raw markdown text from `https://internals.rust-lang.org/t/crates-io-package-policies/1041`?

**Comment by carols10cents** [comment]
This was fixed in rust-lang/cargo#3057! http://doc.crates.io/policies.html
