### ISSUE TITLE
Show all crates owned by a user or group

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#409]
Much like I have a page of "my crates", I would like to be able to see a page of all crates that, say, the pistondevelopers github organization is listed as an owner on.

This would let me discover crates that are officially supported to work well together, as well as find other crates by authors who I trust.

**Comment by alexcrichton** [comment]
I believe the original design had a whole "look at this user" page as well, I just never got around to implementing it :(

I'd love to have this though!
