### ISSUE TITLE
More metadata in index?

### ISSUE THREAD

**Issue by kyrias** [rust-lang/crates.io#410]
Currently the metadata available in the git index is very small[[1]](https://github.com/rust-lang/crates.io/blob/bc4f1d79dcaac2b44e51fb7f67751d2bacca0453/src/git.rs#L15), containing just what cargo itself needs, but the index would be very useful for other purposes as well, since there's no other way to get a dump of the crates data.  A few things in the `krate::Crate` struct that would be useful for other things are the license, repo, homepage, docs, description, et.c.

Another solution would be to provide another form of data dump of the crates.io index, but adding it to the git index seems like the simplest way.  Comments/thoughts?

**Comment by alexcrichton** [comment]
You can use the crates.io API to learn about the full metadata for a crate, but the index is intended to be a very efficient data structure used by Cargo to perform resolution very quickly, so I'd be hesitant to start expanding it for other tools.

**Comment by kyrias** [comment]
It would be useful to be able to download the repository data somehow without having to query the API every time at least though.

**Comment by riivo** [comment]
Would it be possible to obtain a dump of the crates.io database, including the full metadata and stats for each crate and excluding user information? (similarly as RubyGem provides https://rubygems.org/pages/data).

**Comment by alexcrichton** [comment]
@riivo perhaps yeah! Sounds like a neat idae

**Comment by Keats** [comment]
@alexcrichton even a `pg_dump` of the tables related to the crates would be enough I think

**Comment by carols10cents** [comment]
Closing in favor of #630!
