### ISSUE TITLE
Adding more categories

### ISSUE THREAD

**Issue by elpiel** [rust-lang/crates.io#4105]
Hello :wave:
**Aerospace categories**
I would like to ask about adding more categories regarding `aerospace` in general (from protocol implementations, sdks, apis, simulations, etc).
This issue is more of a discussion on what categories could be added.

**Why?**
I am aware that there are a few categories like `simulations`, `science` & `science::robotics`, etc, however, I would like to have categories specifically for aerospace in order to collect and showcase them in https://areweinspaceyet.org/ automatically.

I'm planning a new version of the website which won't require manually entering crates and instead will build the list of crates for a specific categories and maybe keywords.

**Other options:**
It is possible to use a specific keyword e.g. `#aerorust` that will mark a crate which wants to end up in this list, however, it will still require some categories to be whitelisted and prevent misplaced crates.

I believe that the categories in crates.io could be used by other communities, lists (awesome-lists) and websites like:
- https://www.arewewebyet.org/
- https://areweasyncyet.rs/
- http://www.arewelearningyet.com/
- etc.

**Comment by Turbo87** [comment]
@elpiel just to give you an update, we planned to discuss this in the team meeting on Friday, but ran out of time. we've put it on the agenda for next week again.

**Comment by elpiel** [comment]
> @elpiel just to give you an update, we planned to discuss this in the team meeting on Friday, but ran out of time. we've put it on the agenda for next week again.

Thanks for letting me know, I really appreciate it!
I have listed a few examples in https://github.com/AeroRust/are-we-in-space-yet/issues/17 for categories that can be added.
> - [aerospace]
> - [aerospace.categories.space-protocols]
> - [aerospace.categories.drones]
> - [aerospace.categories.unmanned-aerial-vehicles]
> - [aerospace.categories.simulation]
> - [aerospace.categories.protocols]

During our last meetup someone brought up the issue that maybe we shouldn't have separate websites for different domains like `arewelearningyet`, `areweinspaceyet`, etc. for those crates to be easily discovered.
I do agree with the said, so I think it would be best to develop the `categories` on crates.io so that this kind of websites can be only complementary to crates.io.
This topic is a bit complex to figure out from the first time, however, I do believe that a good starting point is adding and using more categories & keywords on crates.io

**Comment by Turbo87** [comment]
hey @elpiel, sorry for it taking so long. we've finally managed to discuss this today and there are no objections from our side on adding such categories. you can find instructions on how to add them at https://github.com/rust-lang/crates.io#categories if you would like to work on a PR yourself :)

**Comment by elpiel** [comment]
> hey @elpiel, sorry for it taking so long. we've finally managed to discuss this today and there are no objections from our side on adding such categories. you can find instructions on how to add them at https://github.com/rust-lang/crates.io#categories if you would like to work on a PR yourself :)

Thank you very much!
I will look into more categories that could be added, like: `Software defined radio` (there are at least 2 crates that can be added to this category)

I will add the ones above if nobody else wants to add them, just because it's an easy contribution 😋
