### ISSUE TITLE
Show age of last git commit (to distinguish "dead" from "hasn't had a release recently")

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/crates.io#4117]
Inspired by https://www.reddit.com/r/rust/comments/qkt2j7/what_sort_of_mature_opensource_libraries_do_you/hj0abru/

Some crates have a relatively old release published on crates.io, but they have active development going on, just not a new published release. I'd love to have a "last git commit" date on the crates.io page, using the repository linked from the metadata.

If I'm searching for a crate with specific functionality, and I find a crate last published a year ago, but it has a last git commit hours ago, I'm more likely to go see if there's something I can do to help with the crate's development.

**Comment by wonderfulspam** [comment]
Great idea! Would this refer to the last commit on the default branch (typically `main` or `master`) or simply the latest commit altogether?

**Comment by joshtriplett** [comment]
I think the latest commit in the repository would be preferable, in case development is happening on a branch.

**Comment by carols10cents** [comment]
Hi Josh, thanks for the suggestion! The problem with this, though, is that we don't require crates to publish any repository link. I don't think it's fair to crates who choose not to publish their repository to penalize them and make them look inactive for that decision.

**Comment by joshtriplett** [comment]
@carols10cents I'm not suggesting that crates without a repository should be penalized. All crates would continue to show the time since last publish as they do now. I'm just suggesting an additional bit of metadata displayed for crates that *do* set a repository; that data could appear next to the repository link, for instance.
