### ISSUE TITLE
Listing Crates in API shows null for keywords, categories & versions

### ISSUE THREAD

**Issue by elpiel** [rust-lang/crates.io#4118]
**Describe the bug**

**To Reproduce**

1. Go to https://crates.io/api/v1/crates?page=1&per_page=50&q=graphics&category=no-std
2. See `keywords`, `categories` & `versions`

**Expected behavior**
The fields `categories`, `keywords`, `versions` should be populated based on the crate.

There are categories and keywords for the crates: https://github.com/embedded-graphics/embedded-graphics/blob/master/Cargo.toml#L8-L9
32 versions are shown in crates.io: https://crates.io/crates/embedded-graphics/versions

**Screenshots**

![Screenshot from 2021-11-02 16-30-00](https://user-images.githubusercontent.com/8925621/139867170-ca7972dd-59f0-46ad-a69e-d309cddf011c.png)

**Comment by Turbo87** [comment]
if you check https://crates.io/api/v1/crates/embedded-graphics you can see that we do have those relationships, but we intentionally don't serialize them in the crates listing endpoint for performance reasons.

**Comment by elpiel** [comment]
It's a bit odd to have this view not populating these fields and yet returning them.

I'm ok with this behaviour, however, as a user of the API I would expect that something is wrong or not working if the API returns the key but it's empty when the crate endpoint returns them.

Is there any consensus on this?

**Comment by Turbo87** [comment]
yeah, I agree. the serialization format is not perfect, but unfortunately we don't know what existing tools we might break if we remove these keys. :-/
