### ISSUE TITLE
https://crates.io/authorize/github fails to report authorization errors

### ISSUE THREAD

**Issue by kornelski** [rust-lang/crates.io#4176]
**Describe the bug**
Redirect from github login page back to `https://crates.io/authorize/github?code=[redacted]&state=[redacted]` fails to log me in, and it doesn't explain why. When it runs in a pop-up, the popup just disappears (#3810). If I trick it to run in the same window (by running `window.open = () => window`), I get an empty page like in the attached screenshot.

**To Reproduce**
1. Click on 'Log in with GitHub'
2. Nothingness

**Expected behavior**
I expect to be logged in, OR receive an explanation of what went wrong, e.g. authorization failure, wrong token, missing cookies, expected referrer, or whatever is preventing the site from working. I suspect the failure is caused by my browser, but I don't have enough information to fix it.

**Screenshots**

<img width="450" alt="Screen Shot 2021-11-14 at 21 12 19" src="https://user-images.githubusercontent.com/72159/141698809-5f945dff-2d05-4bb6-8996-c3095f4dd635.png">

**Desktop (please complete the following information):**
 - macOS 12
 - Firefox 96.0a1

**Comment by Turbo87** [comment]
hmm... that's definitely unintentional. I'll see if I can reproduce that.

**Comment by k8scat** [comment]
![image](https://user-images.githubusercontent.com/55872984/147105144-1cb7a0ba-816b-4f28-ace4-c478faec0e12.png)

Failed to log in: Service unavailable

**Comment by k8scat** [comment]
![image](https://user-images.githubusercontent.com/55872984/147106728-fc87ae0e-581a-4f95-86c3-a7baa66fdc9c.png)

**Comment by carols10cents** [comment]
@k8scat Our service providers are currently experiencing an outage. Please see https://status.crates.io/incidents/r6qckdr6wtq1 for updates.

**Comment by BlackGlory** [comment]
Still can't log in.

**Comment by onbjerg** [comment]
Experiencing this, too. Firefox 96.0, no extensions installed, on Manjaro. I've tried adding an exception for pop-ups manually as well for crates.io, but that didn't resolve the issue.

**Comment by pranavarora1895** [comment]
Kindly let me know when the bug gets fixed as I need to log in to it and want to learn how to publish my crates. Thanks.

**Comment by pranavarora1895** [comment]
When I was using the **Chrome Browser**, I was unable to log in. I was able to log in when I used **Brave Browser**. Hope it helps while debugging.

**Comment by TheEhsanSarshar** [comment]
### a workaround to solve this issue.
1 - open chrome in incognito mode and log in.
2 - close incognito and log in again in normal mode.

hope the team solves this issue soon.

**Comment by diegochavez** [comment]
I can't log in I thought was only my problem.
OS: macOS Big Sur
Google Chrome - Version 99.0.4844.83 (Official Build) (arm64)

**Comment by wminshew** [comment]
can't log in. Pop up closes quickly w/o any error reporting or further information
intel mbp 2019
macos 12.0.1 (21A559)
chrome Version 100.0.4896.88 (Official Build) (x86_64)

logging out of github and relaunching didn't work

incognito mode did

**Comment by pranavarora1895** [comment]
> can't log in. Pop up closes quickly w/o any error reporting or further information intel mbp 2019 macos 12.0.1 (21A559) chrome Version 100.0.4896.88 (Official Build) (x86_64)
> 
> logging out of github and relaunching didn't work
> 
> incognito mode did

Try using a browser other than Chrome. I used Brave for the same. Cheers!!

**Comment by umop3plsdn** [comment]
I was having the same issue but the chrome incognito initial authorize then close and reopen worked for me.

**Comment by jolestar** [comment]
can't log in. Pop up closes quickly w/o any error reporting or further information.

Both chrome and edge didn't work.

Safari work.

**Comment by ofarukcaki** [comment]
I have the same problem.

Microsoft Edge on MacOS

**Comment by Turbo87** [comment]
We've just deployed a potential fix for this issue. Please report back if this fixes the issue or not.

Thank you to @stefanpenner for debugging this and figuring out that noisy browser extensions were the root cause of this issue.

**Comment by umop3plsdn** [comment]
just revoked and tried it again works for me
