### ISSUE TITLE
the websit can not login with github.

### ISSUE THREAD

**Issue by busgo** [rust-lang/crates.io#4279]
### Current Behavior

Click the "Login with Github" button found the  the confirm window  auto close rigth now.

### Expected Behavior
 
 Should  login with Github.

### Steps To Reproduce

1. open https://crates.io/
2. click the "Log in with GitHub" button .
3. the confirm window auth close right now.

### Environment

- Browser: chrome 
- OS: macOS 11.4

**Comment by Turbo87** [comment]
Thanks for reporting. I assume this is a similar issue as https://github.com/rust-lang/crates.io/issues/4176.
