### ISSUE TITLE
Improve resilience of crates.io during AWS and Heroku outages

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/crates.io#4282]
This plan will add additional mitigations to crates.io to improve the resilience of the service in the event of AWS or Heroku outages, prompted by the December 7th 2021 AWS outage. When this plan is implemented, it will ensure downloads keep working in the event of:

1. AWS S3 outage in the region hosting the `crates-io` bucket (`us-west-1`).
2. AWS EC2 or Heroku outage in the region runnin the app (`us-east-1`).
3. Global CloudFront outage preventing users from reaching the CDN.

Progress on the implementation:

* [x] Create the `crates-io-fallback` bucket and configure cross-region replication from `crates-io`
* [x] Create the `staging-crates-io-fallback` bucket and configure cross-region replication from `staging-crates-io`
* [x] Synchronize existing content in `crates-io-fallback`
* [x] Synchronize existing content in `staging-crates-io-fallback`
* [x] Configure CloudFront to failover to the fallback bucket in production
* [x] Configure CloudFront to failover to the fallback bucket in staging 
* [x] Create a workflow in the production index to update the URL
* [x] Create a workflow in the staging index to update the URL (https://github.com/rust-lang/staging.crates.io-index/pull/1)
* [ ] Update the (private) operations guide with instructions on what to do during these outages
* [x] Add additional monitoring to ensure we catch when this happens

## Retrospective on the last AWS outage

On December 7th 2021 [an outage happened](https://aws.amazon.com/message/12721/) in the `us-east-1` AWS region, affecting the APIs of multiple AWS services including EC2. Starting new instances on Heroku [was also impacted](https://status.heroku.com/incidents/2390).

We got lucky during that outage on multiple fronts, and no issues arose for crates.io, but it could've been worse:

* While the outage affected the EC2 API, it did not stop instances that were already running. The application runs in Heroku's US region, which is powered by EC2 instances in `us-east-1`. If we had to restart the application, or the outage affected running instances, the application would've gone down.
* S3 didn't seem to be impacted by the outage, and the bucket containing all crates is in a different region (`us-west-1`). If the bucket was located in the faulty region and the outage affected S3 we might've encountered downtime though.

## Improvement 1: configure multiple S3 buckets

An additional S3 bucket, `crates-io-fallback`, will be created in a separate AWS Region, and cross-region replication will be configured between the two buckets to make sure they stay in sync. Replication will be unidirectional to ensure the `crates-io` bucket in `us-west-1` stays as the source of truth and we won't have a split-brain situation.

CloudFront will then be configured to use the fallback bucket if it can't reach the primary bucket, protecting us from scenario (1) without the need of any on-call involvement.

## Improvement 2: allow changing the CDN URL in the index

Cargo clients are not hardcoded to use the crates.io API to download crates. Instead, they use the URL specified in the `dl` key of [the index's `config.json`](https://github.com/rust-lang/crates.io-index/blob/master/config.json).

A GitHub Actions workflow will be created to allow on-call operators to change the URL in the `dl` endpoint to one of a set of pre-determined URLs. The operators will be able to use the GitHub UI to queue a job performing the change, providing an audit trail and preventing them from accidentally changing the URL to a wrong one:

![workflow](https://user-images.githubusercontent.com/2299951/146400826-d32ecb80-82be-4837-93ea-4e0783b6ac52.png)

The pre-determined URLs will be:

* The crates.io application. This should be the configured value outside of an outage.
* The direct URL to the CloudFront CDN, if the application is broken.
* The direct URL to the underlying `crates-io` S3 bucket, if CloudFront is broken.
* The direct URL to the fallback `crates-io-fallback` S3 bucket, if both CloudFront and S3 in the `us-west-1` region are both broken.

This will tell Cargo to bypass the faulty piece of infrastructure, protecting us from scenarios (2) and (3). This would require on-call involvement to make the required changes.

## Additional monitoring

We will need to configure additional monitoring to page on-call operators if `static.crates.io` starts returning 404s.

**Comment by pietroalbini** [comment]
This was approved by the team during last week's sync meeting. I already created the bucket, synchronized the staging fallback bucket and I'm in the process of synchronizing the production fallback bucket. The fallback buckets are located in the `eu-west-1` (Ireland) region.

**Comment by bjorn3** [comment]
> A GitHub Actions workflow will be created to allow on-call operators to change the URL in the dl endpoint to one of a set of pre-determined URLs. The operators will be able to use the GitHub UI to queue a job performing the change, providing an audit trail and preventing them from accidentally changing the URL to a wrong one:

Would it make sense to add a field that allows for giving a reason why the download url was switched that will then be part of the audit trail? Or is communication elsewhere enough?

**Comment by pietroalbini** [comment]
On one hand, the on-call operator is expected to log all the actions they make during an incident in a private `incident-response` chat channel, and only do this when there's an active incident.

On the other hand, logging that text as part of the audit trail is not going to be trivial: the values people provide in those input fields are not logged anywhere, and raw logs are deleted after 90 days. The "hack" I used to log the URL they chose permanently is to include that as part of the job title, but including arbitrary text there would be too noisy.

![Screenshot from 2021-12-16 17-06-34](https://user-images.githubusercontent.com/2299951/146407019-d6991782-d516-4a9a-88af-586e02fd80de.png)

**Comment by pietroalbini** [comment]
Created a PR for the workflow on the staging repository: https://github.com/rust-lang/staging.crates.io-index/pull/1

**Comment by pietroalbini** [comment]
The only two items left now are writing documentation for this and setting up additional monitoring. Other than that this is implemented! :tada:

**Comment by pietroalbini** [comment]
Additional monitoring is now up.

**Comment by pietroalbini** [comment]
Documentation draft written, closing the issue :tada:
