### ISSUE TITLE
Download graphs appear to be broken

### ISSUE THREAD

**Issue by palfrey** [rust-lang/crates.io#4285]
### Current Behavior

Download graphs on the bottom of crates pages are broken

![image](https://user-images.githubusercontent.com/38532/146463662-1c37dd7f-8013-427a-8aff-1e9797a3c3b1.png)

### Expected Behavior

Graph data to be there!

### Steps To Reproduce

1. Go to bottom of crate page (e.g. https://crates.io/crates/rand) and have a look at the graph

### Environment

- Browser: Firefox 88.0.1
- OS: Debian

### Anything else?

JS Console has some CSP errors, but nothing screaming "the graph is broken"

**Comment by Turbo87** [comment]
yep, was reported on Discord too. #4284 should fix it. I'm currently deploying that to our servers :)
