### ISSUE TITLE
Removing unused crates, making the name available, possible ?

### ISSUE THREAD

**Issue by conradkleinespel** [rust-lang/crates.io#430]
Hello,

I have a crate (namely `rclip`), which is used by no one (since it's non functional, I don't think anyone uses it) but it takes up space.

Is there a way to remove such crates that just take up crate names and are not even in use ?

Thanks for your help,
Conrad

**Comment by alexcrichton** [comment]
Thanks for the report! We don't actually delete crates from crates.io, but rather we let crates get transferred if someone else wants to take over.

You can just publish a new version indicating to contact you to transfer, and that should do the trick!

**Comment by conradkleinespel** [comment]
Alright, thanks @alexcrichton :)
