### ISSUE TITLE
All series on a given axis must be of the same data type

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/crates.io#431]
https://crates.io/crates/serde

![selection_008](https://cloud.githubusercontent.com/assets/1940490/18193314/26b895a6-7091-11e6-9c95-deeb80676af2.png)

This worked earlier today.

**Comment by dtolnay** [comment]
Looks like old versions work:

![selection_009](https://cloud.githubusercontent.com/assets/1940490/18193825/19645f7a-7096-11e6-9387-9b5811bae8a9.png)

But the newest version is a string for some reason:

![selection_010](https://cloud.githubusercontent.com/assets/1940490/18193836/2d3ac7b4-7096-11e6-9d07-3a6eda8bdd69.png)

> Data column(s) for axis #0 cannot be of type string

**Comment by alexcrichton** [comment]
cc @TyOverby 

Perhaps related to https://github.com/rust-lang/crates.io/pull/426 ?

**Comment by dtolnay** [comment]
Looks like this is caused by https://github.com/google/google-visualization-issues/issues/1487. It should not add empty series to the chart.

**Comment by TyOverby** [comment]
This is a change that was exposed by #426.  

I can reproduce.

Working on a fix.

**Comment by TyOverby** [comment]
Reproduction steps: 

* View a crate that has a version which has never been downloaded.  [Example](https://crates.io/crates/flame)

**Comment by TyOverby** [comment]
Fix here: #432

I'm working on cleaning up the code though, so don't merge yet.

**Comment by SoniEx2** [comment]
Shouldn't this be closed?
