### ISSUE TITLE
BUG: Can't search any crate

### ISSUE THREAD

**Issue by marc2332** [rust-lang/crates.io#4312]
### Current Behavior

![image](https://user-images.githubusercontent.com/38158676/147097191-f7c457a6-4f5a-40b3-9e2f-967672992a03.png)

### Expected Behavior

It should list the crates matching my search

### Steps To Reproduce

1. Just search for a crate

### Environment

- Browser: Firefox and Chrome
- OS: Windows and Android

### Anything else?

No.

**Comment by marc2332** [comment]
Well, looks like it works, now. Probably the server just went done for a minute. Closing this

**Comment by Turbo87** [comment]
it's related to https://status.crates.io/incidents/r6qckdr6wtq1
