### ISSUE TITLE
Download graph no longer displaying old crate versions

### ISSUE THREAD

**Issue by atouchet** [rust-lang/crates.io#4373]
### Current Behavior

The download graph on crates.io no longer shows download stats for crate versions older than the last 5 releases as of a recent update. Is this a bug or intended behavior? For crates where a non-trivial number of downloads are for older releases this makes the download graph a less useful resource.

Example:

![screenshot](https://user-images.githubusercontent.com/26315797/147516201-9ec2c450-517f-41a5-a444-6bee5bf48a19.png)

This is the current graph for the winapi crate. From experience there are still a significant number of downloads for the 0.2.8 version which used to be shown on this graph. It is no longer possible to determine the amount of older version downloads from looking at the graph.

### Expected Behavior

I expect the download graph to display accurate info including download stats for older crate releases.

### Steps To Reproduce

1. Go to a crate page with more than 5 released versions on crates.io.
2. Scroll down and look at the download graph.

### Environment

- Browser: Firefox 95.0.2
- OS: Windows 1

**Comment by Turbo87** [comment]
thanks for reporting this, @atouchet! this was indeed an unintentional bug. I've opened a bugfix PR at https://github.com/rust-lang/crates.io/pull/4377 which should hopefully be merged and deployed in the near future :)

**Comment by Turbo87** [comment]
Merged and deployed! 🎉
