### ISSUE TITLE
"Latest updates" never loads

### ISSUE THREAD

**Issue by Keruspe** [rust-lang/crates.io#438]
On https://crates.io/dashboard the "Latest updates" section on the right never seems to load.

The spinner keeps being displayed for some time, then is replaced by a "Load More" button.

Same thing happens again when clicking "Load More".

Note that when the page is loading, and then each time I click "Load More", I get this in the console:

<details>
TypeError: e is undefined
a()
vendor-b5eaa22629fc0ae42aba95c5979b7b1f.js:8
n()
vendor-b5eaa22629fc0ae42aba95c5979b7b1f.js:8
C()
vendor-b5eaa22629fc0ae42aba95c5979b7b1f.js:16
o.inline()
vendor-b5eaa22629fc0ae42aba95c5979b7b1f.js:16
u.prototype.populateNodes()
vendor-b5eaa22629fc0ae42aba95c5979b7b1f.js:17
u.prototype.render()
vendor-b5eaa22629fc0ae42aba95c5979b7b1f.js:17
o()
</details>

Not sure how I can provide more information.

**Comment by utkarshkukreti** [comment]
I've been seeing this behavior for months now. Just decided to open the console and saw this error logged:

    Error: Compile Error: from-now is not a helper

I think the following change should fix this but I'm unable to setup logging in with `start:live` (is that even possible?) so I can't test right now.

```diff
diff --git a/app/templates/dashboard.hbs b/app/templates/dashboard.hbs
index f0b074e..9be2ff6 100644
--- a/app/templates/dashboard.hbs
+++ b/app/templates/dashboard.hbs
@@ -52,7 +52,7 @@
                         {{link-to version.crate.name 'crate.version' version.num}}
                         <span class='small'>{{ version.num }}</span>
                         <span class='date small'>
-                            {{from-now version.created_at}}
+                            {{moment-from-now version.created_at}}
                         </span>
                     </div>
                 </div>
```

If anyone else is able to test this, please feel free to commit this if it works.
