### ISSUE TITLE
VersionEye integration

### ISSUE THREAD

**Issue by benaryorg** [rust-lang/crates.io#439]
Is there any integration into [VersionEye](https://www.versioneye.com/) planned?

I guess it would be nice for some people to get a notification when a new version of a crate is available.

**Comment by steveklabnik** [comment]
> Is there any integration into VersionEye planned?

Not that I'm aware of.

> I guess it would be nice for some people to get a notification when a new version of a crate is available.

This is covered by https://github.com/rust-lang/crates.io/issues/381
