### ISSUE TITLE
frontend.Dockerfile fails over incompatible yarn version

### ISSUE THREAD

**Issue by lukehinds** [rust-lang/crates.io#4491]
### Current Behavior

When running `docker-compose -d` from main as of commit ec630a0271de51a0705fbdc1843f7c279ece6408 it fails due to incompatible yarn versions

```
Step 4/6 : RUN yarn install
 ---> Running in b8254ff04fab
yarn install v1.22.15
[1/5] Validating package.json...
error cargo@0.0.0: The engine "yarn" is incompatible with this module. Expected version "1.22.17". Got "1.22.15"
```

### Expected Behavior

docker-compose should complete successfully

### Steps To Reproduce

1. `git clone https://github.com/rust-lang/crates.io && cd "$(basename "$_" .git)"`
2. `docker-compose up -d`

### Environment

- Browser: N/A
- OS: Fedora 35 .

**Comment by lukehinds** [comment]
p.s happy to make the PR if someone could point me in the right direction (not much experience with the frontend world)

**Comment by Turbo87** [comment]
I guess something like https://dev.to/michalbryxi/volta-in-docker-162a might work. We already specify the `volta` keys in the `package.json` file, so if the Docker container would use https://volta.sh too then the yarn version conflict would go away.

**Comment by rdewaele** [comment]
Because the `frontend.Dockerfile` does not modify its base image `node:16:13.2-alpine` in any significant way, I presume this is a temporary error until the node docker container comes with an updated yarn installation.

In the mean time, the following workaround did the trick for me:

```
diff --git a/frontend.Dockerfile b/frontend.Dockerfile
index 544a4840..d6626e0d 100644
--- a/frontend.Dockerfile
+++ b/frontend.Dockerfile
@@ -3,7 +3,7 @@ FROM node:16.13.2-alpine
 WORKDIR /app
 COPY package.json yarn.lock /app/

-RUN yarn install
+RUN npm install -g --upgrade --force yarn && yarn install

 COPY . /app
```

**Comment by Turbo87** [comment]
can we modify the first snippet to use `ENV YARN_VERSION 1.22.17` and then something like `npm install -g --upgrade --force yarn@$YARN_VERSION`?

if we could do that then we could configure renovatebot to keep that env var up-to-date with the other yarn versions in the project

**Comment by rdewaele** [comment]
Yes, I think that's possible.

I am not really experienced with yarn and related tooling, so this question may be ill-informed. It looks to me that the second alternative makes sure that the expected versions of all relevant software is installed by means of configuration already present _today_ in the repository. So I am left wondering why the first alternative would be preferential.

**Comment by Turbo87** [comment]
> So I am left wondering: Why the preference for the first alternative?

primarily just because it's shorter, less complex, and lets us keep the smaller alpine base image. there is certainly a bit more duplication if we go that route, but since we rarely change the version *manually* it should probably be fine.

**Comment by Turbo87** [comment]
now that we've moved to pnpm I guess this issue can be closed  😅
