### ISSUE TITLE
New crates.io design mockups

### ISSUE THREAD

**Issue by vis-kid** [rust-lang/crates.io#450]
@wycats @aturon @alexcrichton @steveklabnik 

Below are a few early!! sketches that I would like to play with some more. I’d be happy to take some responsibility, continue this work and implement them as well. Since this is not exactly a tiny undertaking, it would be nice get some sort of “official” O.K. before I jump into this.  

None of the designs below are meant to be set in stone. They are early starting points to get this topic moving forward. I think big parts of this community want to see a fresh site as well as concerted efforts to make this finally happen.

![crates-index](https://cloud.githubusercontent.com/assets/1353214/19043976/a15f58d4-8992-11e6-98aa-c7e297a5cb19.png)

![creates-search-02](https://cloud.githubusercontent.com/assets/1353214/19044040/e9f28e86-8992-11e6-8db1-6b1cc3820502.png)

![crates-detail](https://cloud.githubusercontent.com/assets/1353214/19044071/050023b4-8993-11e6-8658-2b791db6ad3a.png)

![crates-search](https://cloud.githubusercontent.com/assets/1353214/19044099/1fa5c6c4-8993-11e6-990d-995d8eb38fa9.png)

![logo03](https://cloud.githubusercontent.com/assets/1353214/19044156/4d9bfd96-8993-11e6-8215-95d0b4538eb7.jpg)
![logo04](https://cloud.githubusercontent.com/assets/1353214/19044154/4d9546b8-8993-11e6-85ae-735904907060.jpg)
![logo05](https://cloud.githubusercontent.com/assets/1353214/19044155/4d9b19bc-8993-11e6-9443-0f79ae1d0353.jpg)
![logo06](https://cloud.githubusercontent.com/assets/1353214/19044137/4107e3f6-8993-11e6-8eb1-c92d6cd7f44f.jpg)
![logo07](https://cloud.githubusercontent.com/assets/1353214/19044139/41135556-8993-11e6-9031-29e6efb94c78.jpg)
![logo08](https://cloud.githubusercontent.com/assets/1353214/19044140/413852c0-8993-11e6-88b6-8d1e4afb7449.jpg)
![logo09](https://cloud.githubusercontent.com/assets/1353214/19044141/414776e2-8993-11e6-819f-b6b6b0428286.jpg)
![logo10](https://cloud.githubusercontent.com/assets/1353214/19044142/41647d00-8993-11e6-8320-d9d260a70b57.jpg)

**Comment by carols10cents** [comment]
I'm going to close this as we still don't have the people with the time available to implement a redesign, as we haven't for 3 years now. Thanks though!

**Comment by vis-kid** [comment]
@carols10cents Hi! If the core team wants to see this happen, I'd be interested in implementing a redesign…

**Comment by Turbo87** [comment]
@carols10cents just FYI I'm totally up to work on that too on the frontend side 😉
