### ISSUE TITLE
Frontpage Columns Messed Up

### ISSUE THREAD

**Issue by alanhdu** [rust-lang/crates.io#451]
On the front page of https://crates.io, the really long version number messes up the formatting: 

![screenshot from 2016-10-03 20-46-34](https://cloud.githubusercontent.com/assets/1914111/19051496/284321ba-89ab-11e6-82aa-eb9d851e66c4.png)

This is on Linux (Ubuntu 16.04 x86-64) with both Chrome (Version 50.0.2661.86 (64-bit)) and Firefox (Mozilla Firefox 51.0a2)

**Comment by steveklabnik** [comment]
I am seeing this as well.

**Comment by alexcrichton** [comment]
Looks bad! We should definitely clip the version text in one form or another.
