### ISSUE TITLE
Feature request / discussion: add some discussion on crates.io to leave feedback and compare functionality (to avoid Pythonic mess)

### ISSUE THREAD

**Issue by d33tah** [rust-lang/crates.io#452]
I love the concept of crates.io! Having learned from Python though, may I suggest that you add some way to leave feedback for the projects? My reasoning is that unless crates.io becomes moderated, sooner or later there will be multiple crates for the same problems, leading to confusion about what each project is good at. Alternatively, crates.io could have the concept of "features" comparison, like shown here:

https://djangopackages.org/grids/g/admin-styling/

Note that the later the feature gets added, the less packages will support it - it's better to add an imperfect solution to this problem now than none at all and get back with a Pythonic mess.

**Comment by carols10cents** [comment]
So any comments on crates.io would need to be moderated, at the very least for spam. The moderation team doesn't have the bandwidth to moderate crates.io too.

Please see rust-lang/rfcs#1824 for discussion of automated ways to make it easier for people to find better quality crates.
