### ISSUE TITLE
False positive in reverse dependencies

### ISSUE THREAD

**Issue by numero-744** [rust-lang/crates.io#4523]
The crate `check` lists into [its dependents](https://crates.io/crates/check/reverse_dependencies) the crate `divisibility_check` which does not use it. Instead, according to its [`Cargo.toml`](https://github.com/wasim-dhamriya/divisibility_check/blob/master/Cargo.toml#L13), `divisibility_check` uses a crate with the same name through a local path.

**Comment by JohnTitor** [comment]
Hmm, it looks correct to me?

The dependency tree is:

```text
divisibility_check v0.1.0
└── check v0.1.0 (yanked)
```

Note that the `path` will be ignored when publishing. That might've been unintentional, but anyway crates.io displays the relation correctly, I think.

**Comment by numero-744** [comment]
Ah okay so the problem is that the crate `check` in the dependency graph was not intended to be the one published on crates.io, but it actually is since `divisibility_check` has been published. So the problem is not crates.io but the `divisibility_check` crate.

Thanks for the explanation!
