### ISSUE TITLE
Update README to mention yarn?

### ISSUE THREAD

**Issue by rjgoldsborough** [rust-lang/crates.io#456]
https://yarnpkg.com was just released and seems pretty cool.

Too early to update README to mention/use yarn?

They add a lockfile that may be worth versioning
https://yarnpkg.com/en/docs/yarn-lock#toc-check-into-source-control

**Comment by alexcrichton** [comment]
Looks like this is being done in #457

**Comment by rjgoldsborough** [comment]
Dang. It is indeed.
