### ISSUE TITLE
Missing Category Slug: gui-application

### ISSUE THREAD

**Issue by mark-summerfield** [rust-lang/crates.io#4669]
### Problem

There is already a category slug for `command-line-utilities`, but there is no equivalent for GUI applications. The `gui` slug is for "Crates to help you create a graphical user interface.", not for applications themselves.

### Proposed Solution

Add a new category slug called, say, `gui-applications`.

**Comment by ehuss** [comment]
Transferred to crates.io, as the website handles the categories.

**Comment by weihanglo** [comment]
Hi, I believe this issue belongs to [rust-lang/crates.io](https://github.com/rust-lang/crates.io), and I found you've already asked the same question in GitHub Discussions. [I've replied to you there] and hope you can solve the problem soon 😄

[I've replied to you there]: https://github.com/rust-lang/crates.io/discussions/4387#discussioncomment-2437766

**Comment by Turbo87** [comment]
@weihanglo is correct, there is already an open GitHub discussion for this, so I'll close the issue as a duplicate :)
