### ISSUE TITLE
crates.io should encourage use of latest stable version, not alpha/beta versions

### ISSUE THREAD

**Issue by briansmith** [rust-lang/crates.io#468]
I just published *ring* 0.6.0-alpha so I could get some pre-release feedback. I expected that the page at https://crates.io/crates/ring would continue to say `ring = "0.5.3"` bit instead it says `ring = "0.6.0-alpha"`. If somebody goes through the trouble to use the `-alpha`/`-beta` modifiers then they probably don't want the average user of their crate to use that version.

**Comment by alexcrichton** [comment]
Agreed!

**Comment by steveklabnik** [comment]
Especially given that you don't get a pre-release version without specifically selecting it; this seems quite consistent.

**Comment by carols10cents** [comment]
Fixed by #577!
