### ISSUE TITLE
HTTP 500 internal server error on running "cargo publish"

### ISSUE THREAD

**Issue by CensoredUsername** [rust-lang/crates.io#469]
Hello,

I was recently trying to publish version 0.0.2 of my [whitespacers](https://crates.io/crates/whitespacers) crate, but for some reason every time I try to do this it results in an nondescript internal server error. The error is shown below:

```
error: failed to get a 200 OK response, got 500
headers:
    HTTP/1.1 100 Continue



    HTTP/1.1 500 Internal Server Error

    Connection: keep-alive

    Server: nginx

    Date: Wed, 16 Nov 2016 00:43:21 GMT

    Content-Length: 30

    Via: 1.1 vegur



body:
Error 404: Not Found
Not Found
```

I'm pushing from a clean version of the [master branch](https://github.com/CensoredUsername/whitespace-rs) of the project, if the actual files are helpful.

**Comment by alexcrichton** [comment]
This *may* have been fixed by https://github.com/rust-lang/crates.io/commit/e190f2beff4a57ee08b77986b66bc60c6508fe95, could you try publishing again and seeing if it works?

**Comment by CensoredUsername** [comment]
Looks like that fixed it. I must be the only person currently using "0.*.*" versions as this is the second time I ran into breakage because of it.

**Comment by alexcrichton** [comment]
Ok, thanks for the update!

**Comment by steveklabnik** [comment]
> I must be the only person currently using "0.*.*" versions as this is the second time I ran into breakage because of it.

In general, it's not 100% clear how two `*`s work; this should be the same as `0.*`.
