### ISSUE TITLE
Error: failed to download from `https://crates.io/api/v1/crates/adler/1.0.2/download`

### ISSUE THREAD

**Issue by zzzgit** [rust-lang/crates.io#4691]
### Current Behavior

I am going to use this [package](https://crates.io/crates/arboard). I pasted the dependency:

<img width="263" alt="image" src="https://user-images.githubusercontent.com/1060733/161719049-b52e7dd9-895a-46b9-b61f-83e25139cfef.png">

got the toml:

```
[dependencies]
arboard = "2.1.0"
```
and then I got the error: 
`failed to download from https://crates.io/api/v1/crates/adler/1.0.2/download`

**Comment by Turbo87** [comment]
do you have any more information? with the given information this is a bit hard to debug.

one thing that looks suspicious is that the version numbers of the dependency and the url don't match up.

**Comment by zzzgit** [comment]
> do you have any more information? with the given information this is a bit hard to debug.
> 
> one thing that looks suspicious is that the version numbers of the dependency and the url don't match up.

Hi, I am a newbie in Rust.
What do you mean don't match up?

**Comment by Turbo87** [comment]
> What do you mean don't match up?

sorry, I missed that it was `arboard@2.1.0` and `adler@1.0.2`.

https://crates.io/api/v1/crates/adler/1.0.2/download works fine for me though, so this is/was most likely a network issue. our team is not aware of any connectivity issues of our servers at the moment.

**Comment by zzzgit** [comment]
I am using the IDE vsc. Okey, maybe it's a bug of the vsc addon for Rust.
