### ISSUE TITLE
Make some env vars optional for easier dev setup

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#470]
Right now [`cargo_registry::env` panics if there isn't a value set for an env var](https://github.com/rust-lang/crates.io/blob/e190f2beff4a57ee08b77986b66bc60c6508fe95/src/lib.rs#L198), so you can't run the server locally unless you set values for everything in `.env`. 

If you're just working on part of the backend that you don't need users logged in for, there's no reason to have to set up github tokens and all that.

I tried to make this easier to set up by setting the values in `.env.sample` to `""`, which gets around the panic, but apparently [that caused problems with zsh](https://github.com/rust-lang/crates.io/issues/417).

I think it'd be better to have another function, like `env_with_default` or something, and maybe warn that functionality that needs that env var isn't going to work?

I'm happy to do this, just not right this second, so I wanted to open this to remind me (and maybe entice someone else to do it, i don't think it would be very hard #famouslastwords)

**Comment by alexcrichton** [comment]
Sounds good to me!

**Comment by kelcecil** [comment]
I'd be happy to take this task.

**Comment by kelcecil** [comment]
My thought is that we may want to still panic for certain environment variables not being set where we absolutely can't progress. TEST_DATABASE_URL, S3_* variables, and GH_* variables would all be okay for defaults, but the Postgres URL and GIT_* variables would pretty much be required and should panic if not set. Thoughts?

**Comment by alexcrichton** [comment]
@kelcecil yeah sounds good to me. We may want to assert that in production everything is set, but otherwise sounds good

**Comment by carols10cents** [comment]
I *think* we fixed this. If anyone hits this problem, please reopen!
