### ISSUE TITLE
Instructions provided by the init-local-index.sh should use replace-with

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#471]
Since `replace-with` has now landed and `registry.index` is being deprecated, [these instructions echoed by the script that sets up a local index for development](https://github.com/rust-lang/crates.io/blob/master/script/init-local-index.sh#L35-L36) should instead instruct you to use `replace-with` (as [the README does](https://github.com/rust-lang/crates.io/blob/master/README.md#local-cargo-setup)) instead of `registry.index`.

**Comment by alexcrichton** [comment]
👍

**Comment by kelcecil** [comment]
@carols10cents Happy to do this! One question though. I notice that the script uses `[registry]` while the README examples uses variations of `[source]`. Are these table names interchangeable, or is `[registry]` an outdated name?

**Comment by carols10cents** [comment]
> @carols10cents Happy to do this! One question though. I notice that the script uses [registry] while the README examples uses variations of [source]. Are these table names interchangeable, or is [registry] an outdated name?

\o/ `registry` is the outdated name, `source` is the new way of configuring this functionality. Please let me know if you have any other questions! <3
