### ISSUE TITLE
Crates where all versions are yanked do not show up in the list of the list of owned crates

### ISSUE THREAD

**Issue by thomcc** [rust-lang/crates.io#4750]
### Current Behavior

As an example, @ockam-network/crate-publishers is listed as an owner of `ockam_credential` on this page: [crates.io/crates/ockam_credential/settings](https://crates.io/crates/ockam_credential/settings), but it does not show up on the list here https://crates.io/teams/github:ockam-network:crate-publishers.

This is also the case for a few other crates for this team, and I think it has to do with all versions being yanked

### Expected Behavior

The team/owner page should show all crates owned by the owner.

### Steps To Reproduce

1. Go to https://crates.io/teams/github:ockam-network:crate-publishers
2. Look for `ockam_credential`.
3. Fail to find it.
4. Go to https://crates.io/crates/ockam_credential/settings
5. See that `@ockam-network/crate-publishers` is present.
6. Lament that computers are bad sometimes.

### Environment

- Browser: Firefox Nightly 101.0a1 (2022-04-24)
- OS: macOS 12.3 on aarch64-apple-darwin.

But I don't think this is relevant to this issue

### Anything else?

Sorry if this is a dupe, I looked but it wasn't clear.

**Comment by carols10cents** [comment]
Yes, this was done on purposoe: https://github.com/rust-lang/crates.io/pull/1642

**Comment by thomcc** [comment]
Hm, fair enough!
