### ISSUE TITLE
Cargo error / error: failed to verify the checksum of `mongodb v2.2.1`

### ISSUE THREAD

**Issue by nicolasJJJ** [rust-lang/crates.io#4774]
### Current Behavior

C:\Users\XXXXX>cargo install mongodb
    Updating crates.io index
  Downloaded mongodb v2.2.1
error: failed to verify the checksum of `mongodb v2.2.1`

### Expected Behavior

Successfully installed mongodb

### Environment

- OS: WIN 10

### Anything else?

Hello,

I have a company computer with Win 10. I'm in a team trying to introduce Rust in a big company with constraints.
I have the authorization to go in crates.io and i have set all proxies, enven  ~.cargo/config file. All is alright.

However, when i install any rust package, i go through this error telling me that Cargo can't verify the checksum. 

Did anyone had this error ? How can i resolve this ?
Is it possible to disable checksums verifications ?

Thank you in advance,
Nicolas

**Comment by Turbo87** [comment]
I guess this question might be a better fit for the cargo team. @ehuss any clues?

**Comment by ehuss** [comment]
The checksum validation can't be disabled. You're going to need to make sure that your proxy does not modify the file in any way, such as recompressing it.

You can validate with curl.  For example:

`curl -L https://crates.io/api/v1/crates/mongodb/2.2.1/download | sha256sum`

The checksum here should match 49a2fe500edae1ffc8e4bbc731e54a44638e5ec59fbff967f1cb8306867f5b53.

BTW, `mongodb` is not a package that can be used with `cargo install`, as it only has a library.

**Comment by nicolasJJJ** [comment]
OK i've got another result : crates.io is still blocked by my organization.

$ curl -L https://crates.io/api/v1/crates/mongodb/2.2.1/download | sha256sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: crates.io
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 *-

So i guess Cargo receives a response from crates.io wich is false anyway.

@ehuss @Turbo87  thank you 

So it's not a cargo bug.
