### ISSUE TITLE
Unable to access the crates.io website through cURL or pragmatically without extra HTTP headers

### ISSUE THREAD

**Issue by JeffResc** [rust-lang/crates.io#4783]
### Current Behavior

Unable to access the crates.io website through cURL or pragmatically without extra HTTP headers. Returns a 404 error, for example:
```
# curl https://crates.io/crates/rand
{"errors":[{"detail":"Not Found"}]}
```

### Expected Behavior

I expect the request to respond with status 200 and the page contents

### Steps To Reproduce

Run the following command on the command line:
```
curl https://crates.io/crates/rand
```

### Environment

- Browser: curl 7.68.0
- OS: 20.04.4 LTS (Focal Fossa)

### Anything else?

Please see [Kovah/LinkAce#465](https://github.com/Kovah/LinkAce/issues/465) for more details.

**Comment by carols10cents** [comment]
Duplicate of https://github.com/rust-lang/crates.io/issues/788. Please search existing issues to see if your problem has been reported before. Thanks!
