### ISSUE TITLE
Page title to reflect the crate name or ID

### ISSUE THREAD

**Issue by peter-kehl** [rust-lang/crates.io#4828]
### Current Behavior

A working example: visit https://crates.io/crates/markdown-toc. The page title is "markdown-toc". OK.

But, visit https://crates.io/crates/cargo-run-bin. The page title is "crates.io: Rust Package Registry". As per #1930, the page title should reflect the crate name. (Another past issue about titles seems to be #1341).

If some crates are missing their names, how about using the URL part in the title, please.

### Expected Behavior

Show the crate name in the title. If a crate doesn't have a name or it can't be retrieved, show its URL postfix.

### Environment

- Browser: Current Firefox 100
- OS: Current Manjaro x64 w/ GNOME 40+

**Comment by JohnTitor** [comment]
Hmm, it works fine on my end (Firefox 100):
![image](https://user-images.githubusercontent.com/25030997/169676304-a95063bc-9058-4fab-8a05-2a26b4a18f8c.png)

And when loading the page, I've found there're some gaps until the page title is filled out. My guess is that your connection was corrupted and the page wasn't loaded completely.

**Comment by Turbo87** [comment]
yep, works fine here too 🤔

**Comment by peter-kehl** [comment]
Thank you. It must have got fixed already.

Enjoy improving Rust toolset.
