### ISSUE TITLE
Feature request: easily visible easy cross-compilability.

### ISSUE THREAD

**Issue by vi** [rust-lang/crates.io#484]
Somes crates are easy to cross-compile: just have appropriate rust-stdlib, linker and maybe some object files.
Other crates (notably those dependent on `gcc` or `pkg-config` or maybe just containing `build.rs`) are not so easy: they require C compiler and/or additional headers or libraries being present. It may be one of practical reasons of making pure Rust implementation of things typically done by linking to some system libraries.

To encourage making more pure Rust reimplementations there may be special badge like "Cross-compile-friendly crate" for things that does not require tricky steps to cross-compile (either directly or via dependency).

Another idea: special badge for "nostd"-compatible crates.

**Comment by Turbo87** [comment]
at this point we decided to not add any more custom badges and instead rely on maintainers adding custom badges directly to their README files. you can use e.g. https://shields.io for that.
