### ISSUE TITLE
Disallow non-sensical version predicates

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/crates.io#486]
crates.io currently prevents publishing a package with a dependency version predicate of `*`.  Please consider disallowing a few more version predicates, for similar reasons.  (Cargo itself doesn't need to prohibit them, but crates.io could.)

- `>=0` - Equivalent to `*`
- `0.*` - 0.x and 0.y aren't compatible for x != y, so this doesn't make any more sense than `*`.
- `=0` - Equivalent to `0.*`.
- `~0` - Equivalent to `0.*`.
- `<0` - Doesn't match anything at all.

**Comment by steveklabnik** [comment]
Does this need an RFC? @rust-lang/core

**Comment by joshtriplett** [comment]
Depends on how much impact it would have.  I did some analysis of all dependencies observed on crates.io, and as far as I can tell, this wouldn't have any significant impact.  The only one of these I observed in quantity was ~0, which it looks like some packages use for "I have a path dependency in dev-dependencies and I don't want to specify the real version because nobody will use dev-dependencies but me and I use the path dependency so the version doesn't matter".

**Comment by alexcrichton** [comment]
I don't really see a particular reason why but I don't really see a particular reason why not either. This seems minor enough though that it's fine to do w/o an RFC. I don't think there's many backcompat concerns as we'd just change crates.io, not Cargo.

**Comment by joshtriplett** [comment]
@alexcrichton Motivation: in writing a packaging tool to produce Cargo dependencies, I found myself thinking very carefully about every possible combination of semver predicate operators and major.minor.patch versions, and writing an exhaustive match operation over them to translate them to Debian package dependencies.  In the course of doing so, I ran into the above corner cases.  After doing some analysis on the crates.io index to determine that they ranged from incredibly rare to non-existent, I figured it couldn't hurt to get crates.io to keep it that way.

**Comment by alexcrichton** [comment]
In some sense I'd rather not get too far in the business of "nonsensical versions" where so long as it's syntactically valid we should interpret it as it says. Sure something like `<0` doesn't work but you'd find that out real quick and almost no one would be using the crate anyway.

**Comment by joshtriplett** [comment]
@alexcrichton Fair enough. I'm more concerned about things like `>=0` (since that would work around the crates.io prohibition on `*`), or `0.*` (since that would introduce major compatibility issues).

**Comment by alexcrichton** [comment]
Banning versions like that was [explicitly addressed in the relevant RFC](https://github.com/rust-lang/rfcs/blob/master/text/1241-no-wildcard-deps.md#alternatives) actually I believe. Historically it attempted to reject version requirements without upper bounds, but after discussion the conclusion was just to disallow literally `*`

**Comment by carols10cents** [comment]
Since the RFC discussion explicitly decided to allow version ranges like `>=0` and only disallow `*`, imo this change would need a new RFC to reopen the discussion...

**Comment by joshtriplett** [comment]
@alexcrichton I'm definitely not proposing to ban all version requirements without upper bounds.  (On the contrary, I'm usually more concerned about excessively tight upper bounds.)  I had just hoped to eliminate the possibility of version requirements that didn't make sense at all, or that were completely equivalent to `*`.

**Comment by joshtriplett** [comment]
@alexcrichton I'm definitely not proposing to ban all version requirements without upper bounds.  (On the contrary, I'm usually more concerned about excessively tight upper bounds.)  I had just hoped to eliminate the possibility of version requirements that didn't make sense at all, or that were completely equivalent to `*`.

**Comment by aturon** [comment]
See [this comment](https://github.com/rust-lang/rfcs/pull/1241#issuecomment-138643318) for a summary of the change to the RFC to only restrict `*`. I agree with @carols10cents that further policy changes are RFC-worthy.

**Comment by Turbo87** [comment]
Given that this needs an RFC and there hasn't been any movement on this in four years I'll go ahead and close this issue for now. We can always reopen if someone takes the time to write an RFC for this.
