### ISSUE TITLE
Why are all the version numbers so low?

### ISSUE THREAD

**Issue by NeoLegends** [rust-lang/crates.io#487]
It seems like there is quite a refusal of stable version numbers in rust crate authors. There are lots of crates that mission critical software depends on (`libc`, `mio`, `winapi`, `rand`, `gcc`) that have not yet reached an officially stable status. Why is that? Wouldn't using those libraries on thousands (if not millions) of machines and the time they've already been available satisfy a 1.0-release and stability guarantees? I understand that libraries like `futures-rs` that have existed publicly for half a year are not considered stable, but in practice, those other libraries _are stable_ (and usually tested), but the version number says they are not. Why?

**Comment by steveklabnik** [comment]
Could you please post this to http://users.rust-lang.org/ ? We try to keep the bug tracker for bugs, not for general discussion. Thanks!

**Comment by NeoLegends** [comment]
Okay, I'll do the xpost.
