### ISSUE TITLE
Reverse dependencies should be ordered by number of downloads by default

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#495]
When looking at a crate's reverse dependencies, right now it's ordered alphabetically. This doesn't convey as much information as ordering this list by number of downloads by default, since a crate could be assumed to be "better" if the crates that depend on this crate are popular.

**Comment by pornel** [comment]
Maybe order by number of dependencies of dependencies first? (i.e. show "heaviest" dependencies first).

**Comment by carols10cents** [comment]
@pornel Sorry, this issue is for *reverse dependencies*, so if you were looking at [a logging library](https://crates.io/crates/log), you can click on the [dependent crates](https://crates.io/crates/log/reverse_dependencies) link to see all the crates that depend on the logging library. Right now when you click on that link the default ordering is alphabetical; this issue proposes to make the ordering by number of downloads (which is already available) the default.

I'd recommend filing a new issue to suggest improvements for ordering *dependencies*!

**Comment by LeopoldArkham** [comment]
I assume this would also mean displaying the number of downloads for each dependency, right? Otherwise it'll be unclear how they're ordered and it won't really help the prestige of the crate they depend on.

Also, could this be done simply by editing the SQL query :

```rust
pub fn reverse_dependencies(...) {
...
let fetch_sql = format!("SELECT DISTINCT ON (crate_name)
                                        dependencies.*,
                                        crates.name AS crate_name
                                        {}
                               ORDER BY crate_name ASC
                                 OFFSET $2
                                  LIMIT $3", select_sql);
...
}
```
in `krate.rs` ? (I see this has an ember tag)

**Comment by carols10cents** [comment]
@LeopoldArkham You're absolutely right. I had thought the list of dependent crates already had the downloads number, so that this would just need a frontend change, but yeah, the query needs to be edited. I was thinking we could offer a sorting option like [other crate list pages have](https://github.com/rust-lang/crates.io/blob/master/src/krate.rs#L488-L491), but that logic is kind of messy, maybe we just change the default to number of downloads and not offer an option for sorting since there isn't an option now, and see what people think.

Let me know if you have any other questions!!

**Comment by LeopoldArkham** [comment]
@carols10cents At a glance, it seems dependencies have no awareness of downloads. Is the best course of action to update the ember dependency model and have _it_ fetch the number of downloads, then sort accordingly, or to change the server-side representation of dependencies and propagate that to ember?

**Comment by carols10cents** [comment]
I would lean towards changing the server-side query to do a JOIN to the table that has the download counts and send that back to ember all at once.

**Comment by LeopoldArkham** [comment]
Hey @carols10cents, just got started on this for real. Is there an easy way to populate the database to have some stuff to work with?

**Comment by carols10cents** [comment]
@LeopoldArkham unfortunately, there isn't an *easy* way to get data in the database right now, I should work on that soon. For now, [here's some data for the crates and versions tables](https://gist.github.com/carols10cents/1c2a7c25e40c6b4d6e3cc63dd0a7c496) that you should be able to load into your `cargo_registry` database using `psql -f crates.sql -d cargo_registry`. Then you should be able to create records connecting these crates and versions in the `dependencies` table [like this code does](https://github.com/rust-lang/crates.io/blob/master/src/dependency.rs#L53-L60) and then change the `downloads` column for the entries in the `crates` table to be whatever you want them to be for what you're trying out.

Let me know if you have any questions about doing this!
