### ISSUE TITLE
Feature Idea: automated appveyor and travis (similar to docs.rs)

### ISSUE THREAD

**Issue by stephanbuys** [rust-lang/crates.io#497]
[docs.rs](docs.rs) is a great addition to the Rust ecosystem, having documentation automatically taken care off just makes for a great developer experience. That said, in a drive to have better/more reliable crates available and to provide developers with strong signals wrt crate stability, etc, I would like to suggest automated CI for your consideration/discussion.

Disclaimer, I have no special knowledge related to the terms of service of the major CI services, which would perhaps make this impossible, but I think it is a common repetitive task undertaken by many, many crate authors - so worth discussing.

Riffing on the idea a bit further, surfacing number of tests, coverage and success/failure trends would be awesome signals and would definitely encourage having good testing (especially if `crates.io` has a `no tests` label surfaced on the crate's page when no tests are run/detected).

A standardized workflow could be:
- `clone repo` (handled by CI)
- `install rust` (or work from standard rusty Docker containers?) 
- `rustc -vV`
- `cargo test --verbose --no-default-features`

This feature could be opt-out for authors with custom scripts, etc.

**Comment by steveklabnik** [comment]
I personally feel that crates.io should do one thing and do it well: host crates. Integration with other services to make things easy might make sense, but there's a number of reasons that it's a good idea to split this kind of thing up.

What would an "official" CI do for you that Travis/Appveyor wouldn't?

**Comment by stephanbuys** [comment]
@steveklabnik, apologies - what I meant is "auto-configuring", or providing the necessary scaffolding to use appveyor or travis - not to have crates.io as the CI server.

**Comment by steveklabnik** [comment]
Ah ha! That makes sense 👍 

Isn't that more of a Cargo thing than a crates.io thing, though?

**Comment by carols10cents** [comment]
Hi @stephanbuys! :) I think templates that could be passed to `cargo new` that include CI setups (and badges in the README?) would be awesome -- [this cargo PR](https://github.com/rust-lang/cargo/pull/3004) to support templates looks like it's almost merged in.

So I'm going to close this, let me know if I'm missing anything that crates.io should be doing here!
