### ISSUE TITLE
Log in with GitHub doesn't work

### ISSUE THREAD

**Issue by chicoxyzzy** [rust-lang/crates.io#498]
Confirmed by various people 
<img width="936" alt="screen shot 2016-12-29 at 01 14 55" src="https://cloud.githubusercontent.com/assets/1507086/21532750/458f4134-cd64-11e6-9b6e-cee0eac2ee4a.png">

**Comment by alexcrichton** [comment]
Thanks for the report! I've rolled back the recent deployment for now to fix this issue and I'll work on fixing it in the source soon.

**Comment by alexcrichton** [comment]
Ok I believe this is fixed now, so closing.
