### ISSUE TITLE
Website renders incorrectly on mobile browsers

### ISSUE THREAD

**Issue by nc-x** [rust-lang/crates.io#499]
I am using Chrome on Android.
See the attached long screenshot for the issue -
![s61231-15384577 1 1 1 1 1](https://cloud.githubusercontent.com/assets/16458742/21577013/4b169202-cf70-11e6-987f-228cdcd2880e.jpg)

**Comment by ducks** [comment]
It looks like the above screenshot, and the cargo docs in general, aren't contained in the same crates.io repo. They are located here https://github.com/rust-lang/cargo/tree/master/src/doc and hosted on the http://doc.crates.io/index.html subdomain.

This means the two sites are using different html, css, etc. It kind of makes sense to me to keep at this content in one place, but I also see the benefit of keeping cargo docs in the cargo repo.

We would need to either 1) fix the responsive stuff on the cargo docs side which includes some html tweaking and css changes I think, or 2) move the cargo docs content to static ember pages hosted on crates.io which is already responsive.

Any thoughts on which way to handle this one? @carols10cents

**Comment by carols10cents** [comment]
Yeah, there have been multiple issues with the HTML/JS/CSS that's duplicated between the two repos getting out of sync. I wonder if there's a not-too-complex way that the text of the cargo docs could continue to live in the cargo repo, but could be fetched and inserted into the HTML/JS/CSS that lives in the crates.io repo...?

**Comment by carols10cents** [comment]
I'm closing this since the cargo docs are moving to mdbook and are going to be rendered completely differently :)
