### ISSUE TITLE
Cannot create a new API token

### ISSUE THREAD

**Issue by tversteeg** [rust-lang/crates.io#5062]
### Current Behavior

Clicking on the "New Token" button on https://crates.io/settings/tokens doesn't do anything and shows the following error in the console:

```
Uncaught TypeError: l.randomUUID is not a function
    y chunk.b8d872939540e67d9962.js:2
    createIdentifierForNewRecord chunk.b8d872939540e67d9962.js:2
    _build chunk.b8d872939540e67d9962.js:2
    build chunk.b8d872939540e67d9962.js:2
    createRecord chunk.b8d872939540e67d9962.js:2
    _run loader.js:2
    _join loader.js:2
    join loader.js:2
    createRecord chunk.b8d872939540e67d9962.js:2
    _run loader.js:2
    _join loader.js:2
    join loader.js:2
    createRecord chunk.b8d872939540e67d9962.js:2
    startNewToken chunk.8f717926b74c4089c120.js:2
    s chunk.b8d872939540e67d9962.js:2
chunk.b8d872939540e67d9962.js:2:266642
```

### Expected Behavior

I should be able to create a new token.

### Steps To Reproduce

1. Go to https://crates.io/settings/tokens
2. Press the "New Token" button

### Environment

- Browser: `Mozilla Firefox 89.0.2`
- OS: `Linux 5.18.0-3-amd64 Debian 5.18.14-1 (2022-07-23) x86_64 GNU/Linux`

**Comment by Turbo87** [comment]
you might have to update your browser. Firefox 89 is over one year old and not supported anymore. according to https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID the missing API was introduced in Firefox 95.

**Comment by tversteeg** [comment]
Shouldn't at least an error be thrown when this function is not available?

**Comment by Turbo87** [comment]
yeah, there might be error handling missing for that button 🤔

**Comment by Turbo87** [comment]
@WGH- that is a fair point. I guess we would need some sort of polyfill in that case.
