### ISSUE TITLE
Uppercase categories are rejected

### ISSUE THREAD

**Issue by terrarier2111** [rust-lang/crates.io#5083]
### Current Behavior

When specifying categories with an upper case, they are rejected even though their lower case equivalent would be accepted.
Also using spaces instead of `-` signs makes said categories to be ignored.

### Expected Behavior

Upper cased categories get treated as lower cased ones and spaces get treated as `-` signs.

### Steps To Reproduce

Just put:
categories = ["Rendering", "Game development"]
into your Cargo.toml and when publishing the crate, all categories will be ignored and it will have no categories associated with it at all.

### Environment

- Browser:
- OS:

**Comment by Turbo87** [comment]
this is not a bug, but currently works as intended. third party tools that analyze the `Cargo.toml` files would have a hard time to adjust to this change, so it seems unlikely to get changed given that the advantages seems quite limited. you can find the list of valid category slugs at https://crates.io/category_slugs
