### ISSUE TITLE
[dependencies] nginx = { git = "https://github.com/arvancloud/nginx-rs.git", tag = "0.15.0" }

### ISSUE THREAD

**Issue by pranaw215** [rust-lang/crates.io#5096]
### Current Behavior

While downloading the crates for nginx-rs binding after setting the dependency in Cargo.toml the below line.

```
[dependencies]
nginx = { git = "https://github.com/arvancloud/nginx-rs.git", tag = "0.15.0" }
```

The following error is encountered.

```
error: failed to run custom build command for `nginx v0.15.0 (https://github.com/arvancloud/nginx-rs.git?tag=0.15.0#2b72469c)`

Caused by:
  process didn't exit successfully: `/home/new-ubuntu/rust_weserver/warp-upload-download-example/target/debug/build/nginx-55cdb34e9e60c60d/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=NGINX_VERSION
  cargo:rerun-if-env-changed=NGINX_PATH

  --- stderr
  thread 'main' panicked at 'unable to prepare nginx: "preparing nginx exited with non-zero status code"', /home/new-ubuntu/.cargo/git/checkouts/nginx-rs-3ad6d7e8a6feb35c/2b72469/build.rs:52:6
```

The env  variable of the NGINX_VERSION is nginx/1.18.0 and for NGINX_PATH is /etc/nginx.
Please help me out for to fix this. 

### Expected Behavior

Nginx has to build and run through nginx-rust bindings.

### Steps To Reproduce

1) Create cargo toml with below dependency
[dependencies]
nginx = { git = "https://github.com/arvancloud/nginx-rs.git", tag = "0.15.0" }

2) Set the env variable "NGINX_PATH" and "NGINX_VERSION" to /etc/nginx and  nginx/1.18.0 respective. 

3) Give cargo run

### Environment

- OS: Ubuntu
 
uname -a

Linux newubuntu-VirtualBox 5.11.0-49-generic #55-Ubuntu SMP Wed Jan 12 17:36:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Turbo87** [comment]
you might want to report this to the `nginx-rs` maintainers at https://github.com/arvancloud/nginx-rs instead :)
