### ISSUE TITLE
Development tools category is too specific

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/crates.io#511]
I'm trying to determine the category to place the [addr2line](https://github.com/gimli-rs/addr2line) crate in, and I think `development-tools` is probably the best fit. However, the category description currently only allows tools that make **Rust** code easier to write. addr2line is language agnostic, and instead acts directly on binaries, which is not "allowed" by the description. Could it be changed to talk about development tools in general? Alternatively, could we split it into two categories: one for Rust tools, and one for development tools?

**Comment by carols10cents** [comment]
I think making it more general is fine! Would you like to send in a PR?

**Comment by jonhoo** [comment]
Sure! See #518.
