### ISSUE TITLE
Pluralization of crate counts in categories and keywords

### ISSUE THREAD

**Issue by wezm** [rust-lang/crates.io#513]
When the number of crates in a category is shown, 1, is not handled properly resulting in "1 crates".

<img width="534" alt="screen shot 2017-01-21 at 8 08 12 am" src="https://cloud.githubusercontent.com/assets/21787/22165606/e0ba7184-dfb0-11e6-8829-bd0f36ef9a69.png">

**Comment by shepmaster** [comment]
If you scroll far enough into the keyword pages, you can see the same issue:

![image](https://cloud.githubusercontent.com/assets/174509/22165956/89cc21bc-df2c-11e6-94af-e6a31182be70.png)

I'm sure Ember has a nice tool to prevent this, we just need to look across the UI when we apply it.

**Comment by carols10cents** [comment]
Yeah searching for `format-num` and checking all of those places would be good...
