### ISSUE TITLE
Improper Image Link For Appveyor Badge

### ISSUE THREAD

**Issue by Susurrus** [rust-lang/crates.io#519]
Badge image links for non-Github projects for Appveyor seem to be incorrect. I'm hosting my repo on Gitlab (this is also indicated in the `package.repository` in cargo.toml) and while the correct link should be `https://ci.appveyor.com/api/projects/status/gv9v4b78ywa4bn2g/branch/master?svg=true` it's actually `https://ci.appveyor.com/api/projects/status/github/Susurrus/serialport-rs?svg=true&branch=master`. I believe there was mention in the release announcement of a `repository` setting within the `badges` section, but it said it only supports Github and Bitbucket right now. Is that what this problem is related to? Adding Gitlab support for appveyor? And is this not a value that can be parsed out of the `package.repository` value already in `Cargo.toml`?

**Comment by carols10cents** [comment]
Oh, I wasn't aware that appveyor supported badges for gitlab at all. We're using [this method](https://github.com/appveyor/website/blob/31845d611455db36ddf9b2c2ece76859dc5d9cb6/src/docs/status-badges.md#badges-for-projects-with-public-repositories-on-github-and-bitbucket) of creating the URL, which doesn't mention gitlab support. But it looks like https://ci.appveyor.com/api/projects/status/gitlab/Susurrus/serialport-rs works, I guess their documentation is out of date!

This just means we'll need to add gitlab as a recognized value for the `service` key for the appveyor badge.

As far as being able to infer the badge from the repository value, some people who list their repository might not want to show their badges. Some people who want to show their badges might not want to list their repository. There might be some CI services that don't have a clear correspondence to the repository. This was the clearest way to give crate owners control over what gets shown for their crate and support every situation we could conceive of.

**Comment by Susurrus** [comment]
Indeed this support already exists. I just set the service to gitlab and it worked, you can see here: https://crates.io/crates/serialport

I've already supplied a PR to cargo to document this functionality (rust-lang/cargo#3597) so I'm closing this issue as resolved.
