### ISSUE TITLE
Redirect to repo

### ISSUE THREAD

**Issue by SirVer** [rust-lang/crates.io#520]
I have a Chrome search for the crates io searchbar, so typing 'crate regex' gives the the search results directly for the regex crate. 

However, very often i just require the repo or the documentation of a crate. Currently I search for the crate on crates.io and then click (this got much quicker with the new links in the search results, thanks for that!). It would be terrific if crates.io could do a redirect service for me, so I could use a Chrome autosearch to quickly jump to the documentation. For example, `https://crates.io/crates/regex/documentation` should redirect to `https://doc.rust-lang.org/regex/regex/index.html`.

**Comment by LeopoldArkham** [comment]
The `/docs` route does this already. There's no equivalent for the repository though.
