### ISSUE TITLE
No way to see API tokens

### ISSUE THREAD

**Issue by Timmmm** [rust-lang/crates.io#5204]
### Current Behavior

[This page](https://crates.io/settings/tokens) says:

> You can use the API tokens on this page to run [cargo](https://doc.rust-lang.org/cargo/) commands that need write access to crates.io.

Well, I can't. There's an API token I created a year ago that I would like to use but there's no way to see it. I can only revoke it and create a new one.

![image](https://user-images.githubusercontent.com/376842/189183097-e5a345a2-bf44-433d-a324-0f3d87ad433a.png)

### Expected Behavior

There should be some kind of "show API key" button on the keys.

### Steps To Reproduce

I guess

1. Create an account.
2. Create an API key.
3. Go to the API keys page.

### Environment

- Browser: Chrome
- OS: Mac

**Comment by carols10cents** [comment]
No, this is a security risk. Why is it important to you to reuse a token?

**Comment by Timmmm** [comment]
I guess it doesn't really matter but it seems silly not to. I would generate a new SSH key for every computer I use.

What's the security risk? If someone can access that page they can just create a new token if they want to publish crates with your account.

At the very least the page should explain that you can't view existing tokens and you need to create a new one if you didn't record the existing ones. And ideally it should explain *why* - what is the specific security risk. Something like this:

> Note that you can only view API tokens when they are first created. If you did not record the token at that point you should revoke it and create a new one. This restriction is to ensure that anyone who gains unauthorized access to your account will have to create a new token to publish crates and if you regularly check this page you might notice.

**Comment by Turbo87** [comment]
The security risk is that we would have to save the tokens in plaintext in our database, which would allow any attacker that gains access to the database to take over *all* associated GitHub and crates.io accounts.

Instead we save hashed tokens so that we're able to verify whether a valid token was used without knowing the actual token. The only time the server knows the token is during the request that generated it.

**Comment by Timmmm** [comment]
Ok that seems reasonable. I'll open a new task to explain that on the page.
