### ISSUE TITLE
API token page should explain why you can't see existing tokens

### ISSUE THREAD

**Issue by Timmmm** [rust-lang/crates.io#5207]
### Current Behavior

Currently the API token page doesn't really make it clear why you can't see existing tokens.

### Expected Behavior

It should explain it. See #5204.

### Environment

- Browser:
- OS:

**Comment by gabrielleecredera** [comment]
not sure if a message is needed for this, it's pretty common practice to not store, and thus show, existing API keys.
e.g. your github personal access tokens

**Comment by Turbo87** [comment]
yeah, you're right that GitHub does not seem to explain this on the personal access token page either. on the other hand, I do also agree that this might be surprising for new developers who are not used to this. having 1-2 short sentences somewhere on the page that explain it probably won't hurt, so I'd be fine with adding something like this :)
