### ISSUE TITLE
Yanked Crate removes too much information

### ISSUE THREAD

**Issue by WalterSmuts** [rust-lang/crates.io#5208]
### Current Behavior

When a crate is completely yanked, for example [constfft](https://crates.io/crates/constfft), you lose a bit too much information on it. There is no `README` anymore and no graph on recent downloads. I still think it's  useful to see how much people are still using it and specifically the `README` can be useful to re-direct folks to an alternative.

### Expected Behavior

* BIG RED BANNER (or something - I am not a UI designer) saying the crate is yanked.
* Still display the same information as before for latest version.

### Steps To Reproduce

1. [constfft](https://crates.io/crates/constfft)
2. Observe no README
3. Observe no graph of downloads

### Environment

- Browser:
```
$ google-chrome-stable --version
Google Chrome 103.0.5060.134
```
- OS:
```
$ uname -a
Linux cuddles 5.18.16-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 03 Aug 2022 11:25:04 +0000 x86_64 GNU/Linux
```

### Anything else?

See related [issue on docs.rs](https://github.com/rust-lang/docs.rs/issues/1822).

**Comment by Turbo87** [comment]
IMHO it's best to keep the versions unyanked and add a note in the README. yanking can generally create quite a bit of problems for the endusers, which is fine if it's a direct dependency, but complicated when it's coming from some 5th level transitive dependency.

as we are unlikely to change the way that this is currently handled, I'll close this issue for now.
