### ISSUE TITLE
Update the site to include the email address help@crates.io somewhere

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/crates.io#522]
I got a question sent through rustlangs' DMs about some stuff regarding crates; I had to point them to email @alexcrichton directly, but there should at least be an email on the policy page or something.

**Comment by steveklabnik** [comment]
That is, not _support_ help but like "I want to rename a crate" kind of things.

**Comment by carols10cents** [comment]
@alexcrichton I'm assigning this to you, since I'm not sure what this email address should be and who all it should go to. If you can specify which email address should be used, I think anyone could take care of listing it somewhere.

**Comment by alexcrichton** [comment]
How's help@crates.io sound?

**Comment by carols10cents** [comment]
sgtm!

**Comment by alexcrichton** [comment]
Ok I've created the email and unilaterally added Steve, me, and Carol to the forwarding list.

@carols10cents want to update the site to include it? (I'm fine with it wherever)

**Comment by alexcrichton** [comment]
I also just sent a test email you two should have received

**Comment by carols10cents** [comment]
Yup, the email works! So finishing this issue will involve deciding where people would look for a contact email and adding `contact: hello@crates.io` there. I would say [in the footer](https://github.com/rust-lang/crates.io/blob/51a3f149c7017fbda4f5be3927147ede3cd03865/app/templates/application.hbs#L116-L122) and on the policy page, which [lives in cargo's repo](https://github.com/rust-lang/cargo/blob/eaebe26441344d600d42f3f8c549f42c0c80a1ec/src/doc/policies.md).

**Comment by alexcrichton** [comment]
Sounds good to me!

**Comment by hiseni** [comment]
Hey, guys! 😃
Anyone started to work on this issue? ❓
PS: I want/can do it. 😺

**Comment by hiseni** [comment]
Here is what I came up with:
![](https://pageshot.net/images/ffa0c8c5-5186-406b-a6a7-b42cace77dd6.png)

It seems nice for a general help (smth is not working) as well as for more specific (ex: renaming a crate) questions :slightly_smiling_face:

**Comment by carols10cents** [comment]
Looks great! Send that PR in!! :)

**Comment by carols10cents** [comment]
#561 has been merged and rust-lang/cargo#3738 has been r+'d, so I'm closing this!! Thank you @hiseni !!
