### ISSUE TITLE
Sorting by downloads and recent-downloads produces unexpected results

### ISSUE THREAD

**Issue by mjpieters** [rust-lang/crates.io#5247]
### Current Behavior

Sorting by either (all-time) downloads or by recent-downloads returns results that are not (properly) sorted.

E.g. the [search for `multiset` ordered by downloads in the API](https://crates.io/api/v1/crates?q=multiset&sort=downloads) returns the following results:

| # | id | downloads |
|-|-|-|
| 1 | multiset | 37315 |
| 2 | hashbag | 363685 |
| 3 | mset | 39412 |
| 4 | hyperloglogplus | 16332 |
| 5 | threshold | 13464 |
| 6 | winter-air | 10209 |
| 7 | utote | 2260 |
| 8 | more_collections | 2207 |
| 9 | sets_multisets | 1030 |
| 10 | winterfell | 900 |

It took me quite a while to realise that `multiset` is placed first here because it matches the search term; the *expected* order would be (row numbers retained to aid referencing):

| # | id | downloads |
|-|-|-|
| 2 | hashbag | 363685 |
| 3 | mset | 39412 |
| 1 | multiset | 37315 |
| 4 | hyperloglogplus | 16332 |
| 5 | threshold | 13464 |
| 6 | winter-air | 10209 |
| 7 | utote | 2260 |
| 8 | more_collections | 2207 |
| 9 | sets_multisets | 1030 |
| 10 | winterfell | 900 |

So with `multiset` with 37315 placed 3rd.

The same applies to `sort=recent_downloads`

### Expected Behavior

When ordering search results by all-time  or by recent downloads, *only sort by those numbers*. An exact keyword match should not matter here, that's what `relevance` sorting is for.

**Comment by Turbo87** [comment]
good catch! I totally agree that this is surprising and unintentional behavior that should be fixed.
