### ISSUE TITLE
.randomUUID is not a function

### ISSUE THREAD

**Issue by 89z** [rust-lang/crates.io#5254]
### Current Behavior

On this page:

https://crates.io/settings/tokens

If I click "New Token", nothing happens. Checking the Console, I see this:

~~~
Uncaught TypeError: l.randomUUID is not a function
~~~

supposedly this was fixed with:

https://github.com/rust-lang/crates.io/pull/5233

but still not working for me.

### Expected Behavior

no

### Environment

- Browser:
- OS:

**Comment by Turbo87** [comment]
@runspired any clue?

**Comment by runspired** [comment]
You have to add crypto for fastboot, and activate the polyfill for older safari or insecure contexts.

**Comment by runspired** [comment]
That said there is one report of embroider code-stripping the polyfill irregardless of setting. Haven't poked at that yet but sounded like an embroider bug.

**Comment by Turbo87** [comment]
we're not using fastboot in prod and the PR above should have enabled the polyfill, but apparently it didn't work? unfortunately @89z did not reveal in which browser this issue occured so but sure how to reproduce it.

**Comment by Turbo87** [comment]
hmm, we are using embroider, so that might be related.

**Comment by 89z** [comment]
Mozilla Firefox

**Comment by 89z** [comment]
> did not reveal in which browser this issue occured so but sure how to reproduce it.

Mozilla Firefox. Until this is fixed, you can manually PUT:

~~~
PUT /api/v1/me/tokens HTTP/1.1
Host: crates.io
Cookie: cargo_session=YMPeZl1wwJDxYTCraGw2hd1X3PP2qEug3zZUSnlwMD0=dXNlcl9pZP8...

{
   "api_token": {
      "name": "hello"
   }
}
~~~

and DELETE:

~~~
DELETE /api/v1/me/tokens/71018 HTTP/1.1
Host: crates.io
Cookie: cargo_session=YMPeZl1wwJDxYTCraGw2hd1X3PP2qEug3zZUSnlwMD0=dXNlcl9pZP8...
~~~

and GET:

~~~
GET /api/v1/me/tokens HTTP/1.1
Host: crates.io
Cookie: cargo_session=YMPeZl1wwJDxYTCraGw2hd1X3PP2qEug3zZUSnlwMD0=dXNlcl9pZP8...
~~~

**Comment by mpalmer** [comment]
I'm seeing this fault on Firefox v91.5.0esr and Chromium 90.0.4430.212, both running on Debian Linux, if that helps with repro.  Thanks for posting that workaround, @89z, that'll get me out of trouble while the Demon JavaScript is wrestled into submission.  For anyone who needs a bit more of a guiding hand, this `curl` command will create a new token:

```sh
curl -X PUT -b cargo_session=<cookie_value> -H 'Content-Type: application/json' --data-binary '{"api_token":{"name":"Token Name"}}' https://crates.io/api/v1/me/tokens
```

The output JSON has the token value in `.api_token.token`.

**Comment by 89z** [comment]
@mpalmer thanks for the update. After I posted that comment, I thought about it some more, and I don't even see why `randomUUID` is needed in the first place. The Cookie is returned from a previous login request, so not needed there. And as can be seen from the sample requests, no random is needed at all.

Which leads me to think its just for some unneeded telemetry. If thats the case, I would strongly suggest just ripping it out. Crates.io is used by millions of people every day, I think they should be catering to a wide base, not forcing people into update treadmills.

**Comment by carols10cents** [comment]
> Which leads me to think its just for some unneeded telemetry.

We do not intentionally do any telemetry in JavaScript.

> Crates.io is used by millions of people every day, I think they should be catering to a wide base, not forcing people into update treadmills.

Please see https://github.com/rust-lang/rfcs/pull/1985 where the community decided on our browser support policy. As a security-focused language, staying on the most up-to-date browsers available is consistent with our community values.

**Comment by 89z** [comment]
> We do not intentionally do any telemetry in JavaScript.

> Please see [rust-lang/rfcs#1985](https://github.com/rust-lang/rfcs/pull/1985) where the community decided on our browser support policy. As a security-focused language, staying on the most up-to-date browsers available is consistent with our community values.

@carols10cents hopefully you can see that these are deflections, so I will try to steer the conversation back on topic. Heres a couple of questions:

1. What is randomUUID even being used for?
2. Is that purpose essential for key management?

If 1 cant be answered, I think it should be removed. If 1 can be answered, but the answer to 2 is "no" (which seems to be the case based on my sample requests), I think it should be removed.

**Comment by mpalmer** [comment]
> As a security-focused language, staying on the most up-to-date browsers available is consistent with our community values.

As a security focused language, requiring the local execution of arbitrary code in order to manage API keys (which, as the `curl` example above shows, is not a *technical* requirement) would seem to be inconsistent with community values, and yet...

**Comment by carols10cents** [comment]
https://github.com/rust-lang/crates.io/search?q=randomUUID

**Comment by 89z** [comment]
@carols10cents https://meta.stackexchange.com/a/8259

**Comment by carols10cents** [comment]
As my link illustrated, `randomUUID` does not appear anywhere in the code of crates.io.

**Comment by 89z** [comment]
@carols10cents I don't understand what you're getting at. If you confirming that `randomUUID` isn't used, then I think that lends to my idea that it can just be removed.

**Comment by carols10cents** [comment]
We can't remove it because *we don't use it*. If you disagree, please send a PR removing `randomUUID` from crates.io's codebase, thanks!

**Comment by 89z** [comment]
@carols10cents checkmate:

https://crates.io/assets/chunk.f697d20072a83b80934e.js

**Comment by runspired** [comment]
It is used, though its usage is able to be configured. Calling part of a core library "arbitrary code execution" is ridiculous: if you don't want your code to ever have any dependencies then why are you even using crates 😉

**Comment by mpalmer** [comment]
> Calling part of a core library "arbitrary code execution" is ridiculous: if you don't want your code to ever have any dependencies then why are you even using crates

Crates are supplied as source, which can be audited, and I can decide which crates to include in my project.  Giant blobs of minified JS shipped directly into my browser that I can't disable while still being able to reasonably use crates.io... not so much.

**Comment by runspired** [comment]
1886 called and would like their horses-are-better old-fogie back

**Comment by 89z** [comment]
why does every thread have to devolve into childish comments FFS. Anyone who actually took the time to investigate the issue, would know that this is a valid issue. Instead we have people posting *GitHub search results*, including *Rust members*, thinking that somehow is a valuable contribution to the conversation. Please just stop and keep it technical. I don't post issues lightly, as was hopefully demonstrated by my later comments with example requests and such. I did at least some research before throwing up an issue.

**Comment by runspired** [comment]
@89z 

> If you confirming that randomUUID isn't used, then I think that lends to my idea that it can just be removed.

To answer your question: when a new resource is created on a client EmberData creates and assigns it a UUID. This allows it to be serialized for local caches and restored and enables applications to do transactional, nested, or sidechanneled persistence requests with their API without accidentally ending up with duplicate cache entries.

Using a UUID for this is just the default behavior, applications can decide instead to just assign an incrementing counter or some other identifier string based on their actual use cases and needs.

**Comment by 89z** [comment]
> To answer your question: when a new resource is created on a client EmberData creates and assigns it a UUID. This allows it to be serialized for local caches and restored and enables applications to do transactional, nested, or sidechanneled persistence requests with their API without accidentally ending up with duplicate cache entries.

Sorry, I only use Vanilla JS(TM), so I don't know what "resource" means in the context you are talking about. If its just some HTML fragment, then I assume a monotonically increasing integer would work just as well, and use less memory in many cases. Not to mention, it has the benefit of being *universally available*, as opposed to UUID.

I am all for fancy tools, but time and place. HTML fragments are not crypto sensitive database stuff that needs the benefit of UUID. Of course I am a rookie on this stuff, so you can probably have a good argument for why its needed.

> Using a UUID for this is just the default behavior, applications can decide instead to just assign an incrementing counter or some other identifier string based on their actual use cases and needs.

whoops, I should have read your full comment hehe.

**Comment by runspired** [comment]
This has nothing to do with html. EmberData is a library for managing network requests and data in an application. A resource in this client is an entity your API would generally treat as unique (such as a user, or post, or based on the report here a token)

**Comment by 89z** [comment]
How long does it take for this to go live? Just checking so I know when to follow up

**Comment by Turbo87** [comment]
the bugfix was deployed on 2022-10-02T20:53:30Z
