### ISSUE TITLE
Allow deletion of crates within 24 hours of publishing

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#5293]
NPM has this policy to better handle accidental publishing.

**Comment by Turbo87** [comment]
@carols10cents did you mean to say "Allow deletion of crate **versions**"? At least that is what I would expect 😅

**Comment by carols10cents** [comment]
Well if you create the only version of a crate, then I think people would expect the entire crate would be deleted and available for someone else to claim again, right?

**Comment by Turbo87** [comment]
yes, that would be the consequence :)

**Comment by ThrashAbaddon** [comment]
I like this. For every package in the company we have `publish = false` in `Cargo.toml` for _just in case_.

**Comment by wildwestrom** [comment]
I think it's a good idea. Pretty harmless. 
You can't be that invested in a crate if you just depended on it within 24 hours of publishing.

**Comment by Turbo87** [comment]
- https://github.com/rust-lang/rfcs/pull/3660 is open now to adjust our policies to allow this
