### ISSUE TITLE
Most relevant results are listed last

### ISSUE THREAD

**Issue by jpryne** [rust-lang/crates.io#5312]
### Current Behavior

When I search for "bevy_rapier" sorted by Relevance, I expect to see "bevy_rapier2d" & "bevy_rapier3d" at the top of the list. Instead, they are at the bottom of the results. The top result is "bevy-inspector-egui-rapier", which, while it is related, is not what I'm looking for.

### Expected Behavior

I expect to see "bevy_rapier2d" & "bevy_rapier3d" at the top of the list.

### Steps To Reproduce

1. Go to crates.io
2. Be sure "Most Relevant" is selected in the Search Results pulldown menu.
3. Search for "bevy_rapier"
4. Find "bevy_rapier2d" & "bevy_rapier3d" at the end of list list.

### Environment

- Browser: Chrome, latest
- OS: Windows 10 64

**Comment by Turbo87** [comment]
thank you for the report. there are quite a few other reports about the suboptimal search results though, so I will close this one as a duplicate for now :)
