### ISSUE TITLE
Support Gitlab badges

### ISSUE THREAD

**Issue by Susurrus** [rust-lang/crates.io#537]
In addition to AppVeyor and Travis it'd be good to support Gitlab CI badges. I use AppVeyor for Windows, but use Gitlab CI for Linux build testing and I'd like to have both badges shown for my crate. Documentation for their badges is here: https://gitlab.us/help/user/project/pipelines/settings.md#badges

I'll try to whip up a PR for this in the next few days if I have time, I'm mostly posting this issue to see if a PR for this would be accepted before I spend my time on it.

**Comment by carols10cents** [comment]
Yes!! ❤️ ❤️ ❤️ We started with the most popular ones, but I would love to have gitlab too, personally, as well as any other CI services. We explicitly thought about extensibility in the way it's implemented-- let me know if you have any questions when you're working on it!
