### ISSUE TITLE
Document how to cargo publish to local installation

### ISSUE THREAD

**Issue by ralph** [rust-lang/crates.io#54]
I'm currently having a hard time figuring out how to push to my local crates.io installation. The `--token` part is pretty clear, but I don't know what to use as `--host`. I tried setting it to my local rust server `http://localhost:8888`, but from what I can see in the log it tries to do some kind of git request. So I forked the central https://github.com/rust-lang/crates.io-index repository, adjusting the https://github.com/rust-lang/crates.io-index/blob/master/config.json file to point to my local rust server, but I'm still getting an error:

```
cargo publish --host https://github.com/ralph/crates.io-index --token XrD3BRBV4IH1yxBw5sNMVWjS66ruVEbq --verbose                                                                                      ⏎ ✱
    Updating registry `https://github.com/ralph/crates.io-index`
Warning: manifest has no description or license. See http://doc.crates.io/manifest.html#package-metadata for more info.
   Uploading zcolor v0.0.1 (file:///Users/ralph/Documents/work/rust/color-rs)
http error: Couldn't connect to server
```

(That's my local crates.io token in the snippet.)

I'm trying to push the color-rs package (https://github.com/bjz/color-rs) from the Guide (http://doc.crates.io/guide.html), btw., but have the package name changed to `zcolor`.

Can you help me publish to my local crates.io? I'd like to have a few packages in there, in order to be able to play with the Ember code.

Also, is there a better way to get sample data?

**Comment by metaclips** [comment]
Hello @ralph how were you able to generate your token locally
