### ISSUE TITLE
README doesn't specify what the 'database' is for TEST_DATABASE_URL

### ISSUE THREAD

**Issue by Susurrus** [rust-lang/crates.io#541]
I'm working on committing to crates.io, but I don't know how to run the official tests because I don't know what "database" means in the context of the README, specifically what kind of database the `TEST_DATABASE_URL` should point to. Both the database type and minimum version information is missing I think.

**Comment by carols10cents** [comment]
Great suggestion! I've added some docs in #550, wdyt?

**Comment by Susurrus** [comment]
Awesome, that's very helpful. That seems clear and concise, though I didn't follow the instructions to test, but I can do that if you'd like (tomorrow I'll probably have time).
