### ISSUE TITLE
Recent download count higher than all-time

### ISSUE THREAD

**Issue by allan2** [rust-lang/crates.io#5419]
### Current Behavior

I recently published a new crate. When I searched for it on crates.io, I saw this:
![new-crate-search-page](https://user-images.githubusercontent.com/6740989/200065211-f362bfde-0b8d-4f7c-ae2e-426e49ff343c.png)

The response body of *https://crates.io/api/v1/crates/my-crate-name* contained `"downloads": 2` and `"recent_downloads": 4`.

**Comment by carols10cents** [comment]
The all-time count is processed in a background job, so it can be delayed. Not sure what to do about that.
