### ISSUE TITLE
Feature request: Show crates' deprecated status in the search result list.

### ISSUE THREAD

**Issue by zoumi** [rust-lang/crates.io#542]
Is it possible show crates' deprecated status in the search result list or filter out deprecated crates?

**Comment by carols10cents** [comment]
We'd have to decide on a way for crates.io to tell that a crate is deprecated first, it's not possible to display that right now :) There's some discussion on this in rust-lang/rfcs#1824 (warning: there's lots of comments, search for "maintenance" to find some relevant discussion), but there isn't consensus on the best way to indicate this yet.
