### ISSUE TITLE
Download count in graph doesn't match recent download count

### ISSUE THREAD

**Issue by allan2** [rust-lang/crates.io#5420]
### Current Behavior

My new crate has a recent download count of 4.

The graph is showing a count of 5, both in the y-axis and also in the overlaid value. 
![Download graph](https://user-images.githubusercontent.com/6740989/200067441-55e7f22d-9c23-43b7-9318-e44bc6c6e75b.png)

### Expected Behavior

The graph count should match the recent download count.

### Anything else?

#5419 related, but that one is for recent count exceeding all-time count.
This issue is for graph count not matching the recent count.

**Comment by Turbo87** [comment]
While the other issue (#5419) is something we can work around, the graph is hard to fix. The whole download counting system is eventually consistent, so at some point all the downloads will be counted correctly, they are just not updated instantaneously. If you have an idea on how we can fix this I'm happy to discuss it though :)
