### ISSUE TITLE
Document applying categories/adding new categories

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/crates.io#544]
Looking through the categories on crates.io I see no information on how to apply these categories to my own crate/add new categories. I assume there are plans to document this, but I couldn't see any open issue about it.

Maybe as a first step http://www.integer32.com/2017/01/20/categories-and-ci-badges.html could be linked to from the categories page, or the relevant part of it could be replicated as a "Categories" doc page on crates.io; @carols10cents what do you think?

**Comment by carols10cents** [comment]
There is documentation here: http://doc.crates.io/manifest.html#package-metadata

Where would you expect to look for it that we could link to that?

**Comment by Nemo157** [comment]
Ah, cool, I guess that makes sense for how to apply them. I can't remember where I looked in the docs, but that's exactly where I would expect to find them so I guess I must not have been looking too hard 😕

I was almost expecting a link somewhere near the footer to a page describing how to submit new categories. At least while the feature is new and the categories need filling out making this very obvious seems helpful.

**Comment by carols10cents** [comment]
Yeah, a footer sounds good. I'm thinking:

- At the bottom of the ["All categories" page](https://crates.io/categories) (markup in [categories.hbs](https://github.com/rust-lang/crates.io/blob/master/app/templates/categories.hbs))
- Add a link to https://github.com/rust-lang/crates.io/blob/master/src/categories.toml#L1-L3 that says something like "how to propose a new category to this page"
- Add a link to http://doc.crates.io/manifest.html#package-metadata that says something like "how to put your crate in a category"

Does that sound good?

**Comment by Nemo157** [comment]
Sounds good to me 😀

**Comment by treiff** [comment]
I'll take look at this. 😄

**Comment by treiff** [comment]
Sorry everyone, been super busy lately and not sure when I'll get to this so have at it.

**Comment by jdno** [comment]
It has been a while since the issue has been opened, so I'm wondering if this is still desired? If so, this seems like a good first issue I'd like to pick up. 🙂

**Comment by carols10cents** [comment]
Sorry this has been a while since you commented, but yes, this is still desired! Please feel free to open a pull request, @jdno or anyone else reading this!
