### ISSUE TITLE
Downloads are being displayed on the wrong day following daylight saving

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/crates.io#5477]
### Current Behavior

The following screenshot is from `quote`'s downloads (https://crates.io/crates/quote) but the same pattern is visible in the downloads graph of *all* widely used crates.

<img src="https://user-images.githubusercontent.com/1940490/201798660-66fa677a-dd0b-4a42-9f83-a2a887352e72.png" width="400">

I am viewing the page in US Pacific Standard Time (UTC -8) but I don't know if that makes a difference.

Notice how there is a very obvious difference between weekday downloads (high) and weekend downloads (low) which is historically extremely well established for pretty much all widely used crates.

Notice anything strange? One of the weekends is missing a day. The missing day is November 6 which is the day that US clocks move back 1 hour for the end of daylight saving time. I highly doubt that this is a coincidence.

Prior to DST ending, all the points showing low are Saturdays and Sundays, like October 29 and October 30. After DST ending, all the points shown low are Fridays and Saturdays, like November 11 and November 12.

Based on my understanding of typical download trends and patterns on crates.io, I do not believe that this is a real phenomenon in the correct data. I believe the data is either being collected wrong or being plotted wrong.

Here is the corresponding download counts for the same crate from the crates.io database dump (https://crates.io/data-access):

```console
2022-10-29  107667 (weekend)
2022-10-30   93257 (weekend)
2022-10-31  250133
2022-11-01  264847
2022-11-02  282642
2022-11-03  285118
2022-11-04  258680
2022-11-05  118764 (weekend)
2022-11-06  109690 (weekend)
2022-11-07  281916
2022-11-08  318215
2022-11-09  295067
2022-11-10  289740
2022-11-11  237139
2022-11-12  114835 (weekend)
2022-11-13  108130 (weekend)
```

This data appears correct as far as I can tell. 2022-11-06 is low in the database dump but is incorrectly shown high in the graph, as is 2022-11-13. Meanwhile 2022-11-11 is high in the database dump but is rendered low on the graph.

### Expected Behavior

The data rendered in the graph should match the download counts in the database dump.

### Steps To Reproduce

Go to https://crates.io/crates/quote, maybe in a negative (West) UTC offset that recently ended daylight saving.

**Comment by Turbo87** [comment]
timezones... always fun 😅 

anyway, thanks for reporting. I'll look into it :)

**Comment by Turbo87** [comment]
![Bildschirmfoto 2022-11-15 um 11 44 27](https://user-images.githubusercontent.com/141300/201920343-4674b901-f142-4c9c-bbd9-f456b5d747a8.png)

the good news is: the API appears to return the right numbers

the bad news is: whatever timezone I use, I can't reproduce the issue above... :-/

**Comment by Turbo87** [comment]
<img width="483" alt="Bildschirmfoto 2022-11-15 um 04 29 39" src="https://user-images.githubusercontent.com/141300/201920550-bb8f093e-8ee1-4311-af71-b3f52ce3d51a.png">

the good news is: the API appears to return the right numbers

the bad news is: whatever timezone I use, I can't reproduce the issue above... :-/

**Comment by dtolnay** [comment]
I am not seeing it anymore either on the same machine. :confused: I guess it was a bug in a dependency, fixed by #5470 or some other recent update? Thank you for investigating.

Actually let me try to remember to check again exactly 24 hours after yesterday's screenshot, 4:45pm local time, which is suspiciously between midnight and 1am UTC, exactly the range that might screw things up when there is a 1-hour offset. I'll close the issue if it doesn't reproduce then.

<img src="https://user-images.githubusercontent.com/1940490/201983091-6e354bd9-9f8e-4bc8-aee5-07577bdde141.png" width="400">

**Comment by dtolnay** [comment]
Yeah it's broken again as soon as UTC hit midnight. Presumably for the next hour.

**Comment by a1phyr** [comment]
This is probably the same issue than #3093. In that case it came back to normal soon after.
