### ISSUE TITLE
Dependent Crates Link is broken for some users on Live

### ISSUE THREAD

**Issue by danielbodart** [rust-lang/crates.io#553]
Clicking the dependent crates link shows "Crate not found" for some users:

For example on lazy static:

https://crates.io/crates/lazy_static/reverse_dependencies

Shows:

http://imgur.com/a/szSaC

In the console the following URL is 404ing:

https://crates.io/crates/lazy_static/api/v1/crates/lazy_static/reverse_dependencies?page=1&per_page=10&_=1486799702812

This appears to be a per user problem so maybe it's relying on Ember state or a cookie. I.e some users it works for.

Have tried in Chrome and Firefox, logged in and out. Note was logged out to start so if feature requires to be logged in maybe it's caching the error.

**Comment by carols10cents** [comment]
Looking into this now. I deployed an upgrade to ember last night, so that might be the cause.

**Comment by carols10cents** [comment]
Yup, the ember upgrade seems to be the cause, I've rolled back that deploy til I figure out what the issue is. Thanks!
