### ISSUE TITLE
Index may need squashing again

### ISSUE THREAD

**Issue by ilyapopov** [rust-lang/crates.io#5563]
Last time index was squashed was on 2022-08-31. Since then, it accumulated 67k commits. Fetching the index becomes painfully slow on weaker machines. 

I understand that switch to HTTP index should happen "soon", but in the meanwhile index may need squashing again.

Previously, index squashing was discussed at https://github.com/rust-lang/crates-io-cargo-teams/issues/47 , but that repository has been archived, and I don't see any obvious place where this is discussed, and therefore open this issue. 

CC @jtgeibel

**Comment by Eh2406** [comment]
Thank you for opening, and you are correct that it is needed. 
It is being discussed at:

https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/When.20will.20the.20next.20crates.2Eio-index.20squash.20be.3F

**Comment by Turbo87** [comment]
The index has been squashed today. The `master` branch is down to a couple of commits again now.
