### ISSUE TITLE
Expose all download history through the API

### ISSUE THREAD

**Issue by Eh2406** [rust-lang/crates.io#557]
Hi,

What is the best way to get the download history for all crates? The data is publicly available by scraping the graphs out of each crates page, but that is rude and inelegant.

If the data is available, how can I improve the docs to make it easier to find?
If it is not available, what can I do to add that functionality?

**Comment by alexcrichton** [comment]
Right now the only route for this is the [downloads route](https://github.com/rust-lang/crates.io/blob/e0d46b31e5950c8057c5800a833e89856f4a6a93/src/krate.rs#L993-L1043) but that just provides the data you see rendered already. I don't believe there's a route for a historical paginated version of this. Adding one would be fine though!

**Comment by Eh2406** [comment]
Thank you for that link! I will try and grok the code and open a pr. So far I mostly have questions. :-P

I think the comment may be out of date or I don't know how to read it, the link [/crates/quadrature/downloads](https://crates.io/crates/quadrature/downloads) just gets me an error. It seems to be maching [L89: "/crates/:crate_id/:version"](https://github.com/rust-lang/crates.io/blob/e0d46b31e5950c8057c5800a833e89856f4a6a93/src/lib.rs#L89) insted of line [L94: "/crates/:crate_id/downloads"](https://github.com/rust-lang/crates.io/blob/e0d46b31e5950c8057c5800a833e89856f4a6a93/src/lib.rs#L94).

Is there some kind of caching for `tx.prepare(` or are we rebuilding with each request?

Is there some kind of caching for the website? All the download counts (except for today's data) are going to be static, seems a shame to hit the database repeatedly.

Is there a schema for the tables that we can query?

**Comment by alexcrichton** [comment]
Nah currently we don't have any caching, everything hits the database. Also there's currently no caching around `tx.prepare(..)`. The schema is probably best looked at by following the README to prepare a local database and exploring that.

**Comment by Eh2406** [comment]
I will experiment with a locale instance when I have a chance. :-)

How do I hit the "/crates/:crate_id/:version" target? Everything I try just gets me error messages.

**Comment by alexcrichton** [comment]
This should do the trick:

```
curl -H 'Content-Type: application/json' https://crates.io/api/v1/crates/libc/downloads
```

**Comment by Eh2406** [comment]
Concrete suggestion:
Add an `offset` query parameter to [`version::downloads`](https://github.com/rust-lang/crates.io/blob/master/src/version.rs#L308). This value is the number of days ago the most recent result will be from.
```rust
let offset = req.query().get("offset").parce().unwrap_or(0);
let cutoff_date_end = ::now() + Duration::days(-offset);
let cutoff_date_start = cutoff_date_end + Duration::days(-90);
```
This is primarily the smallest change I can think of to make the data available.

**Comment by Eh2406** [comment]
Alternative suggestion:
Add a `page` query parameter to `version::downloads`. This is the number of 90 day units ago to get.

```rust
let offset = req.query().get("page").parce().unwrap_or(0);
let cutoff_date_end = ::now() + Duration::days(-90 * offset);
let cutoff_date_start = cutoff_date_end + Duration::days(-90);
```

Are these at all an acceptable iday? How can these ideas be improved?

**Comment by carols10cents** [comment]
Sure, paging sounds great and would match other endpoints' interfaces.

**Comment by sgrif** [comment]
Random note if that endpoint is using Diesel by the time someone gets to it -- it can be done entirely in SQL as

```rust
use diesel::expression::dsl::*;

let cutoff_end_date = now - (90 * offset).days();
let cuttof_start_date = cutoff_end_date - 90.days();
```

**Comment by sgrif** [comment]
> Also there's currently no caching around tx.prepare(..).

All of the endpoints moved to Diesel do! ;) https://github.com/diesel-rs/diesel/blob/428db9515e5c7769a9313b4cf9bc14f1ced290e7/diesel/src/connection/statement_cache.rs

**Comment by Eh2406** [comment]
Closed in https://github.com/rust-lang/crates.io/pull/611
