### ISSUE TITLE
Weirdness on Windows Phone

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/crates.io#56]
https://news.ycombinator.com/item?id=8640487

**Comment by carols10cents** [comment]
Since the screenshot in the HN post is gone, I'm looking for general weirdness on windows phones I guess? Anyone know of any?

**Comment by carols10cents** [comment]
I asked on twitter and didn't get any screenshots of anything that isn't broken for all mobile layouts, so I'm closing this. If anyone finds any suspected window phone weirdness, please post a screenshot! ❤️

**Comment by mdekstrand** [comment]
A couple that I have found quickly on Windows Phone 8.1:

![wp_ss_20170222_0001](https://cloud.githubusercontent.com/assets/186612/23231515/5e8226f8-f905-11e6-809f-1a4de887cfb1.png)

![wp_ss_20170222_0002](https://cloud.githubusercontent.com/assets/186612/23231520/629f8f50-f905-11e6-9756-d57e5028ca66.png)

**Comment by Rekeyea** [comment]
It is shown correctly on Edge on Windows 10 Mobile

**Comment by michallepicki** [comment]
I confirm the same issues as @mdekstrand 's on screenshots, also Windows Phone 8.1. On Windows 10 mobile it looks fine though.

**Comment by mdekstrand** [comment]
Probably not worth fixing then - Win Phone 8.1 is effectively EOL (no security updates in quite some time).

**Comment by carols10cents** [comment]
Ahahaha that is quite broken! Probably flex-box just doesn't work at all. Thank you for investigating for me-- if yinz think it's not worth fixing, then I guess we'll just let it be...
