### ISSUE TITLE
Translation is blocked, anti-multilingualized

### ISSUE THREAD

**Issue by falsandtru** [rust-lang/crates.io#5625]
### Current Behavior

Chrome's builtin translation feature is not usable on crates.io because crates.io is explicitly blocking translation as follows. Why is crates.io anti-multilingualized?

```html
// crates.io
<html lang="en" class="notranslate" translate="no">
```

### Expected Behavior

Machine translatable.

```html
// crates.io
<html lang="en">
```

### Steps To Reproduce

1. Open crates.io.
2. Translate it from address bar or right click menu.
3. Not translated.

### Environment

- Browser: Chrome
- OS: Ubuntu

**Comment by falsandtru** [comment]
I found #4781 but it shouldn't be a permanent solution. Multilingualization is more important than choice of frameworks. No plan to support browser translation for multilingualization?

**Comment by falsandtru** [comment]
As https://github.com/facebook/react/issues/11538#issuecomment-350110297 referenced by #4781, that fix should be "until the underlying issue is fixed". And as the next comment explained, this issue is caused by virtual DOM rather than a framework (if not, there is a bad code somewhere). So you can support in-browser translation tools and multilingualization by using a framework that uses real DOM.

**Comment by falsandtru** [comment]
Can you make a plan or a policy to support in-browser translation tools and multilingualization?

**Comment by Turbo87** [comment]
yes, eventually we would like to support that, but as you can probably imagine it's a nontrivial amount of work to rewrite the whole page in a different framework. since Google translations aren't that great anyway I'd rather see the page translated properly anyway, which also would not require a framework change.

sidenote: this is not a bug since it's working as designed. whether that design is useful is up for discussion, but we have GitHub discussions enabled for things like that 😉

**Comment by falsandtru** [comment]
It is unfortunate that you don't make a plan. FYI, you can make static pages to SPA without a framework using [pjax](https://github.com/falsandtru/pjax-api). However, crates.io is suitable for traditional MPA rather than SPA.

**Comment by falsandtru** [comment]
Ah, I found @Turbo87 is a member of ember. It is impossible to stop using ember even when ember prevents multilingualization.

**Comment by jelipo** [comment]
If you still want to use the browser's translation, you can try this script. https://github.com/jelipo/translate-crates-io

**Comment by lanten** [comment]
I made a Chrome extension that solved this problem: https://chromewebstore.google.com/detail/cratesio-translation/faeifcikhbfnlbombjehieklfimahpnc
