### ISSUE TITLE
Add a "Copy to clipboard" button

### ISSUE THREAD

**Issue by Insomgla** [rust-lang/crates.io#563]
When on a page about a crate, we have first to select the content of the text area in order to paste it in the `Cargo.toml` file, which is quite a pain to do when browsing keyboard-only.

It would be a nice little improvement to have a button that copies the content of this textarea directly into the clipboard. Libraries such as https://github.com/zenorocha/clipboard.js seem to be able to handle that pretty smoothly, and is compatible with a broad variety of browsers.

**Comment by carols10cents** [comment]
I'm confused, you'd like a button that you'd click on with your mouse to copy, to make it easier to browse keyboard-only?

**Comment by steveklabnik** [comment]
Even without keyboard-only, this kind of thing is convenient.

Historically, it's required flash, but IIRC the requisite APIs in browsers are starting to land?

**Comment by Insomgla** [comment]
Indeed, such features can now be easily done via Javascript. As for the keyboard-only navigation, that would allow me to use "TAB" to focus on the "copy button" and here we go. Besides, as @steveklabnik said, it's quite convenient anyway.

**Comment by carols10cents** [comment]
Ok, that makes sense, just wanted to make sure I understood! 

So this will involve:

- `bower install`ing [clipboard.js](https://github.com/zenorocha/clipboard.js)
- Adding it to the HTML around [here](https://github.com/rust-lang/crates.io/blob/master/app/templates/crate/version.hbs#L60), setting it up to copy the text in that `code` element
- Testing it out on the major browsers (firefox, chrome, ie, safari?)
- Testing it out with keyboard navigation

If anyone thinking about picking this up has any other questions, please ask! ❤️

**Comment by Insomgla** [comment]
I can try doing it.

**Comment by Insomgla** [comment]
Just a little question, as I'm not really a pro with EmberJS, where do I put my `<script> `thingie so I can initialize `clipboardjs` ?

**Comment by Insomgla** [comment]
Currently trying to implement it. I'll do my best to test on as most browsers as I can.
