### ISSUE TITLE
Differentiate no_std crates

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/crates.io#565]
Is there a way to see whether a crate can be used with `no_std` ? (e.g. always or by activating some feature?)

**Comment by carols10cents** [comment]
Not yet! We did add a [no_std category](https://crates.io/categories/no-std) recently, as a stop-gap until someone implements a better way to identify no_std crates (possibly automatically?)

**Comment by sgrif** [comment]
We've got a duplicate issue #737, which has some more specific ideas on this issue and a bit more discussion, so I'm going to close this in favor of that issue.
