### ISSUE TITLE
better UI for 7-day moving average graphs

### ISSUE THREAD

**Issue by durka** [rust-lang/crates.io#567]
The moving average lines added in #552 initially confused me -- I thought the output was broken. There is no UI describing why the graph has both lines and dots. I suggest either some explanatory text in the graph legend or a toggle to switch between fine-grained and averaged plotting.

**Comment by bstrie** [comment]
I agree that the dots look strange at first glance, though I think the current legend suffices. And I think adding a toggle might be too much, I'd suggest just removing the dots and leaving the ability to hover over a point on the graph in order to see the raw data for that period.

**Comment by remram44** [comment]
When hovering the version numbers, the dots for that version get highlighted but not the line, that looks like a bug.

I suggest just using a checkbox to toggle the 7-day average off. I think using the average for smoothing is fine, but going half-way and showing both is just confusing. The dots just look like noise right now.

**Comment by bburdette** [comment]
this is incredibly hard to read.  colors for the different versions are barely different from each other.  how about put 7 day average into a different graph, or provide a toggle to make it visible for people who care about it?

**Comment by carols10cents** [comment]
I don't think we're going to do this.
