### ISSUE TITLE
crates.io-index has duplicate packages.

### ISSUE THREAD

**Issue by gmjosack** [rust-lang/crates.io#569]
I was unable to vendor `fixedbitset` because it appears in the index for the same version multiple times: https://github.com/rust-lang/crates.io-index/blob/b6019e876b323f4e6e43d597c5e65c09fd345eeb/fi/xe/fixedbitset#L12

Ran a sloppy diagnostic and it seems 2 other packages are also duplicated:

```
crates.io-index$ cat */*/* | sort | uniq -c | sort -n | cut -c -40 | tail -n5
      1 {"name":"zxcvbn","vers":"0.2.1",
      1 {"name":"zxcvbn","vers":"0.3.0",
      2 {"name":"capnp-rpc","vers":"0.1.
      2 {"name":"fixedbitset","vers":"0.
      2 {"name":"quickcheck_macros","ver
```

**Comment by alexcrichton** [comment]
These unfortunately happened so long ago that we don't have logs for all of them, but I'm going to keep digging for the root cause.
