### ISSUE TITLE
API Token page copy is wrong about credentials file

### ISSUE THREAD

**Issue by sinistersnare** [rust-lang/crates.io#5732]
### Current Behavior

It states on the [tokens page](https://crates.io/settings/tokens)

> This will save it to a local file (`~/.cargo/credentials.toml` by default).

### Expected Behavior

But the file for me on MacOS is `~/.cargo/credentials`.

Its not a huge bug, but it could be fixed!

### Steps To Reproduce

1. Go to https://crates.io/settings/tokens
2. With a token added, read the text
3. Notice the text points to a credentials file that probably does not exist.

### Environment

- Browser: Firefox
- OS: MacOS

### Anything else?

Thanks!!

**Comment by Turbo87** [comment]
Not sure why this is popping up twice today, but please take a look at the discussion in https://github.com/rust-lang/crates.io/pull/5730 😉 

crates.io has essentially just copied what's in the cargo documentation, so if that is wrong then it's a bug on that side too :)

**Comment by sinistersnare** [comment]
Sorry! Oh wow thats hilarious.

**Comment by Turbo87** [comment]
closing this, as https://github.com/rust-lang/crates.io/pull/5730 has implemented a fix for now :)
