### ISSUE TITLE
Add rustfmt to run on travis and fail the build

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#575]
After #574 is done, so that we have one commit with all the old code reformatted, I'd like to keep the code formatted nicely going forward by adding rustfmt to Travis like we have jslint that fails the build if the javascript isn't formatted correctly.

So this bug entails:

- Waiting until #574 is done
- Follow [the instructions in rustfmt's README on adding rustfmt to .travis.yml](https://github.com/rust-lang-nursery/rustfmt#checking-style-on-a-ci-server)
- Get the build to pass, if there's code that snuck in between #574 and this one that isn't formatted right
- Add documentation to crates.io's README that we use rustfmt, and point to rustfmt's README for instructions for people working on crates.io to run rustfmt while they're developing if they want

**Comment by ishitatsuyuki** [comment]
rustfmt has awful side effects. Clippy deprecated the approach: https://github.com/Manishearth/rust-clippy/issues/1487

**Comment by carols10cents** [comment]
@ishitatsuyuki Are you talking about the contributor-scaring-away side effects? We already have jslint that fails the build if the javascript isn't formatted right, and I have seen PRs that contributors have had the jslint check fail and then they fix it and push another commit, which hasn't seemed to be a deterrent to contributing. I'd like to try, and I'll be here to help people understand... 

If those aren't the awful side effects you're talking about, could you elaborate please? Thanks!

**Comment by ishitatsuyuki** [comment]
rustfmt could generate wrong, or unintended ugly output. See the clippy issue for details.

**Comment by carols10cents** [comment]
Wrong output sounds like a bug in rustfmt, and more users of rustfmt would help find and fix these bugs. 

Ugly is in the eye of the beholder; what I'm trying to solve here is consistent code formatting.

Unintended sounds like something we could add a rustfmt ignore annotation to. 

I don't see anything egregious in the issues linked in that clippy issue, I remain unconvinced that we shouldn't even try.

**Comment by ishitatsuyuki** [comment]
At least, we would get a failure even when the code is not wrong (only formatting problems), and that looks bad. Clippy's PR list was filled with failed statuses before, which was caused by probably broken formatting in master.

**Comment by vignesh-sankaran** [comment]
Hey, is this still an issue that is still blocked? If so, what's the block?

**Comment by carols10cents** [comment]
I forget why I added the blocked label, tbh!

**Comment by carols10cents** [comment]
Closed by #771!
