### ISSUE TITLE
cmd-enter on macOS to submit the search field doesn't open the results in a new tab

### ISSUE THREAD

**Issue by nox** [rust-lang/crates.io#579]

**Comment by carols10cents** [comment]
Which browser(s) please? Trying to figure out whether this is a browser-specific problem or not.

I'd also be interested to know if this is a macOS specific problem or if this is also a problem for control-enter on Windows and Linux (and across browsers there too). Anyone reading this on those OSes, could you try it out for me and report back?

**Comment by elliotekj** [comment]
OS X 10.11.6:

- Chrome 56: cmd-enter does nothing
- Safari 9.x: cmd-enter submits the search in the same tab
- Firefox 54: cmd-enter submits the search in the same tab

GitHub used to have this behaviour in Chrome when searching and that's no longer working for me, though that may simply be due to the new header(?). The number of relevant bug reports on their respective issue trackers would suggest that this behaviour is something that's usually implemented at the browser level by vendors. I haven't found a reason as to why none of them support it anymore though.

**Comment by Insomgla** [comment]
I don't have this feature on Chromium, using ArchLinux. Or I don't know how to use it :)

**Comment by nox** [comment]
> I don't have this feature on Chromium, using ArchLinux. Or I don't know how to use it :)

Don't have it how? On crates.io or in general?

**Comment by nox** [comment]
I filed https://bugs.chromium.org/p/chromium/issues/detail?id=698196.

**Comment by Insomgla** [comment]
In general

**Comment by nox** [comment]
Could anyone tell me how that can be fixed? I'm willing to write the patch myself if no one else wants to fix that papercut.

**Comment by nox** [comment]
Ping on this? This is still not working for me.

**Comment by nox** [comment]
This is still broken.

**Comment by locks** [comment]
I've done a bit of investigating and I believe that the search is behaving as it should and it is not something we want to address as we would be introducing a bunch of specific logic for this case.
Thanks for reporting and I hope you understand the position 🙇

**Comment by nox** [comment]
This still doesn't work correctly, cmd-enter doesn't open the results in a new tab, unlike 99% of the rest of the Web.

**Comment by Turbo87** [comment]
@nox do you have a link to the browser spec that specifies this as default behavior? I've tried to search for it but I can't find anything. It seems to work here on GitHub, but even if I remove the JS-based submit handler and let the regular form submission do its thing it doesn't work for the crates.io page. I'm wondering if that is indeed regular browser behavior or just something that is custom-built at GitHub.

I've also tested this with the following snippet:

```html
<form action="/test">
  <input name="test">
  <button>submit</button>
</form>
```
and it doesn't work either, so I'm not so sure about your "This still doesn't work correctly" assumption.
