### ISSUE TITLE
Consider migrating from Rust-Postgres to Diesel

### ISSUE THREAD

**Issue by Eh2406** [rust-lang/crates.io#588]
Diesel has better performance at runtime and moves errors to compile time. This sounds like a win win.

However, they are both good libraries, and diesel is under active development. So, it is an open question whether it is worth migrating. I hope this can be a place for that discussion to happen.

**Comment by steveklabnik** [comment]
Tagged with those tags.

I know @sgrif has said that this is a pre-req for diesel 1.0, but I don't think we as a team have made the decision to actually do this, just that it's something I know he tries from time to time.

**Comment by Eh2406** [comment]
Maybe next time he or someone else tries it, they can leave a link hear. It would be a great demo/blog of how to do a migration, if nothing else.

**Comment by sgrif** [comment]
Last I heard everyone on the team was open to it, it's just missing a PR. I had planned to lay out a "we can do this in small chunks" PR some time soon, but my daughter came earlier than expected and I haven't had time. If nothing else, I think the biggest step would be to confirm that we would be interested in doing this, and lay out the groundwork required to move one module or one method over at a time. I don't think anybody wants to review a "port the whole project over to Diesel" PR in one go.

**Comment by carols10cents** [comment]
I am interested in doing this! And yeah, incremental would be awesome.

**Comment by sgrif** [comment]
Ok. I'll open a PR.

**Comment by carols10cents** [comment]
There are PRs out for the rest of this, I just need to review them!

**Comment by sgrif** [comment]
I think we can safely close this issue though at this point. It's been thoroughly considered. :D
