### ISSUE TITLE
Non-ASCII crate names don’t seem to work

### ISSUE THREAD

**Issue by ftxqxd** [rust-lang/crates.io#59]
``` bash
$ cargo new áccênts
$ cd áccênts
$ cargo publish
    Updating registry `https://github.com/rust-lang/crates.io-index`
Warning: manifest has no license. See http://doc.crates.io/manifest.html#package-metadata for more info.
   Uploading áccênts v0.0.0 (file:///home/me/%C3%A1cc%C3%AAnts)
failed to get a 200 OK response: Response {500, content-length: 30, server: nginx, via: 1.1 vegur, connection: keep-alive, date: Sat, 22 Nov 2014 01:35:10 GMT, Error 404: Not Found
Not Found]
```

I’m not sure if this a Cargo bug or a crates.io bug. Should non-ASCII crate names be allowed at all (at this stage)?

**Comment by JonasOlson** [comment]
Is there somewhere one can see a specification of what names are allowed?

**Comment by dtolnay** [comment]
@JonasOlson this is the current crate name validation logic:

https://github.com/rust-lang/crates.io/blob/54a3f10794db7f57e3602426389c369290a8a3d5/src/views/krate_publish.rs#L73-L80

https://github.com/rust-lang/crates.io/blob/54a3f10794db7f57e3602426389c369290a8a3d5/src/models/krate.rs#L252-L264

https://github.com/rust-lang/crates.io/blob/54a3f10794db7f57e3602426389c369290a8a3d5/src/models/krate.rs#L276-L281

https://github.com/rust-lang/crates.io/blob/54a3f10794db7f57e3602426389c369290a8a3d5/src/models/krate.rs#L73

**Comment by JonasOlson** [comment]
@dtolnay: Thanks. And then there are [reserved names](https://github.com/rust-lang/crates.io/search?p=1&q=reserved_crate_names), I understand (though I don't know what "migrations", which appear as the name of a directory in the path, are).
