### ISSUE TITLE
Make the "fork me on github" ribbon appear on narrower widths/zoomed in

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/crates.io#596]
When I wanted to report an issue with the crates.io site, I didn't immediately know where to look.

It would be good if the site had one of those "fork me on github" ribbons; then someone could just click on that if they want to file an issue (or contribute!)

**Comment by carols10cents** [comment]
. . . we have one of those though. . . 

<img width="1272" alt="screen shot 2017-03-06 at 10 52 09 am" src="https://cloud.githubusercontent.com/assets/193874/23617421/13338714-025b-11e7-83fc-c573d0b1f982.png">

It's on individual crate pages too:

<img width="1264" alt="screen shot 2017-03-06 at 10 53 06 am" src="https://cloud.githubusercontent.com/assets/193874/23617443/26110366-025b-11e7-9760-e05cb27bfab1.png">

Is there a page that doesn't have this ribbon in the upper right?

**Comment by pnkfelix** [comment]
ah my browser windows are narrower than yours, and the ribbon disappears when the window is sufficiently thin.

**Comment by pnkfelix** [comment]
Example of "sufficiently thin": 

<img width="1173" alt="image" src="https://cloud.githubusercontent.com/assets/173127/23619152/034ccf12-0293-11e7-842f-ddf10523ec17.png">

**Comment by carols10cents** [comment]
Whew, ok, I thought I was really losing it :)

**Comment by Insomgla** [comment]
I think this raises a bigger issue. Many issues in the UI category make me wonder: why not redoing a design from scratch, using a mobile-first grid system (be it bootstrap, semantic ui, or anything else). 

There are many inconsistencies with the current design on narrow screens, but I don't think its worth pointing them out, I think a complete redesign would be easier to do than monkey-patching everywhere. 

If such a decision was taken, please count me in, I may be a bad Rust developper, but as far as front end design go, that's another story :p

**Comment by carols10cents** [comment]
@Insomgla yes, there's actually [a PR for a new design](https://github.com/rust-lang/crates.io/pull/347) that's been outstanding, and [another issue](https://github.com/rust-lang/crates.io/issues/223) that links to other PRs.

I know @aturon has thought about doing a redesign that unifies crates.io and rust-lang.org (which needs some Information Architecture work as well), but that's a bigger project that might need to go through the RFC process (or at least needs research with a variety of stakeholders). This is likely to be contentious with the community, and is tough to do incrementally.

Would you be up for leading a design effort like that?

**Comment by Insomgla** [comment]
I would 100%

**Comment by carols10cents** [comment]
@Insomgla Could you send me an email please? carol.nichols@gmail.com. Thanks!

**Comment by ehuss** [comment]
At certain widths, the "fork me" link overlaps with my username. Attempting to click on this region of my name takes me to GitHub.

<img width="232" alt="image" src="https://user-images.githubusercontent.com/43198/59161691-adfac400-8a9a-11e9-983b-1c265a6f803f.png">

Perhaps some z-index trickery or a non-rectangular click box could be used to avoid that.

**Comment by locks** [comment]
I personally think that the ribbon looks very out of place in crates.io, and an eventually design could provide better UI for both going to a crate's repository as well as contributing to crates.io itself.

**Comment by Turbo87** [comment]
the ribbon has been converted to a link in the footer, so this issue no longer applies :)
