### ISSUE TITLE
Docker Compose; Migrations failed; error applying hunk #1; Custom ports

### ISSUE THREAD

**Issue by zifik** [rust-lang/crates.io#6018]
### Current Behavior

Running via docker-compose the logs continuously show

```
backend_1   | error applying hunk #1
backend_1   | Migrations failed, retrying in 5 seconds...
backend_1   | error applying hunk #1
backend_1   | Migrations failed, retrying in 5 seconds...
```

### Expected Behavior

No errors

### Steps To Reproduce

1. Clone the latest master branch at revision 3f67fb381a5b69b668bc6083e392cdc8fd6b622d
2. Update docker-compose.yml to use custom external ports for postgres `127.0.0.1:5111:5432` and backend `8123:8888`
3. Create `.env` file with custom SESSION_KEY, DATABASE_URL, and POSTGRES_PASSWORD
4. Run `docker-compose up -d; docker-compose logs -f`
5. Postgres DB starts up fine; worker starts downloading crates; frontend looks normal; but backend is broken. After printing out a bunch of `Running migration` lines it gets stuck in the loop applying the migrations.

```
backend_1   | error applying hunk #1
backend_1   | Migrations failed, retrying in 5 seconds...
backend_1   | error applying hunk #1
backend_1   | Migrations failed, retrying in 5 seconds...
```

### Environment

Docker

### Anything else?

Front end is accessible on port 4200 in the browser, but backend is stuck printing that error indefinitely. 

I jumped into the backend container with `docker exec` and I was able to verify that it can connect to the database container.  

Can anyone provide some insight into this issue?   Thank you

**Comment by mdtro** [comment]
I'm able to recreate this issue as well.
The `diesel` version installed on the backend container is `2.0.1`.

This also might be relevant: https://github.com/rust-lang/crates.io/discussions/5348

**Comment by Turbo87** [comment]
looks like we should adjust the `backend.Dockerfile` to install the same `diesel_cli` version that CI is also using. PRs welcome :)

**Comment by mdtro** [comment]
Ah, yep! Progress, with version `1.4.1`.

```
cratesio-backend-1   | Migrations failed, retrying in 5 seconds...
cratesio-backend-1   | Command would result in changes to src/schema.rs. Rerun the command locally, and commit the changes.
cratesio-backend-1   | Migrations failed, retrying in 5 seconds...
```

**Comment by Turbo87** [comment]
`2022-11-23-135139_add-token-scopes` is the latest migration that was added. either that one is broken, which seems unlikely since it works on CI, or something else about the setup is causing issues with the `schema.rs`. would be interesting to see what the diff would look like for that file.

**Comment by mdtro** [comment]
Here's the diff I ended up with:

```
root@825fb4082185:/app/src# diff -u schema.rs schema.rs.old
--- schema.rs	2023-02-01 06:01:51.068643373 +0000
+++ schema.rs.old	2023-02-01 05:57:31.991453562 +0000
@@ -675,24 +675,6 @@
 }

 table! {
-    /// Representation of the `recent_crate_downloads` view.
-    ///
-    /// This data represents the downloads in the last 90 days.
-    /// This view does not contain realtime data.
-    /// It is refreshed by the `update-downloads` script.
-    recent_crate_downloads (crate_id) {
-        /// The `crate_id` column of the `recent_crate_downloads` view.
-        ///
-        /// Its SQL type is `Integer`.
-        crate_id -> Integer,
-        /// The `downloads` column of the `recent_crate_downloads` table.
-        ///
-        /// Its SQL type is `BigInt`.
-        downloads -> BigInt,
-    }
-}
-
-table! {
     use diesel::sql_types::*;
     use diesel_full_text_search::{TsVector as Tsvector};

@@ -715,6 +697,24 @@
     }
 }

+table! {
+    /// Representation of the `recent_crate_downloads` view.
+    ///
+    /// This data represents the downloads in the last 90 days.
+    /// This view does not contain realtime data.
+    /// It is refreshed by the `update-downloads` script.
+    recent_crate_downloads (crate_id) {
+        /// The `crate_id` column of the `recent_crate_downloads` view.
+        ///
+        /// Its SQL type is `Integer`.
+        crate_id -> Integer,
+        /// The `downloads` column of the `recent_crate_downloads` table.
+        ///
+        /// Its SQL type is `BigInt`.
+        downloads -> BigInt,
+    }
+}
+
 table! {
     use diesel::sql_types::*;
     use diesel_full_text_search::{TsVector as Tsvector};
```

Steps to re-create:

1. Configure the `backend.Dockerfile` to install `diesel_cli` version `1.4.1` with [a quick edit](https://github.com/rust-lang/crates.io/pull/6021/files).
2. Update the `docker-compose.yml` for the `backend` service to allow writing to the file system. By changing this line to

    ```yaml
        volumes:
           # Mount the src/ directory so we don't have to rebuild the Docker image
           # when we want to change some code
    -     - ./src:/app/src:ro
    +    - ./src:/app/src
    ```

4. Open a shell on the backend container, `docker exec -it cratesio-backend-1 bash`.
5. Copy the original schema, `cp src/schema.rs src/schema.rs.old`
6. Run `diesel migration run` to generate the new schema.
7. `diff src/schema.rs src/schema.rs.old`

The `backend` service reported the below in the logs immediately after manually running the migration command. I can hit the site locally successfully.

```
cratesio-backend-1  | Command would result in changes to src/schema.rs. Rerun the command locally, and commit the changes.
cratesio-backend-1  | Migrations failed, retrying in 5 seconds...
cratesio-backend-1  | tmp/index-bare already exists, exiting
cratesio-backend-1  |    Compiling cargo-registry v0.2.2 (/app)
cratesio-backend-1  |     Finished dev [unoptimized + debuginfo] target(s) in 35.01s
cratesio-backend-1  |      Running `target/debug/server
```

It appears diesel just moved the lines to a new location in the file? I'm not too familiar with how diesel manages migrations. 🙃

**Comment by mdtro** [comment]
It looks like CI isn't running the migration command, but rather: `diesel database setup --locked-schema`
https://github.com/rust-lang/crates.io/blob/f119cc1c3952c4b10a644a729a3afc71a0d5edb7/.github/workflows/ci.yml#L120

The `docker_entrypoint.sh` for the backend container is running: `diesel migration run --locked-schema`
https://github.com/rust-lang/crates.io/blob/f119cc1c3952c4b10a644a729a3afc71a0d5edb7/docker_entrypoint.sh#L4

I'll try setting up the entrypoint to run the setup command versus migration in the morning and report back (if no one beats me to it). 🙂

**Comment by zifik** [comment]
So I tried doing this myself too following everyone's suggestions

1. I added the version to diesel in the `backend.Dockerfile` as suggested `cargo install diesel_cli --version 1.4.1`
1. I removed `--locked-schema` from `docker_entrypoint.sh`. (This errored out unless I also removed the `:ro` attribute from the `src` folder mount in `docker-compose.yml`

And now it looks like everything started up as it should!  Of course I have a modified `schema.rs` file now.

**Comment by mdtro** [comment]
Just to close the loop here after the migration to Diesel 2.0.x, I was able to get this working correctly on the master branch.

One note however, on the backend build of the Dockerfile, I had to specify `FROM --platform=linux/arm64 rust:$RUST_VERSION` to get it working correctly. It was failing in `apt-get update` in regards to invalid signatures.

I figure it's because I'm on a M1. 🤷
