### ISSUE TITLE
Spurious network error installing large crate — Varnish 503

### ISSUE THREAD

**Issue by bglw** [rust-lang/crates.io#6028]
### Current Behavior

Running `cargo build --release` in GitHub actions and fairly reliably hitting a network error when the crate `lindera-ko-dic-0.17.0` is being downloaded. Error excerpt as shown, from [pagefind CI run](https://github.com/CloudCannon/pagefind/actions/runs/4068933664/jobs/7008075221):

```
error: failed to download from `[https://crates.io/api/v1/crates/lindera-ko-dic/0.17.0/download`](https://crates.io/api/v1/crates/lindera-ko-dic/0.17.0/download%60)

Caused by:
  failed to get successful HTTP response from `[https://static.crates.io/crates/lindera-ko-dic/lindera-ko-dic-0.17.0.crate`](https://static.crates.io/crates/lindera-ko-dic/lindera-ko-dic-0.17.0.crate%60), got 503
  body:

  <?xml version="1.0" encoding="utf-8"?>
  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
  <html>
    <head>
      <title>503 Response object too large</title>
    </head>
    <body>
      <h1>Error 503 Response object too large</h1>
      <p>Response object too large</p>
      <h3>Error 54113</h3>
      <p>Details: cache-iad-kcgs7200110-IAD 1675287753 434188138</p>
      <hr>
      <p>Varnish cache server</p>
    </body>
  </html>
```

`static.crates.io` resolves to Fastly, and this this error looks to match Fastly's [503 Response object too large](https://docs.fastly.com/en/guides/common-503-errors#503-response-object-too-large) error:
> If Fastly determines the object being fetched exceeds the [resource size limit](https://docs.fastly.com/en/guides/failure-modes-with-large-objects#maximum-object-size-limits) of your Fastly service, we will generate a 503 Response object too large response to the client. You can use the [Segmented Caching](https://docs.fastly.com/en/guides/segmented-caching) feature to eliminate these errors.

### Expected Behavior

Asset to download and compilation to continue.

### Steps To Reproduce

I haven't reproduced this on my MacBook locally, but it is now happening _most_ of the time on my GitHub action runs for [Pagefind](https://github.com/CloudCannon/pagefind). It might be hard to setup a reliable reproduction case but I can attempt to do so if it is required. I'm hoping Fastly will have logs available on your end to help dig into this.

### Environment

- Browser: N/A
- OS: macOS runner on GitHub Actions, windows runner on GitHub actions

### Anything else?

Can provide full logs if required, though there doesn't appear to be any extra useful information there beyond the Varnish 503 response.

**Comment by bglw** [comment]
Reading up through Zulip and https://blog.rust-lang.org/inside-rust/2023/01/24/content-delivery-networks.html — I can see the reason this won't reproduce for me locally is that my DNS is still resolving `static.crates.io` to Cloudfront. 

My action runner must be resolving to Fastly (as is `who.is/dns/static.crates.io`) and thus causing a build failure.

**Comment by jdno** [comment]
Thanks for reporting this, @bglw. I've confirmed the issue and disabled Fastly for now so that we have time to implement a solution.

**Comment by jdno** [comment]
The limit has been raised to 50MB and `lindera-ko-dic` seems to download fine through Fastly. Please let me know if you're still experiencing any issues, though.

I'll leave the issue open for now while we monitor the situation.

**Comment by jdno** [comment]
We've been monitoring the traffic over the past two weeks and everything looks fine in our end. I'm going to close the issue, but please let us know if you experience any issues again.
