### ISSUE TITLE
Readme.md not found in Firefox but not in Chrome

### ISSUE THREAD

**Issue by pacak** [rust-lang/crates.io#6080]
### Current Behavior

Crates.io can't find README.md file even though it is present in an archive you get by running `cargo download bpaf`

In firefox

### Expected Behavior

this file should be displayed at 

https://github.com/pacak/bpaf/blob/master/README.md

at this link https://crates.io/crates/bpaf

### Steps To Reproduce

Visit https://crates.io/crates/bpaf

### Environment

- Browser: Firefox
- OS: Linux.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.crates.io/readmes/bpaf/bpaf-0.7.9.html. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.
```

Strangely enough it works in chrome or with other crates

### Anything else?

firefox:
![1](https://user-images.githubusercontent.com/66211/219135202-c3855e54-5b33-4eb3-a481-26b5816cc01c.png)

chrome:
![1](https://user-images.githubusercontent.com/66211/219135263-5d896a63-9c3d-4359-af73-256067db6868.png)

**Comment by Turbo87** [comment]
@jdno did we change anything about the CORS headers when we moved to the new CDN?

**Comment by jdno** [comment]
Sorry for the late reply.

I started looking into this a few days ago, but wasn't able to reproduce it with Firefox on macOS.

> did we change anything about the CORS headers when we moved to the new CDN?

We didn't. But it might still be related.

> Strangely enough it works in chrome or with other crates

My initial guess is that this might've been caused by caching. We're not sending all traffic through the new CDN, so a bad response for `bpaf` might've been cached in Firefox. When trying other crates or a different browser, those requests were sent through the old CDN and worked just fine.

**Comment by jdno** [comment]
@pacak When/if you can still reproduce the issue, can you gather a bit more information for me?

Check DNS:
- Open a terminal
- Run the following command and paste the canonical name here:
   `nslookup static.crates.io`

Copy the request headers from Firefox and Chrome:
- Open https://crates.io/crates/bpaf in each browser
- Open the developer tools and click on the Network tab
- Reload the page and find the request to `static.crates.io` (e.g. with the filter at the top)
- Copy the raw response headers and paste them here

Verify the issue with curl:
- Open a terminal
- Run the following command and paste the output here
   `curl -I https://static.crates.io/readmes/bpaf/bpaf-0.7.9.html -H 'Origin: https://crates.io'`

**Comment by pacak** [comment]
Unfortunately (or fortunately) I'm no longer able to reproduce the issue, problem went away a few days after my initial report - I assumed it was fixed. Maybe it was caused by caching but I tried to reload it with Ctrl-F5 so not sure. I guess it's safe to close the issue now, I'll keep it in mind in case I ever encounter this problem again.

**Comment by jdno** [comment]
We did run less traffic than usual through Fastly during the past week. So if the issue is related, it might come back in the next few days since we're slowly ramping up traffic again. Let's keep the issue open for a few more days.
