### ISSUE TITLE
Peer certificate cannot be authenticated with given CA certificats

### ISSUE THREAD

**Issue by Nixota** [rust-lang/crates.io#6082]
### Current Behavior

Trying to install a package (mdbook) with $ `cargo install mdbook` on CLI

The system gives the following feedback: 

>   [60] Peer certificate cannot be authenticated with given CA certificates (SSL certificate problem: certificate has expired)

### Expected Behavior

the package should get curl'ed and installed on locale

### Steps To Reproduce

1. CLI/terminal
2. $ cargo install mdbook

### Environment

- Browser:
- OS: mac darwin mojave

**Comment by pietroalbini** [comment]
Is the time and date on your system correct? The certificate should be valid.

**Comment by Nixota** [comment]
Hello, I checked: yes, the OSX Date & Time settings are ok. 

How strange! Just now I repeated the `cargo install mdbook` and everything is downloading correctly. 

Thanks for the help anyhow. Bye.
