### ISSUE TITLE
crates.io taking more time than usual to respond to requests. Everytime it is failing with downloading one or other libraries

### ISSUE THREAD

**Issue by U100-web** [rust-lang/crates.io#6085]
### Current Behavior

crates.io failing to download one or other libraries.

### Expected Behavior

It used to download on time without any issue

### Environment

- Browser:
- OS:

**Comment by Turbo87** [comment]
@jdno might be related to Fastly too? hard to say without such little information though 😅 

@Ushanv any idea when this issue started for you? how is it failing? is it showing any error messages?

**Comment by Ushanv** [comment]
For me build went fine upto Feb 8th. After that next build I executed on Feb 14th. From Feb 14th 2023 , I am facing this issue.
It's during build , it will download few libraries from crates.io . After each run, it is failing to failing to cdownload one or the other libraries.
*** ERROR ***: error: failed to download from `https://crates.io/api/v1/crates/bstr/0.2.16/download`
make: *** [.cargo_libraries] Error 101

**Comment by Eh2406** [comment]
Is there some build system you are using around cargo? What exactly are you running on the command line? Cargo errors normally do not have `*** ERROR ***:` nor `make: *** [.cargo_libraries]`. Also by looking at cargoes code https://github.com/search?q=repo%3Arust-lang%2Fcargo++%22failed+to+download+from%22&type=code it looks like that error message is only attached to an existing error. Could you include the rest of the error?

Also, did you update the version of cargo you were using during that time?

**Comment by Ushanv** [comment]
Yes on build system we using Cargo. No updates are done.
this is one more I saw  - perror(" FB: Error in reading from BSD server\n");

**Comment by Turbo87** [comment]
this appears to be an error that is unrelated to crates.io or cargo itself. please check what custom build system you are using and potentially report an issue there :)
