### ISSUE TITLE
Crates.io API does not correctly set Access-Control-Allow-Origin header when looking up crates that do not exist.

### ISSUE THREAD

**Issue by xfbs** [rust-lang/crates.io#6142]
### Current Behavior

When using the crates.io API (https://crates.io/api/v1/crates/:name) with a crate name that does not exist, no ` Access-Control-Allow-Origin`  header is sent in the response.

### Expected Behavior

When using the crates.io API (https://crates.io/api/v1/crates/:name) with a crate name that does not exist, an ` Access-Control-Allow-Origin: *`  header should be sent in the response.

### Steps To Reproduce

When looking up a crate that exists, the header is set correctly:
` ` ` 
$ curl -v https://crates.io/api/v1/crates/test
...
< access-control-allow-origin: *
...
` ` ` 

When looking up a crate that does not exist, the header is missing:

` ` ` 
$ curl -v https://crates.io/api/v1/crates/test2
...
*no access-control-allow-origin header in output*
` ` ` 

### Environment

- Browser: curl
- OS: Debian 11

**Comment by walterhpearce** [comment]
as requested gave it a peak and a whirl. LGTM, as `verify_origin` is called for all authenticated requests and prevents CSRF on all actions that require authentication.

**Comment by Turbo87** [comment]
awesome, thanks :)
