### ISSUE TITLE
crates.io index repository contains an empty crate file

### ISSUE THREAD

**Issue by kornelski** [rust-lang/crates.io#6159]
### Current Behavior

There is a 0-byte file:

https://github.com/rust-lang/crates.io-index/blob/c5001c3770fa59f531c2ddb52c8a0e09334d0f09/po/ds/podsync

### Expected Behavior

This looks like a data consistency bug, because crates without releases are not supposed to exist (even yanked releases have their JSON lines).

This breaks assertions in the crates-index crate, which assumes there's always at least 1 version.

**Comment by Eh2406** [comment]
cc https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/crate.20deletion.20requests

**Comment by carols10cents** [comment]
The owner of the podsync crate has uploaded a placeholder version.

I don't think this is a frequent enough occurrence to address specifically, so I'm closing this. Anyone who disagrees, feel free to reopen!
