### ISSUE TITLE
Missing CORS headers for crate download (sometimes), breaks https://diff.rs

### ISSUE THREAD

**Issue by xfbs** [rust-lang/crates.io#6164]
### Current Behavior

When downloading a crate from crates.io, it sometimes does not send an `Access-Control-Allow-Origin` header.

I'm building a web app that attempts to render a diff between two crate versions (https://diff.rs). This needs to fetch the crate sources in the browser. It does so by making a GET request to `https://crates.io/api/v1/crates/axum/0.6.10/download` (for example). It then gets a response:

```
HTTP/2 302 Found
content-length: 0
location: https://static.crates.io/crates/axum/axum-0.6.10.crate
server: nginx
date: Wed, 08 Mar 2023 21:03:30 GMT
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
content-security-policy: default-src 'self'; connect-src 'self' *.ingest.sentry.io https://docs.rs https://play.rust-lang.org https://static.crates.io; script-src 'self' 'unsafe-eval' 'sha256-n1+BB7Ckjcal1Pr7QNBh/dKRTtBQsIytFodRiIosXdE='; style-src 'self' 'unsafe-inline' https://code.cdn.mozilla.net; font-src https://code.cdn.mozilla.net; img-src *; object-src 'none'
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubDomains
via: 1.1 vegur, 1.1 b4904c5988fd0eaae341a12cc47f3766.cloudfront.net (CloudFront)
vary: Accept,Accept-Encoding,Cookie
x-cache: Miss from cloudfront
x-amz-cf-pop: FRA60-P3
x-amz-cf-id: 2BhTCO35spTaGxUJ66YmutNFf5dieUzj2Uk3YiVXvRZayLXbyBH7EQ==
X-Firefox-Spdy: h2
```

This is a redirect to `https://static.crates.io/crates/axum/axum-0.6.10.crate`, and this is fine because it does contain a `Access-Control-Allow-Origin` header. But then on the next request it gets this response:

```
HTTP/2 200 OK
x-amz-id-2: SiguwpKhFtt3/J+/0OXaUPImUqT6ZTU7fbFbzIS1obxaZuj8z/YYPdnaD30p0AJrY5gBnFh52ntURF32qLkz9A==
x-amz-request-id: 3CJF6SEVVCS339A7
x-amz-replication-status: COMPLETED
last-modified: Fri, 03 Mar 2023 17:19:30 GMT
etag: "e24d789f871a7e8991702d676c6c151c"
x-amz-server-side-encryption: AES256
cache-control: public,max-age=31536000,immutable
x-amz-version-id: gudbMZYeYHUYkQ4V_axwCl8Ia5o2_qDs
content-type: application/gzip
server: AmazonS3
x-timer: S1678309410.290123,VS0,VE1
accept-ranges: bytes
date: Wed, 08 Mar 2023 21:03:30 GMT
via: 1.1 varnish
age: 343704
x-served-by: cache-fra-eddf8230083-FRA
x-cache: HIT
x-cache-hits: 1
content-length: 138884
X-Firefox-Spdy: h2
```

As you can see, this second response does **not** contain a `Access-Control-Allow-Origin` header and as a result, this request is blocked by the browser. 

<img width="1470" alt="Screenshot 2023-03-08 at 22 01 09" src="https://user-images.githubusercontent.com/786420/223851132-3db6a157-9016-4da2-8564-6e8d8ee66411.png">

It also seems like this issue does not consistently occur.

I believe that it should be possible to update the S3 settings to always add an `Access-Control-Allow-Origin: *` header to responses, this should fix the issue.

### Expected Behavior

The GET request to `https://crates.io/api/v1/crates/axum/0.6.10/download` should succeed, all redirects should have an `Access-Control-Allow-Origin: *` header indicating that browsers may fetch crate sources.

### Steps To Reproduce

1. Go to <diff.rs/serde>.
2. See `Error: error sending request: JsValue(TypeError: NetworkError when attempting to fetch resource. )`.

### Environment

- Browser: Firefox
- OS: macOS

### Anything else?

I hope you guys don't mind me using the crates.io API for this project. The application is smart about caching crate metadata and sources so as to avoid creating too many requests. It would be very awesome if we could fix this!

**Comment by Turbo87** [comment]
@jdno I assume this "sometimes it works" behavior might be due to the different CDNs?

but I'm also not sure whether we really want to enable CORS for crate file downloads. on first glance it would seem better to me if they were downloaded by the diff server and cached there instead of in every user's browser.

**Comment by jdno** [comment]
Thanks for the detailed issue, @xfbs, all the information is much appreciated!

As a little bit of background: We are using two different CDNs, namely CloudFront and Fastly, and are in the process of moving more traffic over to the latter. Traffic is balanced using DNS, which is probably why the issue does not occur consistently.

From the infrastructure perspective, the behavior is definitely different between CloudFront and Fastly. We should fix that to prevent accidentally breaking anything as we're relying more and more on both.

**Comment by jdno** [comment]
I have deployed a fix that ensures the same behavior between CloudFront and Fastly. That should've fixed the issue.

**Comment by xfbs** [comment]
Hey David,

Thanks for the quick response! I figured that it would have something to do
with CDN and load balancing, that makes a lot of sense.

Do you guys think this is something that could be fixed easily?

Also, is it okay for diff.rs to fetch the crates from your API? It would be
quite convenient if it is possible for browser applications to be able to
interact with crates.io in this way, and with some sane caching I would
hope that it does not put undue strain on your systems. But I would also
understand if this is not desired, in that case I would have to deploy some
proxy somewhere.

**Comment by Turbo87** [comment]
> is it okay for diff.rs to fetch the crates from your API?

hi @xfbs, first of all sorry for the late reply to your question. we discussed this question in our last crates.io team meeting last week, and while we don't want to forbid this kind of usage we would like to encourage using a server-side cache on your side. you might also want to take a look at https://www.pietroalbini.org/blog/downloading-crates-io/ as an alternative way of downloading the crate files directly from the CDN to not inflate the download stats of all the crates that your service is diffing.



> Do you guys think this is something that could be fixed easily?

as @jdno mentioned above, a fix has been deployed and everything should work fine now. if you're still seeing this problem please let us know so that we can reopen the issue.
