### ISSUE TITLE
Can't log in with github locally

### ISSUE THREAD

**Issue by lucypero** [rust-lang/crates.io#6173]
### Current Behavior

I'm following the [CONTRIBUTING](https://github.com/rust-lang/crates.io/blob/master/docs/CONTRIBUTING.md#using-your-local-cratesio-with-cargo) page for hosting a private mirror of crates.io but this part doesn't work:

`Go to http://localhost:4200/me to get your API token and run the cargo login command as directed.`

When you click on "Log in with GitHub", the popup hangs forever on "Please wait while we redirect you". 

Looking in the inspector, the browser is doing a GET request on `/api/private/session/begin` that returns a 404.

I'm hosting everything on docker locally as instructed in the CONTRIBUTING page.

### Expected Behavior

It should redirect me to Github to log in.

### Steps To Reproduce

1. set up your docker instance
2. Follow [these instructions](https://github.com/rust-lang/crates.io/blob/master/docs/CONTRIBUTING.md#using-your-local-cratesio-with-cargo) up to "Go to http://localhost:4200/me to get your API token and run the cargo login command as directed."

### Environment

- Browser: Edge
- OS: Windows 11

**Comment by lucypero** [comment]
It seems like the frontend is using the wrong port when hitting the backend. it's using its own port (4200) instead of the backend port (8888)

**Comment by lucypero** [comment]
the frontend just assumes that the backend is in the same url and port. How do I change that?

**Comment by lucypero** [comment]
is that what the `proxy` flag is for? it's not working. whatever I set here doesn't change the fact that it is still trying to hit `localhost:4200`

`pnpm start -- --proxy http://backend:8888`

**Comment by Turbo87** [comment]
> is that what the `proxy` flag is for?

yes, in theory that should be the thing that makes it work. using `--proxy` should forward API requests on `localhost:4200` to whatever you specify as the `--proxy` argument.

I have to admin that I don't think I've ever tried to use local GitHub auth with the Docker setup. I usually run the frontend and backend locally without Docker.

**Comment by Turbo87** [comment]
@liborty you will need to follow https://github.com/rust-lang/crates.io/blob/master/docs/CONTRIBUTING.md#publishing-a-crate-to-your-local-cratesio to make this work


> hosting a private mirror of crates.io

@lucypero just FYI, this codebase here is only meant for serving crates.io itself, not for running any local mirrors. the instructions in that document are primarily intended to set up a local development environment for contributors, but not for running a mirror. the codebase used to have such functionality but it wasn't really maintained and we decided to focus on crates.io itself instead.

**Comment by liborty** [comment]
I am just a normal crates.io user, have published a few crates there. 
I used to be able to login to crates.io website with my github account but today for some reason it no longer works.
Are all the complications described in the link above some new requirements?

**Comment by lucypero** [comment]
@liborty 

no, you should still be able to log in through the website. This is unrelated.

**Comment by liborty** [comment]
I have crates.io and internals.rust-lang.org set up as authorized OAuth apps and it always worked before.
I guess I should file a new bug report then?

**Comment by Turbo87** [comment]
> I guess I should file a new bug report then?

@liborty yes, this issue is only about running the crates.io codebase locally for development purposes, not about logging in on crates.io itself

**Comment by lucypero** [comment]
> @liborty you will need to follow https://github.com/rust-lang/crates.io/blob/master/docs/CONTRIBUTING.md#publishing-a-crate-to-your-local-cratesio to make this work
> 
> > hosting a private mirror of crates.io
> 
> @lucypero just FYI, this codebase here is only meant for serving crates.io itself, not for running any local mirrors. the instructions in that document are primarily intended to set up a local development environment for contributors, but not for running a mirror. the codebase used to have such functionality but it wasn't really maintained and we decided to focus on crates.io itself instead.

@Turbo87 

I see, so it's not recommended? What would you recommend instead? Maybe [meuse](https://github.com/mcorbin/meuse)?

**Comment by Turbo87** [comment]
https://github.com/rust-lang/cargo/wiki/Third-party-registries has a few suggestions, but I don't have any first-hand experience with them
