### ISSUE TITLE
failure to login to crates.io website with github

### ISSUE THREAD

**Issue by liborty** [rust-lang/crates.io#6175]
### Current Behavior

Fails to login with GitHub. 

### Expected Behavior

automatic login to crates.io website 

### Steps To Reproduce

clicking on 'login with github'

### Environment

- Browser: Firefox 110.0.1 (64-bit
- OS: System:  Kernel: 5.15.0-67-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: Cinnamon 5.6.7
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy

### Anything else?

the 'transferring' console briefly appears and disappears but no login is achieved

**Comment by Turbo87** [comment]
unfortunately this is not enough information to be able to debug this.


> clicking on 'login with github'

I've just tried it and "it works on my machine" 🙈 😅 

you could try to revoke OAuth access for crates.io on https://github.com/settings/connections/applications/9fe8110dfe185fe90b5c and then try to log in again

we did not deploy any substantial changes to the login process in the past weeks/months, so I'm not sure what might have caused this to stop working for you.

**Comment by liborty** [comment]
I did revoke. Next time I tried to login to crates.io it asked me to authorize again, so I did but it is still not logging me in. 
There are no messages, the transferring window just disappears. At that stage I would have normally been logged in but now I am not.

**Comment by Turbo87** [comment]
https://github.com/rust-lang/crates.io/discussions/4320#discussioncomment-2718890 indicates that some people have issues logging in because of their browser addons. can you check if you have any addons enabled that could interfere with this?

**Comment by liborty** [comment]
You are right, it was some unknown Firefox Issue. It was throwing up errors and refusing to die. I had to reinstall Firefox, reboot and now it works again.
