### ISSUE TITLE
Consider rejecting stable releases while the language is changing

### ISSUE THREAD

**Issue by huonw** [rust-lang/crates.io#62]
Rust itself is still changing, so a crate cannot really guarantee the kind of backward compatibility that cargo assumes for deduplicating dependencies etc. People may not realise this and so accidentally upload something that is forced to break semver as the language changes (or else be forced to do a lot of major version releases, which is unlikely to be what someone wants & is better served by 0.x releases).

This limit would of course be removed closer to 1.0 after associated types and unboxed closures etc. land.

**Comment by tbu-** [comment]
I believe this issue is outdated.

**Comment by alexcrichton** [comment]
Indeed!
