### ISSUE TITLE
embedded-hal-nb v1.0.0-alpha.2 missing from index.

### ISSUE THREAD

**Issue by Dirbaio** [rust-lang/crates.io#6306]
### Problem

`embedded-hal-nb v1.0.0-alpha.2` was [released yesterday](https://crates.io/crates/embedded-hal-nb/1.0.0-alpha.2), however trying to use it as a dependency fails, as if it wasn't there.

### Steps

```
[dirbaio@mars ~]$ cargo new repro
cd     Created binary (application) `repro` package
[dirbaio@mars ~]$ cd repro/
[dirbaio@mars repro]$ echo 'embedded-hal-nb = "=1.0.0-alpha.2"' >> Cargo.toml 
[dirbaio@mars repro]$ cargo build
    Updating crates.io index
error: failed to select a version for the requirement `embedded-hal-nb = "=1.0.0-alpha.2"`
candidate versions found which didn't match: 0.0.0
location searched: crates.io index
required by package `repro v0.1.0 (/home/dirbaio/repro)`
perhaps a crate was updated and forgotten to be re-vendored?
```

### Possible Solution(s)

Looking with `CARGO_LOG=trace`, it seems it's downloading this https://index.crates.io/em/be/embedded-hal-nb, and indeed `v1.0.0-alpha.2` is missing.

It seems to be an issue of the new sparse protocol only. Forcing using the old one works:  `CARGO_REGISTRIES_CRATES_IO_PROTOCOL=git cargo build`

### Version

```text
[dirbaio@mars repro]$ cargo version --verbose
cargo 1.70.0-nightly (0e474cfd7 2023-03-31)
release: 1.70.0-nightly
commit-hash: 0e474cfd7b16b018cf46e95da3f6a5b2f1f6a9e7
commit-date: 2023-03-31
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 8.0.1-DEV (sys:0.4.61+curl-8.0.1 vendored ssl:OpenSSL/1.1.1q)
os: Arch Linux Rolling Release [64-bit]
```

**Comment by Turbo87** [comment]
as a short term fix, we ran a complete sync from the git index to the sparse index. https://index.crates.io/em/be/embedded-hal-nb for me now shows the missing version.

the cause of the issue is described in the Zulip thread that was linked above and still needs a more long-term fix though, so I'll keep this issue open for now.

**Comment by Dirbaio** [comment]
@Turbo87 just in case you missed it, I yanked the dummy `0.0.0` version hoping it'd cause the index file to get regenerated and it did, [3 days ago](https://github.com/rust-lang/crates.io/issues/6306#issuecomment-1503776723), so it was already "fixed" before the sync. Wanted to point it out in case it had interfered with your troubleshooting. Sorry for interfering, but the missing version was causing some issues.

Thanks guys for all your work btw, crates.io is awesome :)

**Comment by Turbo87** [comment]
@Dirbaio oops, I missed that comment 😅 

it looks like we had a few more unsynced crates though, so performing this syncing operation was apparently still useful. unfortunately now we have to find a solution to prevent the desync from happening in the first place 🙈
