### ISSUE TITLE
Error message for missing verified e-mail address points to `/me`

### ISSUE THREAD

**Issue by Marcono1234** [rust-lang/crates.io#6364]
### Current Behavior

When you try to run `cargo publish` without verified e-mail address on crates.io, it says:

> Caused by:
  the remote server responded with an error: A verified email address is required to publish crates to crates.io. Visit https://crates.io/me to set and verify your email address.

The relevant code seems to be here:
https://github.com/rust-lang/crates.io/blob/fd002a7b3152ce3a1c5ecf17fa0eb29ba0654e11/src/controllers/krate/publish.rs#L104-L105

The problem is that you restructured the crates.io account settings page (#4309), and then added a redirect for `/me` (#4311), which now points to the wrong page, the API token page.

### Expected Behavior

The error message should point to https://crates.io/settings/profile

### Environment

_should not matter_

### Anything else?

Maybe also make it more obvious on the Profile page that you have currently not set an email address. Currently it looks like this:
![Profile page screenshot](https://user-images.githubusercontent.com/11685886/233790932-10283a8d-9ae8-4b24-a158-9bfdedce163b.png)

I even had that page open before, but assumed it just did not display the e-mail address, maybe for privacy reasons. (Though I might not have read the text closely enough.)

Also, you could probably obtain a default e-mail address from GitHub if you wanted, see [`user:email` scope](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/scopes-for-oauth-apps). Though in that case you should still consider it sensitive and not display it publicly anywhere.

**Comment by Turbo87** [comment]
whoops, thanks for letting us know!

https://github.com/rust-lang/crates.io/pull/6365 should fix the issue :)
