### ISSUE TITLE
Log queries in development mode?

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#639]
Another thing I am spoiled by rails about is that when you're running the server in development mode, it prints out the SQL that the requests are running in with the server logs. 

This would be super helpful since I'm still learning diesel and I'm often not getting the results I think I should be getting, but it's hard to see what SQL my diesel code is generating in order to figure out what I'm doing wrong.

I suspect getting this for crates.io depends on https://github.com/diesel-rs/diesel/issues/150... ? Or is there something we could do in crates.io that wouldn't be as general as diesel would need, since we're only running postgres? @sgrif

**Comment by sgrif** [comment]
If you set `log_statement` to `'all'` that will cause PG to log all queries it receives. I'll put logging on the 0.13 milestone for Diesel though, I've got the design pretty much worked out I just need to implement it.

If you're just trying to see the SQL that's generated though, you can always use `print_sql!` or `debug_sql!` (The former prints to stdout, the latter returns the SQL as a string).

**Comment by carols10cents** [comment]
> If you set log_statement to 'all' that will cause PG to log all queries it receives

Yeah, that's in postgres' logs though, right? I like seeing the queries in with the requests so I know for sure which request is creating which queries.

> I'll put logging on the 0.13 milestone for Diesel though

❤️ 🎉 🌮 !!

> If you're just trying to see the SQL that's generated though, you can always use print_sql! or debug_sql! (The former prints to stdout, the latter returns the SQL as a string).

yeah but then i have to recompiiiile *whine* ❤️

**Comment by sgrif** [comment]
I've pulled this off of the Diesel milestone, as I don't think the ecosystem is where we need it to be to ship logging as a feature yet. https://github.com/diesel-rs/diesel/issues/150#issuecomment-318928436

If this is still a big concern I can put something together that implements it on the crates.io side (basically just decorating `PgConnection` and using `debug_sql` on every call. It's much easier to do after  https://github.com/diesel-rs/diesel/pull/1051)

**Comment by Turbo87** [comment]
closing this for now until the `diesel` project has figured out how to best do this :)
