### ISSUE TITLE
The transfer_crates script should use gh_id instead of gh_avatar

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#645]
This script was made before we had gh_id on all users, which should be more reliable than avatar URL.

**Comment by vignesh-sankaran** [comment]
I'd be happy to take this up @carols10cents, I'm not sure how to test the script though once the changes are made.

**Comment by carols10cents** [comment]
@vignesh-sankaran yeah, this script is only run occasionally, so I think manual testing is fine. You'll need to create two users, publish a crate with one user, then run this script to transfer the crate to the other user. Then check that the UI shows the crate as being owned by the second user, and that the second user can publish new versions of that crate and the first user cannot.

Publishing locally can be tricky, I think I've documented the setup in docs/CONTRIBUTING.md but please let me know if you have any trouble!
