### ISSUE TITLE
unable to add owner to the crate

### ISSUE THREAD

**Issue by softstream-link** [rust-lang/crates.io#6475]
### Current Behavior

Tried on both Safari and Chrome from MacOS

Open(crates.io) -> Click(Login with GitHub not under Account A) -> Find(owned crate) -> ClickTab(Settings) -> EnterAddOwner( Valid Github account B) -> Click(Save)

ERROR: Error sending invite: could not find user with login `......@gmail.com`

### Expected Behavior

expected to work

### Steps To Reproduce

See in Current  Behavior

### Environment

- Browser: Chrome & Safari
- OS: Mac

**Comment by carols10cents** [comment]
Hi, sorry this isn't clear, but inviting works by putting in the person's
crates.io/ github username, not their email address.

**Comment by softstream-link** [comment]
Thanks that worked, what i am guessing confused me is the fact that owner himself directly below was showing the email and not account. Even thought it clearly states user name in the box.
