### ISSUE TITLE
Allow people to directly download crate source tarball

### ISSUE THREAD

**Issue by sfackler** [rust-lang/crates.io#65]
I find it useful if I want to check out a package before depending on it or need to look at the source.

**Comment by gdamjan** [comment]
There needs to be some pointer to the source, regardless what's in the projects `Cargo.toml`. 

Take for ex. https://crates.io/crates/servo-glutin/0.4.10  the only link is to https://github.com/tomaka/glutin which doesn't even have a 0.4.10 version/tag (and this is actually the servo/glutin repo).

The servo/glutin repo only has a `servo-0.4.10` tag, which I don't know if is the version on crates.io

**Comment by flying-sheep** [comment]
as a packager, i need this. i need to point to a file and say “download this and verify with that sha1” instead of “let something download stuff for me”

**Comment by carols10cents** [comment]
So the URLs https://crates.io/api/v1/crates/name/version/download work, but that's not really exposed anywhere. 

In what manner would yinz want to see this exposed? API docs? A link on the crate page?

**Comment by ljedrz** [comment]
> So the URLs https://crates.io/api/v1/crates/name/version/download work

It doesn't work anymore; it used to in the past, but I tried it with a few crates and it didn't do the trick.

**Comment by carols10cents** [comment]
It won't work with a browser, no, but `curl` should work.

**Comment by ljedrz** [comment]
> It won't work with a browser, no, but curl should work.

I checked it; it works.

I would suggest describing this download method in the API docs, especially since it is not trivial - you need to pass the **-L** option (follow redirects), otherwise you may not receive anything. In addition, although the downloaded file's extension is .crate (and after unzipping it the file has a .crate extension again), it is a tarball (.tar.gz).

**Comment by sgrif** [comment]
It should work in the browser after the next deploy

**Comment by carols10cents** [comment]
Deployed! this should now work!

**Comment by sneurlax** [comment]
> Deployed! this should now work!

This is no longer working via either curl or browser, is this intended now?

**Comment by Turbo87** [comment]
> This is no longer working via either curl or browser

can you be more specific what you mean by "this"? downloads seem to be working without any issues here.
