### ISSUE TITLE
Can't figure out how to publish a crate with a dependency to a locally-running crates.io override

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#652]
I can publish a crate without any dependencies to an instance of crates.io that I have running locally by using `cargo publish --host=file:///path/to/my/crates.io/tmp/index-co/`.

I can download a crate from my local crates.io since i'm using the local uploads thing I implemented that stores and serves .crate files from the file system when running in development mode without S3 configured.

In a new crate, I've specified in `.cargo/config` that I want to replace crates.io with my local instance:

```
[source]

[source.mirror]
registry = "file:///path/to/my/crates.io/tmp/index-co"

[source.crates-io]
replace-with = "mirror"
```

And I can make this other crate depend on the crate i've published locally, and I can `cargo build` the second crate, and it downloads the dependent crate from my local crates.io.

I cannot, however, publish the second crate to my local instance in the same way as the first one by specifying the host:

```
    Updating registry `file:///path/to/my/crates.io/tmp/index-co/`
error: crates cannot be published to crates.io with dependencies sourced from a repository
either publish `foo` as its own crate on crates.io and specify a crates.io version as a dependency or pull it into this repository and specify it with a path and version
(crate `foo` has repository path `registry https://github.com/rust-lang/crates.io-index`)
```

The Cargo.lock file does have `(registry+https://github.com/rust-lang/crates.io-index)` in it for the dependent crate, but just replacing that by hand with my index location has no effect.

This makes it difficult to test scenarios involving crates with dependencies locally, and I think also prevents having private crates.io instances.

**Comment by carols10cents** [comment]
This was fixed in #601!

**Comment by carols10cents** [comment]
oh wait no it wasn't. i need to actually read what i wrote haha

**Comment by sharksforarms** [comment]
Any workaround for this? I have the same issue.

**Comment by Turbo87** [comment]
@carols10cents do you know if this is still an issue? and if so, I guess this might have to be solved on the cargo side, no?
