### ISSUE TITLE
My Github account was banned and I can't access to my crates.io account

### ISSUE THREAD

**Issue by 0xMcraxker** [rust-lang/crates.io#6549]
### Current Behavior

Hello, my github account was banned (mcraxker) and I can't enter by github, I have the crates.io account on my mobile but i can't change my github so im searching help to fix this.

### Expected Behavior

I wanna change mcraxker to 0xMcraxker, im developer of https://crates.io/crates/debugprotector and i wanna to clone a repository of a collaborator to push changes.

If you want talk me to support me, here is my E-Mail address: mcraxker@deltanetwork.cc or contact@mcraxker.dev.

Thanks.

### Environment

- Browser:
- OS:

**Comment by Turbo87** [comment]
please contact help@crates.io for issues like this :)
