### ISSUE TITLE
Add logging of useragent, headers to figure out 404 requests to /crate/name

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#655]
We get a lot of requests to `/crate/name` URLs that show up in the logs as 404s. Some of these might be a bug, some of these might be normal. I'd like to figure out which it is to better inform what we should do about it so that bugs are more noticeable.

The reason I don't think some of these are bugs is that *sometimes* the request works perfectly fine! These two requests happened within 15 min of each other, no deploy in between or anything, but one has `status=404` and one has `status=200`:

```
Mar 29 03:43:57 crates-io heroku/router: at=info method=GET path="/crates/assert_approx_eq" host=crates.io request_id=982e02d4-764c-4207-b22f-e985ef568aff fwd="34.208.116.58" dyno=web.1 connect=0ms service=1ms status=404 bytes=283 protocol=https 
Mar 29 04:00:14 crates-io heroku/router: at=info method=GET path="/crates/assert_approx_eq" host=crates.io request_id=3a682c52-ea80-4ac5-a11a-e631f078d930 fwd="178.19.212.229" dyno=web.2 connect=0ms service=2ms status=200 bytes=1904 protocol=https 
```

My current suspicion is that the 404s are from webcrawlers that don't use JS or aren't sending the right headers.

If I do a plain `curl`, I get a 404 response:

```
curl -v https://www.crates.io/crates/assert_approx_eq
...
< HTTP/1.1 404 Not Found
...
{"errors":[{"detail":"Not Found"}]}
```

If I copy as cURL from my browser, I get a 200 response. Narrowing it down, it appears to be the headers that are needed. This returns 200:

```
curl -v 'https://crates.io/crates/assert_approx_eq' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
```

I'd like some more info about what/who is making requests without headers to inform what we should do about it, so I'd like to add logging of the useragent and headers that were passed when a request like `/crate/name` is about to return a 404.

Kind of related to #201, but not the same.

**Comment by kzys** [comment]
Aren't we logging User-Agent now?

https://github.com/rust-lang/crates.io/commit/4138c08a60783fe487e646b305587325b2716a24

**Comment by sgrif** [comment]
Yes, thanks
