### ISSUE TITLE
Add a ranking of crates by number of crates that directly depend on it

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang/crates.io#659]
The current # of downloads ranking tends to favor crates that are at the bottom of the dependency graph. Ranking by number of crates that directly depend on a particular crate seems like it would produce a more interesting list of suggested crates as these are the crates that authors have explicitly made a choice to depend on.

**Comment by carols10cents** [comment]
Please see rust-lang/rfcs#1824, it's in Final Comment Period and is going to change the default ranking of crates. Thanks!
