### ISSUE TITLE
Crate version order is randomly generated

### ISSUE THREAD

**Issue by bluss** [rust-lang/crates.io#664]
+ Example: https://crates.io/crates/ndarray/versions
+ Example: https://crates.io/crates/libc/versions

They are not correct in neither publish date nor version order. The output order also changes from time to time when your reload (but sometimes it's cached or something).

The same order is used for the version list on the crate's page.

**Comment by carols10cents** [comment]
On it.

**Comment by carols10cents** [comment]
The fix has been deployed and looks good to me. Sorry for the inconvenience!!
