### ISSUE TITLE
Inconsistent 400 response for download request with authorization header

### ISSUE THREAD

**Issue by ronshemerws** [rust-lang/crates.io#6655]
### Current Behavior

I am working on a system that sends GET requests endpoint `/crates/:crate_id/:version/download`, with 2 headers:
```
Authorization: <key>
User-Agent: whitesource_bot
```
Usually it works, and we use the same header values in two separate environments (production, development).

A temporary issue in development came up, the download failed with the following response:
```
Code from server:400, body: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidArgument</Code><Message>Authorization header is invalid -- one and only one ' ' (space) required</Message><ArgumentName>Authorization</ArgumentName><ArgumentValue>...</
```
This was consistent for several hours. 
There were only manually triggered requests, so just one attempt every few seconds. 
While the issue lasted, manually triggered requests in production environment were working as expected and package download was successful. 
Specifically it was trying to download `https://crates.io/api/v1/crates/ring/0.13.5/download`.
This was around 11:25:00 AM UTC (20/06/23) when the issue came up.
Generally, the system is limited to send  requests at max rate of 1 request/sec, and anyway at the time of reproducing the issue none of the systems were sending requests automatically.
Then around 12:10 PM UTC (20/06/23), without changing anything on the development environment, the requests succeeded again.

### Expected Behavior

Requests should be consistently accepted or rejected.

### Steps To Reproduce

Irrelevant, as the issue seem to be temporary.

### Anything else?

I do not assume this is a bug/issue in crates.io, it very much possible that the systems I work on are responsible for the inconsistency. Could it be related to rate limit or the fact that two independent systems use the same user agent and key?

Also, it is unclear to me if the authorization key is relevant at all. It was added 4 years ago by people I cannot contact.
Is it fine to use the endpoint without authorization key?

**Comment by Turbo87** [comment]
> Is it fine to use the endpoint without authorization key?

yes, the download endpoint does not need authorization at all.

I would recommend to read through https://www.pietroalbini.org/blog/downloading-crates-io/ though. Bots generally should not use the regular download endpoint and should hit the CDN directly to not artificially inflate the download numbers.

**Comment by ronshemerws** [comment]
Thank you for the quick response! This is very helpful.

There were no additional headers.
I am adjusting the requests to no longer use the authorization header and go directly to the CDN as the blog suggests.
