### ISSUE TITLE
Feature request: way to set up a mirror

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#67]
I'm so excited crates.io has arrived!! :tada: Great work, Alex and everyone!!! 

This is a longer-term feature request... one thing that has been an occasional yet painful experience with rubygems.org or npmjs.org is when they're down. At various points in time, my coworkers and I have tried to set up mirrors under our control of both of these and it never went very smoothly, neither on the setup or usage side of things.

I would love love love to have mirroring be something officially supported and encouraged for the health of the community, but I realize this is a difficult problem too :)

Thank you for your work!! :heart:

**Comment by steveklabnik** [comment]
https://gmjosack.github.io/posts/dissecting-cratesio-minimum-mirror/

**Comment by weiznich** [comment]
I've written a simple [caching server](https://crates.io/crates/crates-mirror). Similar to Artifactory it pulls down transparently those crates that are really requested. Currently it is only a simple application without any interface or anything. Also it only mirrors an index. It's not possible to add or yank crates to the mirror.

**Comment by gilescope** [comment]
This feels linked to https://github.com/rust-lang/rust/issues/44931

**Comment by ishitatsuyuki** [comment]
For initial fetch, we should provide daily database dumps which is less overhead to serve and better compressed.

For dynamic syncing, [the Kubernetes model](https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes) is a very friendly way to organize the API.

**Comment by happyaron** [comment]
Would like to bump this issue a bit since it looks like not getting love from guys for a long time - people from certain parts of the world (in my case, China mainland) does not have decent connectivity to some most used CDNs, so that mirroring is a must for getting a decent speed of using the repository.

Almost all the other languages have some form of mirroring being widely used, for example[1] we have CPAN/CTAN/CRAN, pypi, julia, etc. There are lots of Nexus instances to partially mirror the Maven Central repository. If crates.io can be mirrored in some way, it will surely make Rust user's lives easier in those places.

[1]https://mirrors.tuna.tsinghua.edu.cn/
[2]https://github.com/tuna/issues/issues/941
    a bit background: TUNA mirror is the largest syncing source of other mirrors in the country, with an average rsync traffic of more than 1Gbps

**Comment by skyzh** [comment]
We have built a tool to mirror `static.crates.io` at https://github.com/sjtug/mirror-clone . Meanwhile, we have also set up an experimental full-mirror of static.crates.io at `https://s3.jcloud.sjtu.edu.cn/899a892efef34b1b944a19981040f55b-oss01/crates.io/crates/{crate}/{crate}-{version}.crate`

**Comment by Turbo87** [comment]
seeing as e.g. Artifactory now supports Rust (see https://www.jfrog.com/confluence/display/JFROG/Cargo+Registry) I guess we can close this :)

**Comment by happyaron** [comment]
@Turbo87 maybe a proprietary tool is not sufficient to close this issue, as a person who runs public mirror for various FLOSS, I'd like to find an open source solution, :)

**Comment by Turbo87** [comment]
@happyaron absolutely, I would prefer that too. what I meant to say was that if Artifactory can build it then the necessary things are there for open source tools to also build something like this and there is nothing left on the crates.io side that we would need to build to enable this :)
