### ISSUE TITLE
Fonts not loading

### ISSUE THREAD

**Issue by maxdeviant** [rust-lang/crates.io#6708]
### Current Behavior

The fonts on crates.io don't appear to be loading:

<img width="1416" alt="Screenshot 2023-06-28 at 11 07 03 PM" src="https://github.com/rust-lang/crates.io/assets/1486634/f67ad93e-ca8d-46d7-bc4d-b778944ae838">

<img width="1416" alt="Screenshot 2023-06-28 at 11 07 33 PM" src="https://github.com/rust-lang/crates.io/assets/1486634/b766d3aa-4ea3-407f-809c-b738b50f9cf9">

Looking in the browser console, I'm seeing a number of CORS errors:

<img width="355" alt="Screenshot 2023-06-28 at 11 08 32 PM" src="https://github.com/rust-lang/crates.io/assets/1486634/1cafbeaa-ce97-44d6-84ba-4d6bef75e714">

Here's one of them written out:

> Access to font at 'https://code.cdn.mozilla.net/fonts/woff/FiraSans-Medium.woff' from origin 'https://crates.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### Expected Behavior

The fonts should load, as seen in this screenshot from a month ago:

<img width="1206" alt="Screenshot 2023-05-28 at 1 28 17 PM" src="https://github.com/rust-lang/crates.io/assets/1486634/e236c7f4-6429-45fc-9786-cea24430c9b5">

### Steps To Reproduce

1. Got to crates.io
2. Observe the fonts do not load

### Environment

- Browser: Google Chrome Version 114.0.5735.133 (Official Build) (arm64)
- OS: macOS Ventura 13.4.1

**Comment by maxdeviant** [comment]
The fonts don't load in Firefox:

<img width="1392" alt="Screenshot 2023-06-28 at 11 11 45 PM" src="https://github.com/rust-lang/crates.io/assets/1486634/42a78368-948c-4295-a7fb-c1bfb261930a">

They do, however, appear to load in Safari:

<img width="1206" alt="Screenshot 2023-06-28 at 11 13 03 PM" src="https://github.com/rust-lang/crates.io/assets/1486634/4eacdf83-b58b-4c54-af68-777f5fa81a78">

**Comment by LawnGnome** [comment]
This is working OK for me today in Firefox — are you still seeing this issue?

**Comment by maxdeviant** [comment]
Yea, I am still seeing the issue in Firefox v114.0.2 on macOS Ventura:

<img width="1392" alt="Screenshot 2023-06-30 at 2 42 40 PM" src="https://github.com/rust-lang/crates.io/assets/1486634/e389049a-43e7-45bf-9cff-270679a8d7fd">

**Comment by LawnGnome** [comment]
Interesting! Sorry for the unexpected fonts.

Could you copy/paste the response headers from the initial `https://crates.io/` request, please? I'm particularly interested in the `Content-Security-Policy` header, but also the CDN headers as well.

Specifically, if you right click on the first request in the network tab after a reload:

![image](https://github.com/rust-lang/crates.io/assets/229984/40389259-57e8-4b89-b26e-ef2bbced7fbb)

You should be able to right click, then select `Copy Value` and `Copy Response Headers`.

**Comment by maxdeviant** [comment]
Here are the response headers for `https://crates.io/` after a simple refresh (served from the cache):

```
HTTP/2 304 Not Modified
server: nginx
date: Fri, 30 Jun 2023 20:52:01 GMT
last-modified: Mon, 26 Jun 2023 09:45:44 GMT
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 0
content-security-policy: default-src 'self'; connect-src 'self' *.ingest.sentry.io https://docs.rs https://play.rust-lang.org https://static.crates.io; script-src 'self' 'unsafe-eval' 'sha256-n1+BB7Ckjcal1Pr7QNBh/dKRTtBQsIytFodRiIosXdE='; style-src 'self' 'unsafe-inline' https://code.cdn.mozilla.net; font-src https://code.cdn.mozilla.net; img-src *; object-src 'none'
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubDomains
via: 1.1 vegur, 1.1 c5c79ef7442267e414f3389ffcc2f0fa.cloudfront.net (CloudFront)
vary: Accept,Accept-Encoding,Cookie
x-cache: Miss from cloudfront
x-amz-cf-pop: EWR53-C2
x-amz-cf-id: r2NdVGgBfOmK-HiX3BzMPS64SFpLjNPH1RYV6zfHvoKLuUKaQIzpNQ==
X-Firefox-Spdy: h2
```

And for a hard refresh (<kbd>Cmd + Shift + R</kbd>):

```
HTTP/2 200 OK
content-type: text/html
server: nginx
date: Fri, 30 Jun 2023 20:52:26 GMT
last-modified: Mon, 26 Jun 2023 09:45:44 GMT
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 0
content-security-policy: default-src 'self'; connect-src 'self' *.ingest.sentry.io https://docs.rs https://play.rust-lang.org https://static.crates.io; script-src 'self' 'unsafe-eval' 'sha256-n1+BB7Ckjcal1Pr7QNBh/dKRTtBQsIytFodRiIosXdE='; style-src 'self' 'unsafe-inline' https://code.cdn.mozilla.net; font-src https://code.cdn.mozilla.net; img-src *; object-src 'none'
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubDomains
content-encoding: gzip
via: 1.1 vegur, 1.1 2755a65ada03bcb40dcec9e77a7c9160.cloudfront.net (CloudFront)
vary: Accept,Accept-Encoding,Cookie
x-cache: Miss from cloudfront
x-amz-cf-pop: EWR53-C2
x-amz-cf-id: YeXlpjTdxwSUlnOajw0OAdkfOCCnxG5Sk2w09wcVaji_E1zA9gJGYQ==
X-Firefox-Spdy: h2
```

**Comment by LawnGnome** [comment]
Thanks. So much for that theory — the CSP header is identical to what I see, and _seems_ like it should be sufficient to allow the font resource to be loaded.

I'll borrow a Macbook shortly just in case it's a weird platform difference, since I'm on Linux, but otherwise I'm stumped right now. Hopefully someone else on the crates.io team has a bright idea.

**Comment by Turbo87** [comment]
just in case, what Firefox add-ons/extensions are you using?

**Comment by maxdeviant** [comment]
> just in case, what Firefox add-ons/extensions are you using?

I'm not much of a Firefox user, so it's a fresh Firefox installation; no add-ons, extensions, or modification whatsoever.

I am using a number of extensions in Chrome (including uBlock Origin), but the fonts still don't load in incognito with uBlock Origin disabled.

**Comment by Turbo87** [comment]
I've tried to reproduce the issue, but the fonts are loading with the correct response headers for me:

<img width="463" alt="Bildschirmfoto 2023-07-07 um 16 17 39" src="https://github.com/rust-lang/crates.io/assets/141300/ae553588-b2f0-45af-af6d-a8894131c58e">

Can you check what headers you are seeing for these requests?

**Comment by maxdeviant** [comment]
> I've tried to reproduce the issue, but the fonts are loading with the correct response headers for me:
> 
> <img alt="Bildschirmfoto 2023-07-07 um 16 17 39" width="463" src="https://user-images.githubusercontent.com/141300/251770260-ae553588-b2f0-45af-af6d-a8894131c58e.png">
> Can you check what headers you are seeing for these requests?

Interestingly enough, I went to check for these headers and now the fonts are loading correctly again.

Not sure what changed 🤔

Anyways, apologies for the noise!
