### ISSUE TITLE
Make some way to be "signed in" when running only the front end locally

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#671]
It's kind of annoying to have to set up the backend, and a github application, and the environment variables, all to check that the frontend still looks all right when you're logged in.

Maybe just adding fake user data to the mirage fixtures and documenting that a bit more would do it?

**Comment by Turbo87** [comment]
> Maybe just adding fake user data to the mirage fixtures and documenting that a bit more would do it?

that should be possible. our test suite is using such code now, so in theory it should also be possible for the mirage setup in dev mode.
