### ISSUE TITLE
Stop the squatting?

### ISSUE THREAD

**Issue by TomMD** [rust-lang/crates.io#6755]
### Current Behavior

People are taking advantage of the shared namespace and squatting. This seems net harmful to the community.

### Expected Behavior

Package names are available until taken by an honest attempt to provide code.

### Steps To Reproduce

Observe https://crates.io/users/swmon

### Anything else?

(Re)write a use agreement and delete accounts that violate the terms.

**Comment by Turbo87** [comment]
we are actively discussing this at https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/policy.20updates. in the interest of not spreading the discussion between too many different places I'll close this issue for now. once an RFC has been written, the PR will be the official record to discuss the policy changes.
