### ISSUE TITLE
Wrong API URL in `index.crates.io/config.json`?

### ISSUE THREAD

**Issue by NiklasRosenstein** [rust-lang/crates.io#6768]
### Current Behavior

```
$ curl https://index.crates.io/config.json
{
  "dl": "https://crates.io/api/v1/crates",
  "api": "https://crates.io"
}
```

I think this is wrong because fetching metadata from the specified API fails:

```
$ curl https://crates.io/1/a -v
...
< HTTP/2 404 
```

Wheras using `index.crates.io` works, as one would expect:

```
$ curl https://index.crates.io/1/a 
{"name":"a","vers":"0.0.1","deps":[],"cksum":"bae3d8de1b7fd1fef6c2da3130a7d06d32499fd5292a9c1309681ac79e98c643","features":{},"yanked":false}
```

Yet, `cargo` seems to be able to work with this and make requests to `index.cargo.io` instead. I confirmed this with `mitmweb`.

![image](https://github.com/rust-lang/crates.io/assets/1318438/4fa5a40f-cf23-4a12-be0c-645ea8ee186e)

### Expected Behavior

```
$ curl https://index.crates.io/config.json
{
  "dl": "https://crates.io/api/v1/crates",
  "api": "https://index.crates.io"
}
```

**Comment by Eh2406** [comment]
This is confusing, but correctly implemented. The index and the API have different URLs. The index is at `https://index.crates.io/` and the API is at `https://index.crates.io`. There is more details on how the design works at https://doc.rust-lang.org/cargo/reference/registries.html
