### ISSUE TITLE
node-sass dependency missing

### ISSUE THREAD

**Issue by seeekr** [rust-lang/crates.io#679]
This is the first time I tried running crates.io on my local machine. Followed the instructions for frontend work, got this error message:

```$ yarn run start:staging
(...)
ENOENT: no such file or directory, scandir '/Users/denis/Code/crates.io/node_modules/node-sass/vendor'
Error: ENOENT: no such file or directory, scandir '/Users/denis/Code/crates.io/node_modules/node-sass/vendor'
(...)
```

This is how I fixed it:

`yarn add node-sass`

---

Not sure whether instructions need to change or package.json. Can send PR if you like, if you let me know how this needs to be solved.

Cheers!

**Comment by carols10cents** [comment]
Yeah I'm getting this too. I wonder what changed to require this...? I'd love a PR!

**Comment by carols10cents** [comment]
Actually, [this issue](https://github.com/sass/node-sass/issues/1579) seems to say running `npm rebuild node-sass` fixes it, and I tried that and it worked for me. I'm not sure if you can get back in this state and see if that works for you, but if you can and if that works, perhaps we should add that to the setup instructions? I wish I knew why this is happening :-/

**Comment by seeekr** [comment]
Hmm.... interesting. On my local machine I can't reproduce the issue after it has worked for me once. I can't even try `npm rebuild node-sass` because it just stopped breaking :-)
I might try building from scratch in a container instead of locally in order to avoid things working only because something somewhere is being cached etc.

**Comment by carols10cents** [comment]
> I might try building from scratch in a container instead of locally in order to avoid things working only because something somewhere is being cached etc.

That would be a huge help! ❤️

**Comment by seeekr** [comment]
Cannot reproduce inside a fresh container either... Dockerfile I used, in case anyone else will be interested:

```
FROM node:7

RUN git clone https://github.com/rust-lang/crates.io.git
WORKDIR crates.io
RUN yarn
RUN yarn run -- bower install --allow-root

CMD yarn run start:staging
```

In the issue you've linked to some people said the issue was intermittent for them, maybe that's the case here as well. Right now I don't have a really good idea for how to identify the issue properly...

Should we not make any progress here with any real solution, I'd suggest to add a short note in the installation instructions regarding this particular error and its easy fix.

**Comment by carols10cents** [comment]
Sounds good! I would accept a PR for a note in the readme if you have time :)

**Comment by carols10cents** [comment]
I haven't heard of this happening recently, so I'm going to give this a close. If anyone sees this again, please reopen!
