### ISSUE TITLE
Impossible to remove yourself as crate owner, even though there are other owners

### ISSUE THREAD

**Issue by aochagavia** [rust-lang/crates.io#680]
I recently wanted to transfer ownership of a crate to someone else, so I tried the following:

```
cargo owner --add someone
cargo owner --remove aochagavia
```

However, the latter command failed with the message: `failed to remove owners from crate sudoku: api errors: cannot remove yourself as an owner`.

I think it would make sense to allow this when a crate has more than one owner. The current workaround is to ask the new owner to remove you. It is not a big deal, but it does feel unnecessary.

**Comment by carols10cents** [comment]
Removing yourself, as long as there is at least one other owner, sounds reasonable.

**Comment by autodidaddict** [comment]
I have this change in a local branch. I want to do more testing then I'll submit a PR.

**Comment by carols10cents** [comment]
Fixed and deployed to production!! Thank you @autodidaddict!
