### ISSUE TITLE
Crates last published multiple years ago say they were updated "a year ago"

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/crates.io#681]
The most recent version of the [xxhash crate](https://crates.io/crates/xxhash) was published on Jan 12, 2015. Today is Apr 19, 2017, a difference of over two years.

The page says the crate was updated **a** year ago. Something like "over a year ago", "two years ago", etc. seems like it would be more appropriate.
 
![image](https://cloud.githubusercontent.com/assets/174509/25182483/bb7cba72-24e2-11e7-8bd0-82ebda9a3e1b.png)

![image](https://cloud.githubusercontent.com/assets/174509/25182480/b537aabe-24e2-11e7-882e-188d859ae2b8.png)

**Comment by alexcrichton** [comment]
There was a bug around a year ago where all crates had their "last updated" field updated whenever they were downloaded (as opposed to when they were actually updated). That means that very little is likely "last updated" older than a year ago

**Comment by shepmaster** [comment]
I was afraid that "last updated" was going to be based on something besides a publish, but I didn't expect it to be a bug!

This is tricky, because this crate has pre Rust-1.0 syntax in it. It turns out the crate I was looking for is `xxhash2`. If I'd seen "2 years ago", I would have been more cognizant to check a different crate. 

It might be a niche case, but I wonder what the fallout of changing the updated at time to `max(published_time)` would be.

**Comment by shepmaster** [comment]
> changing the updated at time to max(published_time) would be.

I meant this as "do a migration to fix data", but realized it could also mean "change the UI to show the `max`, instead of using `updated_at`."

**Comment by alexcrichton** [comment]
Yeah chaning the UI seems plausible to me!

**Comment by locks** [comment]
This seems to have been addressed meanwhile. Thanks for reporting :)
