### ISSUE TITLE
Inconsistency in which version is considered to be the latest

### ISSUE THREAD

**Issue by dotdash** [rust-lang/crates.io#682]
For example on the page for [slog-term](https://crates.io/crates/slog-term), the header and the Cargo.toml example show 1.5.0, but the version badge and the versions list consider 2.0.0-4.0 to be the latest (non-yanked) version.

**Comment by carols10cents** [comment]
I think the versions list is correct, and that is where you should be able to look if you're interested in alpha versions of a crate.

The version badge sounds like a bug though, that should show 1.5.0.

**Comment by kzys** [comment]
Somehow fixed? Now there are no inconsistencies on the page.

**Comment by carols10cents** [comment]
Yes, I think we made some changes in this area... I'm a little unsure, since the example given has different versions now... but we can reopen if we find a case of this again and I'll grab the API response next time.
