### ISSUE TITLE
Still duplicated items in search result.

### ISSUE THREAD

**Issue by kennytm** [rust-lang/crates.io#685]
Test case (2017-04-23):

1. Go to https://crates.io/search?q=address (Search for "address", sort by "relevance")
2. There should be 126 results reported, split into 13 pages.
3. Check the result of each page (run `$('.desc > .info > a').map((t, v) => v.innerText).toArray()` in console):
    1. ipaddress, addressable-pairing-heap, generic-dns-update, ipgen-cli, delix, tokio-http2, addr2line, bind_before_connect, maidsafe_vault, gip
    2. **gip**, **bind_before_connect**, publicsuffix, memrange, coinaddress, serde_json, smoltcp, iban_validate, rbpf, timi
    3. fel-cli, eui48, sbrain, fake, ipnetwork, wping, fastchemail, base58, stable_deref_trait, safe-builder-derive
    4. **safe-builder-derive**, ipecho, fast_chemail, sendmail, maidsafe_types, acto-rs, rzbackup, ip, partners, ip6gen
    5. **acto-rs**, toa-ping, gl, tfs, ipify, asm6502, faker, sozu-command-lib, cidrr, throw
    6. cafs, **ipify**, **sozu-command-lib**, **throw**, **asm6502**, netaddr, letsencrypt-rs, mates, ralloc, **cidrr**
    7. scanner, backtrace, msgpacknet, **cafs**, fibers, conshash, emailaddress, get_if_addrs, tagua-parser, signifix
    8. vectorclock-rs, path, libproc, psl, tagua-llvm, lia, multiboot, dotenv_codegen, fsuipc, clap
    9. subotai, rsure, domain, nom, stellaris-launchpad, rustful, fractal-utils, rubbish, treebitmap, rusty-blockparser
    10. oscpad, dht, lettre, tftp_server, aerospike, igd, fs_eventbridge, koukku, hexplay, pistoncore-glfw_window
    11. dotenv, uuid, multiaddr, wesers, lovesense, resolve, austenite, finch, dotenv_macros, dcpu16-gui
    12. routing, zlib, gl_generator, blorb, glutin, spread, cuticula, cmail, encoding_rs, parking_lot
    13. bitcoin, twists, kvm, iron, cpuio, vat
4. Note how 10 results are randomly duplicated in the first few pages.

---

Another search page may has similar results: 

* https://crates.io/search?q=macos (53 results, 5 duplicates):
    1. ssh_bookmarker, enigo, cage, qcow2-fuse, rat, mac-notification-sys, gmp-mpfr-sys, notify-rust, osascript, emoji-commit
    2. context_bind, ring, adi, **emoji-commit**, freefare, vgrs, tantivy, rugrat, tutil, opencv
    3. rusty-tags, subprocess, auxv, coarsetime, rucaja, amqp, tokei, git-brws, substudy, dcpu16-gui
    4. rugcom, free-space-wipe, process_path, lua, keystroke, fs_eventbridge, shoop, region, djangohashers, javascriptcore-sys
    5. rugrat, **opencv**, **tantivy**, gog-sync, **tutil**, **vgrs**, an-rope, rugflo, kic, flatbuffers
    6. openssl, pcsc, perfcnt
* There is no problem when sorted by downloads:
    1. openssl, ring, context, tokei, rusty-tags, notify-rust, amqp, lua, webbrowser, substudy
    2. djangohashers, opencv, cage, perfcnt, dcpu16-gui, vgrs, gmp-mpfr-sys, keystroke, subprocess, shoop
    3. tantivy, rucaja, flatbuffers, tutil, coarsetime, rugint, freefare, rugrat, kic, kaws
    4. git-brws, rugflo, region, enigo, pcsc, auxv, an-rope, qcow2-fuse, emoji-commit, philips_hue_client
    5. rugcom, fs_eventbridge, context_bind, process_path, free-space-wipe, ssh_bookmarker, mac-notification-sys, git-interactive-rebase-tool, javascriptcore-sys, gog-sync
    6. osascript, rat, adi
* From this we can see the crates **context**, **webbrowser**, **rugint**, **philips_hue_client** and **git-interactive-rebase-tool** are hidden from the relevant view.

cc #162, #199 (@gkoz), not sure if the fix is really deployed.

**Comment by carols10cents** [comment]
0e491f405117a44aa2a173b507c6d045e0bf1627 is certainly in the master branch, we probably re-broke it in the switch to diesel.

**Comment by Deedasmi** [comment]
Appears to be resolved.

```
richardp@localhost:~/crates_scrape|
⇒  cargo search --limit 100 derive | cut -d " " -f 1 | uniq -cd
    Updating registry `https://github.com/rust-lang/crates.io-index`
richardp@localhost:~/crates_scrape|
⇒  cargo search --limit 100 address | cut -d " " -f 1 | uniq -cd
    Updating registry `https://github.com/rust-lang/crates.io-index`
richardp@localhost~/crates_scrape|
⇒  cargo search --limit 100 macos | cut -d " " -f 1 | uniq -cd
    Updating registry `https://github.com/rust-lang/crates.io-index`

```

**Comment by sgrif** [comment]
Looks resolved to me as well.
