### ISSUE TITLE
Crates.io crate download API is redirecting to invalid URL

### ISSUE THREAD

**Issue by lucacasonato** [rust-lang/crates.io#6850]
### Current Behavior

`https://crates.io/api/v1/crates/smallvec/1.10.0/download` is redirecting to `https://static.crates.iocrates/smallvec/smallvec-1.10.0.crate`

### Expected Behavior

`https://crates.io/api/v1/crates/smallvec/1.10.0/download` should redirect to `https://static.crates.io/crates/smallvec/smallvec-1.10.0.crate`

### Steps To Reproduce

```
$ curl -i https://crates.io/api/v1/crates/smallvec/1.10.0/download
HTTP/2 302 
content-length: 0
location: https://static.crates.iocrates/smallvec/smallvec-1.10.0.crate
server: nginx
date: Thu, 20 Jul 2023 12:23:43 GMT
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 0
content-security-policy: default-src 'self'; connect-src 'self' *.ingest.sentry.io https://docs.rs https://play.rust-lang.org https://static.crates.io; script-src 'self' 'unsafe-eval' 'sha256-n1+BB7Ckjcal1Pr7QNBh/dKRTtBQsIytFodRiIosXdE='; style-src 'self' 'unsafe-inline' https://code.cdn.mozilla.net; font-src https://code.cdn.mozilla.net; img-src *; object-src 'none'
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubDomains
via: 1.1 vegur, 1.1 6851e5f468b237438eae4078fbc9d3b8.cloudfront.net (CloudFront)
vary: Accept,Accept-Encoding,Cookie
x-cache: Miss from cloudfront
x-amz-cf-pop: AMS1-P2
x-amz-cf-id: VcRQX1BJXPCa2qSk0PuDBugdc8eZ6BRDJBNX2KqLrCkUFmKfpFmuQw==
```

**Comment by TheTerrasque** [comment]
Noticed the same for https://crates.io/api/v1/crates/mumblelink_reader/0.3.5/download

**Comment by lucacasonato** [comment]
@Turbo87 is aware of the issue, and is reverting the latest rollout. No need to +1 this issue. Please use :+1:, not comments.

**Comment by ximon18** [comment]
Works for me again now.

**Comment by lucacasonato** [comment]
Rollback is complete, and I am seeing recovery. Thanks @Turbo87!

**Comment by nevins-b** [comment]
seems likely related to this change yesterday https://github.com/rust-lang/crates.io/pull/6834/files#diff-18c17f16d6477d10ed90360fe38e0e13fc117ecd9548f8f9374236c3ec7f8750R201

**Comment by Turbo87** [comment]
@nevins-b yep, I'm already working on a fix for that :)

**Comment by Turbo87** [comment]
I've updated our [status page](https://status.crates.io/incidents/qtcxln295f0n) too now.
