### ISSUE TITLE
Allow generating multiple authentication tokens

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/crates.io#688]
I use Travis CI for publishing all my crates to avoid any chance of weird local settings influencing the package that gets published. At the moment that means all my repositories are sharing the one authentication token that crates.io makes available. I have accidentally leaked and had to revoke this token multiple times when trying to improve my CI scripts, this then provokes a round of replacing the token in all the repositories that use it. If I was instead able to generate a new token for each repository then I would be able to just revoke the one token that was leaked and update that one repository.

🌟 Bonus points for being able to restrict the tokens to only have access for publishing a subset of my crates, but I assume that would probably come in a second feature request after multiple full-access tokens are available.

**Comment by Nemo157** [comment]
This is something I've been meaning to request for quite a while, but keep forgetting. Finally reminded at just the right time by

> Notable is that each time on each machine that you run npm login, a new token gets generated and saved in the registry so that you can later revoke a subset of the tokens.
> — @carols10cents https://github.com/rust-lang/cargo/issues/3917#issuecomment-297751222

**Comment by Nemo157** [comment]
Assuming this is something that is wanted, I might submit a PR for it; been taking a look at the codebase and think I can find my way round everything that would be needed.

**Comment by carols10cents** [comment]
Awesome! Yes, I definitely want such a thing for a variety of reasons :) Let me know if you have any questions!
