### ISSUE TITLE
Stale link in doc.crates.io

### ISSUE THREAD

**Issue by vi** [rust-lang/crates.io#692]
http://doc.crates.io/manifest.html#building-dynamic-or-static-libraries

"You can read more about the different crate types in the [Rust Reference Manual][1]" (should be [this link][2]).

Additionally the [redirection page][1] could have a script that detects `#linkage` and forwards appropriately.

[1]:https://doc.rust-lang.org/reference.html#linkage
[2]:https://doc.rust-lang.org/reference/linkage.html

**Comment by carols10cents** [comment]
Oops, not sure why I didn't notice this: the docs live in cargo's repo, and this was fixed in https://github.com/rust-lang/cargo/pull/4057.
