### ISSUE TITLE
/api/v1/crates?following=true only works with legacy tokens

### ISSUE THREAD

**Issue by LawnGnome** [rust-lang/crates.io#6929]
The way the [auth check is set up on this endpoint](https://github.com/rust-lang/crates.io/blob/18599be82a5faedf28e21ea7865397cb8cefe37a/src/controllers/krate/search.rs#L193) essentially falls through to the ["endpoint only allows legacy tokens" branch in `AuthCheck::check`](https://github.com/rust-lang/crates.io/blob/18599be82a5faedf28e21ea7865397cb8cefe37a/src/auth.rs#L92-L93), which is likely incorrect, since it means the `following` crate search option can only be used with a legacy token in practice. (Or a cookie, of course.)

I think there are two options:

1. Explicitly allow any token to access this endpoint, regardless of scope, or
2. Add a new scope that provides access to user information (which we could then use for currently cookie only endpoints like `/api/v1/me`).

Regardless, we should probably audit all the places we use `AuthCheck::default()` to instantiate the auth check, since the default behaviour right now only allows legacy tokens unless endpoint scopes are then added with `with_endpoint_scope`. (And, of course, you can't actually create a legacy token any more.)

**Comment by Turbo87** [comment]
question is wether that endpoint should support token auth at all. the support for auth there is primarily/only meant to be used by our own frontend, which uses cookie auth.

**Comment by Turbo87** [comment]
since nobody appears to be missing this feature I guess we can close the issue :)
