### ISSUE TITLE
Yanked versions shown as top choice by other sites

### ISSUE THREAD

**Issue by nyurik** [rust-lang/crates.io#6946]
### Current Behavior

The [martin crate](https://crates.io/crates/martin), currently at v0.8.7, at one point published a v1.0.0-alpha version that was later yanked. The crates.io web UI correctly shows the latest version, but other sites incorrectly use the `versions[0]` - first entry in the API response, which is still showing yanked alpha version.  For example, popular `shield.io` site uses `versions[0].license` (see [code](https://github.com/badges/shields/blob/7d966ab6bd340ce358a733c9db40900f3650a573/services/crates/crates-license.service.js#L38)) for detecting latest version.

I believe it would be better to sort versions array first by yanked status and then by version. 

Relevant portion of the API response for https://crates.io/api/v1/crates/martin

```json
{
  "versions": [
    {
      "created_at": "2021-10-18T13:32:02.600041+00:00",
      "num": "1.0.0-alpha.0",
      "updated_at": "2022-11-21T03:56:25.244956+00:00",
      "yanked": true
    },
    {
      "created_at": "2023-06-23T04:05:38.815265+00:00",
      "num": "0.8.7",
      "updated_at": "2023-06-23T04:05:38.815265+00:00",
      "yanked": false
    }
  ]
}
```

### Expected Behavior

Sort versions first by yanked (ASC), and then by semver (DESC)

**Comment by nyurik** [comment]
See also https://github.com/badges/shields/issues/9453

**Comment by Turbo87** [comment]
we are sorting them by publish date. whether yanking matters or not is up for the client to decide but it should not be based only on the default sorting.
