### ISSUE TITLE
Distributing binary blobs on crates.io

### ISSUE THREAD

**Issue by simonsan** [rust-lang/crates.io#6992]
### Current Behavior

My question is regarding the recent publishing of a binary blob on crates.io. Is it allowed (ToS) to distribute a precompiled crate (as in binary files) without the source on that platform? I thought this was not the case (allowance), but haven't found anything online.

### Expected Behavior

Afaics there is nothing saying/proving that this is actually the binary that is built from that source. It's just a blob. As long as crates.io is not able to (automatically) verify that both belong together, I think this shouldn't be given a benefit of a doubt and should be removed by the admins. It could be whatever in that blob.

(I am aware, that the person that published this is actually a known and trustful member of the community.)

I'm also worried, that this might be a precedent and more people will start to do that, essentially undermining the openness of crates.io ecosystem.

### Environment

- Browser:
- OS:

### Anything else?

https://github.com/serde-rs/serde/issues/2538
https://docs.rs/crate/serde_derive/latest/source/

**Comment by Turbo87** [comment]
As far as I am aware our current policies do not restrict this. There is an RFC open to update our policies (https://github.com/rust-lang/rfcs/pull/3463), but unless the binary blob would be malicious or do anything else aside from codegen these policies would also allow this.

FWIW I agree that the serde precompilation isn't particularly great, but the crates.io team will not enforce any opinions in this discussion.

**Comment by Turbo87** [comment]
There are currently no plans to officially support any kind of precompilation and given the struggles with these kinds of things in the Python ecosystem I'm personally not particularly keen on changing that 😅

**Comment by Turbo87** [comment]
The best place to propose something like this is https://github.com/rust-lang/rfcs/ :)
