### ISSUE TITLE
Invalid content of a crate’s page when going back in history

### ISSUE THREAD

**Issue by IvanUkhov** [rust-lang/crates.io#70]
Hello,

I have noticed the following behavior:
1. Open [a package](https://crates.io/crates/git2), say `A`, with a dependency, say `B`, that does not belong to the owner `A`.
2. Note the information given about `A` in the right column (author, license, keywords, etc.).
3. Click on `B` at the bottom of the page under “Dependencies.”
4. Note the information given about `B` in the right column.
5. Press the Go Back button of the browser (tried in Chrome and Safari).
6. See that we are on the page of `A`, but the right column is as if we were on the page of `B`.

Regards,
Ivan

**Comment by carols10cents** [comment]
I just tried and can't get this to happen anymore, please comment and/or reopen if I'm mistaken!
