### ISSUE TITLE
Add a badge for crate authors to self-report their maintenance intentions

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#704]
Part of [RFC 1824](https://github.com/rust-lang/rfcs/blob/master/text/1824-crates.io-default-ranking.md), rust-lang/rust#41616.

Add to the `badges` table in `Cargo.toml` a `maintenance` key that crate authors could use to
self-report their maintenance intentions. The valid values would be along the
lines of the following, and would influence the ranking in the order they're
presented:

<dl>
  <dt>Actively developed</dt>
  <dd>
    New features are being added and bugs are being fixed.
  </dd>

  <dt>Passively maintained</dt>
  <dd>
    There are no plans for new features, but the maintainer intends to respond
    to issues that get filed.
  </dd>

  <dt>As-is</dt>
  <dd>
    The crate is feature complete, the maintainer does not intend to continue
    working on it or providing support, but it works for the purposes it was
    designed for.
  </dd>

  <dt><i>none</i></dt>
  <dd>
    We display nothing. Since the maintainer has not chosen to specify their
    intentions, potential crate users will need to investigate on their own.
  </dd>

  <dt>Experimental</dt>
  <dd>
    The author wants to share it with the community but is not intending to meet
    anyone's particular use case.
  </dd>

  <dt>Looking for maintainer</dt>
  <dd>
    The current maintainer would like to transfer the crate to someone else.
  </dd>

  <dt>Deprecated</dt>
  <dd>
    The maintainer does not recommend using this crate (the description of the crate can describe why, there could be a better solution available or there could be problems with the crate that the author does not want to fix) Added from a suggestion in #549
  </dd>

</dl>

These would be displayed as badges on lists of crates.

These levels would not have any time commitments attached to them-- maintainers
who would like to batch changes into releases every 6 months could report
"actively developed" just as much as mantainers who like to release every 6
weeks. This would need to be clearly communicated to set crate user
expectations properly.

This is also inherently a crate author's statement of current intentions, which
may get out of sync with the reality of the crate's maintenance over time.

Also need to update [the documentation that currently lives in cargo's repo](https://github.com/rust-lang/cargo/blob/8cc22d2c9d9985122f16789ea24cfe6411ae408a/src/doc/manifest.md#package-metadata).

Please let me know if you have any questions, potential implementers!

**Comment by marti1125** [comment]
Hi @carols10cents!! I would like to work on this

**Comment by marti1125** [comment]
Hello @carols10cents I made list of tasks following the email
- [ ] Add another variant to the Badge enum https://github.com/rust-lang/crates.io/blob/master/src/badge.rs#L12
- [ ] Create that variant from the database in this match https://github.com/rust-lang/crates.io/blob/master/src/badge.rs#L48
- [ ] Add tests to https://github.com/rust-lang/crates.io/blob/master/src/tests/badge.rs
- [ ] Add an ember component like the other badge components in app/components
- [ ] Add a template in app/templates/components to display the badge
- [ ] Add JSON to the fixture used for frontend tests here https://github.com/rust-lang/crates.io/blob/master/mirage/fixtures/search.js#L23
- [ ] Add a frontend test that checks that the badge's HTML is rendered on the page around here https://github.com/rust-lang/crates.io/blob/master/tests/acceptance/search-test.js#L27
- [ ] Document how to specify the badge in Cargo.toml over in cargo's repo here: https://github.com/rust-lang/cargo/blob/master/src/doc/manifest.md#package-metadata

**Comment by vignesh-sankaran** [comment]
How do we want the maintenance intention badges to look like? Did we want it to look like the CI badges e.g. TravisCI?

**Comment by vignesh-sankaran** [comment]
We also need to:
[ ] Save the badges into the database in the transaction [here](https://github.com/rust-lang/crates.io/blob/master/src/krate.rs#L1129)
[ ] Remove the warning in cargo that says that the maintenance badge is not a recognised badge and is ignored during a publish. If that metadata is not being passed to crates.io, that needs to be added in as well. It may also require parsing in the crates.io backend.

**Comment by vignesh-sankaran** [comment]
Could we close this issue @carols10cents? I think everything for this issue has been implemented.

**Comment by carols10cents** [comment]
Sounds good!
