### ISSUE TITLE
Add the ability for crate authors to add isitmaintained.com badges to their crate

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#705]
Part of [RFC 1824](https://github.com/rust-lang/rfcs/blob/master/text/1824-crates.io-default-ranking.md), rust-lang/rust#41616.

[isitmaintained.com][] provides badges indicating the time to resolution of GitHub issues and percentage of GitHub issues that are open.

[isitmaintained.com]: http://isitmaintained.com/

We will enable maintainers to add these badges to their crate, in a similar way that the TravisCI/Appveyor/Gitlab badges are implemented today.

Also need to update [the documentation that currently lives in cargo's repo](https://github.com/rust-lang/cargo/blob/8cc22d2c9d9985122f16789ea24cfe6411ae408a/src/doc/manifest.md#package-metadata).

Please let me know if you have any questions, potential implementers!

**Comment by nisargthakkar** [comment]
Hey @carols10cents, I'd like to pick up this task

**Comment by carols10cents** [comment]
Awesome!! I'm imagining that this would fit in to the existing system of CI badges-- take a look in these spots:

- The `Badge` enum will need a new variant: https://github.com/rust-lang/crates.io/blob/b41061fb80ab8e77a0f83ef9d01da1db01de8ae2/src/badge.rs#L15
- The `badge_type` match will need a new arm: https://github.com/rust-lang/crates.io/blob/b41061fb80ab8e77a0f83ef9d01da1db01de8ae2/src/badge.rs#L62
- Add to the tests in https://github.com/rust-lang/crates.io/blob/master/src/tests/badge.rs
- Add a component in https://github.com/rust-lang/crates.io/tree/master/app/components
- Add a template in https://github.com/rust-lang/crates.io/tree/master/app/templates/components 
- Add an instance of the new badge in this front-end test fixture https://github.com/rust-lang/crates.io/blob/b41061fb80ab8e77a0f83ef9d01da1db01de8ae2/mirage/fixtures/search.js#L23
- Add a front-end test looking for the HTML (it doesn't have to *actually* load the badge, just generate the correct HTML) here: https://github.com/rust-lang/crates.io/blob/b41061fb80ab8e77a0f83ef9d01da1db01de8ae2/tests/acceptance/search-test.js#L27
- And then finally make another PR to add documentation over in cargo's repo here: https://github.com/rust-lang/cargo/blob/master/src/doc/manifest.md#package-metadata

Please let me know if you have any questions at all!!!

**Comment by nisargthakkar** [comment]
@carols10cents I was able to set up the badges correctly for isitmaintained (issue resolution and open issues), codecov and coveralls.
I'm not sure what to set the content when the mouse is hovered on it.

This is what I have set currently:
Is It Maintained average time to resolve an issue
Is It Maintained percentage of issues still open
CodeCov coverage status for the <branch> branch
Coveralls coverage status for the <branch> branch

The ones for isitmaintained do not feel right, though. It would be great if you could suggest some improvements

**Comment by carols10cents** [comment]
They sound fine to me, what doesn't feel right about them?

**Comment by nisargthakkar** [comment]
I think it would be better if there were some punctuations like 
Is It Maintained: Average time to resolve an issue

Also in the previous comment, i messed up in markdown, the text for CodeCov and Coveralls was set to:
CodeCov coverage status for the &lt;branch&gt; branch
Coveralls coverage status for the &lt;branch&gt; branch

**Comment by carols10cents** [comment]
Fixed by #726!! Thank you @nisargthakkar!!!
