### ISSUE TITLE
Add the ability for crate authors to add code coverage badges to their crate

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#706]
Part of [RFC 1824](https://github.com/rust-lang/rfcs/blob/master/text/1824-crates.io-default-ranking.md), rust-lang/rust#41616.

Start with [Coveralls] and [Codecov](https://codecov.io/).

[Coveralls]: https://coveralls.io

We will enable maintainers to add these badges to their crate, in a similar way that the TravisCI/Appveyor/Gitlab badges are implemented today.

Also need to update [the documentation that currently lives in cargo's repo](https://github.com/rust-lang/cargo/blob/8cc22d2c9d9985122f16789ea24cfe6411ae408a/src/doc/manifest.md#package-metadata).

Please let me know if you have any questions, potential implementers!

**Comment by nisargthakkar** [comment]
Hey @carols10cents, I'd like to pick up this task

**Comment by carols10cents** [comment]
Awesome!!! The process for this should be really similar to #705 :) Please let me know if you have any questions!!! ❤️

**Comment by carols10cents** [comment]
Fixed by #726!! Thank you @nisargthakkar!!!
