### ISSUE TITLE
Server drops connection while returning a 500 error response

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/crates.io#713]
I forced a 500 error response by deleting the `crates.name` column from my database. When making a request to the crates list with `curl` the connection then hung for 30 seconds. From the final line of the below log, and other log messages I've seen from the proxy in `yarn run start:local`, I believe this is `curl` waiting on the connection for 30 seconds after the server has dropped it without closing it properly.

`curl` log (this hung for 30 seconds after printing the first `HTTP/1.1 500 [...]` line):

```
→ time curl -i http://localhost:8888/api/v1/crates
HTTP/1.1 500 Internal Server Error
HTTP/1.1 500 Server Error
Content-Length: 48
Date: Thu, 04 May 2017 21:59:55 GMT
Connection: keep-alive

Error 500: Server Error
Client closed connection
curl  0.01s user 0.01s system 0% cpu 30.050 total
```

server log (this was all printed as soon as the request was started):

```
  version: 1.1.0
  method: Get
  scheme: Http
  host: Name("localhost:8888")
  path: /api/v1/crates
  query_string: None
  remote_addr: V4(127.0.0.1:60255)
  hdr: Host=["localhost:8888"]
  hdr: User-Agent=["curl/7.43.0"]
  hdr: Accept=["*/*"]
ERROR:conduit_log_requests: 127.0.0.1:60255 [2017-05-04T23:59:25+02:00] Get /api/v1/crates - 16ms 500: column crates.name does not exist column crates.name does not exist
```

**Comment by carols10cents** [comment]
o.O strange. I'm not sure why this is happening, but yeah, sounds wrong.

**Comment by carols10cents** [comment]
Sorry this has sat so long. I just tried to reproduce it following the steps you laid out, and I got an immediate 500 response, so I think this was fixed at some point. Thanks!
