### ISSUE TITLE
Changing metadata should be possible without bumping a version

### ISSUE THREAD

**Issue by lifthrasiir** [rust-lang/crates.io#7146]
Currently Cargo doesn't allow the metadata to be separately updated. This doesn't seem right (as the semantic versioning only concerns about the public API and the metadata is not a part of the public API).

In order to fix this issue, the publish endpoint (`/api/v1/crates/new`) should be adjusted to accept the metadata without the tarball (well, or have a new endpoint for that), and the server will check if the name, version, dependencies and features match to those stored before updating that. In the CLI the `cargo publish` command should ask for the metadata update when the version hasn't been changed.

**Comment by hi-rustin** [comment]
I think the trick part is we also package `Cargo.toml[.orig]` in `.crate` file. If crates.io only allows to update the metadata. Then the metadata of `Cargo.toml[.orig]` from the `.crate` would be different from the database.

Also, I think it would also affect the checksum check of the tarball file.

**Comment by retep998** [comment]
The metadata in the crate itself should not be mutable. Instead the metadata from the crate should be used as the default value displayed on crates.io, but the user can then change the metadata visible on crates.io via the web UI, without affecting the metadata actually stored in the crate.

**Comment by hi-rustin** [comment]
> but the user can then change the metadata visible on crates.io via the web UI, without affecting the metadata actually stored in the crate.

I think this kind of inconsistency would cause a lot of confusion.

Can I ask what kind of metadata you only want to change in creates.io instead of `Cargo.toml`?

**Comment by hi-rustin** [comment]
See: https://blog.vlt.sh/blog/the-massive-hole-in-the-npm-ecosystem

And https://github.com/rust-lang/crates.io/pull/7194 will force us to use these fields from Cargo.toml.

**Comment by Turbo87** [comment]
I just rediscovered https://github.com/rust-lang/crates.io/issues/3167, which basically describes the same thing. Let's move the discussion over there to not have two duplicate issues :)
