### ISSUE TITLE
The note is misleading if the most recent version of the crate is yanked, 

### ISSUE THREAD

**Issue by nagisa** [rust-lang/crates.io#716]
Similar to https://github.com/rust-lang/crates.io/issues/76

Currently if the most recent version of the crate is yanked this is what crates.io says when you click the crate in the search results:

> This crate has been yanked, but it is still available for download for other crates that may be depending on it.
> 
> You may wish to view all versions to find one that has not been yanked.

Clicking on a search result should display the most recent non-yanked version instead.

**Comment by Keats** [comment]
Just ran into this for one of my crates and thought I somehow yanked everything. Very confusing

**Comment by carols10cents** [comment]
Yep, this is a duplicate of #510.
