### ISSUE TITLE
crates.io sends status 200 OK, instead of 404 Not found, when "crate or version not found" error occurred

### ISSUE THREAD

**Issue by devurandom** [rust-lang/crates.io#717]
When a crate or version cannot be found, crates.io sends a `200 OK` status instead of a `404 Not found`:
```
# http -v https://crates.io/api/v1/crates/getopts/0.2/download
GET /api/v1/crates/getopts/0.2/download HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: crates.io
User-Agent: HTTPie/0.9.9



HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 52
Content-Type: application/json; charset=utf-8
Date: Sun, 07 May 2017 19:36:43 GMT
Server: nginx
Set-Cookie: cargo_session=--3Mz45cH3itfVkmY41+nVjWRm9+0=; HttpOnly; Secure; Path=/
Strict-Transport-Security: max-age=31536000
Via: 1.1 vegur

{
    "errors": [
        {
            "detail": "crate or version not found"
        }
    ]
}
```

**Comment by carols10cents** [comment]
Yep, that seems wrong.

**Comment by Phrohdoh** [comment]
What is the expected complexity for fixing this? I haven't looked at the code at all fwiw.

If it is sufficiently simple to run this on my machine I'd like to pick this up.

**Comment by sgrif** [comment]
For endpoints that have been ported to Diesel, the fix is to just to stop calling `human` anywhere that the error message indicates it should be a 404 (`diesel::Error::NotFound` will be properly handled if allowed to bubble up). So at least for those endpoints the complexity is low. Unsure how many places have this issue and are still using rust-postgres

**Comment by mauricio** [comment]
This doesn't happen anymore, was fixed by https://github.com/rust-lang/crates.io/commit/b12e3ce6f02de2266f256166d8da7373aaefcb53 .

**Comment by carols10cents** [comment]
Sounds good!

**Comment by jtgeibel** [comment]
@carols10cents I may be remembering this wrong, but I thought that for the routes `cargo` hits that it is always expecting a JSON response with an embedded error message instead of a 404.  I can't seem to find what gave me this impression though.

**Comment by jtgeibel** [comment]
I've taken a closer look and I don't see any issue with returning a 404 to cargo for the download route.  This route is handled differently by cargo than other api requests.
