### ISSUE TITLE
category_slugs is very hard to find

### ISSUE THREAD

**Issue by lilianmoraru** [rust-lang/crates.io#721]
I wanted to add some categories to a project and I searched ~40-60 minutes until I found them(I found the page randomly before, when trying to publish one of my own projects - so I knew how it should look like and that these exist).

I went through all the options in the `Docs` on `crates.io` and could not find it.
Searched on Google and found `crates.io/categories`, which is something(you can't find the categories very easily from the main page unless you detect the `see all` at the bottom of the page, between the 5 lists), but still not helpful to a developer that wants to add a category to `Cargo.toml`.

In the end, through Google, I stumbled on this issue: https://github.com/rust-lang/crates.io/issues/544 and observed in the mentioned link: http://doc.crates.io/manifest.html#package-metadata through the comments in the code, [crates.io/category_slugs](https://crates.io/category_slugs) was mentioned - I finally found it.

Could we please have the `category_slugs` link in the `Docs` drop-down(crates.io) or maybe somewhere on the `crates.io/categories` page?

**Comment by carols10cents** [comment]
Yup, great suggestion!

**Comment by carols10cents** [comment]
Let's go with the crates.io/categories page. Doing this involves adding a link to `/category_slugs` somewhere in [the categories template](https://github.com/rust-lang/crates.io/blob/405b2ad74715f22d756de749be4acb9626c1019b/app/templates/categories.hbs) -- where and what the link and the text around it says exactly is up to whoever implements this :)

**Comment by autodidaddict** [comment]
![screenshot from 2017-08-20 19-17-30](https://user-images.githubusercontent.com/13748641/29499319-4999983e-85dc-11e7-9200-b397afc41201.png)

Here's a quick straw man I whipped up. The `here` link goes to the category slugs page while the `Cargo.toml` link goes to the manifest documentation page.

Thoughts? I figured showing this here first would be easier than starting a PR. I tried a bunch of variations with this text at the top and I couldn't find any that didn't distract from the category list.

**Comment by lilianmoraru** [comment]
To be sincere, the visibility of that is not very good.
Personally, I probably would never end-up seeing that link.

May be a mention/"chapter" on the ["Publishing on crates.io" page](http://doc.crates.io/crates-io.html)(both options or just on the Publishing page?)?

**Comment by autodidaddict** [comment]
Yeah it's too subtle but this issue called for it being on this page.

**Comment by autodidaddict** [comment]
I think that's a more appropriate location. I also noticed that you can't get to it from the `manifest` docs. I'd like to suggest then : 
* Add a link to the category slugs from the "Publishing on crates.io" with a nice paragraph on picking categories for your crate
* Add a link to the category slugs from the Cargo.toml manifest documentation

Is there a guide for how to make a "good" crate? Because it looks like we're also missing tips like supplying a good readme, supplying keywords, supplying categories, etc.

**Comment by dathinab** [comment]
I would add a link under `Docs` (at the bottom), too.
If you are used to cargo and are in the situation "uh, is there a good slug for it?",
having to go to any of the other documentation entries and scanning it for a link
is a bit annoying.

**Comment by carols10cents** [comment]
Fixed by #1463! Will get deployed in the next few days.
