### ISSUE TITLE
can't create a token

### ISSUE THREAD

**Issue by InfoGraphTheory** [rust-lang/crates.io#7270]
### Current Behavior

Trying to create a token.
I fill out all the fields and press the button Generate token and nothing happens.

### Expected Behavior

I would have expected an API token to be created or an error message telling me what went wrong...

### Steps To Reproduce

1. login
2. goto setting
3. goto api tokens

### Environment

- Browser: firefox
- OS: raspian :)

**Comment by InfoGraphTheory** [comment]
Behind the scenes, I see that I get this JS error when clicking the generate button:  
Uncaught TypeError: ie.randomUUID is not a function

**Comment by carols10cents** [comment]
What version of firefox?

Related:

- https://github.com/rust-lang/crates.io/issues/5062
- https://github.com/rust-lang/crates.io/issues/5103

**Comment by InfoGraphTheory** [comment]
91.8.0esr (32-bit)

**Comment by InfoGraphTheory** [comment]
updating firefox worked
