### ISSUE TITLE
Automatically generated endpoint documentation

### ISSUE THREAD

**Issue by phrohdoh** [rust-lang/crates.io#731]
I did some digging but could not find docs for crates.io endpoints for tool authors.

[Swagger](http://petstore.swagger.io/) is pretty popular these days (not sure how long that will be true, though).

If this exists already and I missed it please link to it here and feel free to close this ticket.

**Comment by carols10cents** [comment]
It does not exist and this is a good idea!

**Comment by shellscape** [comment]
Checking in on this long-dormant issue. I did some poking around, and while there is some documentation on the book, some of the information on return values don't match the API any longer, and it's not very complete. Any chance of this effort getting a revival?

**Comment by carols10cents** [comment]
It'd be great if you revive effort on this!

**Comment by Turbo87** [comment]
closing this in favor of #741
