### ISSUE TITLE
Enable OCSP stapling

### ISSUE THREAD

**Issue by est31** [rust-lang/crates.io#733]
Apparently the latest [cargo outage](https://github.com/rust-lang/cargo/issues/4072) on Windows was caused by downtime of lets encrypt OCSP servers. There is actually something one can do to be resilient against such downtimes, at least for a couple of hours: enabling OCSP stapling. It would be cool to have it to be protected from future downtimes.

One tool which can display the OCSP stapling state for websites: https://www.digicert.com/help/

**Comment by zofrex** [comment]
Double-win: enabling OCSP stapling will also make hitting crates.io (slightly) faster!

If enabling stapling isn't possible or desirable, I would consider changing Cargo to ignore a failure to connect to the OCSP server. This is the more normal behaviour for clients, otherwise the chances of outage are increased (as demonstrated today).

**Comment by carols10cents** [comment]
I'm not sure what's involved in this and whether or not enabling stapling is possible or desirable; I'll have to do some research.

If anyone reading this is knowledgeable on this subject, I'm interested to know:

- Does this change need to happen in crates.io's code base (server side) or cargo's code base (client side)?
- What are the implications of this change?
- Literally what do I do
- Crates.io is running on heroku using their letsencrypt SSL integration, is it possible to do whatever needs to be done with heroku?

**Comment by est31** [comment]
* Both server and client need support, but I want to keep this issue to track the server support. libcurl+openssl almost certainly has support, winapi SSL should have support as well. Rustls seems to have [no support](https://github.com/ctz/rustls/issues/31)?
* Implications are that clients which require ocsp checking for each ssl connection load faster, and that we are a bit more resilient against lets encrypt servers having downtimes.
* Don't know about heroku, their manual seems to [mention no OCSP](https://devcenter.heroku.com/articles/ssl).

**Comment by zofrex** [comment]
According to the headers returned, crates.io is running on nginx. If nginx is terminating SSL for the site then OCSP stapling can be enabled in the nginx config, which is usually straightforward:

```nginx
ssl_stapling on;
ssl_stapling_verify on;
resolver <IP DNS resolver>;
```

**Comment by jtgeibel** [comment]
Our SSL termination isn't done by nginx, but by the Heroku router, and per their [docs] it doesn't look like they currently support OCSP stapling nor have a public timeline for adding support.

[docs]: https://help.heroku.com/OFEFZU06/does-heroku-support-ocsp-stapling

**Comment by kzys** [comment]
`S-blocked`?

**Comment by kzys** [comment]
While I cannot test that from https://www.digicert.com/help/, moving to CloudFront would make enabling OCSP stapling possible.

https://aws.amazon.com/blogs/aws/cloudfront-ssl-ciphers-session-ocsp-pfs/

> OCSP Stapling – An SSL certificate must be validated before it can be used. The certificate authority (CA) for the certificate must be consulted in order to ensure that the certificate is legitimate and that it has not been revoked. In the absence of support for OCSP Stapling, the client (e.g. a web browser) will take care of this interaction with the CA, once again at the cost of some round trips and the associated latency they bring. CloudFront now implements OCSP Stapling. This approach moves the burden of domain name resolution (to locate the CA) and certificate validation over to CloudFront, where the results can be cached and then attached (stapled, hence the name) to one of the packets in the SSL handshake. The clients no longer need to handle the domain name resolution or certificate validation and benefits from the work done on the server.

**Comment by est31** [comment]
According to https://www.ssllabs.com/ssltest/ , crates.io still doesn't have OCSP stapling enabled.

**Comment by kzys** [comment]
It may depend on the edge servers.

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#request-custom-ocsp-stapling

> When CloudFront receives a lot of HTTPS requests for the same domain, every server in the edge location soon has a response from the CA that it can "staple" to a packet in the SSL handshake; when the viewer is satisfied that the certificate is valid, CloudFront can serve the requested object.

Actually https://www.ssllabs.com/ssltest/analyze.html?d=crates.io&s=99.84.224.2 currentlydoes OCSP stapling.

Back to the original issue, we still have a chance of downtime when 1) CloudFront's OCSP server is down and 2) some edge servers don't have a response from the CA and 3) the edge server without the CA response is used.

**Comment by Turbo87** [comment]
while the above comment still identified some scenarios in which we might experience downtime, the original issue appears to have been addressed so I'll close this issue for now until we can figure out a way to solve the other scenarios.
