### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by andydixon** [rust-lang/crates.io#7344]
### Current Behavior

When logging into crates.io, I get a popup window to log into GitHub. After logging in, I am redirected on the popup window to https://crates.io/github-redirect.html?code=c0796018XXXXXX2a5f5f&state=QYyUSFLmnMXXXXXXXXXXXX (obfuscated), and I am left with a white window.

The parent window shows a spinner next to 'Log in with Github', and nothing happens.

I have removed the OAuth from my Github account and let it recreate, but no login is possible for me.

A page refresh still shows that I am not logged in, despite the OAuth token being added to my Github account

### Expected Behavior

Authentication to succeed and login process to complete on the parent window

### Steps To Reproduce

Click 'Log in with GitHub'
Follow authentication flow

### Environment

Tested on: 

Safari, Firefox Developer Edition on MacOS 14.0
Firefox on Windows 11
Safari (over 5G to exclude network) on iPhone 13

### Anything else?

Web developer tools show on the popup window:
Cookie “cargo_session” with the “SameSite” attribute value “Lax” or “Strict” was omitted because of a cross-site redirect.
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). [preload.js:136:52]
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). [github-redirect.html:4:10]

**Comment by Turbo87** [comment]
duplicate of #7343 :)
