### ISSUE TITLE
Show build status for the relevant version, rather than master

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/crates.io#743]
Currently the most recent version of serde is 1.0.8. As such, https://crates.io/crates/serde should show build status for 1.0.8 rather than master.

```diff
- https://api.travis-ci.org/serde-rs/serde.svg?branch=master
+ https://api.travis-ci.org/serde-rs/serde.svg?branch=v1.0.8
```

Similarly, https://crates.io/crates/serde/1.0.7 should show build status for 1.0.7.

Different projects use different naming schemes for their tags, so we would need to insist on one particular scheme or allow it to be configurable.

This came up during the libs team discussion of reqwest. cc @seanmonstar @sfackler

**Comment by seanmonstar** [comment]
Also pointed out in the meeting: the status of the tag build likely is from when the tag was created, and doesn't show that the version could compile on current stable Rust.

**Comment by sfackler** [comment]
This is already doable via the `branch` field in the config struct in `Cargo.toml`.

**Comment by dtolnay** [comment]
Oh but manually writing the crate version in multiple places is a bummer. It's the same complaint we had with html_root_url https://github.com/rust-lang/rust/issues/42300. :crying_cat_face:

**Comment by sfackler** [comment]
Right, but that's a Cargo issue, not a crates.io issue IMO

**Comment by Nemo157** [comment]
See https://github.com/rust-lang/cargo/issues/2075, a full implementation of that feature (IMO) would cover this as well and allow the `branch` field to be based off the "single source of truth for crate versions".

**Comment by carols10cents** [comment]
I don't think this feature would be useful; released versions should always be passing on CI. The CI badges are more of an indication of the general health of the project and a signal of active maintenance.

**Comment by seanmonstar** [comment]
> I don't think this feature would be useful; released versions should always be passing on CI. The CI badges are more of an indication of the general health of the project and a signal of active maintenance.

In this instance, I disagree. When reqwest v1.0 is released, and someone visits its crate page, it should show that v1.0 passed CI. As work on reqwest master continues, and inevitably something causes the build to fail, it would be quite damaging to show a CI failed badge on the crate page, even though 1.0 did pass.

Perhaps #540 better captures this idea, I haven't had time to digest it.
