### ISSUE TITLE
Crate claim

### ISSUE THREAD

**Issue by brynnbrancamp** [rust-lang/crates.io#7482]
The crate "editor" has the following message:

`If you want to use this crate name, please contact the crates.io team at

https://github.com/rust-lang/crates.io/issues or
https://discord.gg/rust-lang
I consent to the transfer of this crate to the first person who requests it.`

Am I able to procure this crate name for this GitHub account? (@brynnbrancamp)

**Comment by Turbo87** [comment]
@brynnbrancamp we've added you to the crate now. feel free to remove the existing owner as you see fit.
