### ISSUE TITLE
Add explanation to clarify what user should be seeing when setting up environment

### ISSUE THREAD

**Issue by natboehm** [rust-lang/crates.io#750]
When completing the section on [Building and serving the frontend](https://github.com/rust-lang/crates.io/blob/master/docs/CONTRIBUTING.md#building-and-serving-the-frontend) it might be useful for the user to be able to see what should be happening if everything is working correctly once running `yarn run start`. At the conclusion of the section, including a screenshot of the page being served or a stated comparison of the live link and link being served locally would be good options. A quick line could also be included explaining something like if all goes well, this is what your page should look like.

**Comment by carols10cents** [comment]
Ooooh I just happened across someone linking to https://asciinema.org/ - it lets you record terminal sessions and then it hosts a little video like thing playing back the output! Example: https://asciinema.org/a/47vbdch8srbhf3j5kta7j9bov

It might be kind of cool to have a recording of setting up and running tests and things!

Or a screencast could work too, to be able to switch to the web browser :)

**Comment by Turbo87** [comment]
closing this issue since there hasn't been much activity here for a while. PRs to improve the contributing docs are always still welcome though :)
