### ISSUE TITLE
Clarify path for publishing a crate to your local crates.io

### ISSUE THREAD

**Issue by natboehm** [rust-lang/crates.io#752]
When setting up the crates environment, towards the end of the section [Publishing a crate to your local crates.io](https://github.com/rust-lang/crates.io/blob/master/docs/CONTRIBUTING.md#publishing-a-crate-to-your-local-cratesio), the description of the path to the directory `tmp/index-co` with the git index set up by `./script/init-local-index.sh` is confusing. Providing an example path for if the repo was cloned, `/rust-lang/crates.io/tmp/index-co`, or describing the path in words would improve readability and reduce confusion. Currently the `/checkout` in front of `/tmp` could mislead someone to believe there is a directory in `/crates.io` named `/checkout`.

**Comment by Deedasmi** [comment]
We could modify the script to give you an example command. 

```
cat - <<-EOF
Your local git index is ready to go!

You can test publishing crates by using:

cargo publish --index $PWD/tmp/index-bare 

Please refer to https://github.com/rust-lang/crates.io/blob/master/README.md for more info!
EOF
```

Alternatively (or combined), we could rewrite init-local-index to be an absolute path (crate root) unless given a location parameter, in which case we could print as above or assume they know what they are doing if they are moving things.
