### ISSUE TITLE
Provide diagram and more detailed explanation regarding local crates.io when setting up environment

### ISSUE THREAD

**Issue by natboehm** [rust-lang/crates.io#754]
The section [Using your local crates.io](https://github.com/rust-lang/crates.io/blob/master/docs/CONTRIBUTING.md#using-your-local-cratesio-with-cargo) with cargo would be improved by providing a diagram to show the interactions of the different services we have thus far set up, creating a visual explanation of how things are supposed to be working.

It would also be helpful to provide a brief explanation under the sections [Publishing a crate to your local crates.io](https://github.com/rust-lang/crates.io/blob/master/docs/CONTRIBUTING.md#publishing-a-crate-to-your-local-cratesio) and [Downloading a crate from your local crates.io](https://github.com/rust-lang/crates.io/blob/master/docs/CONTRIBUTING.md#downloading-a-crate-from-your-local-cratesio) to clarify what these titles conceptually actually mean. Currently these seem to serve as both the title and explanation for the section. An improvement would be to provided a short paragraph initially explaining what it means for the user to publish a crate to their local crates.io, or to download a crate from their local crates.io.

**Comment by Turbo87** [comment]
as I've mentioned in the other issue, PRs are welcome :)

until then I'll go ahead and close this issue for now since there hasn't been much activity on this for a while.
