### ISSUE TITLE
Support connecting to postgres over a socket

### ISSUE THREAD

**Issue by jtgeibel** [rust-lang/crates.io#763]
With the following line in my `.env` file I am able to run `diesel migration run` and access the database over the default postgres socket.  Note the 3rd slash, as no hostname is provided.

    export DATABASE_URL=postgres:///cargo_registry

However, this doesn't work with `cargo run --bin server` as I get an error from r2d2.

    ERROR:r2d2: Error opening a connection: Error communicating with the server: failed to lookup address information: Name or service not known

Interestingly, this seems to only be an issue for the r2d2-postgres adapter, as if I swap lines 82 and 83 of [src/db.rs](https://github.com/rust-lang/crates.io/blob/master/src/app.rs#L82-L83) then the program seems to succesfully create a db::diesel_pool before then crashing on line 83.

By supporting a simplified default DATABASE_URL, then at least on Ubuntu the setup instructions could be simplified to:

````sh
sudo -u postgres createuser $USER
sudo -u postgres createdb cargo_registry
sudo -u postgres createdb cargo_registry_test
sudo -u postgres psql -c "ALTER DATABASE cargo_registry OWNER TO $USER;"
sudo -u postgres psql -c "ALTER DATABASE cargo_registry_test OWNER TO $USER;"
````

I think we can skip the `--superuser` option as well.  I can test similar setups on Fedora and Windows if necessary.

**Comment by sgrif** [comment]
This will be implicitly fixed once the port to Diesel is finished.
