### ISSUE TITLE
Switch back to npm 5 and remove yarn?

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#766]
For discussion. npm5 has a project lockfile now, which is the main reason I was interested in yarn.

Any other thoughts/opinions/pros/cons?

Anyone want to try switching us back?

**Comment by locks** [comment]
cc @rwjblue @Turbo87, as this is an ember-cli project

**Comment by Turbo87** [comment]
I'd say keep yarn for now until npm5 has reached mainstream and people have gathered a bit of experience with it. In my initial tests yarn was still significantly faster than npm5 for some reason 🤔

**Comment by steveklabnik** [comment]
As the person who did the switch, I would also still stick with yarn for a while, but if people felt strongly, I wouldn't object.

**Comment by ashleygwilliams** [comment]
hi. i would like to both highly recommend that we switch to npm5 but i also volunteer to do it.

turns out, it actually Just Works. but i can help update the docs and remove the yarn lock file.
