### ISSUE TITLE
Page still has Twitter logo

### ISSUE THREAD

**Issue by MrEnder0** [rust-lang/crates.io#7697]
### Current Behavior

At the bottom of the crates.io page there is a X handle (@cratesiostatus) the icon next to the handle is a old Twitter icon.

### Expected Behavior

The icon Should be updated to the new X logo. They have an official download available at https://about.twitter.com/en/who-we-are/brand-toolkit

### Steps To Reproduce

Steps to reproduce:
1. Scroll down to the bottom to any pages on crates.io
2. Look at the social media handles

### Environment

- Browser: Firefox & Chrome
- OS: Windows 11

**Comment by Turbo87** [comment]
once our mastodon account is set up we will replace it. until then I don't think it's worth changing it.

**Comment by tadhaQ-nerfed-5misbu** [comment]
Why is my solana pay showing a Twitter page ? I haven't been able to use one penny from this phone or my iPhone 12 I attached solflare so it's shoptify with solana pay. Not functioning any advice I'd appreciate?
