### ISSUE TITLE
Ellipsoid 0.3.1 is not compatible with stable build

### ISSUE THREAD

**Issue by SeymourKnecht** [rust-lang/crates.io#7795]
### Current Behavior

My IDE , IntelliJ, is complaining that:

The source code of the ellipsoid 0.3.1 library is using #![feature(async_fn_in_trait)] which is an unstable feature of Rust, hence it cannot be compiled using stable Rust.

### Expected Behavior

I expected the example source to build

### Environment

- Browser:
- OS:

**Comment by Turbo87** [comment]
please report this on the `ellipsoid` bug tracker. this bug tracker is only for crates.io itself, not for any of the crates hosted there.

**Comment by SeymourKnecht** [comment]
My apologies
