### ISSUE TITLE
Separate ~/.cargo/credentials

### ISSUE THREAD

**Issue by tarcieri** [rust-lang/crates.io#78]
RubyGems uses a separate file for credential storage called `~/.cargo/credentials` which is separate from the rest of the configuration.

I think this is a nice separation of concerns, and something that Cargo might consider adopting

**Comment by Eh2406** [comment]
Does this belong in hear or should it be in [cargo](https://github.com/rust-lang/cargo)?

**Comment by tarcieri** [comment]
It should probably be moved to cargo. Hey @alexcrichton I may have pinged you on this before filing... do you have an opinion?

**Comment by carols10cents** [comment]
Yeah I think this should be in cargo's issues... mind moving it over there @tarcieri ?

**Comment by tarcieri** [comment]
Done: https://github.com/rust-lang/cargo/issues/3748
