### ISSUE TITLE
https://crates.io/crates?page=201&sort=new. Something Went Wrong!

### ISSUE THREAD

**Issue by xuxiaocheng0201** [rust-lang/crates.io#7832]
### Current Behavior

当我尝试访问[Page参数大于200的列表页](https://crates.io/crates?page=201&sort=new)的时候，它提示我`Something Went Wrong!`
>Cannot read properties of null (reading 'length')
>  TypeError: Cannot read properties of null (reading 'length')
>    at mt (https://crates.io/assets/chunk.014ab66a415937e2ba28.js:2:645072)
>    at gt.populateManagedArray (https://crates.io/assets/chunk.014ab66a415937e2ba28.js:2:647521)
>    at https://crates.io/assets/chunk.014ab66a415937e2ba28.js:2:706675

### Expected Behavior

如果是为了减少数据库压力，应该提示用户page太大。
我想这应该是个意料之外的bug。

### Steps To Reproduce

Go to https://crates.io/crates?page=201&sort=new

### Environment

- Browser: Edg/120.0.0.0
- OS: Windows 11 23H2

**Comment by syphar** [comment]
just from the errors (I can't read the rest) I would assume it's the same thing as #7815 , and the pagination in the interface still shows the controls for pages the backend can't render any more.
