### ISSUE TITLE
30 seconds timeout is too short for cargo publish

### ISSUE THREAD

**Issue by uuhan** [rust-lang/crates.io#7836]
### Current Behavior

I have a crate which is of size 74.7MiB compressed.

30 seconds timeout is too short for cargo publish it.

```log
error: failed to publish to registry at https://crates.io

Caused by:
  Request timed out after 30 seconds. If you're trying to upload a crate it may be too large. If the crate is under 10MB in size, you can email help@crates.io for assistance.
  Total size was 78337084.
```

Is there a way to increse the timeout threshold?

### Expected Behavior

publish success

### Anything else?

Is there a way to increse the timeout threshold?

**Comment by Turbo87** [comment]
> I have a crate which is of size 74.7MiB compressed.

crates.io currently has a limit of 10 MB for each uploaded release. in exceptional cases we can increase the limit on a per-crate basis, but unfortunately our CDNs currently have hard limit of 50 MB per crate file as well.

> 30 seconds timeout is too short for cargo publish it.

This 30 second limit is also imposed on us by a service provider, in this case: Heroku. The Heroku router will cancel requests after 30 seconds so there is currently not much we can do here.

Your best option would be to try to decrease the crate size in some way.

**Comment by uuhan** [comment]
> > I have a crate which is of size 74.7MiB compressed.
> 
> crates.io currently has a limit of 10 MB for each uploaded release. in exceptional cases we can increase the limit on a per-crate basis, but unfortunately our CDNs currently have hard limit of 50 MB per crate file as well.
> 
> > 30 seconds timeout is too short for cargo publish it.
> 
> This 30 second limit is also imposed on us by a service provider, in this case: Heroku. The Heroku router will cancel requests after 30 seconds so there is currently not much we can do here.
> 
> Your best option would be to try to decrease the crate size in some way.

Got it.
