### ISSUE TITLE
Need to update text about what `cargo login` does

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#791]
API tokens are in the process of being moved to `~/.cargo/credentials` instead of `~/.cargo/config`: https://github.com/rust-lang/cargo/pull/3978

This is currently in the version of cargo shipping with nightly rust.

Before this change makes it to stable, we should update [this text](https://github.com/rust-lang/crates.io/blob/0f3adf36108dfac662e3463b4ff97567261f5de9/app/templates/me/index.hbs#L31) that says you need a `~/.cargo/config` so that people aren't confused.

Since people may still be on an old cargo though, we should either mention both files (like the [cargo docs do now](http://doc.crates.io/crates-io.html#before-your-first-publish) or just not talk about a file at all....

**Comment by nodakai** [comment]
+1 to not mentioning the file path at all. Knowing the path won't help users very much as they aren't supposed to tweak the credentials manually.

Also,
```
cargo login AbcDefgHijkLmnOpqrStuVwXyz
```
we should not encourage users to type their credentials onto their shell prompt.  Other users on the same server may read it with `ps -a` (don't think it's a momentary event; slow NFS might keep the process for tens of seconds.) Users should type their credentials **onto the `cargo login` prompt** as opposed to their shell prompt.

**Comment by carols10cents** [comment]
care to send in a PR @nodakai ?

**Comment by carols10cents** [comment]
Closed by #980!! 🎉
