### ISSUE TITLE
Pagination is strewn around

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/crates.io#8]
The actual processing code for pagination is refactored into a mixin, but the rendering code is strewn all over mostly because of the need to generate links differently in different contexts:

Examples:
- https://github.com/alexcrichton/cargo-registry/blob/master/app/templates/crates.hbs
- https://github.com/alexcrichton/cargo-registry/blob/master/app/templates/keywords.hbs
- https://github.com/alexcrichton/cargo-registry/blob/master/app/templates/search.hbs
- https://github.com/alexcrichton/cargo-registry/blob/master/app/templates/keyword/index.hbs

**Comment by sgrif** [comment]
We're cleaning out some of the older issues that haven't seen activity lately, so I'm going to close this.

We'd be happy to accept a PR that refactors this code. I'm going to try to open an issue in the next few days with more concrete steps as well.
