### ISSUE TITLE
"See also" metadata field in Cargo.toml, displayed on crate page

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/crates.io#804]
An enhancement request: I suggest to add to Cargo pages a "See also: ..." field, where you can list similar/related crates.

**Comment by carols10cents** [comment]
"you" meaning the crate author or "you" meaning anyone?

**Comment by leonardo-m** [comment]
I meant the crate author. Those pages aren't wikis yet, so I think the crate author is the safest first step.

**Comment by carols10cents** [comment]
I see; we'll consider it. In the meantime, any crate author can indicate this in their description if they so choose.

**Comment by Turbo87** [comment]
since we render the README files on the crates pages now these are relatively easy to add for the maintainers, so I'll go ahead and close this issue as resolved
