### ISSUE TITLE
crates.io's TOML snippet with metadata produces warnings when used in `Cargo.toml`

### ISSUE THREAD

**Issue by epage** [rust-lang/crates.io#8073]
### Current Behavior

On https://crates.io/crates/curl-sys, the following is listed
```toml
curl-sys = "0.4.71+curl-8.6.0"
```

### Expected Behavior

On https://crates.io/crates/curl-sys, the following is listed
```toml
curl-sys = "0.4.71"
```

### Steps To Reproduce

1. Go to https://crates.io/crates/curl-sys
2. See TOML snippet
3. Add this to your `Cargo.tom`
4. Run `cargo check`

```
$ cargo check
warning: /home/epage/src/personal/cargo/Cargo.toml: version requirement `0.4.71+curl-8.6.0` for dependency `curl-sys` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
```

### Environment

- Browser:
- OS:

**Comment by Turbo87** [comment]
<img width="310" alt="Bildschirmfoto 2024-02-13 um 17 19 00" src="https://github.com/rust-lang/crates.io/assets/141300/98e01163-388b-4c5e-95d8-8dd5425bcbcc">

I just noticed that we're still including the build metadata in the `cargo add` command. it looks like `cargo add` can handle and ignore the build metadata, but I'm wondering whether we should remove it there too. It would be a bit more consistent with the other snippet and remove some unnecessary noise from the sidebar.
