### ISSUE TITLE
'Browse All Crates' results in `Something Went Wrong!'

### ISSUE THREAD

**Issue by segfault-magnet** [rust-lang/crates.io#8136]
### Current Behavior

When I click on Menu->`Browse All Crates` I receive the following error:

(On the Brave browser:)
```
Cannot read properties of null (reading 'length')

  TypeError: Cannot read properties of null (reading 'length')
    at mt (https://crates.io/assets/chunk.38215ea770ad6fcae267.js:2:648575)
    at gt.populateManagedArray (https://crates.io/assets/chunk.38215ea770ad6fcae267.js:2:651024)
    at https://crates.io/assets/chunk.38215ea770ad6fcae267.js:2:677659
```

On Firefox:
```
t is null
  mt@https://crates.io/assets/chunk.38215ea770ad6fcae267.js:2:648573
populateManagedArray@https://crates.io/assets/chunk.38215ea770ad6fcae267.js:2:651024
50704/request/<@https://crates.io/assets/chunk.38215ea770ad6fcae267.js:2:677659
```

### Expected Behavior

Don't exactly know, never visited `Browse All Crate` before. But probably I expected to do some browsing :D

### Steps To Reproduce

1. visit https://crates.io/
2. click on `Browse All Crates`
3. see error

### Environment

- Browser: Brave & Firefox
- OS: NixOS

### Anything else?

Brave:
![image](https://github.com/rust-lang/crates.io/assets/37515857/c4c0b2a6-816a-419d-b224-bfa1088d8048)

Firefox:
![image](https://github.com/rust-lang/crates.io/assets/37515857/e7168235-7436-4e28-8994-92eca5650e01)

**Comment by Turbo87** [comment]
we had a bit of a hickup on the server this morning that cause several requests to fail. admittedly the frontend did not seem to handle this particularly well... 😅 

the incident has been resolved at this point though and with https://blog.rust-lang.org/2024/02/06/crates-io-status-codes.html the error reporting on the frontend should also improve, so I'll close this issue as resolved :)
