### ISSUE TITLE
Switching to ember-fetch causes github oauth to fail with error "invalid state parameter"

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#820]
This happened on production when I deployed e921c6eb; the previous deploy of 9172aa4f worked. A bisect pointed to this commit: https://github.com/rust-lang/crates.io/commit/dbc1c9a08b3d9f79fab8e4bef27692aeb38f5a42

I'm reverting that commit, which fixes the problem....

**Comment by sivakumar-kailasam** [comment]
@carols10cents we're good on this now that we've moved to ember-ajax to be FastBoot compatible via #838
