### ISSUE TITLE
Unknown license error message should only list specific license that is unknown when multiple are specified

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/crates.io#84]
Example error message:

```
api errors: unknown license `Apache 2.0 / MIT`, see http://opensource.org/licenses for options, and http://spdx.org/licenses/ for their identifiers
```

“Apache License 2.0” and “MIT license” are listed on http://opensource.org/licenses, so what’s wrong?

After some trial and error, it turns out that crates.io is picky and accepts `Apache-2.0` but not `Apache 2.0` (hyphen v.s. space). opensource.org doesn’t help discover this. Instead of opensource.org, the error message should link to some crates.io documentation that lists the exact strings that are accepted, and from there links to opensource.org. Preferably, both the server-side code and this documentation would be derived from a single source of truth, so avoid them getting out of sync.

**Comment by carols10cents** [comment]
This looks like it was fixed in 9f51a1febb52af151599e31812acfa728262780c but this issue wasn't ever closed 😅
