### ISSUE TITLE
Image rendered wrongly

### ISSUE THREAD

**Issue by daniel-pfeiffer** [rust-lang/crates.io#8409]
### Current Behavior

rust_dot 0.5.0 has an image above the example.

### Expected Behavior

On docs.rs it renders correctly: overlaid on the right of the example. You seem to have dropped the `<img style>` attribute, even though it contains nothing remotely dangerous.
They pull it from `lib.rs`, you from `README.md`, which both contain the identical tag.

### Steps To Reproduce

Go to https://crates.io/crates/rust_dot
and https://docs.rs/rust_dot/latest/rust_dot/

### Environment

- Browser: any
- OS: any

**Comment by Turbo87** [comment]
This is working as intended. We are significantly filtering the allowed styling options to avoid potential security issues, which includes stuff like z-levels and absolute positioning.

**Comment by daniel-pfeiffer** [comment]
How are these security issued? Or put differently: how could docs.rs survive without this filtering it they were?

At the worst I could break the layout of my own crates's display. What would I gain, even if I did this malevolently???

**Comment by Turbo87** [comment]
> how could docs.rs survive without this filtering it they were?

docs.rs has no authentication and is read-only

> At the worst I could break the layout of my own crates's display. What would I gain, even if I did this malevolently???

you could absolute position a malicious link on top of the native crates.io login link for example
