### ISSUE TITLE
Grepping all the Rust code

### ISSUE THREAD

**Issue by behnam** [rust-lang/crates.io#841]
GitHub already allows searching in the code, but it's not always easy to grep in *all the Rust code*: If the search term is generic and matches projects in other languages better, "Rust" won't be listed in the sidebar and you'll have to edit the URL manually to get what you need.

Example: https://github.com/search?utf8=%E2%9C%93&q=hello&type=Code

I think somewhere there should be an easy-to-use grep UI for the Rust projects. Does crates.io have anything planned? If not, maybe we can have a UI to make it easier to search in GitHub for now? What do you think?

**Comment by locks** [comment]
Fo reference: http://codeallday.com/blog/how-ember-observer-searches-addon-source-code/

**Comment by carols10cents** [comment]
Crates.io isn't planning on providing a way to view source code, so there won't be a way to search through all crates' code. Perhaps docs.rs would be interested in this? https://docs.rs/ https://github.com/onur/docs.rs

Thank you for the suggestion though!

**Comment by Piping** [comment]
any tools that is similar to cscope that can search rust code well?
