### ISSUE TITLE
Comparison view

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#843]
- After you search or look in a category/keyword
- Be able to choose a few crates
- See a more direct, more focused view of crate comparison

I will add some more details here later, mostly just putting this in so I don't forget and to see if anyone else thinks this is useful!

Inspired by a comment at the work week made by @dtolnay -- is this along the lines of what you were talking about?

**Comment by dtolnay** [comment]
Thanks for filing this. In an ideal world I would like to be able to search crates.io for the word "yaml" and have [`yaml`](https://crates.io/crates/yaml) and [`yaml-rust`](https://crates.io/crates/yaml-rust) and [`serde_yaml`](https://crates.io/crates/serde_yaml) show up. Then I would want to see a curated, concise overview of why I might want to choose a particular one of these over the others.

In particular:

- `yaml-rust` and `serde_yaml` are pure Rust while `yaml` is based on a C library.
- All three can parse into a weakly typed enum that is able to represent any valid YAML document.
- `serde_yaml` can additionally parse into strongly typed data structures.

I understand this is difficult from a moderation perspective but if we can pull it off, I think this would be really valuable to the way that I evaluate crates, and I would get in the habit of contributing any time I evaluate a set of crates for myself.

**Comment by carols10cents** [comment]
> curated

Yeah that's the part where I'm wary about this :-/ In addition to the moderation perspective, people need to put in this work for every possible search....

**Comment by carols10cents** [comment]
I don't think we're going to do this :(
