### ISSUE TITLE
Policy page is missing indentation, changing its meaning

### ISSUE THREAD

**Issue by kpreid** [rust-lang/crates.io#8509]
### Current Behavior

The bullet list of disallowed content in <https://crates.io/policies> includes:

> * ...
> * is using our servers for other automated excessive bulk activity or coordinated inauthentic activity, such as
> * spamming
> * cryptocurrency mining
> * is not functionally compatible with the cargo build tool (for example, a "package" cannot simply be a PNG or JPEG image, a movie file, or a text document uploaded directly to the registry)
> * ...

### Expected Behavior

As per the text of [RFC 3463](https://rust-lang.github.io/rfcs/3463-crates-io-policy-update.html), the list should have an indent, making it:

> * ...
> * is using our servers for other automated excessive bulk activity or coordinated inauthentic activity, such as
>     * spamming
>     * cryptocurrency mining
> * is not functionally compatible with the cargo build tool (for example, a “package” cannot simply be a PNG or JPEG image, a movie file, or a text document uploaded directly to the registry)
> * ...

### Environment

- Browser: Chrome 124.0.6367.60 (Official Build) (x86_64)

### Anything else?

I have examined the served HTML and determined that this is not a styling issue.

**Comment by Turbo87** [comment]
good catch, thanks! shouldn't have blindly copy-pasted from the RFC... 😅
