### ISSUE TITLE
Failed to log in: Error obtaining token after logging out

### ISSUE THREAD

**Issue by Mirch** [rust-lang/crates.io#8536]
### Current Behavior

I logged out from crates.io. When logging back in with GitHub, I now see a `Failed to log in: Error obtaining token` pop-up.

### Expected Behavior

I should get logged in normally.

### Steps To Reproduce

1. Logout from you account.
2. Revoke the crates.io access from your GitHub account. (optional, I assume, but I gave it a try)
3. Attempt to log back in on crates.io.

### Environment

- Browser: Chrome / Safari
- OS: macOS 12.5.1

**Comment by maxswjeon** [comment]
Me too, for accessing
```
GET https://crates.io/api/private/session/authorize?code=(redacted)
```
responses 500 (Internal Server Error) with body
```
{"errors":[{"detail":"Error obtaining token"}]}
```
with headers
```
X-Amz-Cf-Pop: ICN51-C1
X-Cache: Error from cloudfront
```

Related code is
https://github.com/rust-lang/crates.io/blob/d07e7f77a36455de99933f64f44084d6fb02cc26/src/controllers/user/session.rs#L98-L106

**Comment by Turbo87** [comment]
I can reproduce the issue. I'll roll back today's deployments in the hope that it resolves the immediate issue and will investigate afterwards.

**Comment by glennib** [comment]
I was just able to log in.

**Comment by Mirch** [comment]
Works fine now. Thanks!

**Comment by maxswjeon** [comment]
Works fine too.

**Comment by Turbo87** [comment]
I've found the issue and https://github.com/rust-lang/crates.io/pull/8539 should fix it :)

**Comment by Turbo87** [comment]
the fix is deployed to production now and at least on my side it appears to work as intended. sorry for the interruption!
