### ISSUE TITLE
Total downloads count isn't comma separated on user page

### ISSUE THREAD

**Issue by sfackler** [rust-lang/crates.io#855]
![capture](https://user-images.githubusercontent.com/1455697/27942506-47f8b456-628c-11e7-98c4-5071dc596e27.PNG)

**Comment by carols10cents** [comment]
Thank you for the report! I think [this spot](https://github.com/rust-lang/crates.io/blob/master/app/templates/dashboard.hbs#L9) needs to call the [`format-num` helper](https://github.com/rust-lang/crates.io/blob/master/app/helpers/format-num.js#L3), like, for example, [the crate-row template does](https://github.com/rust-lang/crates.io/blob/master/app/helpers/format-num.js#L3).
