### ISSUE TITLE
API/reverse_dependencies: "crate_id" should be the dependency id, not the crate id

### ISSUE THREAD

**Issue by MoSal** [rust-lang/crates.io#856]
Probably caused by 653945f0f4917516dd0afaf695ff855fa5cb4896

```
curl 'https://crates.io/api/v1/crates/hyper-native-tls/reverse_dependencies'| json_reformat
{
    "dependencies": [
        {
            "crate_id": "hyper-native-tls",
            "default_features": true,
            "downloads": 253971,
            "features": [

            ],
            "id": 151756,
            "kind": "normal",
            "optional": true,
            "req": "^0.2",
            "target": null,
            "version_id": 42224
        },
        {
            "crate_id": "hyper-native-tls",
            "default_features": true,
            "downloads": 58197,
            "features": [

            ],
            "id": 207350,
            "kind": "normal",
            "optional": false,
            "req": "^0.2",
            "target": null,
            "version_id": 53691
        },
        {
            "crate_id": "hyper-native-tls",
            "default_features": true,
            "downloads": 7912,
            "features": [

            ],
            "id": 188737,
            "kind": "normal",
            "optional": false,
            "req": "^0.2.1",
            "target": null,
            "version_id": 50087
        },
[...]
```
[Example of 3d party code that broke](https://github.com/rust-alt/cargo-esr/blob/e5fe9329e6bf5b7d7f1dc876916913f8bd2f8d9f/src/esr_crate.rs#L403-L410).

**Comment by carols10cents** [comment]
@Turbo87 could you take a look at this when you have a chance please? Thank you! ❤️

**Comment by Turbo87** [comment]
That is precisely the issue that was fixed. version_id is referencing the correct thing that you are looking for and should be included in the same response

**Comment by MoSal** [comment]
I'm not sure I understand.

In the snippet above, I expected the first `crate_id` to be `iron`, the second one to be `reqwest`, and the third one to be `rusoto`. That was the previous behavior.

Are you saying that the previous behavior was wrong, and the change to the current one was intentional?

**Comment by Turbo87** [comment]
Yes, that is what I'm saying. It returns "dependency" records and they go from version to crate independent of if it's reverse or not.

**Comment by carols10cents** [comment]
Could we add a `dependency_id` field for the IDs of iron, reqwest, and rusoto? Or would that confuse ember?

**Comment by Turbo87** [comment]
> Could we add a dependency_id field for the IDs of iron, reqwest, and rusoto? Or would that confuse ember?

I'd rather call it `version_name` or something like that. It would be redundant information though since the same thing is also stored in the `version` record that is attached to the request. tl;dr I don't see the need for it 🤔

**Comment by carols10cents** [comment]
Ah, yep, I see. @MoSal cargo-esr can get the name of the crate by matching the `version_id` in the `dependencies` records with data in the `versions` records; for example, in the response you showed, the name for "iron" can be found by matching the dependency record's version_id 42224 with the versions record with id 42224:

```
{
  "dependencies": [
    {
      "crate_id": "hyper-native-tls",
      "default_features": true,
      "downloads": 254482,
      "features": [],
      "id": 151756,
      "kind": "normal",
      "optional": true,
      "req": "^0.2",
      "target": null,
      "version_id": 42224
    },
    ...
  ],
  "versions": [
    ...
    {
      "crate": "iron",
      "created_at": "2017-01-13T01:56:18Z",
      "dl_path": "/api/v1/crates/iron/0.5.1/download",
      "downloads": 47238,
      "features": {
        "default": [],
        "native-tls-example": [
          "hyper-native-tls"
        ]
      },
      "id": 42224,
      "license": "MIT",
      "links": {
        "authors": "/api/v1/crates/iron/0.5.1/authors",
        "dependencies": "/api/v1/crates/iron/0.5.1/dependencies",
        "version_downloads": "/api/v1/crates/iron/0.5.1/downloads"
      },
      "num": "0.5.1",
      "updated_at": "2017-06-25T14:46:48Z",
      "yanked": false
    },
    ...
  ]
}
```

Essentially, cargo-esr was relying on a bug of ours. Sorry about that!
