### ISSUE TITLE
 Why I am removed from my crates? 

### ISSUE THREAD

**Issue by snnsnn** [rust-lang/crates.io#8592]
### Current Behavior

 I was working on a project and did not have time to focus on rust lately but now I see some of my crates changed ownership without my consent. I see there are some policy change but nobody asked my permission or send a request for a change of ownership. 

Edit: I see some of them have boilerplate content like https://crates.io/crates/sky

Edit 2: I see there are some policy change against squatting (https://crates.io/policies) . Squatting was permitted when I take the names, I would not take otherwise and I almost always gave away the names when someone asked for it. 

Policy may change, that is acceptable, but I did not receive any message or notification or warning about the policy change otherwise I would put some effort to keep them or at least donate them to someone who is going to use it. It is really unfair to treat someone as if he is breaking the rules for something you permitted previously and what saddens me most is the new owners are also squatting using boilerplate code just to go around the rules.

Also you are not just about the way you impose the new rules as I see so many squatted packages are left alone.

Please restore my packages or apply the same rule to any squatted package.

**Comment by Turbo87** [comment]
Hi @snnsnn. your account was reported multiple times to us for spamming / name squatting and since this looked like spam we took action.

> as I see so many squatted packages are left alone

feel free to report them and we will take a look.

**Comment by snnsnn** [comment]
Hi @Turbo87

> Hi @snnsnn. your account was reported multiple times to us for spamming / name squatting and since this looked like spam we took action.

This looks like a made-up reason for your arbitrary actions as I was never spamming, and there was no mechanism for reporting a person or a package as a squatter, and as far as I know, there is still none. I don't know how you received those reports but  the course of your actions is unclear and open to manipulations and bias. If you took the time to inspect my profile history, you would see that I donated crates when I was asked. 

Squatting was a contentious issue from day one, and you may say you don't like it, but it was allowed at the time, and there are numerous issues and RFCs to back up my claim. I have never violated the terms of use, and you cannot punish me for something you allowed before. You are treating me as a bad actor, but I have been following the rules all along. On the contrary, you never warned me, never contacted me, or even sent a generic message on the issue.

Look, there is clearly an injustice here, and you are trying to cover it by using broad terms like spamming to justify your arbitrary actions. There is not even a clear definition of spamming in the policy, not even in the new policy.

What saddens me the most is the dismissive attitude you take. We are all bound by the law, and you cannot violate my rights, however small they may be. I would sue you and your organization if I lived in a place that has jurisdiction over the issue.

> feel free to report them and we will take a look.

I don't have to report them, just look through the list: https://crates.io/crates

I still insist  that you apply the rules to every single squatted crate or restore my crates.

**Comment by Turbo87** [comment]
> there was no mechanism for reporting a person or a package as a squatter, and as far as I know, there is still none

help@crates.io

> You are treating me as a bad actor

we are not. we just removed a bunch of spam crates that were reserving names without any content.
