### ISSUE TITLE
https://index.crates.io/ Returns an error, modify https://crates.io/data-access

### ISSUE THREAD

**Issue by FBDev64** [rust-lang/crates.io#8617]
### Current Behavior

https://crates.io/data-access#crate-index Says to go to index.crates.io, but returns :
```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>index.html</Key>
<RequestId>9N18CM92BR5XTWKS</RequestId>
<HostId>q4ty6zmoEGQcE1NRdlL1qFT0U1yIjTb7xPLi1qBBBPYr+KxOgFlUFmifgWnTMcZWwgXVy4x9R1jdxnnCpzh6mA==</HostId>
</Error>
```

### Expected Behavior

Expected a valid site

### Steps To Reproduce

Go to : https://index.crates.io/

### Environment

- Browser: Chrome 124.0.6367.119 (Build officiel) (64 bits) (cohort: Control) 
- OS: Windows 10

### Anything else?

![Capture d’écran (14)](https://github.com/rust-lang/crates.io/assets/122815478/456c90db-a375-4545-87ca-b4778b1beef3)

**Comment by Eh2406** [comment]
The API is set up and works correctly. The only thing missing is a html page. Given that we link to the root, and the number of people been confused by this, perhaps we should add a index.html to the S3 bucket explaining how API is to be used.

**Comment by hi-rustin** [comment]
> [crates.io/data-access#crate-index](https://crates.io/data-access#crate-index) Says to go to index.crates.io, but returns :

From the crate-index page, it gives an example:
<img width="902" alt="image" src="https://github.com/rust-lang/crates.io/assets/29879298/74184fa8-d89f-46ac-af2d-b9007dc39869">

You need to specify the crate name in the index URL.

**Comment by hi-rustin** [comment]
> perhaps we should add a index.html to the S3 bucket explaining how API is to be used.

Sounds good to me! It would help users how to access the index by crate name.

**Comment by Turbo87** [comment]
https://github.com/rust-lang/crates.io-index/pull/25 added a README file to the index repository and I've uploaded a rendered HTML version of it to the sparse index. In other words: https://index.crates.io/ shows a short description now.

**Comment by Balmasexy** [comment]
> ### Current Behavior
> 
> https://crates.io/data-access#crate-index Says to go to index.crates.io, but returns :
> ```xml
> <Error>
> <Code>NoSuchKey</Code>
> <Message>The specified key does not exist.</Message>
> <Key>index.html</Key>
> <RequestId>9N18CM92BR5XTWKS</RequestId>
> <HostId>q4ty6zmoEGQcE1NRdlL1qFT0U1yIjTb7xPLi1qBBBPYr+KxOgFlUFmifgWnTMcZWwgXVy4x9R1jdxnnCpzh6mA==</HostId>
> </Error>
> ```
> 
> ### Expected Behavior
> 
> Expected a valid site
> 
> ### Steps To Reproduce
> 
> Go to : https://index.crates.io/
> 
> ### Environment
> 
> - Browser: Chrome 124.0.6367.119 (Build officiel) (64 bits) (cohort: Control) 
> - OS: Windows 10
> 
> 
> ### Anything else?
> 
> ![Capture d’écran (14)](https://github.com/rust-lang/crates.io/assets/122815478/456c90db-a375-4545-87ca-b4778b1beef3)
>

**Comment by LawnGnome** [comment]
Interesting! This works for me:

![Image](https://github.com/user-attachments/assets/9949dcba-9a60-46eb-8ba6-87eca5e05417)

@Balmasexy Do you also get an error if you `curl -v https://index.crates.io/`? If so, I'd love to see that output; especially the `x-amz-*` response headers.
