### ISSUE TITLE
Dashboard page returns 502 if user doesn't have any published crates

### ISSUE THREAD

**Issue by DorianListens** [rust-lang/crates.io#866]
After signing in via GitHub, visiting the "Dashboard" page results in an unfriendly error page if you haven't published any crates.

Since this page is accessible, and the first link presented after clicking on your avatar, it should handle the first time user use case gracefully.

![screen shot 2017-07-08 at 1 32 20 pm](https://user-images.githubusercontent.com/5692947/27988199-ea39faa8-63e1-11e7-975c-94c63b6b1e65.png)

**Comment by carols10cents** [comment]
Yup, we're on it! This is a problem with Diesel, actually, so we're going to have @sgrif fix the root problem upstream. See commentary here for more info: https://github.com/rust-lang/crates.io/pull/864

I'm glad to have an issue to track this, though, thank you! ❤️

**Comment by carols10cents** [comment]
This is fixed and deployed now! Sorry for the inconvenience!
