### ISSUE TITLE
Write some integration tests

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#868]
Right now we've got the frontend tests in `/tests`, and the backend tests in `/src/tests`. The frontend tests use mirage to make a fake backend, and the backend tests assert some things about the JSON but not everything, and the backend tests create requests to the backend that might differ from what the ember frontend is doing.

Often I catch stuff by running the full app locally or on staging, and sometimes problems make it to production because I'm not perfect either.

It'd be great to have some tests, any tests, that exercise the entire app together to catch potential problems earlier.

**Comment by vignesh-sankaran** [comment]
I'm happy to take this up as my next task @carols10cents :).

**Comment by kzys** [comment]
+1 Can we use BrowserStack's Selenium grid? https://www.browserstack.com/automate/features

**Comment by carols10cents** [comment]
@kzys I've added to travis the environment variables `BROWSERSTACK_KEY` and `BROWSERSTACK_USER` with values so that tests written like [this sample code](https://www.browserstack.com/automate/node) should be able to use browserstack :)

**Comment by kzys** [comment]
Thanks! Can you add them on Heroku as well? Not so sure how we can hide them from the main app though...

https://devcenter.heroku.com/articles/heroku-ci

**Comment by kzys** [comment]
Once we have a Heroku Pipeline, you can set "Test run config vars" from Settings. This would be a good place to keep credentials that are only required for tests.

**Comment by kzys** [comment]
And Heroku CI actually has Chrome without Browserstack. Maybe we can start from there.

https://devcenter.heroku.com/articles/heroku-ci#browser-tests-and-uat-on-heroku-ci

**Comment by kzys** [comment]
I have tried Heroku CI on my personal account, with app.json. It takes 39m 31s and finished unsuccessfully with;

```
...
-----> Caching build
       Clearing previous node cache
       Saving 2 cacheDirectories (default):
       - node_modules
       - bower_components (nothing to cache)
-----> Build succeeded!
-----> Fetching buildpack heroku/ember-cli-deploy
-----> ember-cli detected
-----> Skipping installing bower dependencies, no bower.json detected.
-----> Building ember assets
bash: ember: command not found
Error running: ember build --environment production 2>&1
-----> Failed trying to compile heroku/ember-cli-deploy
```

Maybe I can fix the build, but the it is too slow. 

Let me check Travis CI.

**Comment by kzys** [comment]
Now we are able to run the full app on Travis CI (once #1825 is being merged) and [there is a WebDriver Rust package](https://github.com/jonhoo/fantoccini) and async/await is coming!

**Comment by smokytheangel0** [comment]
what is the status of this issue currently?

**Comment by Turbo87** [comment]
the current status is that the frontend at this point is reasonably well tested, and CI even has test coverage reporting for it. the API tests still need a bit of love and we haven't been able to integrate test coverage there yet either.

I'll still close this issue for now as there is not much actionable stuff left here to do other than randomly looking for uncovered API endpoints and writing tests for them.
