### ISSUE TITLE
`proc-macro2` and `tempfile` error `Failed to load version data`

### ISSUE THREAD

**Issue by segfault-magnet** [rust-lang/crates.io#8685]
### Current Behavior

When I visit: https://crates.io/crates/tempfile or https://crates.io/crates/proc-macro2 I'm greeted with:
![proc-macro](https://github.com/rust-lang/crates.io/assets/37515857/c5560a91-e271-4d82-86f2-6ce2a7156118)
(the same for tempfile)

The browser console shows:
```
/api/v1/crates/proc-macro2:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
```
Also the Githhub action [publish crates](https://github.com/marketplace/actions/publish-crates) fails with:
```text
Error: Package 'fuels-accounts' depends from external 'tempfile' which does not published on crates.io
```

Which I'm guessing is related.

### Expected Behavior

To be shown something :)

### Steps To Reproduce

1. visit https://crates.io/crates/proc-macro2
2. see the issue

### Environment

- Browser: Brave 1.65.133
- OS: 6.6.30-2-MANJARO

**Comment by Turbo87** [comment]
thanks for the notification. this might be related to https://status.crates.io/incidents/dj1bygxvsx67

**Comment by Turbo87** [comment]
it looks like some of our database indexes got screwed up during the update. we've reindexed the tables and it appears to be working again. let us know if you're still seeing any issues.
