### ISSUE TITLE
num-traits inconsistently reported as unavailable

### ISSUE THREAD

**Issue by chrysn** [rust-lang/crates.io#8686]
### Current Behavior

The view crates.io currently gives on num-traits is inconsistent:
* A `cargo update` just reported "Updating num-traits v0.2.16 -> v0.2.19" (although granted, that could have used data I already had on my machine from some days ago)
* A search (<https://crates.io/search?q=num-traits>) lists num-traits
* Following the search results to <https://crates.io/crates/num-traits> shows "🦀 num-traits: Crate not found" (although with an actual Ferris image, not just the emoji)
* Attempting to publish fails:
```
   Uploading coap-message v0.3.2 (/home/chrysn/git/crates/coap-message)
error: failed to publish to registry at https://crates.io

Caused by:
  the remote server responded with an error (status 400 Bad Request): no known crate named `num-traits`
```

### Expected Behavior

If some version of the crate were yanked (or even all of them), I'd still expect to see that that happened -- and uploading should still be possible, especially (what I can't tell whether it's the case) if there is some (not necessarily latest) version matching my crate's requirements that has not been yanked.

**Comment by chrysn** [comment]
Uploading has gone back to normal after a brief "crates.io is currently in read-only mode for maintenance. Please try again later." message, and the website behaves normally again as well. Thanks for fixing this, and sorry if I created noise in what was already an ongoing maintenance operation.

**Comment by Turbo87** [comment]
I assume this was caused by the same issue as https://github.com/rust-lang/crates.io/issues/8685. sorry for the inconvenience 🙈
