### ISSUE TITLE
500 Internal Server Error trying to publish `embassy-usb`.

### ISSUE THREAD

**Issue by Dirbaio** [rust-lang/crates.io#8687]
I'm getting "500 Internal Server Error" while trying to publish `embassy-usb`:

```
[dirbaio@mars embassy-usb]$ cargo publish
    Updating crates.io index
   Packaging embassy-usb v0.2.0 (/home/dirbaio/embassy/embassy/embassy-usb)
   Verifying embassy-usb v0.2.0 (/home/dirbaio/embassy/embassy/embassy-usb)
    Updating crates.io index
   Compiling byteorder v1.4.3
   ... snip ...
   Compiling usbd-hid v0.7.0
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 2.94s
    Packaged 22 files, 175.8KiB (38.2KiB compressed)
   Uploading embassy-usb v0.2.0 (/home/dirbaio/embassy/embassy/embassy-usb)
error: failed to publish to registry at https://crates.io

Caused by:
  the remote server responded with an error (status 500 Internal Server Error): Internal Server Error
```

(A few minutes ago I'd get `the remote server responded with an error (status 503 Service Unavailable): crates.io is currently in read-only mode for maintenance. Please try again later.` but seems crates.io is not readonly anymore so I thought I'd share just in case this error 500 is a different issue)

**Comment by jamesmunns** [comment]
This was resolved after a table re-index by @Turbo87: https://crates.io/crates/embassy-usb/0.2.0

**Comment by Turbo87** [comment]
for more context see https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/database.20upgrade :)
