### ISSUE TITLE
Make the git SHA of the currently deployed code visible through ember-cli-app-version

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#879]
I had this at a previous job and it was *incredibly* useful-- anyone could help debug a problem with the additional information of knowing whether the current master branch matches what's on production.

As discussed below, the frontend part is blocked waiting on [this PR](https://github.com/EmberSherpa/ember-cli-app-version/pull/42) to ember-cli-app-version.

The backend way to get this info isn't blocked though, and implementing that will entail:

- [ ] Add a new `get` route to [the api_router around here in src/lib.rs](https://github.com/rust-lang/crates.io/blob/405b2ad74715f22d756de749be4acb9626c1019b/src/lib.rs#L177) that's something like `/deployed_sha` (I wouldn't call it anything like "version" since we have crate versions all over the place and this isn't a crate version)
- [ ] Make that route call a new function, which could probably just live in `src/lib.rs` since it'll be small and doesn't really have anything to do with anything else, or mayyybe in `src/util/` somewhere, up to you.
- [ ] Make that function return JSON that looks something like `{"sha": "259d028bd03a07b2560f873add4b45f35b1d565b"}`. Assume that I've enabled [this heroku labs feature](https://devcenter.heroku.com/articles/dyno-metadata) and that the sha is available in the env var `HEROKU_SLUG_COMMIT`. [This code](https://github.com/rust-lang/crates.io/blob/405b2ad74715f22d756de749be4acb9626c1019b/src/krate.rs#L1081-L1085) is a decent example of constructing a JSON response that has a `String` value
- [ ] If `HEROKU_SLUG_COMMIT` isn't set, this function shouldn't panic, have it return `{"sha": "unknown"}` or something. [This code](https://github.com/rust-lang/crates.io/blob/4c4381169e82f15a3244d70797092c09bcc225b2/src/bin/server.rs#L95) is a decent example of getting an env var and using a default value if the env var isn't set.
- [ ] Locally, run `HEROKU_SLUG_COMMIT=something cargo run --bin server` and then visit http://localhost:4200/api/v1/deployed_sha (or whatever you decided to call the route), and verify that you get the JSON you expect with the value you set the env var to.
- [ ] Also run without that env var, visit the same url, and verify you get the default value.

I'm not even sure how you'd write automated tests for this backend route, so I don't think figuring that out is worth it. Manual verification should be fine.

**Comment by locks** [comment]
@carols10cents Have you seen [ember-cli-app-version](https://github.com/EmberSherpa/ember-cli-app-version)?

**Comment by carols10cents** [comment]
I HAVE NOT BUT THAT'S WHAT I WANT!!!!!!!!!!!

**Comment by jtgeibel** [comment]
I'd be interested in helping with the backend implementation.  I think we would have to capture the git sha during the build.

It looks like https://github.com/rustyhorde/vergen would be an option.  It also looks like the next stable release (this week already?) will allow for setting environment variable from the build script.  https://github.com/rust-lang/cargo/pull/3929#issuecomment-295837043

**Comment by carols10cents** [comment]
@jtgeibel do you think we need a backend implementation? The backend and frontend should be running the same SHA, right?

**Comment by jtgeibel** [comment]
> The backend and frontend should be running the same SHA, right?

@carols10cents that's a really interesting question that I hadn't thought about.  In production they should never diverge, but during development they would when using `npm run start:live` or `npm run start:staging`.

I'm new to ember and originally misunderstood how ember-cli-app-version works.  I've looked at it closer and I now believe it gets the SHA during the build and then stores this in a meta tag with other ember config information.

A backed API may be slightly nicer because during development you already know what is in the working directory and it would be nice to see the SHA for the backend version.  However, overall I'm pretty neutral on the implementation.

**Comment by carols10cents** [comment]
> but during development they would when using `npm run start:live` or `npm run start:staging`.

OOOOHH hhhmmmmm!! good point!

> A backend API may be slightly nicer because during development you already know what is in the working directory and it would be nice to see the SHA for the backend version. 

Orrrr if you're not running the frontend at all! I don't know if there are any deployments like this out there, but theoretically you *could* just run the backend and only interact with the API, in which case a backend API to get this would be nice.

> However, overall I'm pretty neutral on the implementation.

I think I would merge PRs for either or both :)

**Comment by jtgeibel** [comment]
So it looks like we're already using ember-cli-app-verison.  Now that I have the front-end up and running locally I see the version reported as `0.0.0+ccadd334`.  However, on production there is no git hash, it is only `0.0.0+`.

It seems the git repository is not available at build time on heroku.  Instead a SOURCE_VERSION environment variable is provided to the build.  There is a pull request upstream at EmberSherpa/ember-cli-app-version#42, which is awaiting review.

**Comment by notriddle** [comment]
Heroku does provide access to the git hash at runtime. You just [have to turn it on](https://devcenter.heroku.com/articles/dyno-metadata).

**Comment by treiff** [comment]
Planning on giving this a shot, if anyone is already on it let me know and I'll track down something else.
