### ISSUE TITLE
Migrate to using error-chain

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/crates.io#88]
This module should largely obsolete what we have in `util::error`

**Comment by Eh2406** [comment]
What is the best why to get started on this?

**Comment by alexcrichton** [comment]
Oh dear this is quite an ancient bug! Nowaday's I'd recommend moving to `error-chain`, and that'd just start out by looking in `src/util/errors.rs` and migrating it all to error-chain's errors.

**Comment by Eh2406** [comment]
I have not yet had the pleasure of using `error-chain`, so I am going to go do some reading.
Is there a way to do this cleanup incrementally? If it involves groking all error code in the project than re architecting the hole thing it may be more than I can do. If it can be done one piece at a time, it sounds more doable.

**Comment by alexcrichton** [comment]
Unfortunately this is likely an "all at once transition" rather than a piecemeal one

**Comment by carols10cents** [comment]
I don't think we're going to do this.
