### ISSUE TITLE
redundant `reserved_crate_name` checks

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-lang/crates.io#886]
in an attempt to address https://github.com/rust-lang/crates.io/issues/877 i bumped into the fact that we check if a crate has a reserved name in two places:

- `krates.rs`: https://github.com/rust-lang/crates.io/blob/c66f6e2fc5a5e4ac03488f9dad461b980c5def8e/src/krate.rs#L226-L243
- `up.sql`: https://github.com/rust-lang/crates.io/blob/b0a7a8d2f4356f38145cbbb05715ed0eedb136ce/migrations/20170305095748_create_reserved_crate_names/up.sql#L14-L22

what's the history here? should we dedupe? if so, should which should we go with?

**Comment by ashleygwilliams** [comment]
cc @carols10cents @natboehm

**Comment by sgrif** [comment]
One check is for the user facing error, the other check is for actual data integrity protection.

**Comment by sgrif** [comment]
Both were added in https://github.com/rust-lang/crates.io/commit/a740f3921714bc2e4f4745be5809202f6adca482

**Comment by carols10cents** [comment]
> One check is for the user facing error, the other check is for actual data integrity protection.

thanks! when would it be possible to get past the user-facing-error-check to create invalid data if the data integrity check isn't there?

**Comment by sgrif** [comment]
I honestly don't know. I do know that having a constraint at the database level is the best way to make sure that it never happens as a result of future changes.

**Comment by carols10cents** [comment]
yeah. idk. i'm going to think on this for a bit.

**Comment by Deedasmi** [comment]
Decided to take a look at this. Something LIKE this should work: https://github.com/Deedasmi/crates.io/commit/0db75e73e0c638f1e0de204e4b2180c5a47cba2f

Three options:
* Test for information disclosure on mapping all diesel errors to their strings
* Match this specific error and return human, else just Err (so it 500's)
* Don't worry about the extra query and mark resolved.

Note: It was easier to change the test string than write a DB migration.

**Comment by Turbo87** [comment]
since this has been stale for 4+ years I'm going to close this as it apparently won't be changed anytime soon 😅
