### ISSUE TITLE
Search update trigger causing warnings: words longer than 2047 characters are ignored

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#889]
Logging this mostly for myself since this probably needs some investigation of the production data to fully debug...

I'm seeing a lot of messages in the logs like this:

```
DETAIL:  Words longer than 2047 characters are ignored. 
CONTEXT:  PL/pgSQL function trigger_crates_name_search() line 8 at assignment 
```

The crates name search trigger happens [every time we update a crate row](https://github.com/rust-lang/crates.io/blob/b0a7a8d2f4356f38145cbbb05715ed0eedb136ce/migrations/20141020175650_dumped_migration_76/up.sql#L18), which could be for things like the number of crate downloads. [This is what the function is currently doing](https://github.com/rust-lang/crates.io/blob/b0a7a8d2f4356f38145cbbb05715ed0eedb136ce/migrations/20160219125609_dumped_migration_105/up.sql#L2), which updates the data we index for searching using the crate name, crate keywords, crate description, and contents of the README. 

So somewhere in one of those fields, for some crate that's being updated (which could just be the number of downloads), a crate has a word longer than 2047 characters?? If anyone could devise a query that would figure this out, I would be much obliged :) I'd like to figure out if we're doing something strange to cause this or if there's really some text out there with a really long word for a good reason.

Another thing we could do is adjust the trigger so it only gets run when one of these four fields is updated, since that's the only time we'd need to reindex these fields.

Last resort, I could tell papertrail to ignore this warning, but I want to make sure we're not messing up somewhere first.

**Comment by sgrif** [comment]
I suspect the query to find this would be roughly `where (coalesce(name, '') || coalesce(keywords, '') || coalesce(description, ''), coalesce(readme, '')) ~ [^ ]{2048}' `

**Comment by sgrif** [comment]
lol PG can't handle a regex with a repeater that large

**Comment by carols10cents** [comment]
I don't see this in the logs anymore  ¯\\\_(ツ)\_/¯
