### ISSUE TITLE
Frontend running against live backend doesn't login

### ISSUE THREAD

**Issue by vignesh-sankaran** [rust-lang/crates.io#891]
I'm able to get past the OAuth screen when attempting to login while running the frontend against the live site, but the `Login with GitHub` text isn't replaced with my account name. The OAuth window opens again when I click the `Login with GitHub` button. This functionality works properly when I run against a local backend.

**Comment by carols10cents** [comment]
Yes, the redirect URL specified in github for the production credentials isn't going to redirect to your local instance. I don't think there's a way to make this work, do you know of a way?

**Comment by carols10cents** [comment]
I've been thinking about this and I don't think it's possible to do, so I'm going to close this. Feel free to reopen if you figure out a way!
