### ISSUE TITLE
Documentation link can go to latest published version, not latest non-pre-release version

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#894]
Which can be confusing. 

Example: 
- https://crates.io/crates/data-encoding currently recommends installing v1.2.0, since that's the latest non-pre-release version
- Version 2.0.0-rc.1 has been published.
- Documentation link does go to https://ia0.github.com/data-encoding/v2.0.0-rc.1/data_encoding, which is what was specified in 2.0.0-rc.1's Cargo.toml.

Now, we could switch to storing documentation URL as a property of the version rather than the crate, but I don't think what this crate is doing is what people normally do! If you're using docs.rs, for example, the documentation for a version won't exist until after you publish and docs.rs has a chance to build it, so the documentation link would 404 for a bit after publishing if you specified the version. Updating the version in another spot in your Cargo.toml would also be annoying.

For people hosting their own docs, I don't even know if it's common to publish beneath a version path and keep old docs around, or if people are always overwriting to the same spot. This seems like a tooling issue that perhaps cargo could help with.

Or there may be other solutions to this, or other problems associated with these solutions that I haven't thought of yet. Mostly I just want to track this for discussion.

**Comment by Turbo87** [comment]
I believe this has been fixed. We are now loading the docs.rs metadata for the visible crate version and build the documentation link from that if necessary.
