### ISSUE TITLE
Sort drop-downs are strewn around

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/crates.io#9]
Similar to #8, with the same examples. There's too much duplication for these methods.

**Comment by sgrif** [comment]
We're cleaning out some of the older issues that haven't seen activity lately, so I'm going to close this.

We'd be happy to accept a PR that refactors this code (note: I'd also love to see our dropdowns move more towards being implemented with CSS than JS). I'm going to try to open an issue in the next few days with more concrete steps as well.
