### ISSUE TITLE
Failed to load Readme of crates

### ISSUE THREAD

**Issue by LambdaAlpha** [rust-lang/crates.io#9044]
### Current Behavior

Failed to render Readme of crates.
<https://crates.io/crates/wasm-bindgen>
![image](https://github.com/rust-lang/crates.io/assets/20299598/7978106c-7799-4fee-b934-50ed84773ba3)
<https://crates.io/crates/rand>
![image](https://github.com/rust-lang/crates.io/assets/20299598/7a3875cf-33ab-40a7-9c7e-971342e90078)

### Expected Behavior

Readme is rendered successfully

### Environment

- Browser: Google Chrome | 126.0.6478.127
- OS: Windows 10

**Comment by Turbo87** [comment]
works fine here. can you check the browser devtools if you see any errors?

**Comment by LambdaAlpha** [comment]
Not reproduce now. Maybe my network is not stable.
