### ISSUE TITLE
Spurious Percy test failures

### ISSUE THREAD

**Issue by LawnGnome** [rust-lang/crates.io#9052]
Many recent Percy builds seem to have failed due to it not loading the Fira fonts that crates.io uses, which causes visual changes when the fallback fonts are used.

Example: https://percy.io/b1b3bf45/crates.io/builds/35231632/

**Comment by Turbo87** [comment]
this is caused by us currently running the original frontend test suite, and the playwright test suite in parallel. these both share the same Percy snapshot names, and one loads the webfont, the other doesn't.

tl;dr it's a race condition 🙈

**Comment by eth3lbert** [comment]
It might be better to place it in a separate Percy folder (project?) if possible. Would that be a valid option for us?

**Comment by Turbo87** [comment]
hmm, I think there is a 1-to-1 correlation between Percy projects and GitHub projects, so making it a dedicated project would be difficult, but I guess we could prefix/suffix the playwright snapshots accordingly?

**Comment by eth3lbert** [comment]
> but I guess we could prefix/suffix the playwright snapshots accordingly?

Oh, this should also work.

Then, I believe we only need to adjust the title here https://github.com/rust-lang/crates.io/blob/cb34f1974ffab39e4dde0e0871769dba1886a33c/e2e/fixtures/percy.ts#L13-L18, which I intentionally implemented with the same name as the `@percy/ember` one for consistency.

**Comment by Turbo87** [comment]
it looks like https://github.com/rust-lang/crates.io/pull/9054 has fixed this :)
