### ISSUE TITLE
"Last updated" on a crate page isn't updating on new version publish

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#908]
ex: https://crates.io/crates/conduit-cookie, it says last updated 4 months ago but 0.8.4 was published yesterday 

![screen_shot_2017-07-23_at_6_20_37_pm](https://user-images.githubusercontent.com/193874/28503384-bf33f4c8-6fd3-11e7-87ea-24c439e09a25.jpg)

**Comment by notriddle-cerebrum** [comment]
I'd like to claim this issue.

**Comment by notriddle** [comment]
I'd like to claim this issue.
