### ISSUE TITLE
db-dump backwards-incompatible changes

### ISSUE THREAD

**Issue by kornelski** [rust-lang/crates.io#9081]
### Current Behavior

When you add new columns to the tables, they get added at various column positions in the csv files, which changes positions of existing columns, and breaks code that expects certain columns to be at n-th position.

### Expected Behavior

When you add new columns to the tables, please make them last in the csv dumps, so that the existing code doesn't need to be updated to stay in sync (since the additional unused columns will be ignored).

### Environment

- Browser:
- OS:

**Comment by Turbo87** [comment]
I understand that this would be nice and I'm open to PRs, but the files do have the column name headers, and IMHO those should be used to determine which column is at which index.
