### ISSUE TITLE
Support `<source media>` in Readme.md

### ISSUE THREAD

**Issue by benruijl** [rust-lang/crates.io#9093]
### Current Behavior

Crates.io support dark mode, but does not seem to support parsing the following Markdown/HTML for toggling images to dark mode in `Readme.md`:

```
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://symbolica.io/resources/demo.dark.svg">
  <source media="(prefers-color-scheme: light)" srcset="https://symbolica.io/resources/demo.light.svg">
  <img width="600" alt="A demo of Symbolica" src="https://symbolica.io/resources/demo.dark.svg">
</picture>
```

Github does support this.

As a result, the Readme.md looks bad in dark mode.

### Expected Behavior

I expect that the `source media` tags get parsed as happens on Github, to make `crates.io` render the Readme.md nicely in dark mode.

### Environment

- Browser: any
- OS: any

**Comment by benruijl** [comment]
Yes, 

https://crates.io/crates/symbolica

versus

https://github.com/benruijl/symbolica

**Comment by Turbo87** [comment]
thanks! https://github.com/rust-lang/crates.io/pull/9113 should hopefully solve this :)

**Comment by Turbo87** [comment]
once that PR is deployed you will have to release a new version, which causes the readme to rerender and then the `picture` and `source` elements will no longer be removed from the rendered HTML.

**Comment by Turbo87** [comment]
@benruijl it's deployed to production now :)
