### ISSUE TITLE
Github login fails with invalid state parameter

### ISSUE THREAD

**Issue by twosatsmaxi** [rust-lang/crates.io#9105]
### Current Behavior

`{"errors":[{"detail":"invalid state parameter"}]}`

### Expected Behavior

Should be able to login with github.

### Steps To Reproduce

1. Setup cratesio with docker compose in a standalone instance running locally with local ip.
2. Create app in github and setting redirection url with base `https://192.168.29.108/`
3. Try to login.
4. Redirection works but fails with `invalid state parameter` error.

### Environment

- Browser: Arc
- OS: macOS

**Comment by Turbo87** [comment]
can you debug this further? last time I tried local login it worked for me, but to be fair I wasn't running it inside a container.

**Comment by alpeshvas** [comment]
> can you debug this further? last time I tried local login it worked for me, but to be fair I wasn't running it inside a container.

I have setup debug log using RUST_LOG but nothing helpful there

**Comment by Turbo87** [comment]
you will probably have to look at the devtools/console of the browser and insert a couple of additional logging instructions to see where the state parameter is coming from and how it's flowing through the front- and backend.

**Comment by twosatsmaxi** [comment]
so there is api being called with the endpoint - `http://192.168.29.108:4200/api/private/session/authorize?code=CODEEEEE&state=XXXXXX`
and it returns 
```
{"errors":[{"detail":"invalid state parameter"}]}
```

**Comment by twosatsmaxi** [comment]
I'll fork the repo and docker build with more logs in backend to see the root cause. But do you think this is because the IP is not localhost but some private local ip?

**Comment by Turbo87** [comment]
> But do you think this is because the IP is not localhost but some private local ip?

I would expect this to not be a problem.

I see that you are using port 4200, which is the port that `ember serve` uses. If I remember correctly you will have to run the API server and use port 8888 in the browser to make this work properly. you might also have to include the port in the base URL at GitHub.

**Comment by twosatsmaxi** [comment]
but doc says 4200 
<img width="997" alt="image" src="https://github.com/user-attachments/assets/f874bb57-a278-4fac-bc3c-4317eed6a788">
https://github.com/rust-lang/crates.io/blob/main/docs/CONTRIBUTING.md#using-your-local-cratesio-with-cargo

**Comment by twosatsmaxi** [comment]
<img width="566" alt="image" src="https://github.com/user-attachments/assets/a8442147-2417-4781-88ba-88a5089cd1de">
got this in browser console

**Comment by twosatsmaxi** [comment]
Adding more logs here - https://github.com/rust-lang/crates.io/pull/9107

**Comment by Turbo87** [comment]
> but doc says 4200

hmm okay, I may have misremembered then :D

**Comment by twosatsmaxi** [comment]
so built it with new logs, now I am getting this 
<img width="449" alt="image" src="https://github.com/user-attachments/assets/9a2ec486-ce2a-4ec4-a1cf-889a0d8bef34">

**Comment by twosatsmaxi** [comment]
@Turbo87: I don't know why this condition fails, because in the logs I see same state before and after (check second SS) (token is expired so not an issue) 
<img width="1002" alt="image" src="https://github.com/user-attachments/assets/ecc91dd2-ce65-4fe6-95c7-69b9b2876144">
<img width="945" alt="image" src="https://github.com/user-attachments/assets/deec2741-e174-4416-8f99-6facd728d5c2">

**Comment by twosatsmaxi** [comment]
I feel that maybe after redirection, new session is starting?

**Comment by twosatsmaxi** [comment]
looks like it, I am out of clue now why that's happening.
<img width="529" alt="image" src="https://github.com/user-attachments/assets/33116d28-c480-42df-84a8-99df10fa8151">

**Comment by twosatsmaxi** [comment]
<img width="837" alt="image" src="https://github.com/user-attachments/assets/c4775982-6bbb-4603-a070-50d2c3ab7550">
API shows that it has but first is in the `begin` and second is post flow is redirected from github.

**Comment by twosatsmaxi** [comment]
<img width="656" alt="image" src="https://github.com/user-attachments/assets/7c85944e-2e97-425d-9714-7f624732e8bf">
maybe cookie is not being set when it redirects from github.

**Comment by twosatsmaxi** [comment]
added more logs, axum is not able to get cookies 😕 
<img width="558" alt="image" src="https://github.com/user-attachments/assets/6fa9e16d-e6e0-49a1-89ce-54c633708003">

**Comment by twosatsmaxi** [comment]
confirmed: cookie not being passed 
<img width="1496" alt="image" src="https://github.com/user-attachments/assets/2898d02c-0e57-4e70-b86f-c7eb532a4f53">

**Comment by twosatsmaxi** [comment]
Found the issue, it was so stupid, `secure` property is hardcoded to `true` 🤦 . But since I am doing it locally it won't pass (because of http), changed it to false and it worked, such a silly issue, this should have been passed from env variable or something.

**Comment by twosatsmaxi** [comment]
is there a way to solve it? maybe I set it as environment variable and pass it around? otherwise I'll have to work on my forked version (https://github.com/rust-lang/crates.io/pull/9109/files) with maintainance overhead, I am happy to raise a PR for this.

**Comment by twosatsmaxi** [comment]
can't use localhost because the server is running in a different PC within same wifi network.

**Comment by twosatsmaxi** [comment]
> the alternative is figuring out if you can somehow use HTTPS for that different PC, which would presumably then allow you to use the secure cookies
but isn't it gonna be too much overhead for folks setting up https for local setup.

**Comment by twosatsmaxi** [comment]
I have moved things to environment variable here - https://github.com/rust-lang/crates.io/pull/9109, if you folks consider moving these setting to env config level ever then would be great or I'll have to keep on syncing whenever new versions are rolled out.

**Comment by Turbo87** [comment]
> but isn't it gonna be too much overhead for folks setting up https just for local testing.

sure, but for local testing you can use localhost and then you probably won't have that issue

**Comment by alpeshvas** [comment]
> > but isn't it gonna be too much overhead for folks setting up https just for local testing.
> 
> 
> 
> sure, but for local testing you can use localhost and then you probably won't have that issue

I can't, so I have a home server running on a machine. I can't access that with localhost whenever I want to push some crates to it, I'll have to pass the IP address. Or have to setup local dns entry which will route to that for localhost but that will F up every localhost for other usecases. Anyway, running forked version with config based secure cookie rule is of less overhead, will do that for now.

**Comment by twosatsmaxi** [comment]
> > but isn't it gonna be too much overhead for folks setting up https just for local testing.
> 
> 
> 
> sure, but for local testing you can use localhost and then you probably won't have that issue

I can't, so I have a home server running on a machine. I can't access that with localhost whenever I want to push some crates to it, I'll have to pass the IP address. Or have to setup local dns entry which will route to that for localhost but that will F up every localhost for other usecases. Anyway, running forked version with config based secure cookie rule is of less overhead, will do that for now.

**Comment by Turbo87** [comment]
> I can't, so I have a home server running on a machine. I can't access that with localhost whenever I want to push some crates to it

I'm not sure what you are trying to achieve here. Are you trying to use the crates.io codebase as a local crate registry? if that is you intention then you might be better served with something like https://kellnr.io.
