### ISSUE TITLE
Display doc comments for private types

### ISSUE THREAD

**Issue by vignesh-sankaran** [rust-lang/crates.io#911]
crates.io is documented as its own crate [as cargo_registry](https://docs.rs/cargo-registry/0.1.0/cargo_registry/), and the S3 interaction as [cargo_registry_s3](https://docs.rs/cargo-registry-s3/0.1.0/s3/). I found out about how to display private types' documentation via `cargo doc --no-defaults --passes collapse-docs --passes unindent-comments`, but I don't think docs.rs has an option to do this for us. Is there an option to specify this another way e.g. in the `Cargo.toml`? Otherwise we could host the documentation on a different site ala Serde.

Tasks involved in completing this, added by @carols10cents:

- [ ] Add a `[package.metadata.docs.rs]` to `Cargo.toml` as shown in [this PR description](https://github.com/onur/docs.rs/pull/73)
- [ ] Set the `rustdoc-args` key to  `[ "--no-defaults --passes collapse-docs --passes unindent-comments" ]`
- [ ] Send in a PR and remind @carols10cents to release a new version of cargo-registry after merging the PR :)

**Comment by kureuil** [comment]
Support for custom rustdoc arguments was [merged a while ago](https://github.com/onur/docs.rs/pull/73), so we should be able to expose private types' documentation on docs.rs.

**Comment by mattgathu** [comment]
Hi. I'm interested in implementing this. Can I be assigned. thanks

**Comment by vignesh-sankaran** [comment]
Don't think we assign issues with this repo, you can just start working on it and submit a PR when you're ready :). Let us know if you have any questions :).

**Comment by mattgathu** [comment]
cool. thanks

**Comment by mattgathu** [comment]
Hi I have created a PR: #1042 that implements the tasks in the description.

**Comment by carols10cents** [comment]
Hmmmmmm, so I published cargo-registry 0.2.0, and [it's up on docs.rs](https://docs.rs/cargo-registry/0.2.0/cargo_registry/), but I don't see private things like [the `DOCUMENTATION_BLACKLIST` constant](https://github.com/rust-lang/crates.io/blob/master/src/krate.rs#L41-L43) in the docs :( I'm not sure what's wrong, going to open an issue with docs.rs to try and figure it out.

**Comment by carols10cents** [comment]
v0.2.1 works!!!!! https://docs.rs/cargo-registry/0.2.1/cargo_registry/krate/index.html shows private stuff!!

Thank you @mattgathu and @onur!!
