### ISSUE TITLE
Session cookies should be good for a year

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#918]
See discussion in #888. That didn't end up being a session cookie problem, but setting the expiration time on that came up and I don't want to forget about taking care of that.

**Comment by sgrif** [comment]
This will require changes to conduit-session to implement

**Comment by locks** [comment]
Is this still relevant?

**Comment by Turbo87** [comment]
given that nobody responded to this question for two years I'm gonna assume it isn't actually that relevant (anymore) 😅
