### ISSUE TITLE
Search works incorrectly

### ISSUE THREAD

**Issue by TheGP** [rust-lang/crates.io#9248]
### Current Behavior

When I search "dotenv" it shows me trash unmaintained packages.

### Expected Behavior

"dotenvy" in the first place in the results.

### Steps To Reproduce

1. https://crates.io/search?q=dotenv
2. Observe some trash instead of good packages

### Environment

- Browser:
- OS:

**Comment by eth3lbert** [comment]
With `Relevance` sorting, you will see the entry with an _exact match_ in first place. You could get "dotenvy" in first place when sorting by either `All-Time Downloads` or `Recent Downloads`.

**Comment by Turbo87** [comment]
we already have a couple of other open issues about our search experience (see https://github.com/rust-lang/crates.io/labels/A-search) but unfortunately we haven't found the time yet to properly address them. since we already have these other issues I'll close this one.
