### ISSUE TITLE
Front end won't run without sudo in Linux

### ISSUE THREAD

**Issue by vignesh-sankaran** [rust-lang/crates.io#926]
On Debian sid, I can't seem to run the front end locally without `sudo`. Apparently it tries to create a `/etc/configstore` directory, it looks like `ember-cli` that tries to do this. As a workaround I created the directory manually and `chmod 777`'d it. Is this something you've run into @kureuil?

**Comment by kureuil** [comment]
Nope, never encountered this problem. The directory `/etc/configstore` doesn't exist on my machine and my account cannot use `sudo`.

**Comment by vignesh-sankaran** [comment]
Hmm, do you have a directory in `~/.config/configstore` instead? I'm trying to figure out if I caused this problem by installing `ember-cli` with `sudo` initially

**Comment by kureuil** [comment]
Yes, I do. Can you try using `./node_modules/.bin/ember` instead of the globally installed one ?

**Comment by vignesh-sankaran** [comment]
I resolved it earlier by removing `npm` and `nodejs` and reinstalling it with [nvm](https://github.com/creationix/nvm/blob/master/README.md) instead, but I still ran into this problem :(. Need a clean Linux machine to test this on...
