### ISSUE TITLE
Bot to check if rustfmt is not run

### ISSUE THREAD

**Issue by vignesh-sankaran** [rust-lang/crates.io#929]
Is there a bot that can output a comment on a PR to run `rustfmt` if that particular TravisCI check fails? I'm not sure if bors-ng can do this for us, or if there's another bot out there that can handle this.

**Comment by sgrif** [comment]
We could also just set up `cargo fmt` as a post-commit hook

**Comment by carols10cents** [comment]
> We could also just set up cargo fmt as a post-commit hook

Everyone would have to set that up locally, right?

**Comment by sgrif** [comment]
I'm pretty sure it's possible to check the hooks file into the repo

**Comment by carols10cents** [comment]
> I'm pretty sure it's possible to check the hooks file into the repo

I'm pretty sure it's not (the .git/hooks directory cannot be committed and does not come with a clone), and even if we [use a config var only available in git 2.9 or use symlinks](https://www.viget.com/articles/two-ways-to-share-git-hooks-with-your-team), we still have to get people to set up the git config or symlinks. Even THEN you can bypass pre-commit hooks with `git commit --no-verify` and post-commit hooks can't affect the outcome of the commit.

So we could provide commit hooks for people's convenience if we wanted and if they so choose to use them, but there's not a way to mandate them.

**Comment by vignesh-sankaran** [comment]
Hmm, how about [danger](https://github.com/danger/danger)?

**Comment by Turbo87** [comment]
closing this issue due to missing activity here
