### ISSUE TITLE
webmaster for https://crates.io/crates/clang-tidy-sarif - bad link from https://sarifweb.azurewebsites.net/ text

### ISSUE THREAD

**Issue by michael-paoli-wdc** [rust-lang/crates.io#9316]
### Current Behavior

On page https://crates.io/crates/clang-tidy-sarif
text https://sarifweb.azurewebsites.net/ links to https://ifweb.azurewebsites.net/

### Expected Behavior

On page https://crates.io/crates/clang-tidy-sarif
text https://sarifweb.azurewebsites.net/ should link to https://sarifweb.azurewebsites.net/

### Steps To Reproduce

1. Go to: https://crates.io/crates/clang-tidy-sarif
2. Click on: https://sarifweb.azurewebsites.net/
3. Goes/links to: https://ifweb.azurewebsites.net/
4. Should go/link to: https://sarifweb.azurewebsites.net/

### Environment

- Browser: any
- OS: any

### Anything else?

I didn't find webmaster email/link on page or site,
but there's report bug on page, so ... here I am and have reported.

**Comment by LawnGnome** [comment]
Thanks, but this is a problem in the actual crate, rather than crates.io itself.

Closing, but pinging @psastras, who's the owner of the `clang-tidy-sarif` crate.

**Comment by michael-paoli-wdc** [comment]
> pinging @psastras, who's the owner of the clang-tidy-sarif crate
Thanks!
