### ISSUE TITLE
Backend development environment setup assistant

### ISSUE THREAD

**Issue by vignesh-sankaran** [rust-lang/crates.io#933]
Would be nice if rather than erroring out, the backend had a prebuild script to check if the database is set up, setup a .env file, and initialise the local git repo. I've recloned the repo a few times now and forgot to transfer the .env file, meaning that I had to set one up again.

EDIT: Realised we could extend the scope of this prebuild script to automate most development environment setup steps.

**Comment by sgrif** [comment]
How would a script know where your database lives without a `.env` file?

**Comment by vignesh-sankaran** [comment]
True, which is something we can manage with this setup assistant, perhaps by asking the user to type it in, or to enter the parameters of a connection URI and create one from there.

Does `diesel setup` also run the migrations too?

**Comment by Turbo87** [comment]
https://github.com/rust-lang/crates.io/blob/master/docs/CONTRIBUTING.md#working-on-the-backend describes the necessary steps quite well by now, so I'll go ahead and close this issue for now
