### ISSUE TITLE
recent_downloads is 0 in API data

### ISSUE THREAD

**Issue by djc** [rust-lang/crates.io#935]
I looked at the API data returned for Askama in order to submit it for AreWeWebYet. I thought it might be nice to expose the recent downloads on that site as well, but when I looked into the data `recent_downloads` is 0. If I look at https://crates.io/categories/template-engine, however, the value for askama is 226. Also in the API data, the `downloads` number for the release I did yesterday is 6, so it's not like the underlying data is wrong. (Assuming crate-wide downloads are calculated by summing version downloads.)

**Comment by natboehm** [comment]
> I looked at the API data returned for Askama in order to submit it for AreWeWebYet.

Could you clarify what URL you were requesting where you see `recent_downloads` being zero?

**Comment by natboehm** [comment]
If you mean the route `GET /crates/crate_id`, `recent_downloads` is indeed zero. We're currently working on a fix, however as a workaround you could submit a query to the route `GET /search?q=askama` that searches for the crate. Your crate name of Askama will always be the exact match and I know that the field `recent_downloads` is definitely accessible there.

For reference, [this line](https://github.com/rust-lang/crates.io/blob/master/src/krate.rs#L1090) in `fn show` is problematic.

**Comment by djc** [comment]
Yeah, I'm hitting `/crates/crate_id`.

**Comment by carols10cents** [comment]
This should be fixed now! https://crates.io/api/v1/crates/askama is showing me `"recent_downloads": 141` :)

**Comment by djc** [comment]
Thanks!
