### ISSUE TITLE
Broken dev environment with conduit cookie crate update

### ISSUE THREAD

**Issue by vignesh-sankaran** [rust-lang/crates.io#937]
After #909, I now get ``thread 'main' panicked at 'bad master key length: expected at least 32 bytes, found 6', /home/vignesh/.cargo/registry/src/github.com-1ecc6299db9ec823/cookie-0.9.1/src/secure/key.rs:53
note: Run with `RUST_BACKTRACE=1` for a backtrace.`` with `cargo run --bin server`, and all the integration tests fail :(. This is a problem on macOS and Linux.

**Comment by kureuil** [comment]
Requirements for the secret key have changed in #909, it now has to be at least 32 bytes long: https://docs.rs/cookie/0.9.1/cookie/struct.Key.html#method.from_master

Comments in the `.env.sample` file were not updated to reflect this change though.

**Comment by vignesh-sankaran** [comment]
How do I change the key? And which key is this precisely?

**Comment by carols10cents** [comment]
> EDIT: It appears I can't just put in any arbitrary string, going to need some help with this :(

What does it say?

**Comment by vignesh-sankaran** [comment]
Ok so using crates.io locally works, but all the integration tests are failing :/. Is that the case for you too @carols10cents and @kureuil?

**Comment by kureuil** [comment]
@vignesh-sankaran Both `cargo test` and `npm test` are running just fine on my end.

**Comment by carols10cents** [comment]
Fixed in #941!
