### ISSUE TITLE
Add diagram of database schema

### ISSUE THREAD

**Issue by vignesh-sankaran** [rust-lang/crates.io#938]
As part of the effort to improve crates.io's documentation, we should have a bot that creates an ER diagram, and when there is a change made to the `migrations/` directory, the bot will recreate the ER diagram, and create a PR which we can accept. We can use [SchemaCrawler](https://github.com/sualeh/SchemaCrawler), [schemaspy](https://github.com/schemaspy/schemaspy), or another tool to create the diagram for us.

Steps to get this working:
- [ ] Setup a script that connects to the crates.io repo via webhook
- [ ] Diff between the previous and current commit  to check for changes to the `migrations/` directory
- [ ] Run the ER diagram visualiser if there are any changes
- [ ] Commit and push with the message "Updated database ER diagram" or along those lines, and create a PR

I'm open to hearing if there's an easier way to do this too :).

**Comment by sualeh** [comment]
Sounds like a good idea. You will need to build a database with all the migrations in place, and then run SchemaCrawler. SchemaCrawler can not only produce an ER diagram for documentation purposes, but also a textual description of the schema which can be pushed using a PR. The a textual description of the schema is designed to be diff-ed with previous versions, making it easy to see schema changes over time.

**Comment by carols10cents** [comment]
> but also a textual description of the schema which can be pushed using a PR. The a textual description of the schema is designed to be diff-ed with previous versions, making it easy to see schema changes over time.

Diesel already produces a textual description of the schema here: https://github.com/rust-lang/crates.io/blob/master/src/schema.rs

**Comment by Turbo87** [comment]
closing this as there hasn't been much activity on this issue for a while
