### ISSUE TITLE
suggestion - search by trait

### ISSUE THREAD

**Issue by dobkeratops** [rust-lang/crates.io#939]
[discussion](https://users.rust-lang.org/t/crates-io-search-by-traits-safety/12226/3) : would it be possible to search crates by the traits they implement (more specifically, the traits *of other crates*, since any crate may have internals)

- either adding these directly as keywords,

- or adding something to the UI in parallel with the keywords (so as not to pollute the keywords) .. but still allow these to be found through the search

e.g. imagine when looking for a collection looking for all the crates implementing ```trait Index```, etc.. leverage the traits as a means of discovery

**Comment by sgrif** [comment]
Can you elaborate more on what exactly you're looking to accomplish? Given that the orphan rule would prevent a crate from implementing a trait for any types other than its own, it seems like the reverse_dependencies page already accomplishes the majority of the value we'd get from doing this. Anything which involved actually parsing the code of various crates would be a monumental undertaking, and would need to have an enormous benefit to be worth it.

**Comment by carols10cents** [comment]
Yes, [as I mentioned on the users forum](https://users.rust-lang.org/t/crates-io-search-by-traits-safety/12226/6?u=carols10cents), I think this is beyond the scope of what crates.io is responsible for, and would be best as a standalone tool or perhaps in docs.rs.
