### ISSUE TITLE
"Report a crate" button doesn't require any information

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#9478]
### Current Behavior

[The current implementation of the "Report a crate" button](https://github.com/rust-lang/crates.io/pull/9307) is nice and simple, which I like, but it has led to us getting some support emails where the person reporting the crate has not checked any of the markdown checkboxes indicating why they're reporting the crate, nor have they edited the text that says `<please add more information if you can>`.

This adds more burden on processing support emails, because I have no idea why this person is reporting the crate. 

### Expected Behavior

Brainstorming on a solution, I'd love if there was a little web form that required at least one checkbox to be checked (and one would be "other", which would require entering text in a text box), and the submit button for the form would then generate the `mailto` link once the form was valid.

**Comment by Turbo87** [comment]
![Image](https://github.com/user-attachments/assets/03f43c55-831e-4224-ae6f-b441aee43c0d)

well, that worked great....... 🤦‍♂
