### ISSUE TITLE
Define what "crates.io" is to "rust". "Registry"?

### ISSUE THREAD

**Issue by behnam** [rust-lang/crates.io#950]
I was updating cargo's docs to use the term accurately, and I realized that there's clear term for what "crates.io" *is*.

<https://crates.io/> has these lines in the homepage:
* "Cargo / pacakges for Rust",
* "The Rust community’s crate host",

There's no "About crates.io" page.

In <http://doc.crates.io/manifest.html#the-publish--field-optional>, we have "a package repository", to which I added "(like crates.io)" recently to prevent confusions with a git repository of a package.

In <http://doc.crates.io/manifest.html#the-patch-section>, we also have "the https://crates.io registry".

In <http://doc.crates.io/manifest.html#package-metadata> we again have "The crates.io registry".

In <https://doc.rust-lang.org/book/second-edition/>, we have "the Rust package registry site, crates.io".

IIRC, in some of the error messages and issues/pulls, it's call "package index".

# My Recommendation

IMHO, "package registry" sounds very good to me, and clearly denotes the *registry* role of the website.

When agreed on the term, we should update some of these docs to use the same wording.

**Comment by steveklabnik** [comment]
> I was updating cargo's docs to use the term accurately,

❤️ 💯 

> IMHO, "package registry" sounds very good to me, and clearly denotes the registry role of the website.

👍

**Comment by carols10cents** [comment]
Yep, I agree "package registry" is the right term. Seems like the fixes need to go in the docs in cargo's repo, so I'm going to give this a close!
