### ISSUE TITLE
cargo owner -a fails with HTTP 500 error

### ISSUE THREAD

**Issue by lalitb** [rust-lang/crates.io#9524]
### Current Behavior

For [opentelemetry-etw-logs](https://crates.io/crates/opentelemetry-etw-logs), getting error on adding an owner:

```console
$ cargo owner --add github:open-telemetry:rust-maintainers
-v
    Updating crates.io index
  Credential cargo:token get crates-io
error: failed to invite owners to crate `opentelemetry-etw-logs` on registry at https://crates.io

Caused by:
  the remote server responded with an error (status 500 Internal Server Error): Internal Server Error
```

**Background**:
- The GitHub team `github:open-telemetry:rust-maintainers` was originally an owner of this crate.
- The team was accidentally deleted on GitHub and later re-created with the same name.
- We removed this team as owner and attempted to re-add it.

It seems like the crates.io registry is encountering a server-side issue, possibly related to the fact that the team was deleted and re-created. Please let me know if additional steps are needed to resolve this.

### Expected Behavior

The owner should be added.

### Steps To Reproduce

$ cargo owner --add github:open-telemetry:rust-maintainers

### Environment

N/A

**Comment by Turbo87** [comment]
see https://github.com/rust-lang/crates.io/issues/6949

**Comment by lalitb** [comment]
@Turbo87 - what’s the solution here ? We need to create a GitHub team with different name, and use that ?

**Comment by Turbo87** [comment]
yeah, I think that would be easiest for now.
