### ISSUE TITLE
Login doesn't work using Edge

### ISSUE THREAD

**Issue by kureuil** [rust-lang/crates.io#954]
When you try to login, it raises an exception

```
Calling delete on 'github_response' is not allowed in strict mode
```

![applicationframehost_2017-08-12_19-14-16](https://user-images.githubusercontent.com/1275463/29242758-e0af547a-7f92-11e7-8b31-8191373e827c.png)

Steps to reproduce:

* Open Microsoft Edge & go to https://crates.io/
* Click on "Log in with GitHub"
* Connect to GitHub using your credentials
* "Something went wrong!"

**Comment by carols10cents** [comment]
oh no! thank you for catching this before I deployed it :) <3

**Comment by carols10cents** [comment]
oh wait lol this is on production
