### ISSUE TITLE
Docrs issue with build scripts that require local folders

### ISSUE THREAD

**Issue by gwbres** [rust-lang/crates.io#9567]
### Current Behavior

Hello,

we're facing issues in the `anise` library:  https://github.com/nyx-space/anise/issues/302
because the Docrs auto documentation happens in a docker environment, and it's unable to obtain the local folder that should be shipped with our library.  Error logs: https://docs.rs/crate/anise/0.4.4/builds

The local folder is created by Build.rs. 
Its content is to be embedded with `rust_embed`.
The Docrs job happens in a read only environment and when it is brought up, it seems the ../data folder does not exist and causes are build script to fail.

Can you guys help out:

* we added ../data to `include` in Cargo.toml, to our understanding, this describes what is hosted in crates I/O by publication, so it should exist
* is there a method to detect, in our Build.rs script, that this is a docrs run and possibly bypass all this stuff

### Expected Behavior

Docrs should pass

### Steps To Reproduce

Impossible ? we need a copy of the docrs docker

### Environment

- Browser:
- OS:

**Comment by Turbo87** [comment]
if this is about docs.rs then you might want to open the issue over at https://github.com/rust-lang/docs.rs/ 😉

**Comment by gwbres** [comment]
Thanks, I was not sure this was the correct location either
