### ISSUE TITLE
New policy for transfer of abandonned crates with good handle

### ISSUE THREAD

**Issue by kleenleen** [rust-lang/crates.io#9612]
When browsing crates, I often see that the "purest" handles (names) were taken by anons who literally abandoned them with no care, leaving the rest of us having to deal with crappy names or at least less ideal ones.

Coming to my mind for example the user Meh who is a specialist at reserving official names, making mildly finished bindings and then abandoning them forever.

We need a new policy, where such behavior are not affecting the community who deserves properly named crates, and I think that the website should have a button, "claim crate due to inactivity", and let the admin review if that claim makes sense, so that "ffmpeg" for example can be the healthy-supported crate instead of having to create new ones around it.

**Comment by LawnGnome** [comment]
The [crates.io usage policy][usage-policy] was updated in [RFC 3463][rfc] last year to allow for name squatted crates to be removed upon request.

You can use the _Report Crate_ button on a crate's page on crates.io to open a ticket with the crates.io team to look into a particular crate.

![Image](https://github.com/user-attachments/assets/1bdcc8a6-a77c-4bbc-a6f1-033ca686fd9c)

[rfc]: https://rust-lang.github.io/rfcs/3463-crates-io-policy-update.html
[usage-policy]: https://crates.io/policies
