### ISSUE TITLE
Add another column to the homepage for "Most Recently Downloaded"

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#962]
Instructions for fixing this, can be done in 2 separate PRs but they will need to be done in order :)

## PR 1: backend

- [x] In the [`summary` function that returns JSON for the /api/v1/summary route](https://github.com/rust-lang/crates.io/blob/76d15c1a909ddcbf23413a5a3ad477874baca859/src/krate.rs#L759), add a query similar to [these queries](https://github.com/rust-lang/crates.io/blob/76d15c1a909ddcbf23413a5a3ad477874baca859/src/krate.rs#L782-L797) that selects 10 crates sorted by [recent downloads descending nulls last](https://github.com/rust-lang/crates.io/blob/76d15c1a909ddcbf23413a5a3ad477874baca859/src/krate.rs#L603), which is defined [by this query that's part of the `index` function](https://github.com/rust-lang/crates.io/blob/76d15c1a909ddcbf23413a5a3ad477874baca859/src/krate.rs#L584-L592) (I'm fine with copy-pasting that code, if you feel ambitious and want to refactor to remove the duplication, feel free to give that a try!)
- [x] Add a field for those crates to the [returned data struct definition](https://github.com/rust-lang/crates.io/blob/76d15c1a909ddcbf23413a5a3ad477874baca859/src/krate.rs#L816-L818) and the [returned struct instance](https://github.com/rust-lang/crates.io/blob/76d15c1a909ddcbf23413a5a3ad477874baca859/src/krate.rs#L825-L827) in the same manner as the other fields that return crates
- [x] Add a test that 2 or 3 crates are returned in the expected order for this field, [the `CrateBuilder` provides a way to set a crate's recent downloads for testing](https://github.com/rust-lang/crates.io/blob/76d15c1a909ddcbf23413a5a3ad477874baca859/src/tests/krate.rs#L283-L287). The summary route [isn't tested very much right now](https://github.com/rust-lang/crates.io/blob/76d15c1a909ddcbf23413a5a3ad477874baca859/src/tests/krate.rs#L980-L985); a bonus would be adding more tests for the other parts of summary as well!

## PR #2: Frontend

- [ ] Once /api/v1/summary returns recent downloads, add a section [like these](https://github.com/rust-lang/crates.io/blob/76d15c1a909ddcbf23413a5a3ad477874baca859/app/templates/index.hbs#L39-L50) to display recent downloads. Please think of a good header for this, "Most Recently Downloaded" sounds like this is what crates people have downloaded in the last minute? "Most Downloaded in the Last 90 Days" is accurate but long. "Most Recent Downloads"? "Most Downloads Recently"?
- [ ] Check how it looks and at different browser widths; I think the CSS should Just Work but there's a chance it might need some tweaks :)

**Comment by sabinbajracharya** [comment]
I would like to work on this issue but [](https://crates.io/api/v1/summary) api does not return 'Most recently downloaded' information.

**Comment by carols10cents** [comment]
Yep, changing the API for the /api/v1/summary route to return this information is part of the issue actually. I got confused and thought #935 was about that, but it's not. Sorry for the misleading tags!

**Comment by erewok** [comment]
Hi, I have been looking through this codebase and I'd like to take a shot at implementing the backend changes for this. I appreciate how you have organized this project and how you have encouraged people to get involved in Rust by helping out here. In that spirit, I would like to help.

@carols10cents I've been experimenting with the language by building small things for a few months, but I am new to still really new to the Rust ecosystem, so I have a question related to your initial comment: you stated that the `summary` endpoint is not currently tested very thoroughly and I have been adding some tests in the module you linked, but when I run `cargo test` by default it only runs the tests defined in `src/krates/mod.rs`. 

How can I instruct it to also run the full test suite, including the tests defined in `src/tests/krates.rs`?

**Comment by carols10cents** [comment]
Hi @erewok!! Glad to have you here!! The behavior you're seeing with `cargo test` is definitely not expected... how can you tell it's only running the tests in `src/krates/mod.rs`? Could you gist the whole output you see from `cargo test`?

**Comment by erewok** [comment]
Hi @carols10cents. Thanks for the warm welcome! I am impressed with how well-run this project is.

At any rate, this morning I cloned the repo anew, built, and ran the tests and the problem seems to have disappeared. I'm not sure why it was ever there in the first place but it must have been user error. Thanks. I'm going to work on fixing the tests I wrote for the `api/v1/summary` endpoint.

**Comment by carols10cents** [comment]
The backend for this is now done, thank you @erewok !!!!

**Comment by sabinbajracharya** [comment]
@carols10cents  As the backend is done, may I work on the front-end part?

**Comment by carols10cents** [comment]
@sabinbajracharya absolutely!

**Comment by sabinbajracharya** [comment]
rust-lang/crates.io#1121

**Comment by someguynamedmatt** [comment]
@carols10cents Can this be closed?

**Comment by carols10cents** [comment]
@someguynamedmatt Indeed! good catch!
