### ISSUE TITLE
Searching for "oauth" does not yield "oauth2"

### ISSUE THREAD

**Issue by sxlijin** [rust-lang/crates.io#9633]
### Current Behavior

https://crates.io/search?q=oauth does not show the [oauth2](https://crates.io/crates/oauth2) crate.

### Expected Behavior

https://crates.io/search?q=oauth should show the [oauth2](https://crates.io/crates/oauth2) crate.

### Steps To Reproduce

Visit https://crates.io/search?q=oauth

### Anything else?

Background: while implementing an oauth flow for CLI login earlier this week, I searched "oauth" on crates.io, which turns up effectively no useful results, didn't second-guess the list, and went ahead and hand-rolled my own client implementation. Fast forward a few days, and I realize that there _is_ an `oauth2` crate, but it wasn't in the search results.

(I recognize that this is wading into the "crates.io should show highly relevant crates" problem territory of tags/semantic relevance, but this felt like a very concrete example where, as a user of crates.io, I did work that I should not have done as a result of trusting the crates.io search result.)

**Comment by Turbo87** [comment]
we are painfully aware that our search experience isn't as good as we would like it to be, but there are still a couple more higher-priority items on our todo list before we can tackle this issue. since there are already a number of open issues related to our search functionality (see https://github.com/rust-lang/crates.io/labels/A-search) I'll close this one for now.

**Comment by sxlijin** [comment]
Is there perhaps an issue that this should be duped against?

I ask because I recognize that as an open-source project, one thing that's hard to get is _triaged_ user feedback, so that you can choose which work should get prioritized, and this felt like a relatively impactful user journey to explicitly list in the backlog (e.g. if at some point you decide you want to prioritize search systems that don't rely on author-specified keywords).

But maybe I'm overstepping here, in which case I'll leave this as-is 👍
