### ISSUE TITLE
Rendered README fails to parse links on images

### ISSUE THREAD

**Issue by daboross** [rust-lang/crates.io#966]
Hi! Loving the READMEs showing in crates.io!

I have one bug I'm experiencing for one of my crates, where links surrounding images fail to parse. Specifically, links like `[![Linux Build Status][travis-image]][travis-builds]` - showing the image `[travis-image]` and linking to `[travis-builds]` (both specified at the end of the README).

[github](https://github.com/daboross/fern#fern) vs [crates.io](https://crates.io/crates/fern).

![github screenshot](https://user-images.githubusercontent.com/1152146/29483729-bc424686-8462-11e7-9c0b-4afff66ae55b.png)
![crates.io screenshot](https://user-images.githubusercontent.com/1152146/29483735-db031fe6-8462-11e7-95e5-edbd10abd896.png)

For some reason the first badge shows up as an image surrounded by `[]` and then plain text, and the second one shows up as an image surrounded by `[]` followed by a link.

Source is:
```
fern
====
[![Linux Build Status][travis-image]][travis-builds]
[![Windows Build Status][appveyor-image]][appveyor-builds]

Simple, efficient logging for [Rust].
```

**Comment by carols10cents** [comment]
This has been fixed by https://github.com/rust-lang/crates.io/pull/981!
