### ISSUE TITLE
Please use a little more width for crate pages on screens

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/crates.io#970]
When rendering on a full-size screen (rather than mobile), the crates page still renders content in a very narrow column. The width used on almost every other page seems fine, but crate pages have a sidebar, which narrows the region available for the README content.

Take a look at <https://crates.io/crates/colorparse>, and compare it to <https://github.com/joshtriplett/colorparse/>. Notice how the code in the latter doesn't wrap, while it does in the former.

I think it would be reasonable for the main (non-sidebar) crate content on crate pages to have the same width that the overall (non-columnar) content has on other pages. That would make the README much more readable, without sacrificing the critical property of avoiding excessively wide lines.

Does that seem reasonable?

----

Implementation instructions added by @carols10cents:

- [ ] Increase the [`max-width` set on `.crate-info .docs`](https://github.com/rust-lang/crates.io/blob/566dc51aff42986a669ee0d7eba0d157ee569ae7/app/styles/crate.scss#L211) (I think) so that it's about as wide as readmes appear on GitHub
- [ ] Test that change at different screen widths and make adjustments if anything looks weird
- Send in a PR and include some screenshots! `npm run start:live` will come in handy for this :)

**Comment by tcbyrd** [comment]
Hey all! Just found this after reading through the roadmap for the rest of the year. Happy to help out and submit my first PR to the project, but first wanted to just discuss what I found.

If the docs div is increased to 640px, the overflow goes away in this example without any major side effects:
![screenflow](https://user-images.githubusercontent.com/13207348/30561025-b87fba50-9c87-11e7-8cf6-f3052a6b34b0.gif)

This change would make it so code shouldn't hit the overflow up to about 65 characters of line-length. Making it as wide as GitHub's README would mean having to move the authorship div somewhere else or making everything wider, which is something that may require a bit more discussion beyond the scope of this Issue. I'd be willing to open a PR with some suggestions on the latter if needed.

**Comment by joshtriplett** [comment]
@tcbyrd I think the right solution would be to widen the containing div as well (the beige area) and leave the authorship sidebar the same size. Some other pages already have a wider content area.

**Comment by tcbyrd** [comment]
I agree. 960px is a pretty decent width for the whole thing. I pulled down the source and noticed this doesn't change the docs because they are hosted on GitHub Pages. To make it consistent we'd also need to change [this line](https://github.com/rust-lang/cargo/blob/73eb8c424dc3732cea23769982d0e4e261d5399e/stylesheets/all.css#L6) in [`rust-lang/cargo/tree/gh-pages/stylesheets/all.css`](https://github.com/rust-lang/cargo/blob/gh-pages/stylesheets/all.css)

Since I already setup the dev environment, I'll open a PR tomorrow unless I hear otherwise.

**Comment by dhaval-66degrees** [comment]
Increase width please. why would someone want content width so narrow and wasting most of real estate on most devices?
