### ISSUE TITLE
README files tend to duplicate parts of the crates.io UI

### ISSUE THREAD

**Issue by notriddle** [rust-lang/crates.io#977]
For example, <https://crates.io/crates/chroniker> shows the crate name three times in a row.

Not sure what we should do to make the presentation a bit more reasonable, but it looks awful.

**Comment by carols10cents** [comment]
Yeah, I'm not sure what to do either.

**Comment by locks** [comment]
I am closing this because I don't see an actionable path forward.
This should be kept in mind when doing the future redesign work to see if maybe the impact can be lessened via design.
