### ISSUE TITLE
Notification says invite will be sent when adding a team owner to crate

### ISSUE THREAD

**Issue by wezm** [rust-lang/crates.io#9797]
### Current Behavior

When a GitHub team is added as a crate owner, a notification is shown that reads:

> An invite has been sent to github:org:team

This appears to originate here:

https://github.com/rust-lang/crates.io/blob/4bcae0123322baf69f42378bfef94285eb517e4e/app/controllers/crate/settings.js#L17

However as noted here:

https://github.com/rust-lang/crates.io/blob/4bcae0123322baf69f42378bfef94285eb517e4e/src/models/krate.rs#L463-L464

teams are always immediately added.

### Expected Behavior

I'd expect the notification message to be different when adding a team, indicating that the team has been added. The message about an invite being sent confused me into thinking I needed to find an email.

### Steps To Reproduce

1. Go to the settings of a crate
2. Enter a team in the Add Owner field and press Save
3. Observe notification

### Environment

N/A

### Anything else?

![Image](https://github.com/user-attachments/assets/1880ec18-d663-48eb-a54d-7571b57688b1)

**Comment by Turbo87** [comment]
ouch, yeah, that is definitely a bug in the frontend behavior... I'll take a look :)

**Comment by wezm** [comment]
Awesome, thanks for the quick fix.
