### ISSUE TITLE
Embedded PNG images in README are not rendered on crates.io

### ISSUE THREAD

**Issue by apeduru** [rust-lang/crates.io#982]
See [https://crates.io/crates/bspl](https://crates.io/crates/bspl). Compared to the [README](https://github.com/apeduru/bspl/blob/master/README.md) in the repo, the name of the PNG file itself appears in place of the image on crates.io. 

Viewing on Firefox 55.0.2.

**Comment by kureuil** [comment]
The problem is the `img`'s `src` attribute is an absolute path. These kind of links are not authorized in attributes. Putting an absolute link to the raw image ( https://github.com/apeduru/bspl/raw/master/pics/bspl_screenshot.png ) should resolve the issue.

**Comment by apeduru** [comment]
Confirmed working using absolute link.
