### ISSUE TITLE
Rendered readme does not render table

### ISSUE THREAD

**Issue by ruuda** [rust-lang/crates.io#983]
I have the following table in the GitHub-flavored markdown readme of my crate:

```
| Decoder | Time / reference |
| ------- | ---------------- |
| Claxon  | 1.13 ± 0.03      |
| libflac | 1.00 ± 0.03      |
```

It does [render fine on GitHub](https://github.com/ruuda/claxon/blob/master/readme.md#performance), but [it does not on crates.io](https://crates.io/crates/claxon).

**Comment by kureuil** [comment]
Yeah, I probably forgot to add the [option](https://docs.rs/pulldown-cmark/0.1.0/pulldown_cmark/constant.OPTION_ENABLE_TABLES.html) to render tables in the markdown [renderer](https://docs.rs/pulldown-cmark/0.1.0/pulldown_cmark/struct.Parser.html). We should probably enable footnotes at the same time.

**Comment by carols10cents** [comment]
Tables are rendering now so I'm going to close this-- we didn't have any styling on them, so they're not super nice looking right now but I've got a PR out for that :) https://github.com/rust-lang/crates.io/pull/1016
