### ISSUE TITLE
Panic on valid input

### ISSUE THREAD

**Issue by ytitov** [rust-lang/crates.io#9845]
### Current Behavior

Certain string value for a property causes a panic. Original serde_yaml cratedoes not.  Please see demo project which reproduces the problem. https://github.com/ytitov/demo-serde-yml-panic

### Expected Behavior

It should not panic. 

### Steps To Reproduce

Please see repo for exact code which causes the panic

### Environment

- Browser:
- OS:
n/a

**Comment by ytitov** [comment]
For convenience this 

```rust

pub async fn demo_panic() -> Result<(), Box<dyn std::error::Error>> {
    use serde_yml::Value;

    let t = Test {
        // NOTE: the amount of spaces at the end matters
        content: "\n    a {\n        ".into(),
    };

    // create the file with the failing string
    // ensure to deserialize using serde_yml

    fs::write("./generated-test.yaml", serde_yml::to_string(&t)?).await?;
    let bad_file = fs::read("./generated-test.yaml").await?;
    println!("attempt to deserialize Test");

    // PANICS //
    let _: Result<Test, _> = serde_yml::from_slice(&bad_file);
    println!("attempt to deserialize serde_yml::Value");

    // PANICS //
    let _: Result<Value, _> = serde_yml::from_slice(&bad_file);
    Ok(())
}
```

**Comment by Turbo87** [comment]
you might want to report this at https://github.com/sebastienrousseau/serde_yml instead. this issue tracker here is for crates.io itself.

**Comment by ytitov** [comment]
Oh boy. My mistake.
