### ISSUE TITLE
README.md not rendering in crates.io

### ISSUE THREAD

**Issue by natewilson** [rust-lang/crates.io#9884]
### Current Behavior

https://crates.io/crates/mustache indicates no README.md file present but the linked repo shows a README.md present

### Expected Behavior

Expected to see the same README content rendered on crates.io as is seen rendered on github.com

### Steps To Reproduce

1. Visit https://crates.io/crates/mustache
2. Click link for repository
3. Compare results

### Environment

issue appears to originate in the crates.io page generation environment which is opaque to clients

**Comment by Turbo87** [comment]
the repository might have a readme, but the published crate file apparently doesn't. we only render readmes that are included in the crate files.

**Comment by natewilson** [comment]
Roger that.

Might be good to update presentation of error message and/or related docs then. The message on crates.io indicates no `README.md` file (which is clearly present) and [cargo book](https://doc.rust-lang.org/cargo/reference/manifest.html#the-readme-field) instructs:

> _If no value is specified for this field, and a file named README.md, README.txt or README exists in the package root, then the name of that file will be used. You can suppress this behavior by setting this field to false_ 

That except is found at the target of the "readme" link in the section [Publishing on crates.io](https://doc.rust-lang.org/cargo/reference/publishing.html#publishing-on-cratesio)

Seems like might need coordination with https://github.com/rust-lang/cargo

**Comment by Turbo87** [comment]
> in the package root

that is the important part. if you check https://docs.rs/mustache/latest/src/mustache/lib.rs.html you can see that no such file exists in "the package root". whether or not it was added to a linked repository does not matter, because we display the readme corresponding to the selected version, and that published version did not have a readme at the time.

**Comment by Turbo87** [comment]
nevermind, I looked at the wrong docs.rs view 🤦‍♂ 

https://docs.rs/crate/mustache/latest/source/README.md clearly exists, so I'm not sure what exactly happened 7 years ago when this crate was published 🤔

**Comment by Turbo87** [comment]
I've queued up a rerender of the `mustache` README files and everything appears to be working now :)

**Comment by natewilson** [comment]
> I've queued up a rerender of the `mustache` README files and everything appears to be working now :)

Thanks. 🍻 Hopefully it's isolated and just weird.  🤷
