### ISSUE TITLE
Images in readme have crate name incorrectly injected into URL

### ISSUE THREAD

**Issue by michaelvlach** [rust-lang/crates.io#9886]
### Current Behavior

E.g.

https://crates.io/crates/agdb

Images in any of the following forms:

```
<img width="100" src="./agdb_web/public/images/db.png"
<img width="100" src="/agdb_web/public/images/db.png"
<img width="100" src="agdb_web/public/images/db.png"
```

Will result in incorrect URL:

```
https://github.com/agnesoft/agdb/raw/HEAD/agdb/agdb_web/public/images/db.png
```

The name of the crate is wrongly inserted after the HEAD part.

### Expected Behavior

The URL does not have the crate name injected after HEAD part.

### Steps To Reproduce

1. Go to https://crates.io/crates/agdb
2. Inspect any element of the images not being found.
3. See incorrect URL.

### Environment

- Browser: any
- OS: any

**Comment by Turbo87** [comment]
This is an unfortunate consequence of using `../README.md` in the `Cargo.toml` file (see https://github.com/agnesoft/agdb/blob/v0.9.2/agdb/Cargo.toml) in combination with relative paths in that markdown document.

Upon publish, `cargo` transforms that to `README.md` (see https://docs.rs/crate/agdb/0.9.2/source/Cargo.toml#41) and records that the crate can be found in the `agdb` folder of the repository (see https://docs.rs/crate/agdb/0.9.2/source/.cargo_vcs_info.json#5). crates.io assumes that all relative paths in the README are relative to the `readme` field location in the `Cargo.toml` file, which causes our code to append the `agdb` prefix.

your options are either to use absolute URLs in the document, or to move/copy the document into the `agdb` folder and adjust the relative paths accordingly.

**Comment by michaelvlach** [comment]
Thanks for clartification. Would symlink work in this case? Putting just README.md in Cargo.toml and then having a symlink (not actual file) to the root? I would have to create a release just to test it out so perhaps you would know. Thanks!

**Comment by Turbo87** [comment]
> Would symlink work in this case?

if I remember correctly, this will ultimately result in a similar issue due to the factors mentioned above. sorry :-/
