### ISSUE TITLE
Usernames in /users/ urls should be case-insensitive

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#989]
What happened:

- I typed in crates.io/users/burntsushi
- I got a 404 :(

What I expected to happen:

- I type in crates.io/users/burntsushi
- I am shown the content I see if I go to https://www.crates.io/users/BurntSushi

Github treats usernamse in a case-insensitive manner; I can visit either https://github.com/burntsushi or https://github.com/BurntSushi. 

We should probably lowercase usernames like we do for keywords, and add a unique index. I will write up more instructions later :)

**Comment by baileyn** [comment]
I'd like to tackle this issue if that's okay.

**Comment by Deedasmi** [comment]
Any progress @baileyn? I might take a look soon if not.

**Comment by baileyn** [comment]
@Deedasmi feel free, I've been swamped. Thank you so much.
