### ISSUE TITLE
Show reverse dependencies

### ISSUE THREAD

**Issue by winding-lines** [rust-lang/crates.io#99]
I see that the rust server already has an API for fetching reverse dependencies. Is there a plan/desire to add this information to the Ember app?

Also is it possible to get a dump of the postgres database to have some real data when playing with the application locally?

**Comment by alexcrichton** [comment]
Now that we've got a more prominent location for links than we used to, I think I'd be fine just adding a link to the reverse dependencies page.

**Comment by bjz** [comment]
:+1:

I constantly see 'got to the `/reverse_dependencies` page pointed out in IRC. Folks are always surprised and say, 'that's amazing!' or something. :)

**Comment by alexcrichton** [comment]
cc @Turbo87 

an easy thing that could be added to the links sections for crates! Now that you've fixed the bugs on the page I think it'd be fine to just show it.
