### ISSUE TITLE
Images in rendered README spill out of the crate-readme div.

### ISSUE THREAD

**Issue by olson-sean-k** [rust-lang/crates.io#993]
See one of my crates [here](https://crates.io/crates/bismuth) for an example. The screenshot image spills out of the `crate-readme` `div`. Maybe it would be better to clip or resize elements that spill out of the containing `div`.

**Comment by hoodie** [comment]
also here https://crates.io/crates/cairo-rs

**Comment by Phrohdoh** [comment]
https://crates.io/crates/timi has an ascinema cast.

**Comment by anthonynguyen** [comment]
Seems like it's fixed now, right?

**Comment by olson-sean-k** [comment]
Indeed! Looks nice now. Thanks! :-)
