### ISSUE TITLE
Only interpret README files whose filename ends in `.md` as markdown, render plain text otherwise

### ISSUE THREAD

**Issue by antoyo** [rust-lang/crates.io#995]
Hello.
If the readme is in the asciidoc(tor) format, it is not rendered correctly on crates.io.
[Here's an example.](https://crates.io/crates/relm)
Thanks to fix this.

**Comment by Susurrus** [comment]
Same with [my crate](https://crates.io/crates/serialport). It might be too difficult to support asciidoc at this stage, but I'd suggest not rendering anything if the file doesn't end in ".md".

**Comment by antoyo** [comment]
If someone is interested, I started a [crate to parse asciidoctor](https://github.com/antoyo/asciidoctor-rs).
It is far from finished and I don't have much time right now to work on it, so if anyone is interested, this can be used as a starting point.

**Comment by kivikakk** [comment]
According to [`linguist`](https://github.com/github/linguist/blob/ea3e79a631fb2cd1f1b3c7fa9c6f68892b478892/lib/linguist/languages.yml#L2598-L2604), we might want to render Markdown for at least `.md`, `.markdown`, `.mdown`, `.mdwn`, `.mkd`, `.mkdn`, and `.mkdown`. I don't know the story of how each one got there personally, but it seems a fair assumption they were all added due to real-world use (and lack of standardisation).

Will fix this tomorrow.

**Comment by kivikakk** [comment]
Looks like we need to transmit the README filename while uploading; right now we only upload the content: https://github.com/rust-lang/cargo/blob/ff9ca41fe754f94320ebe69acf4f44842edde3e4/src/cargo/ops/registry.rs#L122-L124.

**Comment by Susurrus** [comment]
@kivikakk The only supported file endings by Commonmark is `.md` and `.markdown` according to the `text/markdown` MIME type [RFC7763](https://tools.ietf.org/html/rfc7763).

**Comment by kivikakk** [comment]
@Susurrus I don't disagree, but RFCs and reality are two very different things. I can find thousands (!) of examples of the alternatives not listed in the RFC by searching around here.

**Comment by kivikakk** [comment]
It's worth noting RFC7763 refers to Markdown, and not CommonMark.  The CommonMark spec doesn't suggest anything about file endings.

(Notably, RFC7764 — while maintaining that ".md" and ".markdown" are the suggested file endings — also [refers to ".mkd" files a few times](https://tools.ietf.org/html/rfc7764#section-4.7))
