### ISSUE TITLE
Repository link for gdk-sys links to archived repository

### ISSUE THREAD

**Issue by divyaranjan1905** [rust-lang/crates.io#9962]
The gdk-sys crate doesn't have a README but the repository section links to gtk3-rs when that repository is archived. It should be changed to gtk4-rs

**Comment by Turbo87** [comment]
you might want to report this at https://github.com/gtk-rs/gtk4-rs. this issue tracker here is for issues with crates.io itself, not the content hosted on it.

**Comment by divyaranjan1905** [comment]
> you might want to report this at https://github.com/gtk-rs/gtk4-rs. this issue tracker here is for issues with crates.io itself, not the content hosted on it.

Understood, apologies.
